### ISSUE TITLE
Add or find source for more TTS voices (online APIs, voice companies, websites, etc)

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#108]
CereProc
    Based in Scotland
    Scottish, Irish, celebrity, Spanish, Japanese,
    https://www.cereproc.com/en/products/voices
    https://www.cereproc.com/en/developers
    https://www.cereproc.com/en/contactus

Natural Reader
    Based in Canada
    Lots of voices: US, british, French, Swedish, etc – all $39.99 per pack/dialect
    Install directly into Window for use with any TTS engine
    http://www.naturalreaders.com/priceorder.html#voices
    sales@naturalreaders.com
    support@naturalreaders.com

Acapela group
    Offices in Belgium, France and Sweden
    Childrens’ voices available
    Proprietary API that is platform based (Win 7&8 vs Win 8 specifically)
    http://www.acapela-group.com/
    http://www.acapela-group.com/contact/

Nuance Vocalizer
    Proprietary API
    Can’t find voices specifically for sale/distribution

AT&T Natural Voices
    Business sold to Interactions? Difficult to find info on voices.
    http://www.interactions.net/products/

**Comment by pporyzala** [comment]
IVONA TTS (originally developed in Poland, currently An Amazon Company): wide selection of voices (51) for 23 languages: https://www.ivona.com/us/about-us/voice-portfolio/.

Available as a Speech Cloud (https://www.ivona.com/us/for-business/speech-cloud/) or installed locally (available in Windows TTS engine, https://www.ivona.com/us/for-individuals/voices-for-accessibility/). 

Commercial solution, pricing ($35-$45) for local installation versions: http://harposoftware.com/en/36-all-ivona-voices.

**Comment by Ar2rZ** [comment]
https://www.modeltalker.org/ 
this company creating customs voices for English only.

**Comment by JuliusSweetland** [comment]
@Ar2rZ It should also be stated that this is what is known as "voice banking" and the service is completely free at the moment. It's excellent and the voices they provide work with OptiKey.

**Comment by JuliusSweetland** [comment]
I am also looking into adding support for Google's online TTS API, but this would require an internet connection.

**Comment by JuliusSweetland** [comment]
Re-posting info from #106 (thanks @delta003):

Assuming there is a internet connection, we can just use Google TTS API
(e.g. http://translate.google.com/translate_tts?tl=en&q=Integrate%20text%20to%20speech)
It should be fast enough and I think it covers all languages as Google Translate

The link is the example of HTTP request. You just make HTTP to translate.google.com/translate_tts setting tl=language (two letters shortcut for language) and query=what_do_you_want_to_say (make sure you escape this string). HTTP response have Content-Type:audio/mpeg so from response you can get audio file. Then you just pass that file to system to play it (I'm don't really know C# but this should be easy). Here are some useful links:
http://stackoverflow.com/questions/184683/play-audio-from-a-stream-using-c-sharp
http://stackoverflow.com/questions/7757881/c-sharp-download-text-to-speech-from-google-translate-comes-with-problems
http://stackoverflow.com/questions/9243560/how-can-i-use-google-text-to-speech-api-in-windows-form
I don't have access to Windows now, so I can't implement this, but if you want I can write you a class that implements IAudioService and use this approach. But you'll have to check it and probably debug it. Just ping me here if you need that. Also, I'll have access to windows in ~month so if this issue is still open I'll develop a feature.

I would like to split out the IAudioService as it's currently in breach of the
single responsibility principle. There should really be an interface and
class for playing sounds and an interface and multiple classes for speech.
Then I can just swap out one speech service for another, and even nest them
so we can fall back to Microsoft TTS if there is no active internet
connection, for example.

**Comment by Ar2rZ** [comment]
thing with google tts, i think they not allow to use there tts, i played around with those examples before started localization... there are more online voice engines, so, will do another research, once will finish with translations.

**Comment by Ar2rZ** [comment]
https://cloud.google.com/translate/docs
http://weston.ruter.net/2009/12/12/google-tts/

**Comment by Ar2rZ** [comment]
https://msdn.microsoft.com/en-us/library/hh361572.aspx

**Comment by Ar2rZ** [comment]
https://www.freedomscientific.com/Downloads/synthesizers

**Comment by JuliusSweetland** [comment]
A user (Udo) has recommended this British English (male) voice for 39 EUR (free 30 day trial available): http://harposoftware.com/en/british-english/140-brian-british-english-voice.html

**Comment by JuliusSweetland** [comment]
Suggestion by Chris Veigl: "what about adding the Microsoft Speech Server 11  as TTS engine (this is very easy - c# examples are there - and it offers voices for 20+ languages for free !)"

**Comment by vdjerek** [comment]
Hi!
I'm planing on using the Alfanum's AnReader for Croatian - it's also available in Serbian. Works very nice, but costs 300€.
Link: http://www.alfanum.co.rs/index.php/en/products-and-services/products-for-disabled/anreader

**Comment by vdjerek** [comment]
Update - open source espeak (http://espeak.sourceforge.net/) sort of works for Croatian, probably also for other languages they advertise (it's a long list). It may be good for testing, or if you can't get something better.

**Comment by alexgranadosp** [comment]
There is an American startup called Vocalid that is making custom voices. I think this is a great option for English speakers (no other languages available). As a volunteer you can donate your voice or find a similar voice for the person that needs it. I have no idea about pricing but is not free.

http://blog.ted.com/everything-you-need-to-know-about-donating-your-voice-why-you-should-help-the-human-voicebank-initiative/

Rupal Patel
https://www.youtube.com/watch?v=d38LKbYfWrs

http://www.vocalid.co

**Comment by JuliusSweetland** [comment]
@alexgranadosp Great find - thank you

**Comment by alexandre-mbm** [comment]
[The MBROLA Project](http://tcts.fpms.ac.be/synthesis/mbrola.html)

**Comment by JuliusSweetland** [comment]
@alexandre-mbm That's a great resource, thanks. Would you be interested in adding support to OptiKey as an alternative to current use of System.Speech.Synthesis?

**Comment by alexandre-mbm** [comment]
No, for now I just wanted to share the info. In future it can be useful into a context of rewriting for Linux.

**Comment by zelmon64** [comment]
@JuliusSweetland I've been having a look at the free voices available and found some that haven't been mentioned.

- The MBROLA voices can be [used with espeak to make them SAPI5](http://espeak.sourceforge.net/mbrola.html). This works okay but the MBROLA license agreement has to be accepted every time the pc is restarted.

- [RHVoice](https://github.com/Olga-Yakovleva/RHVoice) which is again SAPI5 and has a [few languages](https://github.com/Olga-Yakovleva/RHVoice/wiki/Downloads). I think the English Alan voice is fairly nice (haven't tried the other languages).

- [SALB](https://github.com/m-toman/SALB) which provides a SAPI5 interface for the HMM based voice models built by HTS (http://hts.sp.nitech.ac.jp/). It currently only has a German voice but if the other HTS voices can be added it should be quite good.

- [MaryTTS](https://github.com/marytts/marytts) has quite nice voices in quite a few languages but **isn't** SAPI5 (or 4). It's a java server with an HTTP interface. Of all the free voices I've come across this seems to be the nicest sounding and the most active in development. There's even the possibility of using it in conjunction with MBROLA (this was possible in version 4 and might be brought back in version 6). I've successfully hacked it into OptiKey and I believe it works fairly well. Shall I make a new issue to discuss how it should be properly integrated?

**Comment by JuliusSweetland** [comment]
Great info. Thank you. Yes a new issue would be a good idea

**Comment by JuliusSweetland** [comment]
Support for MaryTTS engine added in v2.6.0 which includes free voices in German, British and American English, French, Italian, Luxembourgish, Russian, Swedish, Telugu, and Turkish
