### ISSUE TITLE
Write unit tests!

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#14]

**Comment by DanielHutt** [comment]
Are there any key places that you would like help with unit testing?

**Comment by JuliusSweetland** [comment]
Hi Dan. Yes! The observables. They are complicated as anything and have
zero coverage (like the rest of this project!). Thank you. Help would be
amazing

**Comment by DanielHutt** [comment]
Awesome. I'll pull down the repo when I get home so that I can hopefully start plucking away at it.

**Comment by DanielHutt** [comment]
Hey Julius, do you think it would be wise for me to take the first step and create a Test project that has all the right files and folders ready to unit test stuff? That way it would be easy for people to just unit test one class and move on.

**Comment by JuliusSweetland** [comment]
Hi Dan,

Yes that sounds like an excellent plan. Which test runner are you thinking
of using?

Regards,
Julius

**Comment by DanielHutt** [comment]
I'm most familiar with NCrunch and NSubstitute.  Any objections or suggestions?

**Comment by JuliusSweetland** [comment]
Both fine, but I (and possibly most others) do not have licenses for those
tools. As long as the tests are thanks via ms test or nunit I think most
people will be alright.

Thanks!

**Comment by DanielHutt** [comment]
Shoot, I didn't even think about that. NSubstitute is free and open source and I've found fairly easy to introduce to new people.  I'll leave any references to NCrunch out of my branch.

**Comment by JuliusSweetland** [comment]
Sounds good, thanks Dan. Can NSubstitue be referenced via NuGet in your new
project? Saves people having to try and find it.

**Comment by JuliusSweetland** [comment]
Actually I'm not even sure if that's possible. Ignore that.

**Comment by DanielHutt** [comment]
I would expect that to be possible.  I'll definitely make it as easy as possible for people to jump in and unit test a very small portion of the code. The lower the barrier of entry, the better!

**Comment by JuliusSweetland** [comment]
Absolutely. Thanks Dan. Really appreciate you getting involved.

**Comment by chadkulesa** [comment]
I've created a test project with nunit, and wrote a couple unit tests. 

The main project is directly under src, Do you want to keep the test project outside of src, or move the main project into a sub folder of src and have the test project be under src as well?

**Comment by JuliusSweetland** [comment]
Looking forward to seeing it. I think sub folders of src would be good.

**Comment by JuliusSweetland** [comment]
@chadkulesa Unit test project is great, thank you. I've already used it to solve that SubString problem with the KeyboardOutputService, so thank you.

**Comment by DanielHutt** [comment]
I haven't forgotten about this. I just got incredibly sidetracked learning some python. I have a script right now that clones the project folders' structure, copies only the *.cs files, and then appends Test to the filenames while preserving any currently written unit tests.

I'm currently testing the script before I submit a pull request. Sorry for the awesome month long delay!

**Comment by JuliusSweetland** [comment]
Hi Dan. Not at all. Any time you can give to OptiKey is greatly appreciated
and I don't expect anything from anyone.

Looking forward to seeing what you've learned and how it works.
