### ISSUE TITLE
Localisation: Spanish

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#149]
**1.Transifex translation of UI strings:** 100%

**2.Keyboard layout:**
![image](https://cloud.githubusercontent.com/assets/4722561/13410154/1a9388b6-df2e-11e5-95fb-6e60996626d7.png)
http://ascii-table.com/keyboard.php/071-2

**3.Alphabet:**
a)Letters: 27 individual letters - https://en.wikipedia.org/wiki/Spanish_orthography#Alphabet_in_Spanish
a-z plus ñ (lower and upper case)

b)Diacritics that can be added to individual letters (these will be dead keys): 
acute accent - used on á, é, í, ó, ú (lower and upper cases)
diaeresis - used on ü (lower and upper case)

c)Other keys: No (Catalan uses the apostrophe, but it is rare in modern Spanish so not needed on the main Alpha keyboard)

Total: 29 keys

c)Complexity: *nothing so far...*

**4.Word list:** SpanishSpain.dic on master branch - 71k

**5.Anything else:** "¿" and "¡" characters: Input from Gaspar: "The usage of “ ¿ and ¡” characters has been reduced to formal documents where proper writing is required. For everyday use, we don’t tend to use them (Facebook, chats, whatsapp, informal email), so I wouldn’t be very worried about giving them a very important location."

**6.Other:** Spanish & Catalan will be developed separately - their differences are greater than originally though. New Catalan localisation issue here: https://github.com/OptiKey/OptiKey/issues/235

**BRANCH:** None yet

**Comment by JuliusSweetland** [comment]
From an email discussion with Juan:

I find a very impressive Spanish word list made by a team of La Rioja University lead by Juan L. Varona. It is included at least in winedt: http://www.winedt.org/Dict/

247.049 words no less.

The problem is verb conjugation. I'm not sure if you speak Spanish. If it not the case, let me explain: we have 6 persons (as in English), each one with a suffix. Besides, there are 17 conjugations that make the life of a Spanish learner close to miserable, I guess.

Therefore, if it is intended to predict verbs, a dictionary should be able to predict each form. For instance, the dictionary that I am going to send you covers 56 forms of the verb "desarrollar" (to develop): desarrolla, desarrolle, desarrollo, desarrollé, desarrolló, desarrollad, desarrollan, desarrollar, desarrollas, desarrollen, desarrolles, desarrollos, desarrollaba, desarrollada, desarrollado, desarrollara, desarrollará, desarrollaré, desarrollase, desarrolláis, desarrolléis, desarrollaban, desarrollabas, desarrollable, desarrolladas, desarrollados, desarrollamos, desarrollando, desarrollaran, desarrollaras, desarrollarla, desarrollarlo, desarrollarme, desarrollaron, desarrollaros, desarrollarse, desarrollarte, desarrollarán, desarrollarás, desarrollaría, desarrollasen, desarrollases, desarrollaste, desarrollemos, desarrollo, desarrollabais, desarrollables, desarrollarais, desarrollarlas, desarrollarlos, desarrollarnos, desarrollaréis, desarrollarían, desarrollarías, desarrollaseis, 

On a core i7 of 2012 it works like a charm. I have tested that potential bottlenecks are related with CPU, as optikey weights no more than 200mb in ram. However, on a 2014 atom with 2gb of ram, it is not very usable: a lot of times it introduces a double key instead of just one. Maybe it would work with a slower click on key, but then it would be less useable.

I used optikey with a 50-word text. It saved quite a number of keystrokes and dictionary worked like a charm on core i7. I use swype a lot, which depends of estochastical prediction. Would it be possible to implement a statistical model of word prediction in optikey? It is not a deal-breaker at all, but surely it would help.

**Comment by JuliusSweetland** [comment]
Input from Gaspar: "The usage of “ ¿ and ¡” characters has been reduced to formal documents where proper writing is required. For everyday use, we don’t tend to use them (Facebook, chats, whatsapp, informal email), so I wouldn’t be very worried about giving them a very important location."

**Comment by caspercba** [comment]
Julius, about áéíóúü: Spanish keyboards don't have separate keys for this accented vowels. This is how it works: The user presses the `accent key` + vowel. In other words, pressing the `accent key` nothing is written until the user presses a second key: aeiou; so two independent key presses produce one accented character. Here's an example of a keyboard layout:  https://www.terena.org/activities/multiling/ml-mua/test/img/kbd_spanish.gif

**Comment by JuliusSweetland** [comment]
Thanks. As this is a reasonably long winded process when using the fixation
selection method I would prefer to have dedicated keys for the accented
characters, but thank you for the clarification.

**Comment by JuliusSweetland** [comment]
@utacub Can you review the top post on this page and let me know if everything looks correct? The UI strings are all ready on Transifex: https://www.transifex.com/optikey/optikey/ so there's nothing required there.

I basically need someone to give me some feedback on the word list, or supply a new one. I think the keyboard is self-explanatory, and I'll need to add the ability to add 3 diacritics; an acute accent, a diaeresis, and a tilde (only on certain letters listed in the first post at the top).

I am currently working on Greek, which introduces the idea of dead keys, so everything should be straightforward.

**Comment by utacub** [comment]
@JuliusSweetland  As you said, the word list from the La Rioja University is really extensive. Have you checked the dictionary from OpenOffice? It has fewer words (71165). You can download the original file from: http://extensions.openoffice.org/en/project/spanish-espanol , or a version without any marks from here: https://dl.dropboxusercontent.com/u/2129613/Optikey/es-ES-nomarks.dic

Same for Catalan, OpenOffice dictionary: http://extensions.openoffice.org/en/project/catalan-dictionary-pack-spell-checker-hyphenation-patterns-and-thesaurus , and version without marks: https://dl.dropboxusercontent.com/u/2129613/Optikey/ca-ES-nomarks.dic

**Comment by JuliusSweetland** [comment]
@utacub That dictionary size sounds good. I've not been able to check the file as I don't have OpenOffice and the downloaded file is not a plain text file. If you like these dictionaries could you extract a plain text version (copy the list, one word per line, into Notepad and save the file with format UTF-8). These 2 files (Spanish and Catalan) can be emailed to me optikeyfeedback@gmail.com  and I'll add it to a new Spanish branch. Thanks.

**Comment by JuliusSweetland** [comment]
@utacub Top post has been updated with all latest info. If you can send me the updated dictionary files (without the entries that include numbers and spaces) I will set up the branch. Thanks.

**Comment by utacub** [comment]
@JuliusSweetland  Regarding the differences between Spanish and Catalan. We use the same keyboard with both (the one in the top post), but:

- Spanish has "ñ". Catalan has "ç" and "l·l" (two normal "l" with a floating dot in the middle, the one that is on top of the 3 in the keyboard layout: ·).
- Spanish diacritics: á,é,í,ó,ú,ü. Catalan diacritics: à,è,é,í,ò,ó,ú,ï,ü (Catalan uses both `and ´).
- Catalan uses the apostrophe (the symbol under ? in the keyboard layout): '
- Spanish normally uses !,? and ¡,¿ in formal writing. Catalan only !,?

**Comment by JuliusSweetland** [comment]
@utacub Great info, thank you. I think Spanish and Catalan should be treated separated. I have updated the top post above and split off the Catalan info into this issue: https://github.com/OptiKey/OptiKey/issues/235

I have attached SpanishSpain.dic and CatalanSpain.dic dictionaries to the main branch and will create branches to develop these languages in due course (I am currently up to 5 in progress languages, plus 2 other releases and a re-write of 4 of the current languages). I'll be as quick as I can be, but in the mean time could you please review the top posts in this issue and the Catalan issue. If everything is correct then I think I have everything I need, except the Catalan UI strings need to be completed (currently at 45% complete).

Thanks!

**Comment by interpablo** [comment]
Hi @JuliusSweetland 
I'd like to collaborate in Spanish, it's my native language. What can I do to help out?
Regards,
Pablo

**Comment by JuliusSweetland** [comment]
Hi @interpablo - thanks for the offer. At the moment Spanish looks pretty good so I'll get to it asap (I am currently finalising Greek and Turkish releases and then Spanish will be next). If you know Catalan it would be really helpful for you to get involved here: https://github.com/OptiKey/OptiKey/issues/235 - specifically the Transifex translation is not yet complete? Otherwise I'll let everyone know when I start work on Spanish.

Alternatively, if you would like to start putting together a Spanish keyboard in xaml and making the other localisation changes then please let me know and I'll create you a new Spanish branch for you to fork.

**Comment by utacub** [comment]
Finally finished the Catalan Transifex translation, waiting for new instructions (if needed).

**Comment by JuliusSweetland** [comment]
Hi @utacub - thank you. If I create a Spanish and Catalan branch do you
want to start creating the specialised keyboards?

**Comment by utacub** [comment]
Hi @JuliusSweetland.
Yes, sure, we'll give it a try! You can add us to the Spanish and Catalan branch!

**Comment by JuliusSweetland** [comment]
@utacub Spanish branch created here: https://github.com/OptiKey/OptiKey/tree/Spanish

**Comment by A01221624** [comment]
Hello, I was silently lurking and decided to join in. Anything I can do to help.

I forked and started working on the changes mentioned in [https://github.com/OptiKey/OptiKey/blob/f88cf8dacf38a09302e802af6e52d53bc5804f2c/docs/Localize.md](Localize.md). Found a couple of steps missing (or my sleepy self missed them).

I'd say it's done, but I forgot about the diaeresis (whoops) and I'll be adding that tomorrow.

PS. Noticed that I was spamming this and decided to stop referencing the issue in every commit.

**Comment by JuliusSweetland** [comment]
@A01221624 Good news! Send me a pull request when you're ready. I'm not that active at the moment as I'm moving house, but I can review, test and release when you're ready.

**Comment by JuliusSweetland** [comment]
@A01221624 @utacub Pre-release of v2.3.3 (including Spanish) available here: https://github.com/OptiKey/OptiKey/releases

Please can you let me have your feedback once you've had a chance to test it. Thanks.

**Comment by A01221624** [comment]
A quick test by copying three sentences from a [Spanish newspaper (El País Edición América)](http://elpais.com/elpais/portada_america.html) with successful results:

**Multi-key selection**
- _Nicolás Maduro denuncia una campaña " brutal" contra él desde España_
- _Temer elige a un liberal para dirigir el Banco Central de Brasil._

**Single-key selection aided with prediction**
- _La guerra por el poder en el fútbol argentino, una gran batalla política._

Alas, this is with the mouse and by someone without impairments. Hopefully I'll test it soon with a quadriplegic person who has an EyeX (I ordered another EyeX and should arrive in no more than a month). But as for the language, everything seems fine.

I'll continue testing by copying larger and more complex texts.

**Comment by JuliusSweetland** [comment]
Spanish released as v2.3.3

**Comment by JuliusSweetland** [comment]
Closing this issue as the work is done and released, but please note the issue will remain here, just in a closed state.
