### ISSUE TITLE
Add web browsing keyboard

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#152]
Add new keyboard with specific web browsing functions (see below).

Need to find somewhere for it on menu, but a key could be added to each keyboard where currently each keyboard includes a self reference (e.g. the ALPHA key on the ALPHA keyboard).

The original request I received outlined the below, but I think the keyboard should only contain specific web browsing functionality and the ability to get to the ALPHA, NUMERIC, etc keyboards in one selection (which is the current paradigm), removing the need for all the extra keys:

"On the left side would be a large button dedicated to the left click function. Next to that would be letters in a qwerty setup and then a "123" button to display numbers. To the right would be buttons for Search (ctrl+e, Set focus to search box), Enter, Forward, Back, New Tab, Top (home) and possibly a Google button (launches Chrome and goes to google.com?)."

Here is a nice list of keyboard shortcuts: http://blog.codinghorror.com/standard-browser-keyboard-shortcuts/

**N.B. I have icons:** The user who asked for this has created and supplied icons for Search, Forward, Back, New Tab, etc... so just ask if you start work on this and I'll upload them somewhere.

**Comment by alexandre-mbm** [comment]
Do you sketch keyboards by using some tool?

**Comment by zelmon64** [comment]
@JuliusSweetland has there been any work on this? I think I'll have a go at it since the other keyboards I worked on went so well. Could I have the icons please?

**Comment by zelmon64** [comment]
@JuliusSweetland This is what I have at the moment. What do you think?

![image](https://user-images.githubusercontent.com/15001389/28321217-999165dc-6bca-11e7-9754-deb97aead726.png)

Can the mouse functions be combined with the mod keys? They seem to work independently at the moment but I haven't looked at their coding yet. It would just make it easier to change the zoom level and open links in new tabs if it can recognise when the control key is down etc.

**Comment by JuliusSweetland** [comment]
@zelmon64 I'll look for the icons now. Might have to send them this evening if I don't have the original email on my phone...

Keyboard looks great. You should be able to combine modifiers with mouse actions. There are two settings that currently govern this: SuppressModifierKeysWhenInMouseKeyboard and SuppressModifierKeysForAllMouseActions. From memory both are true. If you want modifiers to start working outside of the mouse keyboard (where I think they should be suppressed, then set SuppressModifierKeysForAllMouseActions to false, BUT be aware that you can perform mouse actions from the alpha keyboards, so the modifiers would have an impact there as well. It might be worth thinking about having separate settings for each keyboard that has mouse actions, i.e. MouseKeyboard, AlphaKeyboard, WebBrowsingKeyboard? That way the user can suppress whatever is appropriate, or just turn them all off with SuppressModifierKeysForAllMouseActions. I'd like to know your thoughts on this.

Also, what do you think about including right click instead of left double click, as you don't often double click in the web browser?

**Comment by JuliusSweetland** [comment]
@zelmon64 Can you email me directly at optikeyfeedback@gmail.com and I'll send you the icons.

**Comment by zelmon64** [comment]
@JuliusSweetland thanks for the information on SuppressModifierKeysWhenInMouseKeyboard and SuppressModifierKeysForAllMouseActions. I'm not sure whether an option per keyboard is a good idea as it may make it too confusing to remember which are enabled.

I think it definitely makes sense to switch the double click for right click instead. 

I've sent you the email thanks.

**Comment by JuliusSweetland** [comment]
@zelmon64 Ok agreed re SuppressModifierKeysWhenInXKeyboard. I think what's there is sufficient. If the user understands modifiers+mouse actions then they can just turn off SuppressModifierKeysForAllMouseActions.

**Comment by zelmon64** [comment]
@JuliusSweetland I used the browser back/forward/search and modified the scroll up for home but I needed two more so I found these:
https://image.flaticon.com/icons/svg/1/1198.svg
https://image.flaticon.com/icons/svg/2/2144.svg

![image](https://user-images.githubusercontent.com/15001389/28329614-5f1983ea-6be2-11e7-8fe1-7e5a3b296d11.png)
![image](https://user-images.githubusercontent.com/15001389/28329555-26f99fcc-6be2-11e7-807b-a696f2cafcb8.png)

**Comment by JuliusSweetland** [comment]
That looks excellent. Two ideas:

1. Could you remove the windows key (as it doesn't serve much purpose on
this keyboard) and add a back button in the bottom right (moving everything
along one).
2. Could you add a web keyboard key to the numeric keyboard also? I'm on
mobile so I can't say exactly where, but a similar idea to how you've added
it to the alpha keyboard.

**Comment by zelmon64** [comment]
1. I agree the windows key isn't that useful but I'm not sure about adding a back button since the alpha and num/sym keyboards don't have one. Perhaps I should add an END key to match the HOME key if someone wants to go straight to the bottom of a web page?

In regards to the windows key, are the arrow keys on any keyboards? I don't think I've come across them. Being able to use the shortcut to position windows would probably be useful. Looking through, I'm not sure where would be best to add them.

2. I had already added the web keyboard key to the num/sym keyboards just didn't post the images.

![image](https://user-images.githubusercontent.com/15001389/28334555-5e78507c-6bf3-11e7-8208-2d8c4a43581a.png)
![image](https://user-images.githubusercontent.com/15001389/28334522-4793bc2a-6bf3-11e7-9de2-17789d0bc965.png)
![image](https://user-images.githubusercontent.com/15001389/28334529-4d4cec2c-6bf3-11e7-8419-88b3fe9b8927.png)

**Comment by zelmon64** [comment]
I swapped the win key for the end key and this is how it looks:
![image](https://user-images.githubusercontent.com/15001389/28335924-fe93473e-6bf7-11e7-87ab-ba8ed4a1d686.png)

**Comment by JuliusSweetland** [comment]
1. Fair point, agreed.
2. Cool

I think the latest keyboard looks great. I'm happy to review a PR whenever
you're ready.

**Comment by JuliusSweetland** [comment]
Released in v2.5.0
