### ISSUE TITLE
Auto learn dictionary entries

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#156]
New setting to enable/disable this behaviour

Currently the user must manually add new words or phrases to the dictionary. With this setting on OptiKey would identify new words and automatically add them to the dictionary.

Care is needed to ensure that mispelled or incomplete words are NOT added to the dictionary as they would then be suggested as auto-complete and multi-key selection suggestions.
- Track new words and delete from dictionary if usage count drops to zero during this session (as the word was incorrect and removed)???

If the setting is enabled then the ADD TO DICTIONARY key might be redundant and need to be removed. Is there a suitable replacement key, or should the scratchpad be redesigned to just exclude this key?

**Comment by Pakosoft** [comment]
Hi Julius,

So when setting is on, for every word the user inputs we need to call the method ExistsInDictionary from the DictionaryService class and if it-s not in the dictionary add it with the correspondent method??
However I don't see any method that checks for misspelled words, I guess it should be implemented too.

For the ADD TO DICTIONARY key I guess you can disable it (make it translucent) when the automatic dictionary feature is on and vicebersa so you don't have to redesign or use another key that could feel misplaced there.

I can work on this.

**Comment by JuliusSweetland** [comment]
Hi. Thanks for looking at this.

I think it should work in a similar way as the increment/decrement usage
count in the dictionary, in that you only auto add a word when we think the
user has "accepted" it, e.g. when the user "moves on" from the word by
inputting space, or something similar. If the user then selects backspace
to go back and continue editing the word then the previous dictionary
addition should be removed and the newly edited one entered once they move
on from it again. Does that make sense?

**Comment by Pakosoft** [comment]
It does. Thank you. Will look into this.

**Comment by alexandre-mbm** [comment]
I will create my dictionary file directly. I see that other dictionary files are not sorted in according with the "sort -u" command from GNU/Linux shell. Which are the rules for the dictionary files?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm The dictionary should be around 100k with not too many proper nouns (names etc). All words should be lower case, unless they are always used with a capital letter.

**Comment by alexandre-mbm** [comment]
I see the instructions at #148.

Dictionaries can become personal topic. So I am creating a small script to mount them from multiple data sources. This will solve some issues with licenses.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm I'll post my linqpad scripts on this issue this evening which include scripts to merge dictionary and frequency lists, perform cleanup and extract the top x entries.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, which scripting languages are fine to the OptiKey ecosystem?

**Comment by JuliusSweetland** [comment]
I only use c# with linqpad.

**Comment by alexandre-mbm** [comment]
> I only use c# with linqpad.

Thanks. I am already finishing a initial research about LINQPad. Cool! I will use this only also...
