### ISSUE TITLE
Change some settings from within OptiKey

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#157]
Currently the management console is inaccessible to people exclusively using OptiKey for computer control as keystrokes on a physical keyboard and the use of a physical mouse are required.

This needs a lot of consideration, but some settings should be accessible from within OptiKey using, for example, an eye tracker. If you are interested in working on this please post your ideas on here for discussion before you start.

Brain dump of my current thinking:
* Just put it somewhere else on the screen and only allow one to be open. This potentially allows people to use the mouse and keyboard control to change settings themselves.
* If in ConversationOnly mode then make it modal as otherwise the user won’t be able to see it and they must have used a physical keyboard to open it anyway.
* Release keys when the management console is opened as modifier keys can bugger up entering numbers etc
* OR simplified version of the settings for use within OptiKey, leaving the management studio as it is?

**Comment by JuliusSweetland** [comment]
Users can now change settings in the Management Console using OptiKey (not when in Conversation mode).

**Comment by alexandre-mbm** [comment]
Yes, I achieve much of it with mouse panel docked and collapsed.
