### ISSUE TITLE
Add Brain-Computer Interface (BCI) support

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#161]
- Look into http://openbci.com/
  $500 board + $500 for Ultracortex (Mark 3) EEG headset kit (or $200 for print it yourself)
- http://youtu.be/k98_1jSnEv4 
- http://neurosky.com/ $80 - this may not be focussed enough to work with ALS patients
- Lucas Steuber suggested that MND/ALS affects the electrical patterns that can be detected on the surface of the skin, so this may be a dead end.

**Comment by jerrywaynewalden** [comment]
This is a very complex subject.  BCI and the utility of various methods spans a massive field spanning decades of research. The comment made where Lucas Steuber is referred to has merit when discussing EEG and BCI as a complete and total solution for ALL ALS patients along every stage in decline to the totally locked in state.  However it has been shown in many studies (google "eeg bci als" and you will see many papers and here is just one - http://onlinelibrary.wiley.com/doi/10.1111/j.1469-8986.2006.00456.x/full) that EEG BCI is quite viable - even in the totally locked in state.  But I am not here to debate this subject.  I am not a speech pathologist or neurologist.  I am adding to this issue to pare it down to an issue where an improvement can be made to OptiKey.  This improvement PROVIDES some ASSUMPTIONS regarding user capability in the same manner the OptiKey in its original incarnation ASSUMED users could properly focus and control they gaze.

This issue needs to highlight the following assumption:

The user with INTENT can RELIABLY and REPEATEDLY move ONE SINGLE muscle with little or no error.

OpenBCI is not the ultimate answer - but for ALS/MND patients - abilities decline along a spectrum.  As long (as is still the case with Stephen Hawking) as the patient can RELIABLY with INTENT move a muscle that is not subject to involuntary twitches - that movement can be filtered and detected with this hardware/software combination.  The idea for this issue being opened is to expose Optikey to a trigger that originates from OpenBCI software where the detector is open source fairly affordable hardware coupled with software that is open signal processing software that contains algorithms and plugins as well as scriptable plugins that can be used to detect alpha waves that originate from - for example - the motor cortex.

This issue should be focused not on the WAY TOO BROAD topic of BCI research and especially EEG technology - this issue really should have the premise - as even the question of the applicability of Eye Gaze technology itself assumes - the status of the patients abilities.  OptiKey was designed for persons with certain visual capabilities.  That is the premise.  Once that ability is accepted (which is not a capability universal to all or even most ALS patients during the entire phase of their disease) then Eye Gaze can be developed, a user interface can be developed that is custom made for use with Eye Gaze input in mind.  And as such OptiKey sits in a position to help untold thousands or more ALS patients to communicate - vastly improving quality of life for the duration of their disease where control of the Eye is viable.  There is a reason Stephen Hawking does not use Eye Gaze technology and instead chooses scan/select methods - I'll leave it to the reader to guess why that is.  I submit and can prove that OpenBCI can be a useful reliable and extensible alternative to Gaze selection methods - or facial recognition methods.

End of rambling diatribe.

**Comment by jerrywaynewalden** [comment]
One last question regarding the reference as follows "Lucas Steuber suggested that MND/ALS affects the electrical patterns that can be detected on the surface of the skin, so this may be a dead end." 

I am no expert so perhaps an expert can comment on my question which is - if those skin patterns were of any significance, they would be used as a diagnostic tool. I have never heard of it, and I read the research reports in the ALS newsletters  Looking for diagnostic tools is one of the areas of research, especially in the early stages. Seems to me that the discussion, if it is worth discussing, should focus on the existence and nature of the phenomena first, and not go further.

**Comment by JuliusSweetland** [comment]
@jerrywaynewalden From what you've told me on email you and your father (a patient with ALS) can reliably produce detectable alpha waves, so this is a viable trigger mechanism for OptiKey.

**Comment by Ar2rZ** [comment]
https://emotiv.com/store/ -  one more brain controller.

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
