### ISSUE TITLE
Add ACAT selection (facial gesture) support

### ISSUE THREAD

**Issue by jerrywaynewalden** [OptiKey/OptiKey#163]
1. For information about ACAT see the following:
   https://01.org/acat
   https://github.com/01org/acat/releases
   http://blogs.msdn.com/b/cdndevs/archive/2015/08/14/intel-just-open-sourced-stephen-hawking-s-speech-system-and-it-s-a-net-4-5-winforms-app.aspx
2. First investigate referencing a built ACAT assembly to add a facial movement trigger to OptiKey

**Comment by JuliusSweetland** [comment]
A reference to a compiled ACAT assembly is preferred/required instead of extracting source code due to the fact that ACAT is licensed under Apache v2.0.

**Comment by Ar2rZ** [comment]
@JuliusSweetland 
what are your views on this?

**Comment by JuliusSweetland** [comment]
I think it could be very beneficial and is certainly worth investigating

**Comment by JuliusSweetland** [comment]
I think it could be very beneficial and is certainly worth investigating

**Comment by Ar2rZ** [comment]
i just looked at this a day ago.. looks like they have nice solutions and functions which can be implemented later..

**Comment by JuliusSweetland** [comment]
Agree. So you know I'm taking a couple of weeks away from OptiKey, but will
pick it up at the start of December. First thing will be the language
selection keyboard and then we can release Russian.

**Comment by Ar2rZ** [comment]
sure, take your time.

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
