### ISSUE TITLE
Running OptiKey on system with multiple screens

### ISSUE THREAD

**Issue by Ar2rZ** [OptiKey/OptiKey#175]
- 1. **Mouse function is working incorrectly**
- 2. **OptiKey console appearing incorrectly, if run on non-primary screen.**
  Steps to reproduce:
- System setup: Two or more screens, primary screen is on the right hand side, or in the middle.
  - Run Optikey on primary screen
  - perform mouse left click => it clicking on secondary screen on the left hand side.
  - Run OptiKey on secondary screen, OptiKey console appear in floating position, by trying to dock console, it throws an exception.

**Comment by Ar2rZ** [comment]
Proposed solution to fix:

*  1. For correct docking:
   * **WindowManipulationService.cs**
      * on line 1207 remove validation finalDockLeftInDp<0, as if screen attached on the left it gives negative value for left screen width.
*  2. For correct mouse functioning:

    * **PublishService.cs**
        * public void MouseMouseToPoint(Point point)
          * change this inside try block:
         
              try
            {        
                Log.DebugFormat("Simulating moving mouse to point '{0}'", point);  
                              
                var getCurrentScreenBounds = Screen.GetBounds(new System.Drawing.Point((int)point.X,(int)point.Y));
                var virtualScreenWidthInPixels = getCurrentScreenBounds.Width * Graphics.DipScalingFactorX;
                var virtualScreenHeightInPixels = getCurrentScreenBounds.Height * Graphics.DipScalingFactorY; 
                                 
                //N.B. InputSimulator does not deal in pixels. The position should be a scaled point between 0 and 65535. 
                //https://inputsimulator.codeplex.com/discussions/86530
                var xd = Math.Ceiling(65535 * (point.X / virtualScreenWidthInPixels));
                var yd = Math.Ceiling(65535 * (point.Y / virtualScreenHeightInPixels));
                inputSimulator.Mouse.MoveMouseTo(xd,yd);

            }

**Comment by Ar2rZ** [comment]
Tested on win8 multi screen environment.

**Comment by Ar2rZ** [comment]
mouse function is working for primary screen, but does not work for secondary screen on windows 7.

**Comment by Ar2rZ** [comment]
"OptiKey console appearing incorrectly, if run on non-primary screen."
reason for this: in **WindowManipulationService.cs**
method : private void **SetAppBarSizeAndPosition(DockEdges dockPosition, Rect sizeAndPosition)**
on line 1207 is validation **finalDockLeftInDp<0**, 
if screen attached on the left of primary screen for **finalDockLeftInDp**  gives negative value for left screen width.

**Comment by Ar2rZ** [comment]
"Mouse function is working incorrectly"
reason for this: **PublishService.cs**
method: ** public void MouseMouseToPoint(Point point)**
**SystemParameters.VirtualScreenWidth** and **SystemParameters.VirtualScreenHeight ** gives value of all screens width, but is required to give only primary screen width. as point is calculated from primary screen dimensions.
instead of using **SystemParameters.VirtualScreenWidth** and **SystemParameters.VirtualScreenHeight ** can be used **SystemParameters.PrimaryScreenWidth** and **SystemParameters.PrimaryScreenHeight**, then mouse functioning correctly on all screens primary and non-primary...

**Comment by JuliusSweetland** [comment]
As this is not supported by the trackers themselves I will close this issue.
