### ISSUE TITLE
for a cerebral palsy patient from Turkey

### ISSUE THREAD

**Issue by gulyalcin** [OptiKey/OptiKey#179]
Hello,

My name is Gul Yalcin Cakmakli. I am a neurologist from Turkey and doing PhD in neuroscience. Currently I am in Atlanta  doing research studies in Emory University. My main area of interest is Parkinson's disease, dystonia and other movement disorders. 

Actually I am contacting you because of a personal situation. I have a disabled brother, who is 45 now. He has cerebral palsy and he is disabled since birth, he can neither walk nor use his hands properly. But after we discovered some devices that he can use either with his head or by blinking, he started using computer now and this made a dramatic change in his life which made us really happy and hopeful for future opportunities. I am now searching eye tracking systems. I think my brother can use it but we can not be sure about it as he has many involuntary movements too, which may destabilize his head. 
I came across optikey during my search for these systems. First of all, I am grateful for your efforts developing such a system both as a neurologist dealing with such patients in need of communication and as a family member of such a patient. The system looks great and a lot more affordable for everyone. Do you think of translating it also to Turkish? I want my brother to try and use it if possible. It will be a lot more practical than the system he is currently using by blinking. It takes him 3-4 steps to get to only one letter. 
I will be very happy to hear your advices regarding this issue.

Best regards,

Dr. Gul Yalcin Cakmakli

**Comment by JuliusSweetland** [comment]
Hi. Turkish is on the todo list, but I can't give you an accurate timeline at the moment. The translation of the user interface strings is a little more than half done. As well as that we need a good Turkish word list and some discussion of the standard Turkish keyboard layout and any special keys. Once we have all that there's a bit of effort involved along with testing. If you can locate a Turkish word list and keyboard layout that would be helpful. Also you can request to join the user interface string translation here: https://www.transifex.com/optikey/optikey/

Some keyboard layout info is available on the link in the first post on this page: https://github.com/OptiKey/OptiKey/issues/148

**Comment by JuliusSweetland** [comment]
Closing this issue as a new issue will be created when Turkish is ready to start (i.e. when the translation on Transifex is complete). Please reopen if you want to publish a keyboard layout or discuss before the translation is ready.
