### ISSUE TITLE
Localisation: Dutch

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#181]
**1.Transifex translation of UI strings:** 100% - Complete

**2.1.Netherlands Dutch Keyboard layout:**
![image](https://cloud.githubusercontent.com/assets/4722561/11516425/fbe794ce-987a-11e5-995d-345f32fe6f62.png)
**2.2.Belgian Dutch Keyboard Layout:**
![image](https://cloud.githubusercontent.com/assets/4722561/11516455/35feec20-987b-11e5-8449-cdea1a971747.png)

Special characters that need to be easy to get to: ?

**3.Word list:**

**4.Anything else:** There are at least 2 versions of Dutch that we need to consider; Netherlands Dutch and Belgian Dutch. The word lists for the two should be very similar, or the same, but the keyboard layouts differ (Netherlands use QWERTY, while Belgians use AZERTY). The layouts above are taken from google images and need confirmation.

**BRANCH:** 'Dutch' branch - awaiting pull request from @petermorlion

**Comment by petermorlion** [comment]
Great! I'll get on this.

I can not confirm the Netherlands QWERTY keyboard, but the Belgian is more or less correct. Mind you, it is an Apple keyboard which has some subtle differences:

 - It doesn't seem to include the Alt Gr key, which is necessary for certain characters. Although these are mostly keys not often used (maybe @ is an exception).
 - The top left key is usually ² and ³ (respectively non-shift and shift), whereas Apple puts in @ en #

**Comment by JuliusSweetland** [comment]
Hi Peter. I've merged your pull request into the new 'Dutch' OptiKey branch. Looks good. I believe the following are still 'in progress':

1.There is no Netherlands Dutch resource file so selecting this language for the UI results in OptiKey falling back to the English strings.
2.It looks like the use of the French layout for Dutch Belgium meets the Belgium layout above. I have extended this to also use the French Diacritic keyboard layout, which puts the àçéèù characters first.
3.The word lists are a bit short at 11k words.

I think we've touched on these issues before, but it's good to list them out so we can tick them off one at a time.

**Comment by petermorlion** [comment]
Cool! I'll get to work again this week.

Sent from my Windows Phone
________________________________

**Comment by JuliusSweetland** [comment]
I forgot:
4.Some of user interface strings (in the resource file) are a bit long. You'll notice that when you hover over the keys on the alpha keyboard (for example) the hover key text is small. This is caused by long text that could be broken over more lines. Effectively they are all scaled to the width of the widest string, so breaking "THIS LONG STRING" into
"THIS
LONG
STRING"
can increase the size of all other impacted keys.

Hopefully I've explained that well.

**Comment by petermorlion** [comment]
Ok, I'll work on it. You've already done number 2 of course. And I don't really know where we could get a comprehensive list of Dutch words. I'll keep that point for later and focus on 1 and 4 for now.

**Comment by Ar2rZ** [comment]
@petermorlion  you can extract most used words from different type of books- scientific, classic, popular literature. may be from some other popular reading sources.

**Comment by petermorlion** [comment]
I've created a [pull request](https://github.com/petermorlion/OptiKey/pull/1) for points 1 and 4.

@Ar2rZ You mention extracting words from books. Have you done this in an automated fashion? Do you have some script or application that can do this (based on an ebook, pdf, ...)?

**Comment by petermorlion** [comment]
About the translations. When we change something in the resx file, should we update Transifex online accordingly? Or is Transifex just a starting point?

**Comment by JuliusSweetland** [comment]
I'll upload the updated resx files to Transifex this evening. Thanks for
the reminder!

**Comment by Ar2rZ** [comment]
@petermorlion no, i don't have any scripts or app, but used somebodies work result to get Lithuanian dictionary. i can create an app after 16 December, as at the moment lack of time, if it still required.

**Comment by Ar2rZ** [comment]
http://wortschatz.uni-leipzig.de/Papers/top10000nl.txt

**Comment by petermorlion** [comment]
Cool, I'll see if I can maybe write a script to consolidate different words into one file, removing duplicates. Chances are slim I'll still manage to do that this year though.

**Comment by JuliusSweetland** [comment]
LinqPad or just Excel are good for this sort of task.

**Comment by petermorlion** [comment]
Cool, thanks for the tip.

Date: Thu, 17 Dec 2015 23:10:37 -0800

**Comment by JuliusSweetland** [comment]
@petermorlion Hi Peter - any joy with the Dutch dictionaries?

**Comment by petermorlion** [comment]
Haven't found the time, but I'll get to this ASAP. Sorry for the wait, and thanks for poking me back into action :)

**Comment by JuliusSweetland** [comment]
No rush, I've been busy too.

**Comment by petermorlion** [comment]
Well now, my words were barely typed, and I decided to do a new search for a wordlist and found one. I created pull request #200.

**Comment by JuliusSweetland** [comment]
@petermorlion It looks like Dutch Netherlands and Dutch Belgium are currently identical in terms of which keyboard layouts they use, UI strings (resource strings) and dictionaries. If that is correct then what do you think about just having Dutch Netherlands. If later we want to customise strings or dictionaries we can create Dutch Belgium - it just seems unnecessary at the moment. For example we have French France, but French is spoken is dozens of countries - at the moment we don't have specific French versions for these countries, so I chose not to split out all French country options as they would not actually be customised yet. Let me know what you think.

**Comment by petermorlion** [comment]
I must have made an error when merging or something. The Netherlands should use a QWERTY keyboard, while Belgium uses an AZERTY keyboard. But the language itself (resource file, dictionary) is the same (slight difference in dialects, but that would lead this project too far, IMO).

I'll look into it, see where I made a mistake, and fix it.

**Comment by JuliusSweetland** [comment]
Thanks for the clarification. Actually the mistake is probably mine as I
didn't look over the code properly. I'll double check.

**Comment by petermorlion** [comment]
I can't find any commit on my part, so possibly I had this locally and overwrote it when I merged in the latest changes from your branch. Anyway, I've created a new pull request (#121) that changes the Netherlands to use the QWERTY keyboard.

**Comment by JuliusSweetland** [comment]
Should the Dutch Netherlands alpha keyboard (alpha and conversation alpha)
not need the same additional accented characters as Dutch Belgium?

**Comment by petermorlion** [comment]
(continued in part from #201):

I'm not sure. The accented characters aren't on the physical keyboards used in the Netherlands, according to [Wikipedia](https://en.wikipedia.org/wiki/QWERTY#Dutch_.28Netherlands.29). :confused:

**Comment by JuliusSweetland** [comment]
Ok then in that case we can leave it as is, but I'll move the accented
characters to the first page of the diacritics keyboard.

It's the Dutch word list ok from your testing? Fast and complete enough?

**Comment by JuliusSweetland** [comment]
@petermorlion I was looking over the Dutch branch and I had a few thoughts:
1.The word list(s) could do with a bit of tidying up. They contain a lot of phrases (words with spaces in between), proper nouns, numbers, and one letter entries.
2.I think the keyboard layouts should look like this:
  a)Dutch Netherlands = Same as English Alpha/ConversationAlpha keyboards, but with the addition of these characters: éëïóöü in a new DutchNetherlands keyboard folder.
  b)Dutch Belgian = Same as French Alpha/ConversationAlpha keyboards, but with the addition of these characters: éëïóöü in a new DutchBelgium keyboard folder.
  c)Dutch diacritics keyboards, which position éëïóöü before the other characters. This is what is done for French and German at the moment.

What do you think? I know the real world Dutch Belgian keyboard is identical to the French AZERTY keyboard (https://en.wikipedia.org/wiki/AZERTY#Differences_between_the_Belgian_and_French_layouts_of_the_AZERTY_keyboard), but if it is useful to have easy access to éëïóöü then I think they belong on the Alpha keyboard.

Lastly I'm interested to know how OptiKey performs with the current Dutch word lists (roughly 343k words). On my laptop it's surprisingly quick.

**Comment by JuliusSweetland** [comment]
Oh, and I updated the Dutch branch with the latest translations from Transifex.

**Comment by petermorlion** [comment]
About 1. I've created pull request #219 for this. Let me know if you still think there's too much in there. I've been a bit careful about removing words, because I'm not always sure where you draw the line.

About 2. That sounds about right. The Belgian keyboard is indeed based off the French keyboard, but we use the éëóöü way less than in France. The ë might be an exception though, as it is used when there are two e's following each other. But I would say not often enough that it deserves its own key on the main keyboard.

Do you need a separate DutchNetherlands and DutchBelgian diacritics keyboard? Would one Dutch diacritics keyboard not suffice?

About the speed. I'd say it's instant on my laptop too. My laptop is an Acer Aspire with the following specs:

IntelCore i5-2430M at 2.4 Ghz
16 GB Ram
64bit Windows 10

I can't notice any delay between typing a letter and seeing the words appear.

**Comment by JuliusSweetland** [comment]
Excellent. I'll try to find time tomorrow to try the PR and t think about
the accented characters. Maybe I can include just the ë on the main alpha
keyboards without impacting the layout much, and then put all éëóöü at the
beginning of the diacritic keyboard for both Belgian and Netherlands Dutch
so they're easy to find if you need them. Sound reasonable?

**Comment by petermorlion** [comment]
Sounds very reasonable. But if OptiKey would be more maintainable if you just put the ë on the diacritics keyboard instead of the main keyboard (thus removing the need for an extra keyboard), that would be fine too I think. Especially as the words with the ë will be in the dictionary and users will be able to select them after choosing a few characters.

For example, poëzie (poetry): the user will select P-O-E-Z, and then poëzie is visible. I believe users would mostly use the suggested words after choosing some letters? Of is that not what you're aiming for? In that case, your solution is more than fine.

**Comment by JuliusSweetland** [comment]
@petermorlion I've spent a bit of time on the Dutch branch today creating customised Alpha/ConversationAlpha keyboards for both BelgiumDutch and NetherlandsDutch, as well as a shared (but Dutch specific) set of diacritic keyboards. I've also had a bit of a cleanup on the dictionary files, removing abbreviations, phrases (more than one word separated with a space in an entry), etc. I've got to add Dutch to the language keyboard, but see what you think.

**Comment by petermorlion** [comment]
@JuliusSweetland I've been busy again, but will check this tomorrow, over lunch. I'll keep you posted.

**Comment by JuliusSweetland** [comment]
Thanks Peter

**Comment by petermorlion** [comment]
Looks fine by me. I'm just wondering about the diacritics keyboard. Some characters are never going to be used in Dutch. Do you want me to remove them, or list them for you to remove?

**Comment by JuliusSweetland** [comment]
Are you referring to the first set of characters on the first row of
diacritic keyboard 1?

**Comment by petermorlion** [comment]
Ah, I see what you did now. It includes all diacritic characters. Just the first row is Dutch specific. I'd argue the ó could be removed there (from the first line). It's not used very often (perhaps in city names or so). Unless you want to be complete.

Other than that, I think your good for the Dutch keyboards and dictionaries.

**Comment by JuliusSweetland** [comment]
@petermorlion Great. I have a few small features & fixes that I want to add to the next release, but I will aim to get Dutch released fairly soon as part of v2.2.4. Thanks for your work.

**Comment by petermorlion** [comment]
Happy to help out. It's a great product!

**Comment by JuliusSweetland** [comment]
@petermorlion Dutch candidate release is now here: https://github.com/OptiKey/OptiKey/releases/tag/v2.2.4_pre-release_1

Could you please test it out? If you're happy then I'll release it as v2.2.4.

Thanks.

**Comment by JuliusSweetland** [comment]
@petermorlion Slightly updated new Dutch release candidate:

https://github.com/OptiKey/OptiKey/releases/tag/v2.2.4_pre-release_2

I'm ready to release I'm just waiting for you to green light it. Thanks.

**Comment by JuliusSweetland** [comment]
Released as v2.2.4

**Comment by petermorlion** [comment]
Hey @JuliusSweetland, sorry for the late reply again. Looks fine by me, but Arjen already checked it out too. Cool to see it released!
