### ISSUE TITLE
Keys always in front of calibration screen

### ISSUE THREAD

**Issue by gwaynieb** [OptiKey/OptiKey#197]
When recalibrating the OptiKey key screen stays in front of the calibration. Thanks for any guidance.

**Comment by JuliusSweetland** [comment]
I am aware of this issue when using the new version (2.0.2.219) of the Tobii EyeX software - is this where you see the problem?

**Comment by gwaynieb** [comment]
Yes. Is there a fix?

**Comment by JuliusSweetland** [comment]
Not yet. I'll look into this soon. In the interim you can roll back to a
previous version of the Tobii software.

**Comment by gwaynieb** [comment]
The tobii update solved the windows update problem that was shutting down the tobii.

**Comment by JuliusSweetland** [comment]
Could you provide more details on the Tobii problem? I'm out of the loop.

**Comment by JuliusSweetland** [comment]
Issue found and fixed in next release (2.2.3). This may be slightly delayed as I intend to include some new functionality. In the mean time please down grade your version of the Tobii EyeX software to the previos version (< 1.8)
