### ISSUE TITLE
Help display

### ISSUE THREAD

**Issue by feugy** [OptiKey/OptiKey#199]
With the addition of voice recognition, users will feel the need to easily access to some help pages.
The case I have in mind is to display the numerous vocal commands.

Currently, they are customizable from the Management Console, which is not accessible because inputs are suspended when it's open.

My first idea was to open on demand a popup with the list, something like the ToastNotification.
But after a while, I though that the modal feature of a popup is not acceptable for displaying help information, that may stay in background if user is not so confident.

My proposal is:
- use a simple browser to display help HTML pages.
- pages should be local, to allow their access even without network
- pages should contain dynamical sections: the voice commands are customizable, and displaying default values wouldn't be enough.

I suggest to use [markdown](https://github.com/Knagis/CommonMark.NET/) and [Mustache](https://github.com/jehugaleahsa/mustache-sharp). 
Markdown will ease the authoring process, and the translation work, while enforcing a certain style consistency.
A template engine like Mustache (wellknown in JS ecosystem) will allow customization.

Your advices and opinions are welcome !

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
