### ISSUE TITLE
How to configure optikey in my computer

### ISSUE THREAD

**Issue by bsimionato** [OptiKey/OptiKey#215]
Please, I need help to configure the program in my computer, I have already downloaded but I´m not getting use.

Please, if exist a manual or instructions, please let me know.

Thanks in advance, 

Bárbara.

**Comment by JuliusSweetland** [comment]
Hi Barbara,

The wiki contains information about getting started: https://github.com/OptiKey/OptiKey/wiki/Get-Started

I'll close this issue for now - please re-open if you are still having problems. Or email me at optikeyfeedback@gmail.com
