### ISSUE TITLE
Usage count not updated correctly

### ISSUE THREAD

**Issue by EddPorter** [OptiKey/OptiKey#217]
When typing multiple words and using the auto complete suggestions to complete each one, the  completed word's usage count is decremented incorrectly when the next key is selected. If the user uses the space key to separate the words, then the usage count is done correctly.

Possibly, using the auto-complete suggestions should place a space after the word so that the look-back doesn't see it.

**Comment by Kerl1310** [comment]
I'm interested in getting involved in this project and have some experience with C#

**Comment by JuliusSweetland** [comment]
@Kerl1310 Hi - that's great. Do you want to look over the issues https://github.com/OptiKey/OptiKey/issues/ and let me know which one you want to take a look at? I can give you any info that you need to get started once we know what you're interested in.
