### ISSUE TITLE
Multiple Dictionaries

### ISSUE THREAD

**Issue by EddPorter** [OptiKey/OptiKey#218]
The `DictionaryService` and the `IAutoComplete` implementations both track dictionary entries. The auto complete dictionaries use (potentially) different storage methods for lookup, which is where the complication lies. Ideally, there'd be a single data structure containing the word entries and usage counts. Indexes would be created as need for the different systems that need to access it.

Considerations:
- adding new words
- removing words
- updating usage counts

**Comment by alexandre-mbm** [comment]
is it about sharing data between two or more assessors?

**Comment by Chopinsky** [comment]
I will take a look at this issue. From the face value, the different ways of storing word counts might be the cause of issue #217.
