### ISSUE TITLE
Hide cursor when using mouse as input.

### ISSUE THREAD

**Issue by kirstymcnaught** [OptiKey/OptiKey#229]
It's useful to be able to use the mouse input option to extend OptiKey for use with sensors that aren't directly supported, but do offer mouse emulation - for example the EyeTech TM5. However, when controlling the cursor with an eye tracker, any errors in the mouse position (jitter or drift) are very distracting when you're trying to dwell on a key. In a worst case scenario, the mouse cursor drags your attention away from the button. 

I've already got the implementation to add an option in the management console to hide the cursor when over the OptiKey UI. This seems to make things a lot better. It isn't working on the edit box though - this seems to have its own setting. 

Video demo - https://youtu.be/FPFjTmPz4wE

**Comment by JuliusSweetland** [comment]
@kirstymcnaught Would either of the 2 solutions in this article suffice: http://www.jholjhaal.com/hide-mouse-cursor-on-windows-with-mouse-pointer-scheme/

**Comment by kirstymcnaught** [comment]
Yes, that's a much better solution. Shall I add something to the wiki to point people there?

**Comment by JuliusSweetland** [comment]
Good idea, thanks

**Comment by JuliusSweetland** [comment]
Closing issue as alternative solutions found
