### ISSUE TITLE
Localisation: Portuguese

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#234]
**1.Transifex translation of UI strings:** 100%

**2.Keyboard layout:**
2 layouts - Portugal and Brazil

![image](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/KB_Portuguese.svg/2000px-KB_Portuguese.svg.png)

_Portugal:_
![image](https://cloud.githubusercontent.com/assets/4722561/13476177/7a90ad98-e0be-11e5-8c4e-fe6fdbb86e43.png)
http://ascii-table.com/keyboard.php/163

_Brazil:_
![image](https://cloud.githubusercontent.com/assets/4722561/13476149/590de5b4-e0be-11e5-8076-f04f30864cc3.png)
http://ascii-table.com/keyboard.php/275

**3.Alphabet:**
a)Letters: 26 individual "cardinal" letters - a-z (lower and upper)

b)Diacritics that can be added to individual letters (these will be dead keys): 
acute accent (áéíóú)
circumflex accent (âêô)
grave accent (à)
tilde (ãõ)
cedilla (ç)
There are also references on some sites to the use of a diaeresis on the letter u: ü - is this used in modern Portuguese (in Portugal or Brazil)?

Total: 31 keys

**4.Word list:** None yet - we need one

**5.Branch:** None yet

**Comment by rfcar** [comment]
Hey there, i can help with the brazilian portuguese.

2. The brazilian keyboard looks good. Is it going to have both?

3. Letters and diacritics are correct. The  ¨ (ü)  diaeresis has been abolished in portuguese from Brazil, but it is still used in foreign words, like "Müller". I believe the same happens in Portugal, but i'm not sure.

4. [This](http://alcor.concordia.ca/~vjorge/Palavras-Cruzadas/Lista-de-Palavras.txt) list contains about 29850 lines, but it looks good. I also found a list with more (300k), but it was filled with garbage and very unusual words, so i believe this one is better. Do you think we need more?

5. How do you guys proceed with the branches? Do you create it yourself when the language you are working on is complete?

**Comment by JuliusSweetland** [comment]
@rfcar Answers:
1. Yes, both.
2. Are foreign words that need the diaeresis used commonly enough to justify having a diaeresis key on the main Alpha keyboard,  or would it be sufficient for the user to have to navigate to the Diacritic keyboard instead?
3.The small size is not hugely significant if the word list is good quality. I can see two small issues with that list: all entries are in capitals (they should be lowercase, unless they are a proper noun, an acronymn, or need to be capitalised in some way for some reason), and there are single character entries (which is not a problem - I have a piece of code to clean that up). Could you take a look and let me know if you would be able to manually correct the casing? 30k words is a lot to parse manually though!
4.When we have everything ready I will create a Portuguese branch. If I create one too early it will be very out of date (relative to master) when we come to use it and there will need to be a manual pull and merge. Not a huge deal, but I like to wait until we're ready to go to avoid the extra work!

**Comment by rfcar** [comment]
@JuliusSweetland 

1. Cool, that's great.

2. It is not common to use it, so i believe it is not necessary in the main keyboard.

3. Sure, here you go. I changed all to lowercase, removed single characters and some inappropriate words. I just left capitalized some abbreviations that i remembered , like ONU (the UN). [wordlist_pt-BR.txt](https://github.com/OptiKey/OptiKey/files/198205/wordlist_pt-BR.txt)

4. Ok, got it.

**Comment by JuliusSweetland** [comment]
@rfcar Actually I've just looked at the 2 layouts more closely and it doesn't look like there's any benefit to having 2 as the main letters are all in the same places, right?

**Comment by JuliusSweetland** [comment]
@rfcar Also great work on the word list!

**Comment by rfcar** [comment]
@JuliusSweetland You're right, apparently the only difference is the disposition of the accents, but as that stays in a secondary keyboard, it should not be a problem.

**Comment by aluizmv** [comment]
Hi Julius, do you have any news about Portuguese Optikey?
Can I help?
Thank you

**Comment by JuliusSweetland** [comment]
@aluizmv @rafael-ac Hi - apologies for the lack of progress with Portuguese. I can work on Portuguese this week if you guys are available to help? If we are happy with the 30k word list (https://github.com/OptiKey/OptiKey/files/198205/wordlist_pt-BR.txt), then we need to start work on the keyboard layout. As it's straightforward I am happy to do this.

Would one or both of you take a look at the Transifex translation for Portuguese (https://www.transifex.com/optikey/optikey/viewstrings/#pt/english-strings-from-resourceresx/97847666?translated=no) - there are a handful of words/phrases that need to be translated, but DON'T bother translating the language string (e.g. "Turkish (Turkey) / Türkçe (Türkiye)") as these get used as they are.

**Comment by aluizmv** [comment]
The list of 30k Words is ok.

Em 30 de out de 2016 5:10 PM, "Julius" <notifications@github.com> escreveu:

**Comment by aluizmv** [comment]
Dear Julius, there is an error on Transifex translation for Portuguese, an
error to access the servidor!
Prease check it.
Tks

2016-10-30 17:10 GMT-02:00 Julius <notifications@github.com>:

**Comment by JuliusSweetland** [comment]
Transifex is working for me?

**Comment by aluizmv** [comment]
Please accept me at Portuguese translate team.
Tks
Aluizmv

Em 2 de nov de 2016 9:11 AM, "Julius" <notifications@github.com> escreveu:

> Transifex is working for me?
>

**Comment by JuliusSweetland** [comment]
Done

**Comment by aluizmv** [comment]
Done!
Please check, not translate only languages!
Ok?

Em 3 de nov de 2016 4:34 AM, "Julius" <notifications@github.com> escreveu:

> Done
>

**Comment by JuliusSweetland** [comment]
Looks good, thank you

**Comment by aluizmv** [comment]
Is there anything else that I can do?

Em 3 de nov de 2016 7:24 AM, "Julius" <notifications@github.com> escreveu:

> Looks good, thank you
>

**Comment by JuliusSweetland** [comment]
Are you a C# & WPF developer? If so then I can guide you through the
localisation process, otherwise I'll pick this up asap.

**Comment by aluizmv** [comment]
Sorry but I am not!
I'm looking for hearing from you!
Bests

Em 3 de nov de 2016 7:31 AM, "Julius" <notifications@github.com> escreveu:

> Are you a C# & WPF developer? If so then I can guide you through the
> localisation process, otherwise I'll pick this up asap.
>

**Comment by aluizmv** [comment]
Hi Julius! How are you?  Do you have any news about Portuguese version? Can I help you ? Thanks Antonio Luiz 

Enviado do Yahoo Mail no Android 
 
  Em 7:40 AM Qui, 3 de nov de AM, aluizmv .<aluizmv@gmail.com> escreveu:   
Sorry but I am not!  
I'm looking for hearing from you! 
Bests

Em 3 de nov de 2016 7:31 AM, "Julius" <notifications@github.com> escreveu:

Are you a C# & WPF developer? If so then I can guide you through the
localisation process, otherwise I'll pick this up asap.

**Comment by JuliusSweetland** [comment]
Hi. I'm afraid I've not started it yet. I will set aside time on Thursday
evening and hopefully break the back of it.

**Comment by JuliusSweetland** [comment]
v2.3.7 (here: https://github.com/OptiKey/OptiKey/releases) is a pre-release which includes Portuguese - please can you test this. I think the dictionary is a bit small and doesn't seem to include any accented words. We should replace this with a better dictionary file if you agree, but everything else can be tested. Let me know.

**Comment by aluizmv** [comment]
Tks Julius!  I will test it ASAP. 

Enviado do Yahoo Mail no Android 
 
  Em 8:45 PM Qui, 10 de nov de PM, Julius<notifications@github.com> escreveu:   
v2.3.7 (here: https://github.com/OptiKey/OptiKey/releases) is a pre-release which includes Portuguese - please can you test this. I think the dictionary is a bit small and doesn't seem to include any accented words. We should replace this with a better dictionary file if you agree, but everything else can be tested. Let me know.

**Comment by aluizmv** [comment]
Hi Julius!
V2.3.7 looks great.
I will take it to the hospital today, my mother will test it too.
Hey, it is Portuguese Brasil, Not Portuguese Portugal.
Thank you very much!


2016-11-10 20:45 GMT-02:00 Julius <notifications@github.com>:

**Comment by JuliusSweetland** [comment]
Good news. At the moment Portuguese Portugal and Portuguese Brazil would be
the same (same layout, same language rules, and same dictionary). If we
differ on any of those then I can split it out into two.

**Comment by aluizmv** [comment]
Julius, sorry to say that the test was not goid.I left the hospital few minutes ago. It was very dificult to her to focalize the letters.And we found that problem when we left the program at Conversation mode. The same problem that we had another day.Another problem is the size of the letters in Portuguese keyboard. The letters are small, to many buttons. Thank you very much!


Enviado do Yahoo Mail no Android 
 
  Em 11:16 AM sex, 11 de nov de AM, Julius<notifications@github.com> escreveu:   Good news. At the moment Portuguese Portugal and Portuguese Brazil would be
the same (same layout, same language rules, and same dictionary). If we
differ on any of those then I can split it out into two.

**Comment by JuliusSweetland** [comment]
Sorry to hear that. What size screen are you using and do you think it
would help if OptiKey was slowed down, i.e. selections took longer and were
more tolerant of losing focus? There are a load of settings we could try
tweaking.

**Comment by aluizmv** [comment]
Notebook 15"We could try the settings... What do I have to do?
Enviado do Yahoo Mail no Android 
 
  Em 2:48 PM sex, 11 de nov de PM, Julius<notifications@github.com> escreveu:   Sorry to hear that. What size screen are you using and do you think it
would help if OptiKey was slowed down, i.e. selections took longer and were
more tolerant of losing focus? There are a load of settings we could try
tweaking.

**Comment by JuliusSweetland** [comment]
Take a look here:
https://github.com/OptiKey/OptiKey/wiki/Speed-up-&-slow-down

I think it's largely up to date

**Comment by aluizmv** [comment]
I will try, and the problem with Conversation mode?

Enviado do Yahoo Mail no Android 
 
  Em 2:54 PM sex, 11 de nov de PM, Julius<notifications@github.com> escreveu:   Take a look here:
https://github.com/OptiKey/OptiKey/wiki/Speed-up-&-slow-down

I think it's largely up to date

**Comment by JuliusSweetland** [comment]
Can you describe the problem again?

**Comment by JuliusSweetland** [comment]
Are you saying that you stay OptiKey, open the conversation keyboard,
navigate back to menu, quit, restart OptiKey and it doesn't fill the
screen? If so it's because there is a setting which controls the startup
keyboard. Open the management console and change the startup keyboard to
Conversation Letters.

If I've misunderstood could you explain.

**Comment by aluizmv** [comment]
Julius, I did it, and reset the optikey.. Now everything looks OK..Tomorrow I wilk test with my mother. Let's find another Portuguese list. Thank you.

Enviado do Yahoo Mail no Android 
 
  Em 3:17 PM sex, 11 de nov de PM, Julius<notifications@github.com> escreveu:   Are you saying that you stay OptiKey, open the conversation keyboard,
navigate back to menu, quit, restart OptiKey and it doesn't fill the
screen? If so it's because there is a setting which controls the startup
keyboard. Open the management console and change the startup keyboard to
Conversation Letters.

If I've misunderstood could you explain.

**Comment by alexandre-mbm** [comment]
> At the moment Portuguese Portugal and Portuguese Brazil would be the same (same layout, same language rules, and same dictionary). If we differ on any of those then I can split it out into two.

@JuliusSweetland, split it please! Me and my brother @alandbm will work in brazilian portuguese up to the optimal.

**Comment by alexandre-mbm** [comment]
Interested persons in Portuguese of Brazil, see: ENE/OptiKey#2

The common results will are returned to the mainstream.

**Comment by alexandre-mbm** [comment]
Interested persons in improving the Portuguese dictionary, see #285 please.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm Pre-release 3 of v2.3.7 has just been released here; https://github.com/OptiKey/OptiKey/releases - It includes your new dictionary. Please test and let me know if it is ready for general release. Great work guys.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, the my father's notebook is without power supply until Tuesday. It was as model for accessibility adjustments. But okay! Until there I am will test OptiKey remotely in my brother's desktop computer. Also my OptiDic manipulator will be enabled to incremental improvements in dictionaries.

**Comment by aluizmv** [comment]
Hi Julius!  In my opinion it is OK!My mother tks you!Thank you!

Enviado do Yahoo Mail no Android 
 
  Em sáb, 19 nov, 2016 às 1:44 PM, Julius&It;notifications@github.com> escreveu:   
@alexandre-mbm Pre-release 3 of v2.3.7 has just been released here; https://github.com/OptiKey/OptiKey/releases - It includes your new dictionary. Please test and let me know if it is ready for general release. Great work guys.

**Comment by JuliusSweetland** [comment]
Excellent. I will convert it into an official release very soon then. All
the best to your family.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, I did not make extensive tests, but I am with the impression of that the algorithm based in counters is bad or will require very time to work. I am wanting to force the counters to increase, for more relevante words in my father vocabulary. Can I edit dictionary file that is for use (user data), is not?

**Comment by JuliusSweetland** [comment]
The counter in the dictionary should increase when you type or select a word. As these counters increase the chosen words will be selected before other matches. If you want to initialise the dictionaries, you could manually edit the dictionaries stored here, but it shouldn't be necessary: C:\Users\YOUR_USER_NAME\AppData\Roaming\JuliusSweetland\JuliusSweetland\OptiKey\Dictionaries 

I will be closing this issue now as Portuguese support has been officially released. Please open a new bug issue if you think word usage count is not working.

**Comment by aluizmv** [comment]
Hi Julius! When will you release a new version with Portuguese support? Tks

Enviado do Yahoo Mail no Android 
 
  Em seg, 21 nov, 2016 às 6:42 AM, Julius&It;notifications@github.com> escreveu:   
The counter in the dictionary should increase when you type or select a word. As these counters increase the chosen words will be selected before other matches. If you want to initialise the dictionaries, you could manually edit the dictionaries stored here, but it shouldn't be necessary: C:\Users\YOUR_USER_NAME\AppData\Roaming\JuliusSweetland\JuliusSweetland\OptiKey\Dictionaries

I will be closing this issue now as Portuguese support has been officially released. Please open a new bug issue if you think word usage count is not working.

**Comment by JuliusSweetland** [comment]
Hi. It is released! V2.3.7

**Comment by aluizmv** [comment]
Great, so do not forget to update information at LANGUAGE SUPPORT page.Tks

Enviado do Yahoo Mail no Android 
 
  Em qua, 23 nov, 2016 às 10:34 AM, Julius&It;notifications@github.com> escreveu:   Hi. It is released! V2.3.7

**Comment by JuliusSweetland** [comment]
@aluizmv Good point! Done...
