### ISSUE TITLE
Localisation: Catalan

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#235]
**1.Transifex translation of UI strings:** Complete

**2.Keyboard layout:**
![image](https://cloud.githubusercontent.com/assets/4722561/13410154/1a9388b6-df2e-11e5-95fb-6e60996626d7.png)
http://ascii-table.com/keyboard.php/071-1

**3.Alphabet:**
a)Letters: 26 individual letters - https://en.wikipedia.org/wiki/Catalan_orthography#Alphabet
a-z (lower and upper case) - it does NOT have Spanish's extra letter ñ

b)Diacritics that can be added to individual letters (these will be dead keys): 
acute accent - used on í, é, ó, ú (lower and upper cases)
grave accent - used on à, è, ò (lower and upper cases)
diaeresis - used on ï, ü (lower and upper case)
cedilla - used on ç

c)Other keys: 
apostrophe
interpunct / middle dot (https://en.wikipedia.org/wiki/Interpunct#Catalan) - used like this "l·l" - two normal "l" with a floating dot in the middle

Total: 31 keys

c)Complexity: _nothing so far..._

**4.Word list:** CatalanSpain.dic on master branch - 130k

**5.Anything else:** "¿" and "¡" characters are not used.

**6.Other:** Spanish & Catalan will be developed separately - their differences are greater than originally though. Spanish localisation is here: https://github.com/OptiKey/OptiKey/issues/149

**BRANCH:** None yet

**Comment by JuliusSweetland** [comment]
@utacub Catalan branch created here: https://github.com/OptiKey/OptiKey/tree/Catalan

**Comment by utacub** [comment]
OK! We have followed the steps in Localize.md to add Catalan. Maybe, we could copy (or adapt) the Spanish keyboard layout once it is done.

**Comment by JuliusSweetland** [comment]
@utacub I included you on my post on issue #262 but I'll post it again here - Spanish is in pre-release and all the code is on the master branch if you'd like to take a look and adapt it for Catalan?

**Comment by utacub** [comment]
OK, I think that Catalan is now ready. Would you mind having a look at: https://github.com/OptiKey/OptiKey/pull/266 ?

Thanks!
First time using git/github 😅

**Comment by JuliusSweetland** [comment]
@utacub I will be releasing Croatian this evening. Italian is ready to go next, and then I'll be pushing out Catalan. I'll be in touch as soon as I get to test your work. Thank you for your effort!

**Comment by utacub** [comment]
Hi @JuliusSweetland 
Are there any news or approximate dates for the Catalan version release?
We have some users eager to use it.
Also, for future versions, is it possible to add Microsoft Speech Platform (https://www.microsoft.com/en-us/download/details.aspx?id=27225) compatibility for the TTS voices?

Thank you for you work!

**Comment by JuliusSweetland** [comment]
@utacub Hi - Sorry for the delay. I will look at Catalan next week. Regarding the MS Speech Platform - are these voices not currently supported? OptiKey should support any SAPI voice.

**Comment by utacub** [comment]
Ok @JuliusSweetland, no problem.
About the voices, Microsoft Speech Platform and SAPI are recognised as different speech engines, you can see the differences in a table here: https://msdn.microsoft.com/en-us/library/jj127858.aspx

**Comment by JuliusSweetland** [comment]
@utacub Ok I remember the difference here; Microsoft.Speech is basically server based, whereas System.Speech (which OptiKey uses) is OS based. What would be the advantage of supporting the MS Speech Platform>

**Comment by utacub** [comment]
@JuliusSweetland MS Speech Platform has more quality voices for more languages (for example, the catalan voice, called Herena, is only available through that engine) and can also be installed locally for free. Some free TTS software, like Balabolka (http://www.cross-plus-a.com/balabolka.htm), can already use this engine, and it works very well.

**Comment by JuliusSweetland** [comment]
Understood. I'm not going to be able to look for a few weeks, but I will
take a proper look at this at the same time as Catalan.

**Comment by JuliusSweetland** [comment]
@utacub Sorry it's taken so long, but I've merged Catalan into master now. I'll perform a bit of testing and then prepare a pre-release version for you to try. One thing - there is a missing translation of "TOBII_EYEX_DATA_STREAM_PROCESSING_LEVEL", which in English is "Data stream processing amount:". In the Catalan branch it only contains "Q". Could you please correct this?

**Comment by utacub** [comment]
@JuliusSweetland Sorry about the missing translation, it has been fixed. Thank you.

**Comment by JuliusSweetland** [comment]
@utacub and all - I am assuming v2.3.8 is good and will be promoting it to an official release now. Thanks for all your hard work.
