### ISSUE TITLE
Screen freezes when change language to Dutch (Nederland)

### ISSUE THREAD

**Issue by Joostvt** [OptiKey/OptiKey#241]
Hello, 

My screen freezes when I choose the Dutch language.

Does someone know an option?

**Comment by JuliusSweetland** [comment]
@Joostvt It should return and work correctly again after a few seconds. It is because the Dutch dictionary is HUGE compared to other languages. I have a change coming that reduces the dictionary size to reduce (but not eliminate) this problem.
