### ISSUE TITLE
Simplified menu

### ISSUE THREAD

**Issue by PiotrKurnik** [OptiKey/OptiKey#244]
Hi, 
I don't know it this feature was already discussed or not. It would be nice to have a simplified keyboard. Could we have a keyboard that is similar to Microsoft's tiles. Each tile would have a graphical symbol on it and clicking it would automatically generate message, including text to speech feature. Examples include: 'I want to eat', 'I am thirsty' and so on. Using eye tracker and full keyboard is a bit of a challenge for some and I am looking for ways of simplifying that. 

Is that possible? What does that take to make feature?

**Comment by JuliusSweetland** [comment]
@PiotrKurnik This is possible. Another user is looking into a similar idea already: https://github.com/OptiKey/OptiKey/issues/242

I've just added some comments to their issue so I'll close this one and we can continue on issue 242.

**Comment by alexandre-mbm** [comment]
@PiotrKurnik, do you want [AAC](https://en.wikipedia.org/wiki/Augmentative_and_alternative_communication) boards like happens in the softwares Grid 2 and GazeSpeaker, right?!

![AAC boards](https://upload.wikimedia.org/wikipedia/commons/c/c3/Sample_page_from_AAC_communication_book.png)
