### ISSUE TITLE
Mouse down/up buttons in inconsistent state

### ISSUE THREAD

**Issue by kirstymcnaught** [OptiKey/OptiKey#252]
Using version 2.3.0, publishing keys (alphanumerics) causes mouse down/up _keys_ to be released, without releasing the accompanying _mouse state_. 

- Go to the mouse keyboard in OptiKey
- Turn on mouse left button down/up 
   - The mouse left down/up key is held down (blue).
   - The mouse's left button is actually held down 
- Go to the alpha keyboard, type something.
- Return to the mouse keyboard
   - The mouse left down/up key has been released, but...
   - The mouse's left button is _still_ held down and has to be released by toggling the key on and then off again.

I'm not sure what the intended behaviour is, but whatever it is, the key state should match.

Video demo here:
https://youtu.be/MFo5YrSD5lE

**Comment by JuliusSweetland** [comment]
Fix will be included in the upcoming release v2.3.2. Closing issue.
