### ISSUE TITLE
Preset short phrases in conversation mode (only?)

### ISSUE THREAD

**Issue by emazero** [OptiKey/OptiKey#258]
Let users save some short phrases for a quick use while in conversation mode.
Phrases might be available in the suggestions navigation bar when scratchpad is empty (now unused).
As you start write, suggestions start work as usual
More: phrases may be read immediatly ( 'Speak' button not needed) when clicked

**Comment by JuliusSweetland** [comment]
@emazero This is already possible. If you type a phrase, e.g. "how are you" and then select the 'AddToDictionary' key (left side of the scratchpad) OptiKey will offer to add the whole phrase to the dictionary, as well as any words it doesn't already know about. Once added you can recall the phrase by typing "h", "ho", "how", etc until the phrase is suggested, or the shortened version "hay" (the first letter of each word). You can even type just "ha" which might be enough to bring up "how are you" as a suggestion.

I'm closing this issue as the feature exists.

A little more info about phrases exists on this page: https://github.com/OptiKey/OptiKey/wiki/Multi-key-selection

**Comment by emazero** [comment]
@JuliusSweetland I already knew about this feature and it's very helpful. 
My suggestion is to improve much more the conversation speed, showing the most used phrases above the scratchpad (when empty) and let users recall/speak them just clicking on it once.
As you say you now have to type some letters, select the phrase and Speak it. 
Let's say I want to say ' How are you' (saved before) => h...a...select...speak = 4 actions (4-5 sec)
With my solution I could find it above the scratchpad and say it in just 1 action (presets don't need Speak button)
Short phrases like Yes/No/I don't know/Let's go/I'm hungry/I'm thirsty ecc.. could be managed in this way.
Of course it's just an idea and it comes from to my observation in using Optikey by people suffering from ALS, and (..I'm a UX Designer) asking them if it could help.
Sorry for my Engish

Thanks
Emanuele

**Comment by JuliusSweetland** [comment]
@emazero I think this could be a smallish enhancement to this issue:
https://github.com/OptiKey/OptiKey/issues/242 - could you add a few lines
about your idea to that issue? Thanks.
