### ISSUE TITLE
Localisation: Croatian

### ISSUE THREAD

**Issue by vdjerek** [OptiKey/OptiKey#263]
![image](https://cloud.githubusercontent.com/assets/19509606/15453740/07a484e2-2021-11e6-9248-853fd505959f.png) 

This is a Croatian localization project issue for the OptiKey - a place to discuss issues related to the translation of the OptiKey to Croatian language. 

**Important information:**

**Translation of the UI strings** - completed in Transifex. Some translations will probably need fine tuning after beta testing, help will be needed with this.

**Alphabet** -  Croatian language uses [Gaj's latin alphabet](https://en.wikipedia.org/wiki/Gaj%27s_Latin_alphabet), which is the same as in Slovenian.Special characters are Č, Ć, Š, Đ and Ž. In practice, the letters Dž, Nj and Lj are always written using two letters, so no special digraphs are needed.

**Keyboard layout** - Croatian and Slovenian share the same keyboard layout. It can be found here: http://ascii-table.com/keyboard.php/234-1
![image](https://cloud.githubusercontent.com/assets/19509606/15453664/fb96cdba-201e-11e6-99a1-00fc02e0a037.png)

**Dictionary** - I propose the default dictionary that comes with Android be used (https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/master/dictionaries/), which also features the word frequency. Less used words could be filtered out to reduce the size of the dictionary (~210k words)
[Android hr_wordlist.combined] (https://github.com/OptiKey/OptiKey/files/276269/hr_wordlist.combined-orig.txt.zip)

**Comment by JuliusSweetland** [comment]
@vdjerek excellent info. I think the dictionary should be cut down to 100k-150k. I've created a beach for you here: https://github.com/OptiKey/OptiKey/tree/Croatian

Due to the strong cross over with Slovenian would you consider tackling looking at that after Croatian? I'm being a bit slow at the moment and I know people would really appreciate it.

**Comment by vdjerek** [comment]
Sure, will try to help if I can. I'll first try to play with Visual Studio and see how that goes, hope I won't have to trouble you with questions too much.

**Comment by JuliusSweetland** [comment]
I'm happy to help if you have questions.

**Comment by vdjerek** [comment]
I did all the steps from the guide at https://github.com/OptiKey/OptiKey/blob/master/docs/Localize.md, but I don't have the  push access to the repository, so I can't upload the files. Also, I'm not really sure how to test if it works, I could use some guidance - compiled OptiKey.exe crashes, but there are no build errors. It'd be great if I could commit so you could check if it works.

Best,

V.

**Comment by JuliusSweetland** [comment]
@vdjerek The usual steps are to FORK my Croatian branch of the OptiKey repo, which creates your own version of the repo and branch. You then make the changes to that and PUSH them from your computer to GitHub (to your forked repo on GitHub). Once you are happy with everything you then create a PULL REQUEST for your changes to be pulled back into my repo.

In terms of the crash: you should run in Debug mode within visual studio. By default it will halt execution at the point where the exception is thrown and you can debug the problem.

**Comment by vdjerek** [comment]
A working Croatian version can be found at https://github.com/vdjerek/OptiKey - further testing is needed, but things seem to mostly work. I had to rearrange the layout of the language selection menu due to adding one more language, and I probably broke something, since now you can't select Croatian from the main UI, only from the Alt+M console - I'll look into that in the future. 
Further testing is needed; if someone needs a compiled version please let me know. Dictionary also needs tuning, there seem to be too many words, especially the short ones. I don't think it's time for a pull request yet, though. I just received an eyeX, so after some more testing I'll probably be happy with everything.

![image](https://cloud.githubusercontent.com/assets/19509606/15635048/76978b8e-25d4-11e6-8ec7-402acbb3b825.png)

**Comment by JuliusSweetland** [comment]
I'm happy to help with the language keyboard problem if you create a PR?

**Comment by vdjerek** [comment]
Ok, great, created a pull request

**Comment by JuliusSweetland** [comment]
@vdjerek Great work - I have a few small changes to make tomorrow, and then I will create a pre-release candidate for you to test. I'll update here when it's ready.

**Comment by JuliusSweetland** [comment]
@vdjerek Is an apostrophe (') commonly used in Croatian? If not I want to remove it from the main alpha keyboards and use the key for one of the other letters.

**Comment by vdjerek** [comment]
@JuliusSweetland  - no, the apostrophe can go, it's practically never used - however, I'd like to keep the other special letters where they are - š,đ,ž,č and ć have a well defined position on every Croatian keyboard. In the place where now is apostrophe usually a hyphen stands (-, and _ with shift).

Great about the pre-release, looking forward to it. I'd still like to improve the dictionary in the future, though, but it would be great to release so people can start using the translation as soon as possible.

**Comment by JuliusSweetland** [comment]
@vdjerek I've tried a few ways to make the š,đ,ž,č and ć keys fit, but the problem is if they are put in the "correct" place they add 3 columns to the keyboard, which leaves a lot of blank keys. Ideally the keyboard should be full as this allows each key to be as large as possible, which is hugely important when using an inaccurate eye tracker! See what you think of this:

![image](https://cloud.githubusercontent.com/assets/4722561/15789646/3f39e872-29c5-11e6-831c-4c364149f5bc.png)

**Comment by JuliusSweetland** [comment]
And this is the conversation screen:

![image](https://cloud.githubusercontent.com/assets/4722561/15791065/18f64df6-29cd-11e6-9a47-1da1d37f2a11.png)

**Comment by JuliusSweetland** [comment]
@vdjerek All changes have been pushed to the Croatian branch, including a rudimentary cleanup of the dictionary. See what you think and let me know.

**Comment by vdjerek** [comment]
@JuliusSweetland Great, looks good! I guess everybody can live with those changes, especially if they contribute to accuracy. I'll look everything over, but I'm sure it's all fine now. Thanks for your efforts, we all really appreciate it!

**Comment by JuliusSweetland** [comment]
@vdjerek It's not an ideal layout, but there have to be a few compromises here and there! I look forward to your feedback after you've tested it properly.

**Comment by JuliusSweetland** [comment]
@vdjerek How is the Croatian build looking? If it's good I can create a candidate release today.

**Comment by vdjerek** [comment]
@JuliusSweetland It looks good. I had some problems though, I wasn't able to access the Alt+M console - it would work every 10th time or so. Also, the cursor, be it EyeX or mouse, didn't work outside of the Letters keyboard (inside the menu). I had to reset everything to factory defaults by deleting the OptiKey folder from the Roaming/AppData, now it works. Perhaps this option (to reset everything) should be somehow made easily accessible. Other than that everything worked really fine, but I haven't had the time to test more. I think we're go for a candidate release, though!

**Comment by JuliusSweetland** [comment]
@vdjerek v2.3.4 pre-release (with Croatian) is available for testing here: https://github.com/OptiKey/OptiKey/releases

**Comment by JuliusSweetland** [comment]
@vdjerek v2.3.4 release candidate 2 is now available for testing here: https://github.com/OptiKey/OptiKey/releases

The only change is to the dictionary, which I have cleaned up by comparing to another Croatian word list. The result is that the dictionary has reduced in size to around 92k words now. To test you'll have to manually delete your copy of the CroatianCroatia.dic BEFORE testing this new copy of OptiKey. The file to delete will be here: C:\Users\YOUR_USER_NAME\AppData\Roaming\JuliusSweetland\OptiKey\Dictionaries

N.B. You must replace "YOUR_USER_NAME" with your actual username. For example this is my directory: C:\Users\Julius\AppData\Roaming\JuliusSweetland\OptiKey\Dictionaries

**Comment by JuliusSweetland** [comment]
@vdjerek How is the v2.3.4 candidate release - is Croatian working as expected? If so I'll make an official release. Thanks.

**Comment by vdjerek** [comment]
@JuliusSweetland Works just fine, looking forward to the release!

**Comment by JuliusSweetland** [comment]
@vdjerek Great. v2.3.4 released officially now. Thank you for your help getting Croatian out the door!

**Comment by vdjerek** [comment]
@JuliusSweetland Great! I've presented the OptiKey and the Croatian translation at our MND support group meeting yesterday, and I'm looking forward to some new Croatian users! :) The people who saw the demonstration were very impressed by your efforts and the performance and capabilities of the OptiKey. I hope we'll all together be able to make it even better in the future!

**Comment by JuliusSweetland** [comment]
That's excellent! I hope it helps.
