### ISSUE TITLE
Menu key works, but shrinks OptiKey as if the Minimise key had been pressed

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#271]
Video of issue here: https://dl.dropboxusercontent.com/u/14358262/fromvalencia.rar

Video filename: VID_20160714_192830.mp4

**Comment by alexandre-mbm** [comment]
I do not reproduce this here.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm I think this was a bug in the WindowManipulationService which I fixed. Closing this issue as I can not longer replicate this issue either.

**Comment by alexandre-mbm** [comment]
Oops! It happened yesterday with me. Maybe after I changing the screen resolution. Workaround: erase config files and reopen the OptiKey.

**Comment by JuliusSweetland** [comment]
If you can provide steps to replicate I will attempt to fix it
