### ISSUE TITLE
Localisation: Czech

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#282]
**1.Transifex translation of UI strings:** Incomplete

**2.Keyboard layout:** http://ascii-table.com/keyboard.php/243
![image](https://cloud.githubusercontent.com/assets/4722561/19223106/56abb1bc-8e5f-11e6-9f51-3b0544b11d7b.png)

*_3.Alphabet:_ 
a)Letters: 42 letters - https://en.wikipedia.org/wiki/Czech_orthography
A a
Á á
B b
C c
Č č
D d
Ď ď
E e
É é
Ě ě
F f
G g
H h
CH ch
I i
Í í
J j
K k
L l
M m
N n
Ň ň
O o
Ó ó
P p
Q q
R r
Ř ř
S s
Š š
T t
Ť ť
U u
Ú ú
Ů ů
V v
W w
X x
Y y
Ý ý
Z z
Ž ž

b)Diacritics that can be added to individual letters (these will be dead keys): 

c)Other keys: 

Total: X keys

**4.Word list:** None yet

**5.Anything else:** None yet

**BRANCH:** None yet

Similar Slovenian keyboard?
![image](https://cloud.githubusercontent.com/assets/4722561/19223086/bb6486b6-8e5e-11e6-9fc8-d9929dbd90e1.png)

**Comment by TheGreenAirplane** [comment]
Czech keyboard layout can be done similarly to Slovak using two dead keys and one extra character key:
A  a  -> Á  á
E  e  -> É  é
I  i  -> Í  í
O  o  -> Ó  ó
U  u  -> Ú  ú
Y  y  -> Ý  ý

ˇ - The caron:
C  c  -> Č  č
D  d  -> Ď  ď
E  e  -> Ě  ě
N  n  -> Ň  ň
R  r  -> Ř  ř
S  s  -> Š  š
T  t  -> Ť  ť
Z  z  -> Ž  ž

Other special characters:
Ů  ů

**Comment by JuliusSweetland** [comment]
@TheGreenAirplane It sounds like the new keyboard could be based off the Slovenian keyboard, with an extra key added to each of the top 3 rows of letters. The space key could then be made one key wider to keep everything balanced. What do you think?

**Comment by TheGreenAirplane** [comment]
I made a quick mockup, just to be sure I understand what you mean:
![czech keyboard proposal](https://cloud.githubusercontent.com/assets/12677130/19286321/828eb190-8ffd-11e6-9ed8-fbabdb1b41e8.png)
If this is what you meant, then yes, this would work. However, there's one thing I'd change about the  dead keys. On the Spanish keyboard, when you click the accent key, you get a selection of letters that can be used with the accent. But the selection shows the basic characters, not the accented ones (i.e. O, not Ó, E not É). I think it would be more intuitive if this selection showed the accented characters.

**Comment by JuliusSweetland** [comment]
@TheGreenAirplane Mock up looks good to me. I can think about how to support modified labels on the keys when diacritic "dead keys" are down. I would guess that will be a reasonably easy thing to code.

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
