### ISSUE TITLE
Error while setting up OptiKey

### ISSUE THREAD

**Issue by ashketh** [OptiKey/OptiKey#284]
While I downloaded the setup files for OptiKey and ran it, It notified me that I didn't have .NET Framework 3.5 loaded on my PC. It assured me that it would download .NET 3.5 for me, but after a while it said that it had an error downloading the framework and asked me to manually download the framework or just restart the computer and run the setup all over again. 

I use a Sony Vaio 15", Intel i5 processor, 4GB RAM, 1.6 Ghz, browser-Google Chrome.

**Comment by JuliusSweetland** [comment]
@ashketh Thanks. It should actually be looking for .Net 4.6. Which version of Windows are you using and do you know which version(s) (if any) of the .Net Framework you have installed? You can look in "Programs And Features" from the Start menu.

**Comment by ashketh** [comment]
I'm using Windows 8.1, and this is a little weird, I just noticed that I don't have any version of .NET installed.

**Comment by JuliusSweetland** [comment]
I believe it is possible to skip the .net framework during the Windows
installation, but 4.5 is the default install with Windows 8.1. I'll look
into why the OptiKey installer failed to get the correct version, but it's
a tricky problem to diagnose without being able to replicate.

Can you manually install 4.6 in the mean time?

**Comment by ashketh** [comment]
Cheers! I'll do that!

**Comment by JuliusSweetland** [comment]
Closing as unable to replicate.
