### ISSUE TITLE
Point To Key Value Map

### ISSUE THREAD

**Issue by dmankran** [OptiKey/OptiKey#289]
Where is the pointToKeyValueMap (the dictionary holding the points of the keys and their values) initiated in the code? I want a key to change its text and have multiple functions

**Comment by JuliusSweetland** [comment]
@dmankran It's built by the TraverseAllKeysAndBuildPointToKeyValueMap() method in the KeyboardHost, bound to a property on the MainViewModel, which then sets it on the InputService to be used by the trigger source. What are you trying to achieve as I don't think a key will currently support multiple functions.
