### ISSUE TITLE
Unexpected auto-spacing behavior with multi-key locked

### ISSUE THREAD

**Issue by gabrielbenjamin** [OptiKey/OptiKey#291]
With "auto-space between words" enabled and the keyboard locked in multi-key mode:
- spaces are added inappropriately after characters like hyphens, slashes, underscores, asterisks and at-signs.
- spaces are added after initial characters in matched pairs like parentheses, brackets and braces.
- as a special case of the above, spaces are always added after quotes, be they opening or closing.
- spaces are NOT added between e.g. periods/commas and initial characters in matched pairs.
- spaces are NOT added between e.g. periods/commas and single-letter words.

Admittedly, fixing these could create overhead from added logic, but on the other hand, working around them can be a hassle.

**Comment by JuliusSweetland** [comment]
@gabrielbenjamin Can you please provide steps to reproduce each example?

**Comment by gabrielbenjamin** [comment]
Gladly. It'll just be a few days.

**Comment by gabrielbenjamin** [comment]
It took well longer than a few days, as personal circumstances intervened. I sincerely apologize for the delay. My observations follow:

Typing the character between two words always produces this (I'll use * to stand in for the character):
`word* word`
That works for postfix punctuation like periods, commas, colons etc. Not so for prefix characters like (in some contexts) &, @ and # or (in all contexts) ¿ and ¡:
`* word`
where
`*word`
would be expected. Or infix, like most of the math symbols, where
`word * word`
is probably desirable, or hyphens or underscores or sometimes @ or / where
`word*word`
is preferable. A single-letter word appearing after punctuation yields
`*word`
in every case (my notation breaks down a bit here; assume word has a length of one letter). Lastly, we have the issue of matched pairs. I'll use [] enclosing a single word to illustrate; one may easily generalize this to a phrase of any length enclosed by any matched pair. The spacing behavior currently in use yields
`word[ word] word`
which is only correct for ]. This occurs also when [ follows postfix punctuation:
`word*[ word] word`
when one would expect
`word* [word] word`

This could be addressed by classifying characters by spacing behavior, perhaps depending on context, the drawback being that this would require quite a few judgment calls. This also wouldn't adequately address the case where [ and ] are the same character; best I can suggest is a parity check on the number of that character seen so far.

**Comment by JuliusSweetland** [comment]
@gabrielbenjamin I'm not sure I've 100% addressed all your examples, but give this pre-release a try: https://github.com/OptiKey/OptiKey/releases/tag/v2.3.16_pre-release_1

It should correct the incorrectly inserted auto-spaces you list, but I cannot currently correctly insert auto-spaces in some scenarios, e.g. when closing a quote, as the opening and closing quote marks are the same and I don't currently have a way of balancing matching symbols.

Let me know what you think.

**Comment by gabrielbenjamin** [comment]
The infix scenario is resolved by this build. In the prefix scenario, one might expect a space before the character, particularly after sentence-terminating characters--periods, question marks and exclamation marks--as well as commas, colons and semicolons.Single-letter words behave the same: no space separating them from punctuation. Also parentheses and the like behave the same as before.

**Comment by JuliusSweetland** [comment]
I have to admit I'm a bit unclear of the specific use cases. Could you give
be one or two specific examples of each with the current and expected
behaviour?

**Comment by gabrielbenjamin** [comment]
Prefix (`@` might be a bad example since it works differently in the context of email addresses, but that would be a poor use case for multi-key):
`It's a nice day.@mark, don't you agree?`
Expected: `...day. @mark...`
`Weather was good!#lucky`
Expected: `...good! #lucky`

Single-letter words:
`If I fits,I sits.`
Expected: `If I fits, I sits.`
`It's a good idea.A very good idea.`
Expected: `...idea. A very...`

Matched pairs:
`This is a sentence.(This is an aside.) This is another sentence.`
Expected: `...sentence. (This...`
`something[something] something`
Expected: `something [something] something`

**Comment by JuliusSweetland** [comment]
@gabrielbenjamin I think I can address the examples where typing follows a sentence ending punctuation (.!? when multi-key selection is enabled) by always injecting a space. I'll have to think about the other use cases separately. I'll try and look at this this weekend.

**Comment by JuliusSweetland** [comment]
@gabrielbenjamin There is a new pre-release of v2.3.16 here: https://github.com/OptiKey/OptiKey/releases/tag/v2.3.16_pre-release_2

I have addressed single letter words, but not the other scenarios for now as I'm not happy that I can correctly identify what the user is trying to do. Let me know what you think.

**Comment by JuliusSweetland** [comment]
@gabrielbenjamin Have you had a chance to test the pre-release?

**Comment by gabrielbenjamin** [comment]
I'm sorry, only just was able to look. I currently have no build tools
installed, and I don't want to make you wait even longer for that. Could
you please add a binary installer for the build?

**Comment by JuliusSweetland** [comment]
Hey. There is an installer if you follow that link.

**Comment by JuliusSweetland** [comment]
@gabrielbenjamin Ok cool - I'm going to think about this some more, but close this issue in the mean time. Thanks for testing.
