### ISSUE TITLE
Recent phrases

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#302]
Suggestion for a new feature.

**Comment by JuliusSweetland** [comment]
Collapsing into #302

**Comment by alexandre-mbm** [comment]
> Collapsing into #302

I do not understand what this means.

**Comment by JuliusSweetland** [comment]
The idea overlaps with the other issue so I'm closing this one and the idea
can live on in the other issue.

**Comment by alexandre-mbm** [comment]
I think them as two different works.
