### ISSUE TITLE
Typo in wiki page "Numbers, symbols and diacritics"

### ISSUE THREAD

**Issue by cudibo** [OptiKey/OptiKey#306]
In this page: https://github.com/OptiKey/OptiKey/wiki/Numbers,-symbols-and-diacritics
At the very end I think we need to change "diacritic":
_You can toggle between the **diacritic** keyboard screens by selecting the keyboard number key._ 

With: **currency**

Congratulations for your great work

**Comment by JuliusSweetland** [comment]
Thanks, corrected.
