### ISSUE TITLE
A couple of buttons no longer traceable after "Add to dictionary" action

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#308]
https://www.youtube.com/watch?v=-PXiWd611lw

**Comment by alexandre-mbm** [comment]
The problem affects that 2nd line of buttons only.

**Comment by JuliusSweetland** [comment]
Is this the same as #272

**Comment by rsrobinett** [comment]
This appears to be the same bug as #272.  I have a fix and will submit a pull request after I confirm that it does not affect adding words to the dictionary while not in conversation mode.
