### ISSUE TITLE
OptiKey's "Calibrate" for EyeX is breaking the config

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#309]
Bad result: https://github.com/ENE/OptiKey-Config/commit/33f915caee2693f8e760afd5a46b1f011381c881

**Comment by JuliusSweetland** [comment]
@alexandre-mbm How was that config changed? Can you provide more detail.

**Comment by alexandre-mbm** [comment]
After calibration OptiKey shows bad behavior. So I make copy of file and then I make diff it with my backup in Git. The changes are these that you are seeing. I make the comparation of them because at first time that this happend I thought the XML had been corrupted.

**Comment by JuliusSweetland** [comment]
Unable to replicate.
