### ISSUE TITLE
Dictionaries for pronunciation

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#310]
Screen readers such as NVDA or Orca have dictionaries for pronunciation. Where for example, in portuguese, the english term "Facebook" would be phonetically setted to _"**feice**b**ú**lque"_.

Without this, the Felipe voice says _"fa**ce**buque"_.

**Comment by JuliusSweetland** [comment]
I believe this should be a customisation to the TTS engine, rather than something OptiKey attempts to influence. Multiple TTS engines are now supported so the effort required to manipulate their output would be significant.
