### ISSUE TITLE
Add support for Intel RealSense gaze tracking

### ISSUE THREAD

**Issue by rsrobinett** [OptiKey/OptiKey#312]
Intel RealSense gaze tracking is a technology available in several [economical laptops](https://www.amazon.com/Dell-Inspiron-15-6-Inch-Touchscreen-RealSense/dp/B01N0K3246/ref=sr_1_1?s=pc&ie=UTF8&qid=1488010328&sr=1-1&keywords=RealSense+Laptop).

Here is some information about the Intel SDK for RealSense
[RealseSense SDK Documentation](https://software.intel.com/en-us/intel-realsense-sdk/documentation)
[Realse Sense gaze tracking documentation](https://software.intel.com/sites/landingpage/realsense/camera-sdk/v2016r3/documentation/html/index.html?gazedata_pxcfacedata.html)

The references can be added to the project as a [nuget package](https://www.nuget.org/packages/libpxcclr.cs/).

**Comment by alexandre-mbm** [comment]
I see possibilities with 3D only. @rsrobinett, can you see more?

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
