### ISSUE TITLE
Multi-key Selection

### ISSUE THREAD

**Issue by RalfCT** [OptiKey/OptiKey#319]
It seems to be impossible to start a sentence with 'I', or have an 'I' after a comma when the software is in Multi-Key Selection mode, or am I missing something?  Surely it's not necessary to deactivate Multi-Key Selection each time one wants to enter 'I', and then re-activate it again before continuing.

**Comment by JuliusSweetland** [comment]
Hi @RalfCT to select single letters with multi key select turned on just select the single key twice, i.e.start and stop the multi key selection on the same key with no other selections in between.

**Comment by RalfCT** [comment]
Aah, thanks Julius.  I downloaded the software earlier and initially thought it a bit cumbersome, but now that I'm finding my way around it's actually quite amazing and fast ... would love to try it with an eye-tracker, and then introduce it to a friend with MS.  Is it possible to dwell on and select desktop icons and menus without first selecting the left mouse-click (I seem to recall doing it earlier before changing something in the Management Console)?

**Comment by JuliusSweetland** [comment]
You can make mouse selections using dwell, yes, but you still need to
select "left click" or whichever mouse operation you want to perform first.

Glad you're enjoying OptiKey.

**Comment by JuliusSweetland** [comment]
@RalfCT I have added a bit more info to this page to make single letter selection; https://github.com/OptiKey/OptiKey/wiki/Multi-key-selection

Closing this issue.
