### ISSUE TITLE
Mouse-click Action in OptiKey

### ISSUE THREAD

**Issue by RalfCT** [OptiKey/OptiKey#320]
I'm not sure if it's possible to properly evaluate the "mouse-click" functionality in OptiKey using an attached mouse, or if the results will only be realistic if an eye-tracker is attached. 

I've been evaluating several software options, including Click2Speak.  If their system is set to "Dwell" one is able to activate to and activate any icon, menu etc. on the desktop or keyboard ... 'drag', 'left-click', right-click' and 'double-click' simply add one-time functionality when specifically required, but "Dwell" remains on, allowing one to navigate icons, menus and sub-menus without prompting the mouse.  

While OptiKey has a "Dwell" function, it only works on the keyboard, not if one hovers over a desktop icon.  Would an attached eye-tracker offer a similar experience to Click2Speak?

**Comment by JuliusSweetland** [comment]
@RalfCT have a read of this and try out the mouse actions: https://github.com/OptiKey/OptiKey/wiki/Simulate-a-mouse

**Comment by RalfCT** [comment]
@Julius, yes I read the article before posting.  If I left-click on the mouse keyboard using a mouse, the cursor appears and times out before I can move it to a point where I can click on anything.  It seems impossible and pointless trying to simulate this action when there's already a mouse attached to the PC.

**Comment by JuliusSweetland** [comment]
@RalfCT Ok - it's possible that the "Point fixation time to complete" in the management console is too low?

**Comment by RalfCT** [comment]
@Julius, I reset to default settings (1.250ms, I think).  My procedure may have been wrong.  I've now picked up that the pie-chart only counts down when the mouse cursor stops moving.  However, when I select the mouse left-click and click on a desktop folder it opens fine (probably due to it being a large target), but trying to close it again after selecting the mouse left-click, results in the OptiKey cursor 'sticking' on screen - the physical mouse cursor will find the "X" while the large OptiKey cursor will not, it can take as much as 6-8 tries before it does.  I assume this issue is only manifesting due to my not using an eye-tracker.

**Comment by JuliusSweetland** [comment]
That's correct. It's down to a setting which controls the lock on
area/radius. You can reduce this to 1px.

**Comment by RalfCT** [comment]
@Julius, another issue I'm picking up is Microsoft's 'error' sound clip playing after almost each completed word/symbol.  Sometimes restarting OptiKey seems to 'cure' this, for it only to return.  Different desktop icons become highlighted on their own during this process.

**Comment by RalfCT** [comment]
Okay, adjusting the "Point lock-on radius" to 1px sorted out the mouse cursor issue.  Thank you.  I should study the User Guide. :)

**Comment by JuliusSweetland** [comment]
Do you also get a red error popup when the error sound plays?

**Comment by RalfCT** [comment]
No, no error pop up, also nothing behind the keyboard when minimizing.

**Comment by JuliusSweetland** [comment]
Could you replicate the issue and then send me your logs? Instructions
here: https://github.com/OptiKey/OptiKey/wiki/Other-issues

**Comment by RalfCT** [comment]
Hi Julius,

I followed your directions below, enabled debugging and tried to 
replicate the error.  The Windows error sound kept playing after every 
word, period, comma etc., but this time several windows were opening 
(see screenshot).  I also noticed that my folder single-click option had 
changed to double-click.  For some reason different desktop icons become 
highlighted each time I finish typing a word - only one icon, changing 
to another with the next word.  Clicking on the desktop below the 
keyboard sometimes 'solves' the problem - a strange intermittent issue 
and difficult to replicate.

I'm not able to send you a log file as the Log folder was never created 
after enabling Debugging (see screenshots).

Regards,

Ralf

**Comment by JuliusSweetland** [comment]
@RalfCT do you still have your screenshots? They didn't attach to this issue.

**Comment by RalfCT** [comment]
Julius, I previously responded via email, let's see if dragging them here directly will attach them.
[Screenshot 3.pdf](https://github.com/OptiKey/OptiKey/files/965464/Screenshot.3.pdf)
[Screenshot 2.pdf](https://github.com/OptiKey/OptiKey/files/965465/Screenshot.2.pdf)
[Screenshot 1.pdf](https://github.com/OptiKey/OptiKey/files/965466/Screenshot.1.pdf)

**Comment by JuliusSweetland** [comment]
@RalfCT From screenshot 2: the log files are inside the OptiKey subdirectory, then the Logs directory; \OptiKey\Logs

**Comment by JuliusSweetland** [comment]
@RalfCT At a guess I believe what is happening is that OptiKey is outputting all your key strokes as you type in it, e.g. when you type "Good morning" you have your Windows desktop focussed and so the desktop is reacting to these key presses. This would result in icons being selected, or error sounds if the key press is unexpected, exactly as you describe. If you don't want to output keystrokes try using the CONVERSATION keyboard (from the menu), which is for speaking only. Alternatively click on OptiKey before you start typing, as OptiKey will ignore the key presses you are generating.

**Comment by RalfCT** [comment]
@Julius, here are some of the log files.  I've zipped them and changed the extension to PDF (wasn't able to upload otherwise).  During the last session everything was fine; no error messages, selected folders or audible errors.  Let me know if you find anything strange in the other logs.

[OptiKey.pdf](https://github.com/OptiKey/OptiKey/files/966628/OptiKey.pdf)
