### ISSUE TITLE
Is there a cost-effective eye-tracker?

### ISSUE THREAD

**Issue by RalfCT** [OptiKey/OptiKey#321]
Commercially available eye-trackers from Tobii and the like kill any plans to implement a communication solution for those no longer able to, even when using OptiKey or similar.  I received quotes this morning ranging fromUSD1,200 - USD2,000, just for the eye tracker.  That's simply unaffordable for the average family dealing with an MS, ALS or similar patient.  

Are there any other, way cheaper options produced by companies who actually care about these patients, rather than their shareholders?

**Comment by alexandre-mbm** [comment]
I am working this for my father together with my brother. It is a DIY solution based in the EyeX (for games) b y using Windows 10. I intent mantain a blog and to write a ebook. It works! My brother configured it. Now I am rebuilding and organizing the knowledge. There is a Youtube vídeo (still private link) that needs to be legended. I can provide a transcritpition in portuguese for this, and for it be translated to english.

https://www.youtube.com/watch?v=b7Y1imMgpeA

That vídeo is a starting point only. To config the system is a hard work and has been a research activity. Everything is acquired ready but integrate and otmimzar requires a detailed step by step besides skills with Windows (while I do not publish the cake recipe).

**Comment by alexandre-mbm** [comment]
@RalfCT, Tobii EyeX é done for gaming. It is cheap!

I am improving the portuguese written.

**Comment by JuliusSweetland** [comment]
@RalfCT Have a look here: https://github.com/OptiKey/OptiKey/wiki/Supported-eye-trackers

The Tobii EyeX and 4C are both very affordable (currently €109 and €159 respectively).
