### ISSUE TITLE
Problem with myGaze

### ISSUE THREAD

**Issue by NexMilford** [OptiKey/OptiKey#323]
Hi everyone. I have a problem with  myGaze and OptiKey. When the pointing and selecting switching devices with the mouse and select myGaze, OptiKey will not work. With Tobii PCEye go mini program running. How to solve this problem?

**Comment by JuliusSweetland** [comment]
@NexMilford Can you please provide the step by step instructions to replicate the problem? For example:

1.Start OptiKey with the point source set to mouse
2.Launch the management console
3.Change the point source to myGaze
4.Click Ok and restart OptiKey when prompted
5.OptiKey stops responding

(the above it just an example set of steps)

**Comment by NexMilford** [comment]
Yes, this is really happening as you describe.

1.Start OptiKey with the point source set to mouse
2.Launch the management console
3.Change the point source to myGaze
4.Click Ok and restart OptiKey when prompted
5.OptiKey stops responding

I do not know how to solve the problem. 
The program responds to the Tobii PCEye mini, also responding with a mouse simulator.

1. I compiled by computer specifications required to run myGaze.
2. I reinstall the computer to Windows 10.
3. Download driver (myGaze) from the official website.
4. Download OptiKey.
5, Install the driver and program.
6. Start the program switch device on myGaze.
7. Click Ok and restart OptiKey when prompted.
8. OptiKey stops responding.

I'm confused.

**Comment by JuliusSweetland** [comment]
Is the myGaze application running and have you calibrated myGaze BEFORE
starting OptiKey? Mygaze must be working completely below OptiKey starts.

**Comment by JuliusSweetland** [comment]
Closing due to lack of a follow up
