### ISSUE TITLE
Bounty on Feature: $400 for visual keyboard 

### ISSUE THREAD

**Issue by joereddington** [OptiKey/OptiKey#324]
Hi everybody, 

We've got a small budget to pay for some development on this project - please let me know if you are interested. 

**Background**
We have a set of open licensed visual keyboards for AAC (as a result of [this project](http://communikate.equalitytime.co.uk).  These are for AAC users who find it difficult to user a 'normal' keyboard (my brother is one of the relevant users). We've been very impressed with Opikey, but we are aware it lacks the ability to use Visual Keyboards, so we wanted to put forward both our pagesets, and some of our funding, to make that happen. 

I've spoken to Julius, and following that, I think what we want is this: 

1. adding a checkbox in the Management Console marked words to the effect of 'use visual keyboard (preliterate user)'. When checked this switches out the qwerty keyboard for a keyboard based on CommuniKate (because it's creative commons licensed and so are the symbols). By default CommuniKate is 4 by 5, but I we can build a 3 by 6 version if that would fit the design better.
2. Second stage - we'd add a file/URL selector under the switch so that Opikey could import any visual keyboard from the http://openboardformat.org

We've had some success with code bounties before, do let me know if you are interested in both contributing to this awesome project and being paid for it! :) 

Joe

**Comment by yahnatan** [comment]
Hi Joe, recognize you from your blog and appreciate your work. I was on a
similar track to you found Optikey, started writing my own picture-based
AAC for my son, and then got a pointer (from Julius) to CoughDrop, which
I've now switched over to using. Given your familiarity w/assistive
technology (and the OBF format, created by the CoughDrop team), and the
fact you've talked w/Julius, I'm thinking you're probably familiar with
CoughDrop. I can imagine added utility for Optikey if it supports OBF...but
I also know that CoughDrop has more than $400 of specialized features for
picture-based AAC (and continues to add more). I'm curious if yo u have a
more limited use case for OBF support in Optikey, whether you're wanting to
see another direct competitor/replacement for CoughDrop, CommuniKate, etc,
or have other benefits in mind?
In any case, cheers, and let's hear it for open software development!
P.S. If you're on Facebook, please join the facebook.com/groups/OptikeyUsers
group I created!

**Comment by joereddington** [comment]
Hey! 

Have joined group.  I also love Brian in particular and Cough Drop more generally. I very much want *everything* in AAC to use OBF.    I'm coming from the perspective of someone who is passionate about both AAC and open development - and I've got a budget for putting the two together. Most of that budget needs to be spent on theopenvoicefactory.org (which will feed into Cough Drop once I've fixed a few bugs) but there is enough spare that we can help the ecosystem in general if that makes sense?

**Comment by zelmon64** [comment]
Hi Joe,

I was looking at this a couple of days ago. I think the difficulty will be in converting the images to xaml vectors and their lack of colour. Obviously the svg images should be okay but the png's may loose too much. I'm no expert though. What do you think?

**Comment by JuliusSweetland** [comment]
@zelmon64 If the images that are out there are svg or png then there is nothing stopping us adding support on a Key for these, I just didn't need that when I initially wrote OptiKey. If we go down that route then a bit of work will have to be done to the theme resources to allow images, text, and paths to scale nicely alongside each other, but it should be possible.

**Comment by zelmon64** [comment]
@JuliusSweetland that's interesting that support for other image formats can be added. I wasn't sure if loading full images would be quick enough for a keyboard.

**Comment by JuliusSweetland** [comment]
@zelmon64 I am not 100% confident either way really, but we can certainly try it out and see. My main concern is whether the selection animations will display well over an image, i.e. will the filling pie animation stand out properly.

**Comment by zelmon64** [comment]
@joereddington I've started to look more into this. I've been using the communikate-20.obz from http://www.openboardformat.org/ as a template. Is that a good example to use for the layout of all the different pages? I was surprised how many pages it has (~100 if I understand correctly). My first attempt won't be able to load custom files so I just want to make sure that's a good choice (seemed good to me).

Here's what I have so far:
![image](https://user-images.githubusercontent.com/15001389/28732961-d1358220-73d1-11e7-95fc-9994855b8c6f.png)

@JuliusSweetland here's the selection animation. With just these images it's quite good (will have to change the text colour of course, or remove it?)
![image](https://user-images.githubusercontent.com/15001389/28733134-9e94886a-73d2-11e7-96cc-20967fd74975.png)

**Comment by JuliusSweetland** [comment]
Looks promising! The text is hard to read on images with light backgrounds,
BUT it might be useful in enough cases to warrant its inclusion. Perhaps a
new setting could be added to suppress text on keys which have Images or
Symbols (this could be 2 distinct settings actually). This could then be
included in the KeyTextStyle in the 2 themes.

**Comment by zelmon64** [comment]
@joereddington and @JuliusSweetland I've done the first page! Unfortunately it looks like quite a few of the images have white backgrounds when they shouldn't. Simple enough it remove the backgrounds but it's going to be rather time consuming unless I find a batch method.

![image](https://user-images.githubusercontent.com/15001389/28824773-9324d6ce-76bb-11e7-83c1-55d73ac78182.png)

**Comment by JuliusSweetland** [comment]
Is that to do with transparency or do they actually have white backgrounds?

**Comment by joereddington** [comment]
I believe the cough drop version of communiKate (which is the one being used) has changed some of the icons - and those have white backgrounds. 

I'm literally this minute testing out a different Communicate OBZ file which would have all transparencies (and I think it's fair to leave the onus on the OBZ maker to have good images) .  Looks beautiful though! I think we're well on our way. :)

**Comment by zelmon64** [comment]
@JuliusSweetland yes it's that the png images have white backgrounds instead of transparent.

@joereddington that sounds good. Is the new version publicly available somewhere? Do you know if all the file names are the same? If they are I can just carry on then swap the new version in when I can get it.

**Comment by zelmon64** [comment]
@joereddington The naming method in that new pageset is so mush nicer than the seemingly randomly generated names in the one I was using. The layout seems a little different but for an example I used the same layout as before:

![image](https://user-images.githubusercontent.com/15001389/28836478-fc945402-76e0-11e7-991c-cf18045d4439.png)

**Comment by JuliusSweetland** [comment]
That's looking amazing William.

**Comment by joereddington** [comment]
That looks extremely super-wonderful.  I'm smiling while I type. 

You may run into a slight problem in that the original layout is technically 5 by 5 - with the top row consisting of the yes button in one corner, the NO in the other, and the middle three intended for the 'message window'.   Clearly we'd do some changes at this end in the final version so that it's more happily 4 by 4. 

So I had the parsing of the files down as the major technical problem to be solved, and this is clearly being done.  In terms of the normal practices of Opikey - what are the steps needed to get this to a minimum viable feature from your point of view? (and how can I help?). 

I'm availble on all of the relevant platforms if anyone would like a proper chat about this. So pleased to see it coming together :)

**Comment by zelmon64** [comment]
@joereddington I'm glad you like it. Once I get all the pages coded into OptiKey it should be pretty much good to go as an initial version. I've done 12 out of the 100 pages so far. It's getting a bit tedious (and giving me a bit of rsi from all the copying and pasting) so I started to look into reading the obf files directly into OptiKey. It won't yet be fully automated but it should speed things along.

I've currently set CommuniKate as an alternative keyboard like the Alphabetical and Simplified keyboards but I noticed there are pages for typing. I'm guessing it would probably be more suitable to change to the normal OptiKey keyboard for typing. What do you think?

**Comment by joereddington** [comment]
Absolutely about the typing pages.    I also think that reading the OBF files directly is going to be a good idea, particularly for other languages (I hadn't actually realised you were doing them by hand) - I certainly remember getting very bored with lots of coping and pasting the first time round and I remember being terrified I was getting things wrong when doing the Portuguese version...  

If it's useful (and I suspect the official OBF libraries are much more useful. There are files here that show how I'm writing to OBF: https://github.com/eQualityTime/TheOpenVoiceFactory/blob/ovfoutput/grab_text.py 

There's also the start of some OBF reading that one of our volunteers (who now is involved in Opikey) wrote for an android app here:  https://github.com/eQualityTime/TheOpenVoiceFactory/tree/master/qt

**Comment by zelmon64** [comment]
@joereddington I have the full automation working! But it has a few bugs and the code's really messy and littered with previous failed attempts.

**Comment by zelmon64** [comment]
@joereddington Here's a (hopefully) fully functioning build: 
https://drive.google.com/open?id=0B7SYYOqNW4FSMEM4Y0ROSzRaWTg

If it's satisfactory shall we discuss the bounty if it's still available?

**Comment by zelmon64** [comment]
@joereddington I have a new build:
https://drive.google.com/open?id=0B7SYYOqNW4FSclhmZUpBc1pQNnM

I fixed a few errors and added the ability to select a different obf file as the top page.

---

This is strange. A couple of days ago I thought I posted [this build](https://drive.google.com/open?id=0B7SYYOqNW4FSMEM4Y0ROSzRaWTg) after fixing the bugs I [mentioned in this post](https://github.com/OptiKey/OptiKey/issues/324#issuecomment-320440607) and asked "if it's satisfactory shall we discuss whether the bounty is still available?" but that post doesn't seem to be on here. I suppose it must have failed to get posted properly or something. 

In that case, if my work has been satisfactory, shall we discus the bounty if it's still available?

**Comment by JuliusSweetland** [comment]
@zelmon64 FYI I can see both of your build posts.

**Comment by zelmon64** [comment]
@JuliusSweetland Thanks. I can see it now as well. When I posted the last I definitely couldn't see it so I don't know what's going on. Oh well.

**Comment by joereddington** [comment]
Awe. Some.  

Yes, still available, and sounds like you have done your thing.   I'm typing this from OS X so I'm going to find it difficult to check it myself - but if Julius says it's doing the thing and has stayed within the normal Opikey way of doing things then I'm going to be happy about it.  

I've got a bit confused about screennames but I think you've either got my email address or my facebook - drop me a line and we'll set up a call to make sure the i's are dotted and so on.  Really pleased.

**Comment by JuliusSweetland** [comment]
I haven't tested this yet. William where is the code and I'll try to check
it tonight.

**Comment by JuliusSweetland** [comment]
Also could you briefly describe how I should use it. Eg where I should
download keyboards from and how I should make OptiKey aware of which ones I
want to use etc. Thanks

**Comment by zelmon64** [comment]
@joereddington great!

@JuliusSweetland The code's [in this branch](https://github.com/zelmon64/OptiKey/tree/CommuniKate). I'll make a PR.

The default CommuniKate layout is included with OptiKey so all that is needed is to enable CommuniKate from the Words tab of the management console. The CommuniKate keyboard can then be access either by selecting it in that tab or by pressing the "CK" key on the Alpha and ConversationAlpha keyboards.

**Comment by JuliusSweetland** [comment]
Do you have support to dynamically load new keyboards if they exist in a
certain directory?

**Comment by zelmon64** [comment]
Yes, I used the same method as selecting the MaryTTS location.

**Comment by JuliusSweetland** [comment]
Great stuff. And how is it personalised? I've just tried the online demo
which includes an About Me board which looks like it needs the user to
specify name, age, birthday, etc. This is in CK20 and CK12.

**Comment by JuliusSweetland** [comment]
@zelmon64 I've just skim read the documentation and I guess the end user customises the keyboard files themselves using a text editor, right?

One thing I've thought of - if you are linking to the CK keyboard from Alpha and ConversationAlpha could I suggest a couple of things:

1.Unless I am wrong I don't think CK is designed for typing into other applications and is instead a speaking tool. If that's accurate I am picturing 3 setting:
    a) Enable CommuniKate? - If disabled the ConversationAlpha keyboard looks as it does now. If enabled then there should be a key on the ConversationAlpha keyboard in the same way as there is a link to the Yes/No keyboard (if ConversationConfirmEnable==true).
    b) Replace Conversation keyboard? If disabled then you get to CK from the ConversationAlpha key. If enabled then the CK keyboard IS the conversation keyboard and you get to it from the Menu, or by setting the startup keyboard to CommuniKate (or ConversationAlpha, which would redirect to CommuniKate).
    c)CommuniKate Only Mode - we could just use the existing Conversation Only Mode setting, which forces the startup keyboard to Conversation Alpha and changes the BACK button to a QUIT button. We should have a similar mechanism so the user cannot BACK out of the CommuniKate keyboard if they are in CommuniKate Only/Conversation Only Mode.

2.Don't link to the CK keyboard from the standard Alpha keyboards as these are predominantly for typing.

What do you think?

**Comment by joereddington** [comment]
The version you are looking at is the 'intended to be personalised' one. Handy making-it-personal video here: https://www.youtube.com/watch?v=hebjNiZaQLY.  Before you put this in the main trunk we'd give you a 'vanilla' version for the default, with the hope that anyone who enjoyed it would create  their own personal version, either in The Open Voice Factory or Cough Drop.   

This is really highlighting a benefit a common format - if something can be edited elsewhere, you don't need to build an editing interface :)

**Comment by joereddington** [comment]
Ah - simultaneous typing...

**Comment by JuliusSweetland** [comment]
@joereddington Ok understood. So William's change supports the default boards, and the user can then add and customise more (using external tooling) as required. Got it.

**Comment by joereddington** [comment]
I'm right now adding a todo item to create the 'uncustomised' board.

**Comment by zelmon64** [comment]
@JuliusSweetland I'm not sure whether CK is designed for typing into other applications or not since it has a key labelled "Computer Control" but I do agree that I should improve the integration with Conversation mode and better support the Conversation Only Mode. The idea would be the CK "Spelling" key would link to Alpha if CK is windowed and to ConversationAlpha if it is full screen (and similarly for the CK "Numbers" key).

**Comment by JuliusSweetland** [comment]
That sounds sensible, thanks.

**Comment by joereddington** [comment]
As promised - I've produced a depersonalised version of CK20.  The master file is [in the relevant repo](https://github.com/eQualityTime/CommuniKate/blob/master/ck20/CK20V2depersonalised.pptx) 

I put it through my testing server [here](http://testing.theopenvoicefactory.org/) (because I've got some bugs to track down) and it produced:
 
* a online version: http://testing.theopenvoicefactory.org/97bb62a2d8c39d0edc65a9eb93dd3edf/?lang=Daniel
* an OBZ file in: http://testing.theopenvoicefactory.org/97bb62a2d8c39d0edc65a9eb93dd3edf/data/

**Comment by joereddington** [comment]
With the linking of the spelling key - I think that's a good idea, and definitely worth a poke - annoyingly I took the spelling pages out of the depersonalised version before reading this.  On the other hand - I think it's worth shooting for the minimum helpful feature.

**Comment by zelmon64** [comment]
@joereddington With that depersonalised version of CK20 I can see the images in the online version but the obz file doesn't contain any.

@JuliusSweetland I'm working on making OptiKey extract the OBZ archive instead of including all the unpacked files so that it'll dramatically reduce the number of changed files in the PR and hopefully make the final package a bit smaller.

**Comment by JuliusSweetland** [comment]
That sounds great. I'll aim to test your current PR anyway, but should I
wait for the final PR before I consider merging?

**Comment by zelmon64** [comment]
Definitely hold off merging. I almost have the new obz method ready to push. Just checking for bugs.

**Comment by JuliusSweetland** [comment]
Will do

**Comment by zelmon64** [comment]
@JuliusSweetland I've now got it using the OBZ archives reliably (still the personalised one as the depersonalised version doesn't seem to have images) and I fixed the position and background colour of the blank keys (they were all clumped at the bottom instead of where they should be).

**Comment by JuliusSweetland** [comment]
Good stuff. I'll try to look tonight, but it might have to be later this
week

**Comment by zelmon64** [comment]
@joereddington I have a couple of questions about the OBF files.

1. I noticed on the `questions` page there are supposed to be keys for `could`, `would` and `should` but I can't find a reference to them in the OBF files anywhere. How and where are they defined?

2. Some keys like `I have pain in my` on the `I don't feel well` page enter text and change the page. Again I can't see how this function is defined in the OBF file. It appears to me as just a text key.

**Comment by JuliusSweetland** [comment]
@zelmon64 @joereddington This is now reviewed, approved, and released in OptiKey v2.8.0. Thank you everyone!
