### ISSUE TITLE
Performance Issues associated with DictionaryService's Disk I/Os. 

### ISSUE THREAD

**Issue by Chopinsky** [OptiKey/OptiKey#332]
While working in `DictionaryService`, 2 performance issues have come into my attention:

1. Implementation of `SaveUserDictionaryToFile` seems to append the entire in-memory entries to the end of the user dictionary file stored on disk indiscriminately, rather than updating the entry usage of existing entries. This will cause performance issue over time -- the user dictionary file will be filled with duplicate entries and grow dramatically large after some time. Since the user dictionary file will be loaded every time at the launch of the app, the launching period will grow over period of use as well. Functional-wise, the entry usage won't be updated correctly, because when we load entries from user dictionary file, we will only write the 1st encounter of the entry along with its usage into the memory, but we will not update the entries usage when encountering newer and more up-to-date usages of the same entry.

2. The same function `SaveUserDictionaryToFile` is called whenever entry usage is updated, while this is a synchronize disk I/O, it's pretty expensive and could block UI while updating user dictionary, especially given problem 1, where we write the entire memory back to disk. This won't be noticeable on a i7/16gb/SSD machine, but for a less superior machine, the lagging will be more of a problem. 

So I can envision a solution contains 2 parts: 1. eliminate duplicate logging of the same entry in the user dictionary; 2. call `SaveUserDictionaryToFile` in another thread so we won't block the UI.

**Comment by JuliusSweetland** [comment]
@Chopinsky Hi Jacob - great spot. I completely agree on both suggestions. Can you make these changes?

**Comment by Chopinsky** [comment]
Sure, this's on my to-do list :)
