### ISSUE TITLE
Add support for MaryTTS

### ISSUE THREAD

**Issue by zelmon64** [OptiKey/OptiKey#334]
[MaryTTS](https://github.com/marytts/marytts) is an alternative speech synthesizer that uses a java server with an HTTP interface instead of SAPI5. It has quite a few languages with rather good sounding voices. It comes with .bat files to start a GUI to install the desired voices and run the server. It's also possible to run MaryTTS as a [socket server](https://github.com/marytts/marytts/tree/master/doc/examples/client/c%2B%2B) so that it doesn't run it's HTTP interface (and uses less resources I think) but I haven't yet figured out how to interface with this.

A quick and dirty integration has been accomplished in 3e38a25f990ed48db01ce2e9e8c930af9d27c2c9 where SoundPlayer has been used to retrieve the speech from the MarryTTS server. In this first attempt speechSynthesiser has simply been replaced with SoundPlayer in the `Speak` function using an `if` statement to choose which is active. All the voice options are currently hard coded but it should be simple to change them to user variables.

There are two drawbacks with the current hacked solution

1. The MarTTS server must be manually started (and closed). I'm not sure if it will be possible to have MaryTTS launch in the background when OptiKey starts (and close when OptKey is closed).
2. The Speak key remains blue after it has been pressed (it returns to white if an alpha/num/sym key is pressed)

**Comment by zelmon64** [comment]
I've managed to retrieve the list of available voices from MaryTTS (842beb686d59378260e1347c9bb238bf31aa7a5b) but for some reason they appear with an extra line in the managment console ComboBox as seen below. It doesn't seem to cause a problem but it's visually displeasing. When I retrieved a similar list for just the locales is didn't have these extra lines so I'm not sure what's causing them

![image](https://user-images.githubusercontent.com/15001389/28498572-4b68b5a0-6f98-11e7-85ff-dfb222fb960e.png)

**Comment by zelmon64** [comment]
@JuliusSweetland I been trying to get the speak key to behave normally when used with MaryTTS but so far what I've tried hasn't completely worked. Here's some of what I've tried and the results:

1. Without any modification the speak key will remain blue until another key is pressed.
2. By making `SpeakNewOrInterruptCurrentSpeech` return false when MaryTTS is used the speak key will immediately turn back to white. 
    1) With asynchronous playback of the voice this gives no visual feedback for when the speech ends.
    2) With synchronous playback of the voice this freezes OptiKey until the speech ends.
3. By muting the System.Speech.Synthesis instead of replacing it completely with MaryTTS, it can trigger the speak key to turn back to white.
    - This works well if the rate of the two voices is similar.
    - Muting doesn't work for all voices (such as ModelTalker Rich).
4. Run synchronous playback of the MaryTTS voice in a new thread and place the `onComplete()` action after it. [The ways I've tried to use a new thread](https://stackoverflow.com/questions/363377/how-do-i-run-a-simple-bit-of-code-in-a-new-thread) have all closed/crashed OptiKey after the speech finishes. I couldn't find any logs so I'm not sure what it's doing.

I thought I was onto a winner with option 3 until I found that not all the voices use the `speechSynthesiser.Volume` parameter. I suppose if enabling MaryTTS also forces the System.Speech.Synthesis to use a specific voice it may be okay but obviously running the two simultaneously isn't really a great solution anyway.

I'm guessing the importance of the visual feedback is for when a deaf person uses OptiKey to speak. Would freezing OptiKey completly with option 2-ii be acceptable? If the visual feedback isn't as important then 2-i is probably the simplest/easiest/best option.

The root of the problem is that `SoundPlayer` doesn't have a trigger for when it stops similar to `speechSynthesiser.SpeakCompleted`. If none of these options are acceptable the only solution will probably be to find something to replace `SoundPlayer` that can trigger something when it finishes.

After this problem is solved the only thing left (I believe) is whether having to run MaryTTS separately is acceptable and if not, how to trigger it with OptiKey. OptiKey already handles when MarryTTS isn't running by showing a red popup.

Any thoughts are appreciated as always.

**Comment by JuliusSweetland** [comment]
@zelmon64 It may be possible to start the MarTTS service to start when OptiKey starts. If MaryTTS is enabled (your new setting) then on startup OptiKey could attempt to start the MarTTS service on startup? If you try that does it result in multiple instances? If so you'd have to try and detect if it is running first.

Regarding the blue/white of the speak key - this is currently implemented both to give the user a visual feedback that sound is playing, but also if you speak a long sentence then selecting the speak key when it is blue cancels the current speech, e.g. if you have typed out a full paragraph, but select speak too early, the speak key allows you to cancel speaking and carry on typing. This was requested by a user.

Calling the speech synthesiser asynchronously is the way forward. If no async method is available from the TTS engine then what you are attempting in attempt 4 sounds like a good idea, but you would have to trigger the onComplete from within the separate thread, so it is only triggered at the end of the speech, not immediately after starting the background thread. Essentially if you are looking at the AudioService then the speakCompleted delegate should be called when the speech is actually finished. The call to speechSynthesiser.SpeakAsync(textToSpeak); may be invoking the onComplete call from the original (UI) thread Your code may be attempting to call onComplete from the background thread and causing an exception because of that. If you use TPL methods you there are ways to marshall back to the UI thread, or you could look at the async/await pattern, which would allow OptiKey to continue, but saves you the bother of thinking about threading (async/await doesn't use threads).

OptiKey logs are here: C:\Users\YOUR_USER_NAME\AppData\Roaming\JuliusSweetland\Logs

**Comment by zelmon64** [comment]
@JuliusSweetland Thanks for all the info. You've given me a lot to got on.

I'm not sure yet how OptiKey might trigger MaryTTS to start but I tried to start it manually while it's already running and it automatically detected the first instance so didn't start a new one. That seems promising at least.

`SoundPlayer` has both a synchronous (`PlaySync`) and an asynchronous (`Play`) mode. At the moment if I use `Play` and press the speak key multiple times it just restarts the speech from the beginning. Hopefully I'll be able to get it to stop on the second press. I hadn't heard about `await` before. Hopefully I'll be able to use it with the `Play` mode and avoid threading like you say.

**Comment by JuliusSweetland** [comment]
I can help with they async/await pattern if you have any questions.

**Comment by zelmon64** [comment]
@JuliusSweetland I've managed to get the correct Speak key behaviour with 70aca37e53c3afe5e4ac7ba976d9399f92189a69. I wasn't able to put `PlaySync` inside async/await but I instead used an `await Task.Delay` with the same duration as the speech. I don't think it should cause any problems doing it this way (it's worked fine for me so far).

The logs helped me find out why the list of available MaryTTS voices had an extra line thanks.

Now to find a way to auto launch MaryTTS ...

**Comment by JuliusSweetland** [comment]
Excellent. Would it not be possible to create a new task which plays the
speech synchronously and await that, rather than await a delay?

**Comment by zelmon64** [comment]
When I tried `await player.PlaySync();` in the task it said **Cannot await 'void'**. I couldn't find a way around it so I used the delay.

**Comment by JuliusSweetland** [comment]
You can spin off the synchronous call to PlaySync onto an awaitable task using Task.Run() (see https://stackoverflow.com/questions/21406973/wrapping-synchronous-code-into-asynchronous-call) for an example. This will call PlaySync on a background thread from the threadpool and then continue from the await when it completes.

**Comment by zelmon64** [comment]
@JuliusSweetland I've managed to make Optikey start and stop MaryTTS: d058446532e1328f2a5cc2c98e6c7ed961f47616.

Unfortunately if MaryTTS is started hidden it can't be stopped so I've set it to start minimised instead. I assume it's better to have it stop when OptiKey is closed but minimised rather than have it hidden but left running when OptiKey is closed.

I've set it to assume the MaryTTS release has been unpacked and placed in "\Resources\marytts" by the user. Would you prefer I try to bundle MaryTTS with the OptiKey installation or is this assumption okay?

Thanks for that link, I'll have a go.

**Comment by JuliusSweetland** [comment]
That all sounds great. I think it is safe to assume the user has installed
MaryTTS themselves, but perhaps the location should be a setting that they
can change where they enable/disabled MaryTTS? Out of interest where is
\Resources\marytts on disk?

**Comment by zelmon64** [comment]
@JuliusSweetland Task.Run() works! It's so much neater!

I put `marytts` in OptiKey's `Resources` folder next to the `Sounds` folder. That makes more sense to make it 's location a changeable setting. Is there a nice way to ask the user where it is?

**Comment by JuliusSweetland** [comment]
What is in the new resources folder? Is it the runtime for MaryTTS itself,
i.e. all the files required to run the service, or is MaryTTS also
installed somewhere else on the disk?

**Comment by zelmon64** [comment]
It's all the files required to run the service. MaryTTS doesn't have a set install location.

**Comment by JuliusSweetland** [comment]
@zelmon64 Ok great. I think two settings may be a good idea; one to say UseEmbeddedMaryTTS installation (bool) and if that's false another to specify the MaryTTS location on disk. If you think this is a good idea the second setting needs an OpenFileDialog (see this link for instructions; http://www.wpf-tutorial.com/dialogs/the-openfiledialog/)

**Comment by zelmon64** [comment]
@JuliusSweetland Thanks for the information on OpenFileDialog. I've managed to make is so that the user must specify the location of MaryTTS (marytts-server.bat): e125cbea78a37307184123d35aee9ee576791d9d. It didn't make sense to me to keep UseEmbeddedMaryTTS because this new method is fairly robust so I removed it.

I'll submit a PR as I think it's ready now.

**Comment by JuliusSweetland** [comment]
Excellent. I'll check it out ASAP.

**Comment by JuliusSweetland** [comment]
Supported added in v2.6.0 - thanks William (@zelmon64)
