### ISSUE TITLE
Localisation: Hebrew

### ISSUE THREAD

**Issue by lilling** [OptiKey/OptiKey#340]
1.Transifex translation of UI strings: 

2.Keyboard layout:
None yet
This was suggested in the past (ignore the number row at the top):
![image](https://user-images.githubusercontent.com/4722561/28912584-bc02bc42-782c-11e7-974b-7b2d0bf41373.png)

3.Alphabet:
a)Letters: 

b)Diacritics that can be added to individual letters (these will be dead keys): 

Total: ? keys

4.Word list: None yet

5.Branch: None yet

**Comment by JuliusSweetland** [comment]
Closing due to lack of progress. This can be re-opened if required.
