### ISSUE TITLE
Add support for nurse call button

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#341]
User suggestion: interface OptiKey with an external call system so that the attention of a nurse/carer can be obtained via a dedicated 'Call' button. This could also be a specific sound (sound and volume should be customisable) which is played when the key is selected.

**Comment by csharperperson** [comment]
Hi! I'd love to get involved with this project, and I was looking over some of the issues, and I believe I can help with this if it's still a relevant issue that needs to be solved. Just doing some late night looking, but tomorrow I'd love to chat more about the project to try and get more involved.

**Comment by JuliusSweetland** [comment]
Hi Tyler,

Yes this issue is still relevent and you'd be very welcome. When would you
like to chat? I'm in London so on UK time.

**Comment by csharperperson** [comment]
I'd be available to chat anytime today.

**Comment by JuliusSweetland** [comment]
Hi Tyler. Which country/timezone are you? I'm a bit busy until later. Maybe
this evening or tomorrow would be better.

**Comment by csharperperson** [comment]
I'm in the US on EST timezone. This evening or tomorrow would be fine. It's the weekend so don't feel obligated haha!

**Comment by JuliusSweetland** [comment]
Hi Tyler. I'm free now if you are? My number is +447989988984

**Comment by csharperperson** [comment]
Yeah i'm free. Shoot me a call whenever! My number is 7063416310.

**Comment by JuliusSweetland** [comment]
Thanks. My little boy isn't feeling very well so I'll give you a call
tomorrow

**Comment by csharperperson** [comment]
No problem. Hope he feels better!

**Comment by JuliusSweetland** [comment]
Thanks.

**Comment by JuliusSweetland** [comment]
Just tried you. Are you available later today?

**Comment by csharperperson** [comment]
Yep! You can call anytime now and I'll answer

**Comment by JuliusSweetland** [comment]
Closing this issue as an alert key has been added to 2.11.0
