### ISSUE TITLE
Presage is not recognized

### ISSUE THREAD

**Issue by mostlyjason** [OptiKey/OptiKey#359]
When Optikey starts I get an error message saying that presage is not available. It gives me this error message even though I have presage installed using the default options. The reason is because presage seems to install for the admin user as opposed to the current user who is logged in. As a result, the folder gets added to the admin user's start menu. I believe this is because the installer has not been updated in a long time, and probably does not support the latest versions of Windows. 

One potential fix for this is to check for the admin user's start menu if it's not found under the current user's start menu. The start menu actually is not required for using presage, I believe you're using it to check the version? If so perhaps there are other ways to check the version?

**Comment by JuliusSweetland** [comment]
@mostlyjason Thanks Jason - good catch

@zelmon64 Do you know if it is possible to check the Admin user's start menu as well as the current user? Also what do you think about performing the start menu check, but only using it to log a warning if the version is not a known supported version?

**Comment by zelmon64** [comment]
@mostlyjason Here's a patch with the checks only logging the errors but not disabling Presage. I looked into my registry and there wasn't a separate admin section but I'm the only user. Can you see an admin section with an equivalent folder for `HKEY_CURRENT_USER\\Software\\Presage`? The registry chechs are also performed by Presage so that it knows where it's files are installed. If you don't pass the registry checks I doubt Presage will work and so the `presageTestInstance` will fail and disable Presage. Is there no way to install Presage for the current user?

[OptiKey_v2.11.0_pre-release_3_patch_1.zip](https://github.com/OptiKey/OptiKey/files/1259643/OptiKey_v2.11.0_pre-release_3_patch_1.zip)

**Comment by JuliusSweetland** [comment]
@zelmon64 To test this you could try running as a user with no admin privileges and running the Presage installer as admin?

**Comment by mostlyjason** [comment]
@zelmon64 the patch you sent didn't do anything when I ran it. Yes I can see the registry key at HKEY_CURRENT_USER\\Software\\Presage however there is not a key here for the start menu. I ran through the presage installer again and there was no way to install for the current user, since installing software requires administrative privileges. Unfortunately the installer does not seem to recognize the current user. I think you can test it using Julius's suggestion to create a nonadministrative user on your computer.

**Comment by zelmon64** [comment]
@JuliusSweetland & @mostlyjason I made a standard account and this is what I learned:

- [ ] There is no registry entry for `HKEY_CURRENT_USER\Software\Presage`.
- [ ] Reinstalling Presage on the standard account does not add the registry entry.
- [ ] Manually adding the registry entries does not enable Presage (tested the included `gprompter.exe` and `OptiKey`).

- [x] Running the application (`gprompter.exe` or `OptiKey`) as admin **works** but uses the admin's registry and log/config files.

Manually adding the registry key passed the manual startup checks but not the `presageTestInstance` which I thought was surprising ( `gprompter.exe`  obviously failed for the same reason). Apart from modifying Presage I can't think of a way around the admin being involved (admin account or run as admin).

**Comment by JuliusSweetland** [comment]
I'm confused why this works for me. OptiKey always runs as a standard user
and it sounds like Presage is always installed as admin?

**Comment by zelmon64** [comment]
@JuliusSweetland When I run OptiKey as standard on my admin account Presage is fine.

**Comment by mostlyjason** [comment]
It's possible that I added the registry key manually many months ago when I was originally doing development on this. I probably just forgot that I did that.

I don't think the registry key is required for the functioning of presage, since it's just a pointer to the location of the installation directory. In the case where the registry key is missing, would it be possible to check the default installation directory to see if the necessary DLL is present? That would bypass this whole issue of what user is running.

**Comment by zelmon64** [comment]
@mostlyjason I learned how to check the registry from the [Presage source code](https://sourceforge.net/p/presage/presage/ci/60cfecabd37370855557efc9782b3d243d1ec14d/tree/bindings/c%23/presage.net/Presage.cs#l303) in order to try to handle when it fails. That's the code the `presageTestInstance` fails at.

**Comment by mostlyjason** [comment]
Yeah that's a bummer I guess we need to include some documentation
instructions for our users telling them where to insert the registry key
then.

Thanks,
Jason

**Comment by JuliusSweetland** [comment]
This sounds as if Jason's install in non standard for some reason. If that
is the case I believe the current Presage checks are fine as they are.
Thoughts?

**Comment by mostlyjason** [comment]
It looks like @JuliusSweetland was right. I looked into this some more and I was able to reproduce @zelmon64's finding that it does not work with a brand-new standard user even after adding the registry key. However, it does work in my current standard user account which I use for development. I am able to run the `gprompter.exe` without errors. Since this was almost a year ago, I no longer remember what changes I made to my environment. It's possible that it was due to installing the development packages for presage including mingw64 and msys. I don't think it makes sense to ask users to install these.

The straightforward workaround I found was to run Optikey as an administrator. Users can turn this on by right clicking the shortcut, clicking the button "Advanced Properties", and then check Run As Administrator.  It might be helpful to add this to the documentation page. Feel free to close this issue.

**Comment by zelmon64** [comment]
@mostlyjason I tried ACAT on my standard account and it used Presage without a problem. I assume this means there must be a way to do it properly. Do you know how similar or different the Presage integration with ACAT is?

**Comment by mostlyjason** [comment]
It's been a long time since I looked at ACAT. I think I remember they had an integrated installer for presage? If that's the case, they may have added additional configurations to make it work. Yes I believe it is possible to use on a standard user account I just don't remember exactly what's required.

**Comment by JuliusSweetland** [comment]
Before I close this could someone please summarise this issue for me as I'm
confused. My main account is an admin account and when I install OptiKey or
Presage I see a Windows User Access Control popup before setup begins. I
don't know if accepting this results in the application being installed as
admin. I have no problems running OptiKey with Presage. Where does this
issue arise? Thanks.

**Comment by zelmon64** [comment]
@JuliusSweetland Here's what I understand of this issue. If a user has a standard account Presage can only be used if OptiKey is run as administrator (either by right clicking and select `Run as administrator` or by setting a shortcut to do that as Jason suggests).

I did some more fiddling and found that if the standard user account is given administrator privileges before installing Presage, the privileges can then be taken away again after it's all installed and it will all work as normal. This way OptiKey doesn't have to be run as administrator and the correct user log/config files are used. Would this be simple enough for people to do?

**Comment by mostlyjason** [comment]
Yes, @zelmon64 is right. Until we determine the unknown dependency, the best solution is to run it as an administrator. I suggest adding the following text to https://github.com/OptiKey/OptiKey/wiki/Next-word-prediction

3. If you are using a standard user account, you must run Optikey as an administrator for presage to work. You may do this by right clicking the shortcut and then clicking run as administrator. Alternatively to save the setting, right click the shortcut, click the button "Advanced Properties", and then check Run As Administrator.

**Comment by JuliusSweetland** [comment]
Added to the wiki page - thank you all.
https://github.com/OptiKey/OptiKey/wiki/Next-word-prediction
Closing.
