### ISSUE TITLE
Communikate pages loaded 5 times per click

### ISSUE THREAD

**Issue by kirstymcnaught** [OptiKey/OptiKey#360]
1. Launch Communikate top page by setting "use CK" and "replace alpha with CK" in the management console
2. Click on any of the buttons linked to another CK page. 
3. The method CK20Page::CKPageFileChanged(...) is called five times; each time reading the (same) obf file.

I imagine this is something to do with the fact that the KeyboardHost is hooked up to changes in CommuniKateKeyboardCurrentContext, CommuniKateKeyboardPrevious1Context, CommuniKateKeyboardPrevious2Context, CommuniKateKeyboardPrevious3Context and CommuniKateKeyboardPrevious4Context (see KeyboardHost.cs lines 61-65). 

If you remove all of the "previous" contexts here (leaving only "current" context property changes) then CKPageFileChanged(...) is only called once, and CK *seems* to work okay including back behaviour. I don't know enough about how the communikate context state is managed to be confident that this is the right fix :) 

Maybe @zelmon64 can comment?

This bug report is based on master @ 55563e05

**Comment by zelmon64** [comment]
@kirstymcnaught thanks for catching this. You are correct that [KeyboardHost.cs lines 62-65](https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey/UI/Controls/KeyboardHost.cs#L62-L65) can (and should be) deleted. I must have added those lines by mistake and hadn't noticed that the pages load 5 times.

How's best to handle this? Should it be corrected in your PR #346 or shall I make a new PR for it after yours is merged?

**Comment by kirstymcnaught** [comment]
If you could make a new PR that would be helpful, thanks. I don't have a commit with these changes, and it isn't related to my PR 346. There shouldn't be any conflicts (I didn't touch the KeyboardHost ctr) so I don't envisage a problem making a PR now and it will merge in fine when Julius accepts the PRs.

**Comment by zelmon64** [comment]
@kirstymcnaught thanks, I'll do that right now then.

**Comment by JuliusSweetland** [comment]
@zelmon64 I've merged PR #367 - can this be closed?

**Comment by zelmon64** [comment]
@JuliusSweetland yes this can be closed. I'll also have a fix for #364 up shortly.
