### ISSUE TITLE
Communikate settings partially-disappear when keyboard language not English

### ISSUE THREAD

**Issue by kirstymcnaught** [OptiKey/OptiKey#364]
- Change language: Management console -> Words -> Keyboard Language -> French
- Close management console.
- Open management console -> Words.
- The option previously labelled "Enable Communikate layout" still has a checkbox, but no label next to it. If the checkbox is checked, then the following options "Replace Alpha keyboard with Communikate" and "Location of ..." are still present with visible labels.

Looks like the culprit is WordsViewModel::UseCommuniKatedKeyboardLayoutIsVisible, and this needs to extend to all the CK options and labels, and not just the first label. It is also worth noting that even if this was working properly, it doesn't update until the changes to language are committed when exiting the management console. Ideally it would reflect the current (uncommitted) selections in the management console UI, rather than the committed settings, otherwise the behaviour when changing language is unexpected.

**Comment by zelmon64** [comment]
@kirstymcnaught thanks for catching this. Part of the problem was a typo that I had only partially fixed.

**Comment by JuliusSweetland** [comment]
@kirstymcnaught Thanks very much for pointing this out.
@zelmon64 Thanks for fixing it so promptly!

I'll close this issue.
