### ISSUE TITLE
Custom Keyboard Editor

### ISSUE THREAD

**Issue by gabrielbenjamin** [OptiKey/OptiKey#366]
I'm given to understand that because Optikey supports Communikate, it also supports the open board format. I gather that means that custom keyboards are possible. I know that currently custom keyboards could be put together using bare text. I'm suggesting that visual editor would make things easier for some users. Perhaps a more friendly directory structure for keyboards, I would really like to dig into the code, and mock something up. As usual, I have developed serious health issues and I have never dealt with C# before.

**Comment by JuliusSweetland** [comment]
Hi @gabrielbenjamin - I would hold off on any new work on this. @kirstymcnaught is working to deliver custom user keyboards at the moment!

**Comment by zelmon64** [comment]
@gabrielbenjamin there is technically already a visual way but it requires Microsoft PowerPoint (I haven't found a way to do it with open- / libreoffice yet). The PowerPoint file can be processed by [The Open Voice Factory](http://www.theopenvoicefactory.org/index.html) to generate an open board format OBZ file. See http://www.theopenvoicefactory.org/guides.html

I haven't personally been able to try this as I don't have Microsoft PowerPoint but from the guides it looks relatively straightforward.

@JuliusSweetland I thought I'd add this information for completeness. I don't mean to diminish kirstymcnaught's work on custom user keyboards in any way.

**Comment by JuliusSweetland** [comment]
That's really useful info, thanks William.
