### ISSUE TITLE
Disable dictionary tab when using Presage

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#369]
Presage has its own built in word list/dictionary. As such the controls in the dictionary tab should be disabled when the suggestion method is Presage.

**Comment by zelmon64** [comment]
I've made a partial PR for this. What's missing are the Resources entries. They've been left out so that they can be added after #377 is merged without any conflicts.

**Comment by JuliusSweetland** [comment]
I've merged the other pr, but I've also added a comment to your pr.

**Comment by zelmon64** [comment]
Thanks. I can't seem to find your comment though. Could you point me at it please?

**Comment by JuliusSweetland** [comment]
Sorry I'm on mobile and hadn't submitted the review. There now.

**Comment by JuliusSweetland** [comment]
Can this be closed?
