### ISSUE TITLE
Catch exceptions from copyfromscreen and display error instead

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#370]
There is an unhandled exception that can be thrown from the CopyFromScreen method (details below):

This occurs in the MagnifyPopup control and I imagine handling this by wrapping the call to DisplayScaledScreenshot(), logging the error, and raising an error toast to the user before continuing.

2017-09-07 16:01:39,244 [ 1] ERROR JuliusSweetland.OptiKey.App: A DispatcherUnhandledException has been encountered...
System.ComponentModel.Win32Exception (0x80004005): 작업을 완료했습니다
   위치: System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   위치: System.Drawing.Graphics.CopyFromScreen(Point upperLeftSource, Point upperLeftDestination, Size blockRegionSize)
   위치: JuliusSweetland.OptiKey.UI.Controls.MagnifyPopup.CaptureScreenshot(Point point) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\Controls\MagnifyPopup.cs:줄 160
   위치: JuliusSweetland.OptiKey.UI.Controls.MagnifyPopup.DisplayScaledScreenshot(Point point) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\Controls\MagnifyPopup.cs:줄 123
   위치: JuliusSweetland.OptiKey.UI.Controls.MagnifyPopup.&lt;&gt;c__DisplayClass5_0.&lt;OnLoaded&gt;b__0(Nullable`1 sourcePoint) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\Controls\MagnifyPopup.cs:줄 55
   위치: System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   위치: System.Reactive.ObserverBase`1.OnNext(T value)
   위치: System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   위치: System.Reactive.ObserverBase`1.OnNext(T value)
   위치: System.Reactive.SafeObserver`1.OnNext(TSource value)
   위치: System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   위치: System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   위치: System.Reactive.Subjects.Subject`1.OnNext(T value)
   위치: System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.&lt;&gt;c__DisplayClass4.&lt;GetHandler&gt;b__1(Object sender, TEventArgs eventArgs)
   위치: System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   위치: Prism.Mvvm.BindableBase.OnPropertyChanged(String propertyName)
   위치: Prism.Mvvm.BindableBase.SetProperty[T](T&amp; storage, T value, String propertyName)
   위치: JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.set_MagnifyAtPoint(Nullable`1 value) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\ViewModels\MainViewModel.cs:줄 176
   위치: JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.&lt;&gt;c__DisplayClass3_0.&lt;SetupFinalClickAction&gt;b__0(Point nextPoint) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:줄 1505
   위치: JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.&lt;AttachServiceEventHandlers&gt;b__0_4(Object o, PointAndKeyValue value) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:줄 91
   위치: JuliusSweetland.OptiKey.Services.InputService.PublishSelection(PointAndKeyValue selection) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\Services\InputService.cs:줄 386
   위치: JuliusSweetland.OptiKey.Services.InputService.ProcessSelectionTrigger(TriggerSignal triggerSignal) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\Services\InputService.subscriptions.cs:줄 0
   위치: System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   위치: System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnNextPosted(Object value)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
</CustomInfo>
  <GeneralInfo>
    <CLRVersion>4.0.30319.42000</CLRVersion>
    <DateTime>2017-09-07 오전 7:01:39</DateTime>
    <ExceptionMessage>작업을 완료했습니다</ExceptionMessage>
    <ExceptionType>System.ComponentModel.Win32Exception</ExceptionType>
    <HostApplication>OptiKey.exe</HostApplication>
    <HostApplicationVersion>2.3.11.0</HostApplicationVersion>
    <NBugVersion>1.2.1.0</NBugVersion>
    <TargetSite>Void CopyFromScreen(Int32, Int32, Int32, Int32, System.Drawing.Size, System.Drawing.CopyPixelOperation) @ System.Drawing.Graphics</TargetSite>
  </GeneralInfo>
</Report>

<SerializableException xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ExtendedInformation>
    <NativeErrorCode>0</NativeErrorCode>
    <ErrorCode>-2147467259</ErrorCode>
    <HResult>-2147467259</HResult>
  </ExtendedInformation>
  <InnerExceptions />
  <Message>작업을 완료했습니다</Message>
  <Source>System.Drawing</Source>
  <StackTrace>   위치: System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   위치: System.Drawing.Graphics.CopyFromScreen(Point upperLeftSource, Point upperLeftDestination, Size blockRegionSize)
   위치: JuliusSweetland.OptiKey.UI.Controls.MagnifyPopup.CaptureScreenshot(Point point) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\Controls\MagnifyPopup.cs:줄 160
   위치: JuliusSweetland.OptiKey.UI.Controls.MagnifyPopup.DisplayScaledScreenshot(Point point) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\Controls\MagnifyPopup.cs:줄 123
   위치: JuliusSweetland.OptiKey.UI.Controls.MagnifyPopup.&lt;&gt;c__DisplayClass5_0.&lt;OnLoaded&gt;b__0(Nullable`1 sourcePoint) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\Controls\MagnifyPopup.cs:줄 55
   위치: System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   위치: System.Reactive.ObserverBase`1.OnNext(T value)
   위치: System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   위치: System.Reactive.ObserverBase`1.OnNext(T value)
   위치: System.Reactive.SafeObserver`1.OnNext(TSource value)
   위치: System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   위치: System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   위치: System.Reactive.Subjects.Subject`1.OnNext(T value)
   위치: System.Reactive.Linq.ObservableImpl.FromEventPattern.Impl`2.&lt;&gt;c__DisplayClass4.&lt;GetHandler&gt;b__1(Object sender, TEventArgs eventArgs)
   위치: System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   위치: Prism.Mvvm.BindableBase.OnPropertyChanged(String propertyName)
   위치: Prism.Mvvm.BindableBase.SetProperty[T](T&amp; storage, T value, String propertyName)
   위치: JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.set_MagnifyAtPoint(Nullable`1 value) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\ViewModels\MainViewModel.cs:줄 176
   위치: JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.&lt;&gt;c__DisplayClass3_0.&lt;SetupFinalClickAction&gt;b__0(Point nextPoint) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:줄 1505
   위치: JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel.&lt;AttachServiceEventHandlers&gt;b__0_4(Object o, PointAndKeyValue value) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\UI\ViewModels\MainViewModel.ServiceEventHandlers.cs:줄 91
   위치: JuliusSweetland.OptiKey.Services.InputService.PublishSelection(PointAndKeyValue selection) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\Services\InputService.cs:줄 386
   위치: JuliusSweetland.OptiKey.Services.InputService.ProcessSelectionTrigger(TriggerSignal triggerSignal) 파일 F:\OptiKey\src\JuliusSweetland.OptiKey\Services\InputService.subscriptions.cs:줄 0
   위치: System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   위치: System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnNextPosted(Object value)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by bswearingen** [comment]
Is help still needed on this? This seems like something I could handle before knowing too much of the code base.

**Comment by JuliusSweetland** [comment]
Hi Ben. It is yes. The idea would be to catch the exception and raise an
error toast popup. Let me know if you have any questions.

**Comment by bswearingen** [comment]
Hi Julius. I have two questions:

1. Do you have any thoughts on what should be done with the mouse action that causes the exception? Logging the error and continuing with the standard flow causes problems in TranslateMagnifiedSelectionPoint(Point point). I think that disregarding the action would make sense, given that the user would be expecting the MagnifyPopup so that they could give a more precise input.
2. Do you know if this error occurs repeatedly? If so, I think it _could_ make sense to make sure that the magnify button is not locked down, as long as I include that behavior in the toast.

**Comment by JuliusSweetland** [comment]
Hi Ben

1. Yes the mouse workflow should be discarded when the error occurs

2. I wouldn't worry about that. If it keeps happening when the user
attempts a mouse click then it would fail each time. I think it would be
more confusing for it to fail once, but half work the next time as
magnification has been silently disabled.
