### ISSUE TITLE
Refactor and possible bugs in the CK20Page class(es)

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#375]
@kmcnaught As discussed...

1. Refactor this method to be smaller/split into more manageable methods: https://github.com/OptiKey/OptiKey/blob/5b64d3551ad4ea3f5a2856f3894e1a8e0ba3de3e/src/JuliusSweetland.OptiKey/UI/Controls/CK20Page.xaml.cs#L54

2.Clean up the code to remove unused elements (commented out code etc)

3.Identify and refactor a possible bug where the key.CKBaCo_00 is set (in multiple places). 

Colours are set in the files like this: "rgb(255,239,7)"
These lines extract this value, but leave the last ")" on the string: colour = CKPageOBF.buttons.ElementAt(buttonid).background_color.Substring(4);
The final ")" is later removed with this line: key.CKBaCo_00 = colour.Substring(0,   colour.Length - 1);

a) It would be cleaner if the colour was extracted in one go and converted into hex outside of the setter.

b) Could the local variables like "defaultcolour" be renamed to lower camel case (forExampleLikeThis): https://github.com/OptiKey/OptiKey/blob/5b64d3551ad4ea3f5a2856f3894e1a8e0ba3de3e/src/JuliusSweetland.OptiKey/UI/Controls/CK20Page.xaml.cs#L87-L93

c) The line key.CKBaCo_00 = colour.Substring(0,   colour.Length - 1); is also applied to the defaultcolour "#000000" reducing it to "#00000". This is actually dealt with by the way hex is handled, but it shouldn't be done really.

d) Is the above code used at all? "(buttonid < ButtonCount)" may *always* be true, since at the start of CKPageFileChanged(...) there's a whole bunch of logic inserting blank buttons (or back buttons) into any gaps in the board, after which ButtonCount is always at the maximum (20)? I have not confirmed this yet - it's from reading the code.

@zelmon64 Kirsty has asked me a few questions about the above points. I put them here so that we can answer a few questions and get the code cleaned up a bit if we agree. We all agree that the code works well, so I hope you aren't offended.

**Comment by zelmon64** [comment]
> We all agree that the code works well, so I hope you aren't offended.

@JuliusSweetland thanks. No offence taken. It certainly does need a clean up! The redundant code (such as the `buttonid < ButtonCount` bits) are leftovers from the evolution. I left them because once it was working I didn't want to risk breaking it again. Ideally the keys should be assigned in a loop rather than how it is which should shrink `CKPageFileChanged` quite a bit. 

I'm happy to tackle this issue after #372.

**Comment by JuliusSweetland** [comment]
Great thanks.

**Comment by zelmon64** [comment]
@kmcnaught I've addressed most (hopefully all) of the points listed above in PR #378. If you have a moment could you please see if it satisfies all of your concerns or if you notice anything else that should be tidied up? Thank you.

**Comment by kmcnaught** [comment]
I've reviewed over at  PR #378.

**Comment by JuliusSweetland** [comment]
Can this be closed?

**Comment by kmcnaught** [comment]
Yes
