### ISSUE TITLE
Performance issue - key fixation delays and freezing

### ISSUE THREAD

**Issue by maartee** [OptiKey/OptiKey#382]
I experience key focus delays and freezing usually after 30-60 minutes of OptiKey intensive use.
This behaviour starts when OptiKey occupies ~700 MB of RAM. If I continue without OptiKey restart, it goes over 1GB or more. Typing becomes very difficult then, because the freezes appear with each new eye focus. After restart, it takes around 50MB and works perfectly for another time period.
Clearing dictionary folder and reinstalling OptiKey did not help.

My setup:
Optikey v2.10.0.0, English US dictionary, key fixation to complete: 290ms
Windows 10 Home 64-bit, EN
Hardware:
Tobii 4C Eyetracker (with 2.10.0 driver sw)
16GB RAM, Intel i7 CPU, SSD harddrive

I am not programmer, but I would be happy to provide details and do more testing/investigating, if needed.

**Comment by JuliusSweetland** [comment]
@maartee When OptiKey is consuming a large amount of ram could you right click on the taskbar icon for OptiKey and minimise it. Then do the same and restore it. Could you tell me the memory usage before and after and if this improves things at all? This isn't a fix, this is just to give me a bit more information

**Comment by maartee** [comment]
I've tried the steps desribed, but minimizing of OptiKey doesn't work for me as with other taskbar icons, so I minimized from OptiKey main menu.
The RAM used dropped by tens of MBs during first minute, then it stays the same.
After restore, the RAM usage went up, almost to amount where it was before.

just an idea -
it seems to me like higher typing speed together with frequent changes of layouts(I use symbols a lot) prevents the app memory optimization to be effective, is that possible? When I started using OptiKey a couple of months ago, my typing speed was much slower and I didn't experience the issue described. It kind of evolved over time.

**Comment by JuliusSweetland** [comment]
It's possible. It sounds like a memory leak. I would guess either with the
keyboards or keys. I'll have to investigate.

**Comment by JuliusSweetland** [comment]
I haven't had a chance to investigate this yet. If anyone else sees this and they are interested then please feel free to get stuck in!

**Comment by JuliusSweetland** [comment]
Closing this issue as it linked to #430 

Potential fix will be released as a pre-release of 2.0.14 shortly.
