### ISSUE TITLE
Simplify keyboard selection in settings

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#383]
Currently if your language is english, the management console allows you to replace the alpha keyboard with  a simplified keyboard layout, an alphabetical layout, or a Communikate layout. Each of these options appears/disappears based on other settings. It would be clearer from a user's perspective to consolidate these into a single option such as "Keyboard style for typing" where the options are qwerty/alphabetic/simplified/communikate.

**Comment by JuliusSweetland** [comment]
I agree with this idea

**Comment by zelmon64** [comment]
I'm going to have a go at this today if that's alright. I thought it would be nice to have for the next release.

**Comment by JuliusSweetland** [comment]
Great thanks
