### ISSUE TITLE
French dictionary missing conjugations of common words

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#385]
I don't know much French so I was limited to testing simple things like "je suis", "je ne sais pas", and it seems that some very common verbs are only in the dictionary in infinitive form, so do not appear as suggestions. This means multi-key selection isn't working for these simple words. It might be worth adding the top 100 or so verbs in different conjugations? This might also apply to other languages with more complex verb conjugations than English.

**Comment by JuliusSweetland** [comment]
Yeah the French dictionary could be improved. Could you double check that these words are not in the source dictionary file?

**Comment by kmcnaught** [comment]
Yes, words like "sais" and "suis" are not in the source dictionary file.

**Comment by kmcnaught** [comment]
To clarify, there are *some* conjugated verbs in the dictionary file, but lots of very common ones are missing.

**Comment by JuliusSweetland** [comment]
Yeah I remember there was difficulty finding a decent French dictionary. Do
you have anything we could use or a word list I could add to the current
French dictionary? I can convince with anything and then clean up dupes etc.

**Comment by kmcnaught** [comment]
[conjugated french verbs](https://www.dropbox.com/s/zsi6nb2p3vluwsv/common-french-conjugated.txt?dl=1)

This might be an okay start (to add to the current dictionary file) - it's the top 100 verbs, conjugated by the verbix API
http://www.verbix.com/webverbix/termsofuse.html

Do you know if other languages have the same problem?

**Comment by JuliusSweetland** [comment]
No one has reported the same problem so far. German may have a similar
problem as they combine words so the possible dictionary of words is
massive.

**Comment by JuliusSweetland** [comment]
@kmcnaught I've updated the French dictionary to include the linked verbs and have parsed the new combined dictionary through a filter to remove dupes etc.
