### ISSUE TITLE
Force caps lock/using shift key 

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#406]
I'm not sure what the use case is for the "force caps lock" setting, but it seems strange as a user that writing in caps lock would also prevent me from using the shift key for other things such as shortcut key combos. Currently if you select "force caps lock" in the settings, then the shift key (on the optikey keyboard) is held down and disabled. (though as far as I can tell shift isn't actually held down)

**Comment by JuliusSweetland** [comment]
@kmcnaught The fact that shift if not actually down is a bug, but the behaviour is designed for users who do not want to consider casing when using OptiKey, i.e. a use case would be to turn on this setting as well as 'Conversation Only Mode' and type in all cape just to talk.

Any chance you could identify why Shift is not pressed when the normal (docked) alpha keyboard is used with 'Force Caps Lock'?

**Comment by kmcnaught** [comment]
I might be wrong - perhaps I'd used the shift key myself at some point and undone the hold-down. I won't get a chance to look at this further I'm afraid. When you type, the letters do all come out in caps, which is the desired behaviour. I'm just not sure why (as a user) that should also impede your ability to use function keys freely for shortcuts. What if I always want to type in capitals, but then I want to "Ctrl-S" my document (or alternately "Ctrl-Shift-S" my document)? Currently you'd only be able to do one of the two, depending on whether shift is correctly held down or not. 

If you'd only ever use this setting in combination with conversation mode then this is irrelevant.

**Comment by JuliusSweetland** [comment]
That it true. I will test the shift behaviour.

**Comment by JuliusSweetland** [comment]
@kmcnaught Hi Kirsty - I have tested and SHIFT is (virtually) pressed for all key presses outside OptiKey, so I am happy that this feature is working as designed. I will clarify the wording of the setting a little bit to make it clearer that it isn't actually CAPS LOCK (which would allow you to still use the SHIFT as a modifier for shortcuts etc), but that SHIFT will be locked down. I'm going to close this issue.
