### ISSUE TITLE
Not getting error messages when eye tracker can't connect

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#409]
Version: 2.11.0.0

When I try to connect to a non-existent or disconnected eye tracker, I'm not getting any user-facing error messages. (there are errors in the logs though). I'm sure we used to get user error-messages (red toasts) along the lines of "Uh oh, can't connect to xx"...

On my own PC (Win8.1) I *never* get any of these messages running v2.11.0.0 (have tested EyeX/MyGaze/EyeTribe/Gaze Tracker). On a different (Win10) PC, using EyeX, I get the error messages *after* turning manual mode on and then off again, i.e.
- Launch OptiKey using an eye tracker that isn't connected
- No error message appears, it just silently doesn't work
- Turn on Manual Mode
- Turn off Manual Mode
- An "Uh oh" message immediately appears.

With MyGaze on the 2nd PC I don't get any error message. I haven't tested other eye trackers.

**Comment by JuliusSweetland** [comment]
Fix in 2.12.0 pre_release_2 (https://github.com/OptiKey/OptiKey/releases/tag/v2.12.0_pre-release_2)
