### ISSUE TITLE
Add ability to change voice without going to the Management Console

### ISSUE THREAD

**Issue by Sheeva007** [OptiKey/OptiKey#415]
With Optikey, i can easily change the language via main page ' language ' this option is pretty cool but, only thing not changing is the most important,the correct voice following my language selection.
My mother language is french but my wife mother language is croatian. Before my desease we speak croatian. And with my kids is a genrous mixup :-) i speak also dutch (in belgium we have 2 official language french/dutch) i know only few sentences of this language but, people love when you know few words of they mother language. Is breaking the ice. So, it's i thing that never exist on other like yours the possibility of changing ON_THE_FLY used language and Optikey is very close to do that. About the voice following your selection, espeak from sourceforge can do the trick. I realy thing is about to make a huge improuvment regarding other 'costy' solutions.

Dominique .

**Comment by Sheeva007** [comment]
With Optikey, i can easily change the language via main page ' language ' this option is pretty cool but, only thing not changing is the most important,the correct voice following my language selection.
My mother language is french but my wife mother language is croatian. Before my desease we speak croatian. And with my kids is a genrous mixup :-) i speak also dutch (in belgium we have 2 official language french/dutch) i know only few sentences of this language but, people love when you know few words of they mother language. Is breaking the ice. So, it's i thing that never exist on other like yours the possibility of changing ON_THE_FLY used language and Optikey is very close to do that. About the voice following your selection, espeak from sourceforge can do the trick. I realy thing is about to make a huge improuvment regarding other 'costy' solutions.

Dominique .

**Comment by JuliusSweetland** [comment]
I think this could be achieved in one of 2 ways:

1.A new keyboard that allows you to select form the installed languages. Changing the keyboard language and the TTS language would then become a 2 step process.
2.The user has to somehow create a link between each Keyboard language and TTS language, which will then be changed together. If this is the chosen solution then it is important that this behaviour is off by default.

**Comment by Sheeva007** [comment]
@JuliusSweetland Sorry, i was sik last week. My vision of this improvment is, while selecting language . The keyboard layout is changing to thenew selection. Missing only the related voice. If thing only 'eSpeak' who is working on command like espeak -voice fr,en,hr,... I know the quality of espeak is not higth but,understandable. Interressant thing to know is ESpeakNG on github. :)

**Comment by JuliusSweetland** [comment]
I think the hardest thing would be associating languages with TTS voices, so perhaps the solution would be, as you suggest, to display the available TTS voices on a keyboard after the user has changed language, so the workflow would be:

a)Menu -> Languages keyboard
b)Select keyboard language
c)Select voice
d)Return automatically to menu

**Comment by Sheeva007** [comment]
@JuliusSweetland Let's do in this way and see whats append. You are still the Guru. :-)

**Comment by Sheeva007** [comment]
i come back to you ASAP.

**Comment by joshlcampbell** [comment]
@JuliusSweetland Hi! I'd like to help out. If you have no objections, I'll start work on this issue.

**Comment by JuliusSweetland** [comment]
That's great, thanks Joshua.

**Comment by JuliusSweetland** [comment]
@Sheeva007 This has been added by @joshlcampbell and is released in new version 2.13.0

Closing this issue. Thanks everyone and happy new year!
