### ISSUE TITLE
Allow pasting of text into the scratchpad (so that it can be spoken)

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#422]
I think of you wanted to type into OptiKey, or paste text in, you would need to:

Make the scratchpad writeable.
Text to text input in the scratchpad in a different way from normal output, i.e. identify when it is typed instead of captured from the output service.
Pass the text one letter or word at a time to the main view model, which would then pass it into the output service, but with a flag denoting that this text was typed not captured.
You could then use this flag to skip any processing in the output service that was not relevant.

**Comment by vijayrajanna** [comment]
Julius and I are currently working on this feature. 
It is partially complete, I am trying to fix a few bugs. We should have this feature in a week from now.
