### ISSUE TITLE
Add alternate mouse scrolling method

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#423]
Looking at the centre of the screen stops scrolling, but looking above/below the centre point scrolls up/down.

Horizontal scrolling could also be achieved.

It might make more sense to allow the user to drop the centre point themselves, so that focus can be given to the window chosen (optional). This would also avoid the potentially wrong assumption that the user always wants to scroll the window under the centre point of the screen.

**Comment by JuliusSweetland** [comment]
Looking at the centre of the screen stops scrolling, but looking above/below the centre point scrolls up/down.

Horizontal scrolling could also be achieved.

It might make more sense to allow the user to drop the centre point themselves, so that focus can be given to the window chosen (optional). This would also avoid the potentially wrong assumption that the user always wants to scroll the window under the centre point of the screen.

**Comment by joshlcampbell** [comment]
I will begin looking into this issue.

**Comment by JuliusSweetland** [comment]
Fantastic, thank you. Happy new year.

**Comment by joshlcampbell** [comment]
Hello again, and happy new year to you as well! 

Happily, I'm able to start working on this in earnest now, but I do have a quick question: do you envision this alternate scrolling method (which I'm tentatively labeling "look to scroll" though I'm open to another name) being used in conjunction with the current methods or more as a replacement (chosen via the Management Console)? 

The reason I ask is to determine whether I need to try to make room for new keys on the Mouse keyboard or can re-use the space given to the existing scrolling-related keys.

**Comment by JuliusSweetland** [comment]
Hi Joshua,

I initially thought this would be an alternative method, chosen from the
management console, but the current scroll functionality has 5 keys
(including the scroll amount) on the expanded mouse keyboard, so there
isn't a straightforward way to replace this with a single new scroll
method. If possible so you think the new scroll method could fit somewhere?
I think a management console setting could control which method appears on
the collapsed view though.

**Comment by joshlcampbell** [comment]
I am thinking -- if you're willing to have this alternative method replace the other via settings -- that I might replace those 5 keys with 5 of my own:

1. Vertical Scroll: look above the center point (which I'm tempted to call the "anchor" to avoid confusion with the screen center) to scroll up and look below the "anchor" to scroll down.
2. Horizontal Scroll: likewise, look left of the anchor to scroll left and right of the anchor to scroll right.
3. Free Scroll: a combination of the previous two.
4. Drop Anchor ("yar har!"): determines whether the user places the anchor themselves before scrolling versus using the center of the screen (or, rather, the portion of the screen not occupied by OptiKey itself) as mentioned in the issue description. It could be up (use screen center), down (drop anchor for the next scroll), or locked down (always drop anchor before scrolling).
5. Scroll Speed: replaces the scroll amount and cycles between a few presets when pressed. The names, base speeds (in mouse wheel units per second), and distance-based speed scaling (look closer to the anchor to go slow down; look farther away to speed up) could be configurable in the Management Console.

For the collapsed view, my gut says Vertical Scroll as it's on there now in the form of two keys and is probably the most common use-case: reading normal wrapped text. With that leftover key, I'd wager a shortened form of the Scroll Speed key would be the next-most useful (for example: quickly flipping through a document on the "fast" preset to find a specific section, then transitioning to the "slow" preset to find the exact line you want).

I don't have lot of experience yet with eye tracking from the perspective of a user, so I apologize if my understanding of the use cases for this feature is off the mark. I'm more than willing to admit I might be over-complicating the issue :). I look forward to hearing your thoughts.

**Comment by JuliusSweetland** [comment]
Actually that sounds really good. Let's go with replacing the keys.

**Comment by joshlcampbell** [comment]
Hello! Just wanted to drop in and let you know I haven't forgotten about this issue. Work is progressing nicely. It's evolved a bit from my last description, based on using myself as a guinea pig and seeing what works / doesn't work. 

For example: I've found some apps don't work well with scroll amounts that aren't whole "clicks" or some exact fraction of a click (1/2, 1/3, 1/4, etc.), so I've made that configurable. I also found myself often switching between horizontal and vertical scrolling in cases where a true "free" scroll wasn't desirable, so I've introduced a "cross" mode where you "switch with your eyes" so to speak: look along the vertical center-line to scroll vertically, look along the horizontal center-line to scroll horizontally, looking anywhere else does nothing. 

Anyway, I should have a pull request for you to review within the next week or so.

**Comment by JuliusSweetland** [comment]
That sounds excellent. Looking forward to it.

**Comment by JuliusSweetland** [comment]
A new pre-release of OptiKey is available as version 2.0.14 which includes an alternative scrolling method (details on the release notes): https://github.com/OptiKey/OptiKey/releases

Could you please try it out and let me know how it works for you.

N.B. I have signed the installer and OptiKey.exe file with a new certificate, so please don't worry if Windows warns you of an untrusted certificate - it takes time for trust to build up again.

**Comment by joshlcampbell** [comment]
Testing on my home PC at present. Running into a bug when using Window bounds while the overlay window setting is enabled. It's selecting some invisible screen-sized window instead of the actual window I'm looking at. Disabling the overlay fixes it. Ran into something similar on my dev PC during development but thought I'd squashed it. Investigating...

Also, here's a screenshot of the SmartScreen popup I got while trying to install since you mentioned in #430 that you were curious. That's in addition to the normal UAC pop-up I got after clicking "Run anyway".

![smartscreen popup](https://user-images.githubusercontent.com/3516600/36325544-20bc4fce-1326-11e8-9898-ea43d8b2afa0.png)

**Comment by joshlcampbell** [comment]
Was able to reproduce it on my dev box. Interestingly, it only occurs using the installed version of OptiKey, not when running it from Visual Studio (even in Release configuration). Maybe the UiAccess flag? Still investigating...

**Comment by JuliusSweetland** [comment]
Perhaps to achieve UIAccess Windows doors something funky like create an
opaque full screen layer to draw on? Kind of like WPF adorners.

**Comment by joshlcampbell** [comment]
Before I had to stop for the day yesterday, I had narrowed it down to the Start screen. Using Spy++, it apparently has the HWND that's being reported as selected in the logs. From what I've been reading the UiAccess flag allows OptiKey to run at a higher privilege level so as to appear on top of and send input to the start screen. Makes sense then I suppose that only when running with UiAccess enabled is the Start screen is enumerated by EnumWindows, since that's the only time the OptiKey process would have access to it. 

It's curious that the WS_VISIBLE and WS_MINIMIZE checks didn't filter it out, but maybe it resides in a completely different desktop where it's always visible and always maximized. I want to try switching to EnumDesktopWindows to only enumerate the windows on the current desktop instead and see if that helps. First, though, I have to figure out how to run my own builds with UiAccess enabled so I can tell if I've actually solved the problem. Your documentation in UiAccess.txt has given me a good place to start. :)

**Comment by JuliusSweetland** [comment]
From what I know it's not possible to run from visual studio with UIAccess
enabled, which is going to make this a particularly difficult issue to
debug.

If it proves impossible I'd be happy with just screen overlay or manual
overlay.

**Comment by JuliusSweetland** [comment]
@joshlcampbell Hi Josh. How is the alternate scrolling method? No rush, just wondering.

**Comment by joshlcampbell** [comment]
Has a good half-day or so of work remaining for the additions mentioned in the original pull request. Nothing difficult, though. I'll try to tackle the majority of it today. And I want to get you that wiki page I promised as well. :)

**Comment by JuliusSweetland** [comment]
@joshlcampbell Lovely stuff. @samgled and I are in the final stages of adding support for Japanese as well so 2.14.0 is looking like a nice chunky release now.

**Comment by JuliusSweetland** [comment]
Thanks to @joshlcampbell this has been implemented and will be released soon in v2.14.0
