### ISSUE TITLE
Suggestion - Automatic Language detection using google API

### ISSUE THREAD

**Issue by pdeclerc** [OptiKey/OptiKey#429]
Hello Junius,
After a home visit to Sheeva700 yesterday evening, seeing him use Optikey for communicating with the outside world 24/7 we wonder if it would be possible to look at the Cloud Machine Learning Engine to integrate automatic switching between languages in Optikey. At this moment if he needs to communicate with people in a different language he has to go through the config menu to change the language (it seems to already be a big improvement to be able to do that without needing to restart the application).
Cloud Machine Learning Engine is able to detect the language from a single phrase (a set of words).
Google previously had a Prediciton API, but from the end of April this api will be E.O.L. and they will stop support and access to it.

Please have a look and let us know if you see a possibility in this.

Cheers,
Peter

**Comment by JuliusSweetland** [comment]
Hi Peter. I'll open this up as an issue that needs attention.

**Comment by maryzam** [comment]
Hello, @JuliusSweetland. 
As soon as Cloud Machine Learning Engine is paid service and it's probably "too smart" to use it only for a language detection, you may be interested in alternative translate services.
There is at least one free alternative for that - Yandex Translate (https://tech.yandex.com/translate/)
I've migrated to this service several projects after Google closed it's Translate API and it works pretty well.
Btw, I'll be happy to help with this feature in case you'll decide to implement it.
