### ISSUE TITLE
Add Canadian french keyboard option

### ISSUE THREAD

**Issue by alecc08** [OptiKey/OptiKey#437]
Currently when selecting french, it displays a european (AZERTY) style keyboard. In Quebec, Canada, we use a french QWERTY style keyboard.

**Comment by JuliusSweetland** [comment]
@alecc08 Please can you test pre-release v2.14.0 (https://github.com/OptiKey/OptiKey/releases) which includes FrenchCanada support (QWERTY keyboard layout).

**Comment by alecc08** [comment]
@JuliusSweetland works great, thanks. Unfortunately my dad passed away before he got to see this feature but he appreciated optikey immensely, as it gave him his voice back 😄 keep up the great work. Hope this feature will benefit other french canadians.

**Comment by JuliusSweetland** [comment]
@alecc08 I'm very sorry to hear that.
