### ISSUE TITLE
Simultaneous keystrokes

### ISSUE THREAD

**Issue by timstewartuk** [OptiKey/OptiKey#448]
Many operations in windows programs are required to be started using multiple key combinations. The obvious one is the key combination, Ctrl+Alt+Delete, which in windows, opens the task manager. Is this/will this be possible?

Thanks for a very useful programme.

Regards Tim

**Comment by JuliusSweetland** [comment]
@timstewartuk you should be able to perform combinations like this. The "modifier" keys such as CTRL and ALT can be pressed down and will stay down until you press a key that will release them, eg delete, which is on the physical keyboard. Does it not work for you?

**Comment by timstewartuk** [comment]
Hi Julius,

for me, in Windows 10, it doesn't work, as you can see in the attached file. My apologies, as I did not edit it.

I can just about manage to do this manually, and the combination brings up a blue screen giving me various options to Lock, Switch user, Sign out, Change password, and Task Manager. This blue screen is in front of everything. To get back to the desktop I have to press the Esc key or Cancel.

Regards Tim

[optikey.zip](https://github.com/OptiKey/OptiKey/files/1825043/optikey.zip)
