### ISSUE TITLE
Look-to-scroll bug

### ISSUE THREAD

**Issue by samgled** [OptiKey/OptiKey#451]
After turning on "Look to scroll" with area setting set to "Window" then scrolling up and down inside Chrome, I select left click without turning off scroll and once I move my gaze through the scroll area, my gaze is no longer recognized by OptiKey. I can still scroll, but I am unable to complete the left click action and can no longer do anything inside the OptiKey keyboard.

The "Do at current location" left click action had no ill effect, even when inside the scroll area.

Suggestion: make it so selecting any other "Do at point" action automatically de-selects "Look to scroll".

**Comment by joshlcampbell** [comment]
I was able to reproduce the bug on my own machine. I apologize. I missed that particular combination of keys during my own testing. 

I like your suggestion of having look to scroll automatically deactivate when using any of those "do at point" keys. Do you think there would be value in having it also automatically reactivate once you're done clicking? Based on your experience with the feature thus far, would you find yourself wanting to keep scrolling after a click more often than you would want it to stop?

It could always be configurable, too, I suppose. What are your thoughts, @JuliusSweetland?

Thanks!

**Comment by JuliusSweetland** [comment]
@joshlcampbell I like the idea of automatically deactivating, with a configurable reactivation? Maybe a setting that defaults to true?

**Comment by samgled** [comment]
Thinking about internet use, mouse clicks navigate to new pages, open drop-downs, or put a cursor in a text entry box. So, after clicking, a user will probably either want to keep scrolling or switch to a new keyboard in Optikey to enter text.

At the moment, look to scroll stays on when you navigate away from the mouse keyboard. Should it also automatically deactivate when you select the back button?

**Comment by joshlcampbell** [comment]
That sounds reasonable. I've tracked down and fixed the immediate issue. I should have the fix and these additional settings rolled up into a pull request shortly.
