### ISSUE TITLE
Tobii 4c eyetracker support

### ISSUE THREAD

**Issue by Blastgraphic** [OptiKey/OptiKey#455]
The program does not work with tobii 4c eyetracker, why? I am using the last version and my pc runs win 10 x64 Creator Update. The eyetracker was calibred correctly.

**Comment by JuliusSweetland** [comment]
As @maartee said, you need to configure the use of an eye tracker, as per this guide: https://github.com/OptiKey/OptiKey/wiki/Using-eye-trackers

Please let me know if this resolves your issue.

**Comment by Blastgraphic** [comment]
Yes i have read the documentation. Settings in OptiKey Management Console seems to be correct. When the program runs, in optikey keyboard, the shift key appear to be pressed.. My eyes doesn't get tracked. In tobii console i can see my eyes.

**Comment by JuliusSweetland** [comment]
Can you take a screenshot of your settings in the management console,
showing the Tobii 4C selected. Can you also screenshot OptiKey as you look
at the keys. Both can be uploaded here.

**Comment by Blastgraphic** [comment]
Fortunately now everything works after a reinstallation of the program!

**Comment by JuliusSweetland** [comment]
Good news. Thanks for the update.
