### ISSUE TITLE
Incorporation of Lyrebird Voices

### ISSUE THREAD

**Issue by TheSchultz** [OptiKey/OptiKey#457]
Hey everyone. I work on http://projectrevoice.org/ (have a look to see what it's about) which is an initiative by The ALS Association in the US. Our goal is to be able to provide everyone with a natural digital copy of their own voices through an easy-to-use voicebank where you're required to bank 2-3 hours of audio. To that end, we have partnered with https://lyrebird.ai/ who specializes in recreating voices and we hope to be able to create voices for anyone with ALS by the end of the year.

Currently, you're going to be able to use it through a webpage, but it would be much more usable for people if you could integrate the voice directly into a keyboard. Is there anyone here who could potentially help with making that happen?

I've found some developer docs here which might help shed some light on what's required; https://docs.lyrebird.ai/#quick-start-hq-voice-api

Thanks in advance.

**Comment by JuliusSweetland** [comment]
@joshlcampbell hi Josh - any interest in adding support for a web request/response method of generating extremely life like (and personalised) voices in OptiKey? This could be a hugely beneficial feature.

**Comment by joshlcampbell** [comment]
I agree, this sounds like a wonderful feature to have, and I'd be honored to work on it! I've looked over Lyrebird's API and will begin researching how best it could be integrated it into OptiKey's existing TTS functionality.

**Comment by JuliusSweetland** [comment]
@joshlcampbell Fantastic - thanks Josh! Great to have you working on OptiKey again.

**Comment by JuliusSweetland** [comment]
@TheSchultz Hi Rene. I've just been reading about Project Revoice and wanted to know how it is being financed? Will users have to pay to generate or use their voices?

**Comment by TheSchultz** [comment]
Hey guys

I might have jumped the gun a little on this one. Just had an updated from Lyrebird and they're going to change their API over the next few months, so it would make the most sense to wait until they're ready. However, it 'should be a very simple API', so hopefully it'll be easy enough to implement. I suggest I write an update here when the new API is launched? Great to see people willing to help though!

@JuliusSweetland We're aiming to make it free for everyone with ALS to use.

**Comment by joshlcampbell** [comment]
Ok, standing down :)

Would I be correct in assuming, though, that it's still going to be a "what do you want to say?" type of request with a "here's the URL to load and play" type of response? If so, perhaps I could put some minimal scaffolding into OptiKey -- minus auth and metadata, just fetch and play -- in the meantime to give myself or the next developer a bit of a head start when the API is ready.

Quite hyped about what you all and the Lyrebird team are doing. Best wishes going forward.

**Comment by TheSchultz** [comment]
Yep, my understanding is it won't change very much from what it currently is. Basically, you'll somehow have to provide log-in information to their server, type what you want to say and then you'll get an URL audio file back to play. 

Thanks for looking into this, it going to make the project even better :)

**Comment by JuliusSweetland** [comment]
I can't imagine it would stray much from an auth, request, response
pattern. If you are keen to work on it perhaps creating a version that
works now and then adapting later to any change would be a good idea? Even
if this API charges a lot there are other web based TTS engines we could
plug into.

**Comment by zelmon64** [comment]
From what I understand this should be fairly similar to the MarryTTS implementation. The differences being a remote server instead of launching a local one and sending authentication information along with the requests.

**Comment by joshlcampbell** [comment]
After a brief look through the code, I think the best place to start would probably be to break out the MaryTTS implementation from the built-in speech synthesizer and add a bit of abstraction around voices, TTS engines, and the selection thereof. A bit of extra upfront work now that should pay off when it comes time to plug in a Lyrebird implementation and especially if additional TTS engines are ever needed. Should clean up a good bit of conditional logic as well. I'll start poking around in that direction if there are no objections.

**Comment by JuliusSweetland** [comment]
Sounds great, thanks.

**Comment by JuliusSweetland** [comment]
@TheSchultz Hi, any news on when the Lyrebird API will be stable? Thanks.

**Comment by TheSchultz** [comment]
So there's some preliminary documentation here. https://docs.lyrebird.ai/ I'm told that the final documentation will be VERY similar, if not identical. Does this help?

**Comment by JuliusSweetland** [comment]
@TheSchultz that's great thanks.
@joshlcampbell fyi there is documentation.

**Comment by JuliusSweetland** [comment]
@TheSchultz Thanks for the update. The user @joshlcampbell seems to have deleted his account, so I'm not sure when this work could be completed.

**Comment by JuliusSweetland** [comment]
Yes please

**Comment by jcamp0x2a** [comment]
I apologize for leaving you guys in the lurch. I should have given you a heads up that I wouldn't be able to continue working on this issue or OptiKey in general _before_ deleting the account, but I messed up the order of operations a tiny bit. Having a GitHub account may still be of limited use going forward, so I wanted to drop in real quick and, again, apologize for that. 

Best of luck in all your endeavors!
