### ISSUE TITLE
Add key (!?) To the keyboard.

### ISSUE THREAD

**Issue by JorgeMattos** [OptiKey/OptiKey#460]
Add question and exclamation mark to the keyboard so you do not have to change the keyboard to finish the sentence. (!?)
![como ficaria o teclado](https://user-images.githubusercontent.com/39384525/40196578-4f63679c-59e7-11e8-901c-729a66264d7e.JPG)

**Comment by JuliusSweetland** [comment]
@JorgeMattos Which language is this?

**Comment by JorgeMattos** [comment]
Currently the space key occupies the space of 4 keys, if it decreases to 2 keys, there is space for two keys, and a score of '!?' Can be added. much used in Portuguese language, especially in conversations chat, Whatsapp, facebook.

**Comment by JorgeMattos** [comment]
Thank you very much.

**Comment by JorgeMattos** [comment]
In version 2.17?
