### ISSUE TITLE
Erase words and phrases in config box

### ISSUE THREAD

**Issue by alandbm** [OptiKey/OptiKey#468]
There are any plan to implement a way to erase custom phrases or words added by user? 
This is my father need.

Thanks

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, maybe @alandbm can to do it by editing some data file, no?

**Comment by JuliusSweetland** [comment]
@alandbm  Hi Alan - you can edit the dictionary from the Management Console - check the last tab, which from memory is labelled "Dictionary" and in there you can manually add and remove entries.

**Comment by alexandre-mbm** [comment]
Are the shortcuts phrases in the Dictionary?

**Comment by JuliusSweetland** [comment]
Yes they are, e.g. "My name is":
![image](https://user-images.githubusercontent.com/4722561/42039361-11941cd0-7ae5-11e8-8bd5-e7567c2c3a1b.png)
