### ISSUE TITLE
Create Portuguese version of CommuniKate

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#469]
@zelmon64 @joereddington How complex would it be to translate CK into other languages? I have a request for a Portuguese version, which I thought would be very helpful. There should be a bounty for the work also. Thoughts?

**Comment by JuliusSweetland** [comment]
Great news. Can you post on there the v2 template so I can provide it to
the user who wants it?

**Comment by joereddington** [comment]
Cool - best bet is to pop it out of here: http://www.theopenvoicefactory.org/upload_board.html  and then the person doing the copying over (or potentially an entirely new translation, can regularly test it on the same page).  There is a *but*, which is that I don't believe I've pushed the latest OBF-producing version of the site yet, I'll make a note, but if I haven't got to it by the time there is a translation, then ping me and I'll make the change :)

**Comment by JuliusSweetland** [comment]
@zelmon64 Once we have a new file format OBF file in Portuguese do you know what work would be required to load language specific OBF files? Or would a better approach be to just turn on/off CK support globally (regardless of the language) and let the user select their localised OBF file?

**Comment by zelmon64** [comment]
@JuliusSweetland currently CK support is off by default and an OBF file in any language should work so nothing has to be done to OptiKey for a Portuguese version of CK to work. 

There is an option in the format to state the locale and to provide translations. If the content of the Portuguese version is the same as the current default they could be combined and used depending on the set language. If they're different we could supply separate language dependent defaults. The benefit of having a combined default is that it would contain just one set of images so it would be smaller than two separate defaults. The downside is that combining them would take more work.

**Comment by JuliusSweetland** [comment]
@zelmon64 Good news. I guess we'd need to change the Management Console so that CK is not language dependent, i.e. the CK options are available regardless of the language.

I've noticed a couple of things as well:

1.There is a padding on the keys - is this something I am doing?
![image](https://user-images.githubusercontent.com/4722561/42058398-3c2d0668-7b18-11e8-977f-8fd3eb5f6062.png)

2. Even with CK enabled the drop down option says CommuniKate is disabled:
![image](https://user-images.githubusercontent.com/4722561/42058501-86891846-7b18-11e8-9186-42fb176f31d6.png)

I'm thinking the 2 CK options could be:
a) Display CK key on Alpha keyboard - this would then need to be added to all language Alpha1 keyboards.
b) Rename the second setting to "Default keyboard style"
c) Remove the concept of CK being disabled and defaulting back to QWERTY - if CK is set as the Default keyboard style then the only validation should be that a valid obz file is selected.

What do you think?

**Comment by zelmon64** [comment]
@JuliusSweetland I forgot I made it accessible only from English. That was a bit short sighted, I don't know why I did that, sorry. 

1. The padding is the boarder support I added like this:
![CK boarder](https://user-images.githubusercontent.com/15001389/40080715-b9d3e292-5883-11e8-8175-43ac290ef3e3.png)
but the default apparently has all the same grey boarder.

2. I just found that was accidentally set when you added the[simplified Turkish keyboards](https://github.com/OptiKey/OptiKey/commit/2891519defef0f7880cb6f9db9e060675636b070#diff-91bcd4b77af2c4899f6458391ed26641). I hadn't noticed it when I did the recent work.

I'll have to think over these options when my head's a bit clearer.

**Comment by zelmon64** [comment]
@JuliusSweetland I've made CK available to all languages in PR #470. I added a CK key to the Output section to ensure it's always accessible.
![ck in top bar](https://user-images.githubusercontent.com/15001389/42126954-402df2ba-7c88-11e8-8798-f6b801973b4e.png)
I made an adjustment to the coloured boarder so that it's thinner when more buttons are present.

I also tagged on an update to the Presage suggestions which I've been meaning to push.

**Comment by JuliusSweetland** [comment]
Excellent, I'll check it out ASAP. Thanks William!

**Comment by JuliusSweetland** [comment]
@zelmon64 FYI I'll be looking at your PR and preparing a new release (hopefully) this evening. I've been quite busy!

**Comment by JuliusSweetland** [comment]
Brilliant, thanks. I'll check everything this evening.

**Comment by JuliusSweetland** [comment]
@joereddington @zelmon64 This has been released in version 2.16.0. Thanks all!
