### ISSUE TITLE
Dynamic keyboard validation

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#475]
Dynamic keyboards allow users to create custom keyboards by providing an XML file. A significant amount of input validation is done by the libraries used to parse the XML, and OptiKey already includes an error keyboard to display those errors.

If you attempt to use an XML file in which two distinct keys have the same row and column numbers, the error keyboard is not triggered and instead OptiKey throws an exception. In the release build, this does not cause OptiKey to crash entirely but does result in some strange behavior. In the example below, the user sees what appears to be one key labeled "B" but the character "a" is actually typed when the key is activated.

This is a very easy error to make when creating keyboard files, and so it would probably be a good idea to present users with an appropriate error message.

```
<Keyboard>
   <Name>SIMPLE</Name>
   <Height>32</Height>
   <Grid>
      <Rows>1</Rows>
      <Cols>1</Cols>
   </Grid>
   <Keys>
	   <TextKey>
         <Label>a</Label>
         <Text>a</Text>
         <Row>0</Row>
         <Col>0</Col>
       </TextKey>
	   <TextKey>
         <Label>b</Label>
         <Text>b</Text>
         <Row>0</Row>
         <Col>0</Col>
       </TextKey>
   </Keys>
</Keyboard>
```

**Comment by JuliusSweetland** [comment]
@kmcnaught This is an interesting bug

**Comment by kmcnaught** [comment]
I'll look into this
