### ISSUE TITLE
steps to add a new language

### ISSUE THREAD

**Issue by smartiptv** [OptiKey/OptiKey#478]
Hi Guys, 

Special thanks to JuliusSweetland,

I am Arabian and I want to know what is the steps and the way how to add a new keyboard layout for Arabic language?

Thanks for all and big efforts,

Mohammad Saeed

**Comment by JuliusSweetland** [comment]
Hi @smartiptv Please find the localisation guide here: https://github.com/OptiKey/OptiKey/blob/master/docs/Localize.md

I'll close this issue now, but feel free to open another if you have more questions.

**Comment by smartiptv** [comment]
Thanks JuliusSweetland 👍
