### ISSUE TITLE
Backspace on Simplified Keyboards

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#479]
I've been doing some work on adding a simplified keyboard layout for German (see [issue 473](https://github.com/OptiKey/OptiKey/issues/473)).  

While working on that, I have been using the simplified layout as I'm writing code and interacting with Power Shell (as a way of testing/debugging). 

I have been absolutely infuriated by the lack of a backspace key. In the current English language simplified layout, you have no way to undo mistakes when they involve actually selecting a character. (The back key will take you back up selection tree, but you can't actually delete the character that you just typed.)

My thought would be to replace the recalibrate key with the backspace key (you can still get to recalibrate in just 2 selections). I could also see replacing the enter key or splitting that key into enter and backspace.

Since I'm already digging in the keyboard layouts, I'd be happy to edit the English simplified layout as well, but I wanted to solicit input first.  While I do use OptiKey on a regular basis, I am not the intended user for this particular feature, and so my opinion/experiences might not be the most relevant.

**Comment by JuliusSweetland** [comment]
Hi @annakirkpatrick - that sounds like a legitimate bug. Thank you for finding it. I agree that re-calibrate is accessible from the menu, so replacing that key with a back key sounds like a great solution.

**Comment by annakirkpatrick** [comment]
@JuliusSweetland Thanks for your input. I will make that edit to the English simplified layout, as well as modifying the German layout that I am currently working on.

Two follow-up questions: 
1. Do we think it is worth the space to include both the 'back one' and 'back word' keys? (This would probably require splitting a key.)  In my testing I found no need for the back word option, but I was doing mainly character-level entry in code or at the command prompt. Given the option to select from predictions, both might be warranted.

2. Are there other languages with simplified keyboards that I should look at to see if the same type of bug exists there, too?

**Comment by JuliusSweetland** [comment]
Hi Anna.

1. No back one should be sufficient. If you select a suggestion you can
actually delete the whole word with back one anyway.

2. Turkish.

Regards,
Julius

**Comment by annakirkpatrick** [comment]
Hi @JuliusSweetland 

1. Thanks for pointing that fact out. Makes it clear that we only need one key. (Can you tell I basically never use word completion?) I've made the change on the English simplified keyboard and will include that in a PR with the German keyboards. (The English simplified conversation keyboard already has a backspace key.) 

2. I will take a look at Turkish, too.

**Comment by JuliusSweetland** [comment]
Great thank you
