### ISSUE TITLE
Confusing highlighting when multiple keys have the same target

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#480]
On some keyboards, such as the simplified keyboard layouts, there are multiple keys that perform the same action. In this case, when the user looks at one of those keys, all of them will be highlighted (outlined in orange).

As an example, take a look at this screenshot:
![image](https://user-images.githubusercontent.com/33188271/43170456-2dde638a-8f73-11e8-8c09-630efe4b1eb7.png)

(Yes, this is in German. I've been working on creating alphabetic and simplified layouts for German. Yes, this behavior also occurs on the English simplified keyboard.)

In the screenshot, I am looking at the back button ("Züruck"), but both the back button and the home button are highlighted.

These two buttons do have the same action/destination. They both bring up the home screen of the simplified keyboard. But I'm obviously not looking at both of them.

It occurs to me that this might be an intentional feature/design decision. If so, I think it might be worth reconsidering.

When I first saw this behavior, I was really confused by it, and it took me a few minutes to figure out what was going on. (In the organizational scheme of the simplified keyboard, "home" and "back" really are different actions, even if they sometimes have the same result.)

Additionally, I think there's something going on here with the physiology or psychology of vision. When things move, our eyes want to follow. On a computer, this means that our eyes are drawn to parts of the screen that are changing. 

Under normal circumstances (and with a properly calibrated eye tracker), OptiKey's highlighting of the key under the current gaze point makes sense. It gives the user confirmation that the software knows where they are looking, and the "motion" only draws the user's eyes to where they already are.

But, if there is also "motion" on the other side of the screen, I see that motion in my peripheral vision and my eyes want to move there to see what is happening. The result is that, when both of these keys are highlighted, my gaze is actually drawn away from the key I intended to activate and towards a different key. 

I've now learned to override this response (in the particular context of the simplified keyboards), so it's not like the keyboards are unusable. But the current highlighting definitely does feel unintuitive.

**Comment by JuliusSweetland** [comment]
@annakirkpatrick Yes I agree that when two keys start animating at the same time it can draw your attention away. Unfortunately this isn't an easy thing to overcome as the key progress (and animations) are stored against the key values - if two keys have the same underlying value then they will both react to show their current selection progress. The only way around this (with the current implementation) is to ensure the same key value is not defined twice on a keyboard.

**Comment by annakirkpatrick** [comment]
@JuliusSweetland I understand.

The only place this really occurs is on the simplified keyboards. Unfortunately I don't see an easy way to eliminate the duplicated key values while maintaining the overall organization of the keyboard, so I suppose we will let it be.

The good news is that this definitely is something you can get used to. I've been working with the simplified keyboards for just a couple of days, and it doesn't bother me anymore.

**Comment by JuliusSweetland** [comment]
There is a potential workaround: create a new function key value to
represent Simplified keyboard home (or similar) and change the home key to
that, but leave the back key as it is. You can then add handling for the
new function key to set us back to the top simplified keyboard level.

Essentially pointless, but it would prevent this issue.

**Comment by annakirkpatrick** [comment]
Well, I admit, I'm too much of a perfectionist to point out the issue and then not implement the workaround.

I created function key SimplifiedKeyboardHome and made appropriate changes in the English and German simplified and simplified conversation keyboards. (The Turkish simplified layout uses what would be the home button for more characters and so doesn't have the same problem.)

I will keep the changes in a commit by themselves so you can decide whether or not you want to merge them.

**Comment by annakirkpatrick** [comment]
@JuliusSweetland Cool. I finished putting together a pull request last night. It has this workaround, backspace for simplified keyboards, and the German layouts.
