### ISSUE TITLE
Calibrating tobii gaming eye trackers no longer requires manual intervention

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#482]
When you activate the recalibrate key, OptiKey presents a message stating that "manual intervention e.g. having to use a mouse mouse" is required to complete calibration and asks the user if they want to continue with calibration.

I don't know whether or not this message varies depending on which type of eye tracker you're using.

With the tobii eye trackers (EyeX, Steelseries Sentry), calibration did previously require clicking the mouse or pressing a keyboard key. This is no longer the case, and that change was made some time ago. I don't have an exact date, but I'm confident it has been more than six months. With both the EyeX and the newer tobii 4C eye tracker, I can verify that, with up-to-date tobii software installed, calibration can be completed with eyes only.

There probably is value in requiring confirmation before proceeding with calibration, since calibration does take around 30 seconds and accidental keypresses could therefore be very annoying. But this message should probably be changed so that new users who do not have the ability to use a keyboard or mouse do not think that they need to avoid calibrating when working alone.

**Comment by JuliusSweetland** [comment]
@annakirkpatrick That sounds like a valid change. I haven't tested the latest version, but I know that the EyeX, 4C, etc (all modern Tobii trackers) run on the same engine, so this should be true for all of them.

**Comment by annakirkpatrick** [comment]
@JuliusSweetland Cool. I made the change and I will create a pull request.
