### ISSUE TITLE
Magnified screen area position 

### ISSUE THREAD

**Issue by maartee** [OptiKey/OptiKey#489]
Hi there!
If a mouse magnifier is used often, there is a lot of eye movements, that could be spared, in my opinion.
This would be accomplished by positioning the magnified rectangle area around the original point of click, and not in the center of the screen.
This could be optional, in case somebody still prefers positioning in the center of the screen.
I believe, that on smaller screens, or with not very precise eyetracker, the magnifier must be on 99% percent of the time. 
I'm not a sw developer, but I'd be happy to do thorough testing

**Comment by aihamhasan04** [comment]
you could choose to simply slide the magnified area "inwards" towards the center of the screen just far enough so that the entire magnified area fits on the screen. This solves the literal problem, but I think it might be disorienting as a user.

**Comment by SSidharth1505** [comment]
Hi all!
I liked the concept! What about adding more features so that we can indulge AI in the program?

**Comment by Teltez50** [comment]
Here's a thought: Why not think outside the box(square); When magnifying at the edge of the screen the screen could slide and expand left, right, up or down and even diagonally while it is being magnified and follow track, in movement, with the magnified area.
I believe this would be possible if the edges were fuzzy areas in code, pliable if you like and not fixed points. 
This would only work whilst the eye tracker was in use and revert when not. 
Just an idea from a naive novice but possible with the code allowing a detached screen overlay that can accomodate the text or image.

**Comment by AdamRoden** [comment]
Let's bring this back to life:
Here are more thoughts regarding how I would like the magnifier should function:

1. In the first step have the cursor be a large window frame with a transparent center representing the area to be magnified.
2. In the second step, (after locking onto a region), expand the window frame to magnify the area, switch to a dot or cross hair cursor, and proceed to click.
3. The dwell times for steps 1 and 2 should be independently configurable so step 1 has a short dwell and step 2 has a long dwell.

In regards to where the magnified window in step 2 appears, I agree that in most cases jumping to the middle of the screen is not preferred.  The magnified window position should be centered on the focus point that was locked in step 1. The tool should also take the screen boundaries into consideration and if centering the magnified window would cause it to exceed the screen boundaries, then shift it inward accordingly.

**Comment by AdamRoden** [comment]
@maartee @annakirkpatrick In v2.25 there is a new setting so the magnifier window will center around the mouse rather than the middle of the screen. I would like to hear what you think of it. 

In the future, I want to try digging into issue #557 and potentially build two alternate mouse click options: one for continuous zoom and a second for a Microsoft style cross-hair style precision click.

**Comment by JuliusSweetland** [comment]
@AdamRoden Thanks again for this. I will close this issue unless someone wants to keep discussing here? Let me know if you do and I'll reopen.
