### ISSUE TITLE
Mouse position incorrect for multi-screen configurations with main monitor on the right

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#490]
I know the OptiKey wiki says that multiscreen configurations are not supported, but hear me out on this, because I think this is actually a really simple bug, and this type of configuration can actually be really useful for a subset of users. (And OptiKey as it currently exists comes really close to being able to do this!)

From personal experience, OptiKey works fine on a multiscreen system with an extended desktop provided that (1) the eye tracker is correctly configured for the primary monitor, and (2) the primary monitor is on the left. Set ups with a duplicated display can also work, though I've had some issues with mismatched hardware and desktop resolutions.

In the case where the eye tracker is placed on the right hand screen, when the mouse tools are used, the mouseclick actions are instead performed on the left screen (at approximately the analogous position, though I'm sure resolution makes a difference). Interestingly, the zoomed in rectangle is taken from the correct screen region and appears on the correct monitor. It's only the actual mouse operations that happen on the other monitor.

My guess would be that the information coming in from the eye tracker is reporting the gaze point position relative to its monitor, while Windows mouse movement commands are relative to the extended desktop. This would mean that the command to move the mouse would simply need to be adjusted with an offset in the x-coordinate equal to the pixel width of the left hand screen.

I don't know the code well enough to figure out where this is actually happening, but it does not seem like a complicated problem. 

A couple notes on multiple monitor configurations and why this is relevant:

First, note that what the eye tracking manufacturers specifically do not support is using multiple eye trackers on multiple monitors simultaneously. This is because of actual interference from the near infrared light used to detect eye position. (You can already get some substantial interference from sunlight; I don't want to think about what another eye tracker would do!) Using 2 monitors, 1 of which has an eye tracker, is totally okay, and the tobii calibration software actually now includes the option to select which screen has the eye tracker.

I have been using a multiple monitor configuration with OptiKey for over a year. (With OptiKey on the left-hand monitor.) Typically, I have OptiKey and my terminal, text editor, or IDE on my main (left) monitor and a web browser or PDF viewer with documentation on my secondary (right) monitor. Since I don't actually need to interact with the stuff on the secondary monitor very frequently, I can do that limited interaction with a trackball (or keystrokes when possible). All of my main, keystroke-intensive, work stays on my primary monitor.

Of course many people like having a second monitor when writing code. There's never enough space for all of your documentation! And this issue actually becomes larger when using an on-screen keyboard. In my typical set up, that keyboard occupies half of my primary monitor. I'm lucky if I can fit a text editor and a terminal underneath it; documentation just isn't going to fit. So, being able to move that  documentation, that I only need to touch occasionally, to a second monitor is really, really helpful. It's not a perfect set up, but, until the technology problem of using multiple eye trackers with multiple monitors is solved, I think it's the best we are going to be able to do.

It occurs to me that I have just written up a bunch of information about using multiple monitors with OptiKey that is not on the wiki. If you would like me to update/rewrite/expand the relevant wiki page, I'd be happy to do that. Just let me know.

**Comment by JuliusSweetland** [comment]
@annakirkpatrick I'll open this up to hacktoberfest

**Comment by Ar2rZ** [comment]
@JuliusSweetland @annakirkpatrick there is proposed fix a while ago..... https://github.com/OptiKey/OptiKey/issues/175

**Comment by JuliusSweetland** [comment]
Fixed in v3.0.3
