### ISSUE TITLE
bug fit size and position.

### ISSUE THREAD

**Issue by JorgeMattos** [OptiKey/OptiKey#494]
Bug in Version 2.16 adjust the size of the keyboard and when restarting computer resets to the old size. To save we have to close Optikey and reopen, then yes get saved the configuration of size and position.

**Comment by JuliusSweetland** [comment]
@JorgeMattos Could this be that OptiKey is not shut down nicely when the computer is rebooted? If the OptiKey process is torn down it may not have a chance to exit gracefully, and settings may not be saved properly.

**Comment by JorgeMattos** [comment]
Yes it may be, let's see if at 2.17 it will continue. Let's save. Thank you very much.
