### ISSUE TITLE
Multi-key selection stays active when changing from normal to simplified keyboard

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#504]
In a normal alpha keyboard enable multikey select (lock it down for ease) and then switch to a simplified keyboard - multi key selection will still be enabled and make typing very difficult.

**Comment by Chopinsky** [comment]
Would you think it's sufficient if we simply toggle off the multi-selection lock if switching to a simplified keyboard? Or should it be better to guard the behavior behind a setting?

**Comment by JuliusSweetland** [comment]
It would be sufficient if multi-key selection were released when switching
to a keyboard which doesn't support it

**Comment by JuliusSweetland** [comment]
Included in 2.0.17
