### ISSUE TITLE
Profile and optimise, especially keyboard transitions

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#51]
http://blogs.msdn.com/b/visualstudioalm/archive/2014/02/28/new-cpu-usage-tool-in-the-performance-and-diagnostics-hub-in-visual-studio-2013.aspx

http://blogs.msdn.com/b/visualstudio/archive/2014/06/12/new-memory-usage-tool-for-wpf-and-win32-applications.aspx

**Comment by JuliusSweetland** [comment]
I would like to investigate whether there are any potential roots which may be causing memory "leaks" (I know a true leak is not possible in a managed language, but rooted resources which should be garbage collected are).

Also if there are any performance improvements which could be made.

**Comment by danielmoncada** [comment]
I can start to look into this as well. Typical issues with WPF include not making specific UI elements 'Freezable' as well as not unsubscribing from events correctly. Lambda event handlers should probably be made into delegate methods so that a "-=" is allowed.

**Comment by JuliusSweetland** [comment]
@danielmoncada Thanks - although I wouldn't change lambda event handlers just for the sake of it as it's possible to unhook them. See here: https://github.com/JuliusSweetland/OptiKey/blob/master/src/UI/Controls/KeyboardHost.cs#L284
Otherwise yes, any help with performance improvement would be great. Thank you.

**Comment by alexandre-mbm** [comment]
> See here: https://github.com/JuliusSweetland/OptiKey/blob/master/src/UI/Controls/KeyboardHost.cs#L284

https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey/UI/Controls/KeyboardHost.cs#L284
