### ISSUE TITLE
Documentation: Convert .txt to .md files

### ISSUE THREAD

**Issue by MauroCoppola** [OptiKey/OptiKey#512]
Hi, I saw that the [docs](https://github.com/OptiKey/OptiKey/tree/master/docs) directory contains .txt files to describe some tasks/aspects of the project, but I think converting them to Markdown files might improve readability (remove horizontal scrollbars, for example). I can work on that if you agree.

**Comment by JuliusSweetland** [comment]
@MauroCoppola sounds good, yes please

**Comment by hugodahl** [comment]
I'd also be glad to help out with this effort, while I get a bit more familiar with the code and functionality, to contribute from that perspective.
