### ISSUE TITLE
Window size not correct anymore after starting OptiKey and then closing it (and even restarting Windows).

### ISSUE THREAD

**Issue by AntonioCaroppos** [OptiKey/OptiKey#516]
I've run the source code in VS2017 on Windows 10.

After I quit Visual Studio, all my windows were half the screen height, as if OptiKey was still running.

I have even restarted Windows, and if I maximize a window and then normalize it, the window becomes half the screen height. 

How can I set the window size back to normal?

This height issue affects all windows (my browser, text files, etc.). 

This must be caused by what you're doing when OptiKey is running, and you make all other windows half the screen height.

**Comment by JuliusSweetland** [comment]
@AntonioCaroppos When OptiKey starts and is docked to a screen edge (which is the default) then it registers with Windows as a toolbar (just like the taskbar at the bottom). This causes Windows to resize the desktop, moving all the icons etc while OptiKey is open. If you close OptiKey gracefully (using the QUIT item in the context menu, or by pressing ALT+F4, or by closing the task in the task bar, then OptiKey will unregister itself with Windows and everything will go back to how it was before. However, if you kill the process (e.g. by stopping the run in Visual Studio, or force killing the process) the OptiKet will  not unregister itself and the desktop will remain resized. When this happens you just need to start OpiKey again and then close it gracefully. Your desktop icons might be moved about following all that though.

I have never seen it remaining after a Windows restart though, as toolbars have to register with Windows on each start.
