### ISSUE TITLE
When typing characters with accents, 'back one' key not working correctly

### ISSUE THREAD

**Issue by hmcomer** [OptiKey/OptiKey#517]
# How OptiKey was being used

I regulary use Optikey to write in Turkish. In Turkish, there're characters like ş, ğ, ç, etc,... and when I type them and then try to erase one of these characters, first optikey gets rid of the accent and then the whole character.

# What the user expected to happen

I think it would be more logical to have the whole character erased when pressing 'back one'.

# What the user actually experienced

For example: when I accidently type 'ğ' and I try to correct it by pressing 'back one', I get the character 'g'. I have to hit 'back one' again to get rid of the character 'g'. When pressing 'back one' the first time on a character with a accent, I noticed that Optikey deletes the whole word (very fast) and then writes it back, but this time with the character (that I intended to delete) but without the accent.

This is actually not annoying most of the time, but it can get messy when you work with two applications. If I type in MS Word and then want to search something on the web for example. If my last word in the Scratchpad had a accent in it and I mispelled something in my browser, then that last word gets rewritten too in my browser.

# Version
 - Operating system and version: Windows 10
 - OptiKey version: v2.18 (I think)

# Steps to reproduce the issue

1. Set Optikey in Turkish
2. Write any character with a accent
3. Try to correct it with the 'back one' key
4. Notice that the whole word gets rewritten, but this time with the character without the accent.

# Any other information that helps to describe and/or reproduce the problem

I hope my explaination was clear enough. If not, feel free to ask questions.

# Screenshots

/

**Comment by JuliusSweetland** [comment]
@hmcomer Thanks for your report. I'll have to think about how to fix this. The current behaviour is intended for languages such as Korean where characters combine. By breaking them apart before the backspace is applied it allows users to remove part of their combined symbols. With languages such as Turkish you instead get the behaviour you describe.

When you are working across multiple applications would it make sense to use the CLEAR scratchpad key to reset OptiKey each time you change application?

**Comment by hmcomer** [comment]
Yes, clearing the scratchpad is definitly a solution. Even if I work in only one application I hit the clear scratchpad button quite frequently when writing in Turkish.

Would it be an easy solution to bypass the scratchpad completely, with a 'raw imput' mode?

**Comment by JuliusSweetland** [comment]
@hmcomer What would the benefit of the raw input mode be? It might instead be better to have a setting which makes the BackOne key always delete one character, not one part of the last character?

**Comment by maartee** [comment]
Hi, I also have this issues when using Czech layout. I  think clearing scratchpad when changing app doesn't help much. 
When you 
1) write some word with diacritics, not finish it with space
2) then navigate to another place in the same text to repair some typos
3) hit backspace/back-one-word
4) see what happens - a messed up text appears when I try

However, I don't know whether raw input solves this?

**Comment by JuliusSweetland** [comment]
OptiKey relies on its memory of what has been typed (shown in the
scratchpad) to figure out what a backspace, for example, should do. If you
navigate the cursor somewhere else OptiKey is not aware of this and thinks
you are continuing to type from where you left things, so the output can be
confused.

**Comment by maartee** [comment]
For some reason, the issue only shows with diacritics, English works as I expect, backspace not adding any characters.

I think OptiKey is aware of cursor positioning- on a second thought:
 what if OptiKey 'forgets' the word after any positioning key(arrows, home, end, pgdn, pgup, tab) is pressed, or left mouse click is performed. After these events, the  continuation of previous word is highly improbable, in my opinion.
I'm clearing the scratch pad manually with each cursor move, but it's not very convenient.

**Comment by JuliusSweetland** [comment]
I think there could be two new settings:

1. Reset scratchpad after cursor move (arrow keys and mouse clicks). This
would be off by default as a mouse click doesn't necessarily change the
cursor position (eg the user clicks on the Italic button in word while
typing).

2. Always backspace one whole character - which would bypass decomposing
the last character before deleting the last character.

**Comment by SamPlusPlus** [comment]
@JuliusSweetland is this language dependent? I don't know much about this, could we have a setting on languages, where for example Turkish would delete the whole letter, and Korean would know that its combining letters? Or are their languages that experience it both ways?

**Comment by JuliusSweetland** [comment]
@SamPlusPlus Hi Sam. I don't think the technical implementation will be language specific. It's more a preference thing. I'm thinking of it like this:
a)Your language does not combine diacritic marks with letters, or letters together to form new symbols. This setting would not impact you at all.
b)Your language combines one or both of the above. By default BackOne would allow you to deconstruct characters. If this setting is turned on then one whole combined character at a time can be delete.

For both BackMany would remain the same and works on white space, deleting "chains" of characters back until it hits a newline/whitespace/punctuation.

**Comment by hmcomer** [comment]
Hi @JuliusSweetland, I just updated to version 2.24. You implemented a setting to type the accents before or after the letter (if I understood it correctly). Does this relate to this issue?

If this is the case, I don't think this solved this issue. In Turkish it doesn't seem to 'back one' the whole character, if that setting is on or off.

**Comment by JuliusSweetland** [comment]
Hi. No that setting only relates to how diacritics are added to letters.

**Comment by JuliusSweetland** [comment]
This should have been fixed in 3.10.0
