### ISSUE TITLE
Ukrainian localization

### ISSUE THREAD

**Issue by Larkailya** [OptiKey/OptiKey#520]
Hey everyone. I with my friend @darinakulish want to make the Ukrainian localization for OptiKey. We are pleased that there is such a project and people care about people with disabilities. We would like to make the support of the Ukrainian language for this application, so that people in Ukraine can use this application.

We have sent a request for access to the Ukrainian language on transifex. My name on transifex **illialarka**, and friend's name **darinakul**.

We look forward to your permission, @JuliusSweetland.

**Comment by JuliusSweetland** [comment]
Granted on Transifex. In addition to doing the translation we also need
customised keyboards for Ukrainian and to also possibly make any little
changes to handle Ukrainian specific behaviours that are needed. There's a
localisation document here:
https://github.com/OptiKey/OptiKey/blob/master/docs/Localize.md

**Comment by Larkailya** [comment]
Hi, @JuliusSweetland !
We have finished translating into transifex everything that applies to the Ukrainian language.

> After completing the translation in Transifex, you should notify us as soon as possible so the translation you made can be checked and have its `.resx` file generated as you will need this in order to implement the new locale inside OptiKey. Having acquired your language `.resx` file it's time to start adding the new Locale inside OptiKey.

Can we continue and start integrating the language into the application?

**Comment by JuliusSweetland** [comment]
Absolutely. You may be able to download the Ukrainian resx file yourself
and continue. If not let me know what I'll download and share it.

**Comment by JuliusSweetland** [comment]
@Larkailya Released! v2.20.0

Thank you very much! Any more contributions from you would be very well received - your changes were very good.
