### ISSUE TITLE
UI localization not working on all languages

### ISSUE THREAD

**Issue by darinakulish** [OptiKey/OptiKey#522]
# How OptiKey was being used

We did Ukrainian translation with Larka Ilya, and while running the application keyboard and dictionary translation run successfully, UI interface is not translated in all languages (stays English).

# What the user expected to happen

When language is switched, buttons have to also change language.

# What the user actually experienced

Keyboard and dictionary are translated while the UI buttons are not

# Version
 - Operating system and version: Windows 10 (64-bit)
 - OptiKey version [last]

# Steps to reproduce the issue

1. Go to 'Languages'
2. Click on 'Ukrainian' (or any other language except English)
3. Go back to keyboard
4. See keyboard is translated while the UI buttons are not

**Comment by dreua** [comment]
I don't know if this is intended behavior or a bug, but as a workaround you can set the UI Language in the Management Console. (Open it via Alt+M or Right-Click menu)

**Comment by darinakulish** [comment]
> I don't know if this is intended behavior or a bug, but as a workaround you can set the UI Language in the Management Console. (Open it via Alt+M or Right-Click menu)

Thank you, found it. Basically it's not obvious for user (that buttons are changed not where keyboard is changed), but if it was intended to be so it's ok:)

**Comment by JuliusSweetland** [comment]
@darinakulish Thank you Darina for explaining where the UI Language is set.
@dreua Hi David - basically the UI language is *your* main language, so for me that would be English. I might want to start typing in English, but then switch to Ukrainian to type something in Ukrainian. I can do this either by changing the Keyboard language in the Management Console, or via the Languages keyboard from the Menu. When I switch the Ukrainian the keyboard changes and the dictionary changes, but my main language is still English, so the UI language remains as English. This only affects the labels on the keys. Does that make more sense?
