### ISSUE TITLE
Wiki - Azure Pipelines Badge

### ISSUE THREAD

**Issue by mamuso** [OptiKey/OptiKey#523]
The Azure Pipelines badge [in the footer of the wiki](https://github.com/OptiKey/OptiKey/wiki#wiki-footer) seems to be pointing to the wrong place and shows as "set up now".

![image](https://user-images.githubusercontent.com/3992/48296633-08249f80-e44e-11e8-8f14-b881b71196b2.png)

**Comment by dreua** [comment]
The footer currently displays this: 
`[![Build status](https://dev.azure.com/optikey/optikey/_apis/build/status/optikey-CI)](https://dev.azure.com/optikey/optikey/_build/latest?definitionId=-1)`
[![Build status](https://dev.azure.com/optikey/optikey/_apis/build/status/optikey-CI)](https://dev.azure.com/optikey/optikey/_build/latest?definitionId=-1)

I think `optikey-CI` is not a valid target (any more?) and it should be changed to this:
`[![Build status](https://dev.azure.com/optikey/optikey/_apis/build/status/OptiKey.OptiKey)](https://dev.azure.com/optikey/optikey/_build/latest?definitionId=-1)`
[![Build status](https://dev.azure.com/optikey/optikey/_apis/build/status/OptiKey.OptiKey)](https://dev.azure.com/optikey/optikey/_build/latest?definitionId=-1)

You might want to add a useful link to the Appveyor-Badge, as the default link just points to the badge image.
`[![Build status](https://ci.appveyor.com/api/projects/status/rqj43c5p8jt86kjo/branch/master?svg=true)](https://ci.appveyor.com/project/OptiKey/optikey)`
[![Build status](https://ci.appveyor.com/api/projects/status/rqj43c5p8jt86kjo/branch/master?svg=true)](https://ci.appveyor.com/project/OptiKey/optikey) 

(I didn't find a way to edit the wiki or send pull requests for that matter, I guess this can only be done by @JuliusSweetland )

**Comment by JuliusSweetland** [comment]
@dreua Thanks David! All working again. I appreciate your help.
