### ISSUE TITLE
Why this project doesn't have tags to help people find it?

### ISSUE THREAD

**Issue by johnnyasantoss** [OptiKey/OptiKey#528]
I mean this project is awesome and you guys deserve the credit of doing this awesome piece of code! Seriously

I forgot the name of the project and spent 15mins just trying to find something related to eye tracking and seems that this projec **don't have tags** to make it more visible to searches!

Look here, a good tag to put this software in https://github.com/topics/eye-tracking?l=c%23&o=asc&s=updated

**Comment by JuliusSweetland** [comment]
@johnnyasantoss Great idea. Done:

![image](https://user-images.githubusercontent.com/4722561/49830945-81374f80-fd8a-11e8-8b6c-1f817f99dcd9.png)
