### ISSUE TITLE
Upgrade standalone

### ISSUE THREAD

**Issue by JorgeMattos** [OptiKey/OptiKey#530]
improvements.

An option in the installer for the patient himself can update Optikey without losing control. Automatic restart at the end.

![cmd do optikey instalador](https://user-images.githubusercontent.com/39384525/50103853-bd960000-020f-11e9-9823-ea28c4263aa6.JPG)
![opcoes do instalador](https://user-images.githubusercontent.com/39384525/50103878-ca1a5880-020f-11e9-8d5f-1848668e3f42.JPG)
![instalador optikey](https://user-images.githubusercontent.com/39384525/50103889-d1d9fd00-020f-11e9-9a98-cfe00de6db2b.JPG)

**Comment by JorgeMattos** [comment]
@JuliusSweetland    Which compiler and installer do you use to compile Optikey? Is Inno Setup Compiler? Do you have the script?
I wanted to do some testing on my machine before posting any suggestions for improvement, so I believe I can contribute more to the project.
I'm new to programming, just moving my eyes, I have a lot of time. I really enjoy contributing to Optikey.

Thank you very much for your attention.

**Comment by JuliusSweetland** [comment]
Yes it's INNO. If you give me an email address I can send over the
deployment scripts. Unfortunately the sign scripts can't be shared as I
can't share the certificates, but everything else will be there.

**Comment by JorgeMattos** [comment]
@JuliusSweetland   Yes, I understand, jorgedimattos@hotmail.com

Question # 531 Can I open a Pull requests? Or is it not right to change the value to WidthSpan = "2"?

**Comment by JuliusSweetland** [comment]
@JorgeMattos I've forwarded you a zipped file of the deployment INNO scripts. I'll reply on the other issue to your other question.

**Comment by JorgeMattos** [comment]
@JuliusSweetland Something went wrong with your file!
I tested some codes in INNO. Look cool a dynamic keyboard with installer.

[Teclado dinâmico Optikey Português M1.zip](https://github.com/OptiKey/OptiKey/files/2752350/Teclado.dinamico.Optikey.Portugues.M1.zip)

deployment.zip
![capturar](https://user-images.githubusercontent.com/39384525/51076715-322f5380-1683-11e9-9c92-75b4063a6031.JPG)

**Comment by JuliusSweetland** [comment]
I'll have to rebuild this and send this to you at three end of next week as
I don't have access right now I'm afraid...

**Comment by JorgeMattos** [comment]
@JuliusSweetland Hello friend, I believe you do not need to put update option, only modify [run] in INNO to start automatic after installation.
The installer will not ask to click to start Optikey, will open Optikey automatically after installation.
Watch the video.
https://youtu.be/OVJzwCb4DJM

[Run]
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}; Flags: shellexec

**Comment by JuliusSweetland** [comment]
Hello. That video looks good, but what happens to the running instance of
optikey when the installer creates a new instance? Does it get closed down
automatically, or are there two running instances of optikey?

**Comment by JorgeMattos** [comment]
@JuliusSweetland The instance is closed by the installer, after installation the installer opens a new instance.
Do not stay two instances at the same time. Now New video with task manager.

https://youtu.be/mY7EOQa62r8

**Comment by JuliusSweetland** [comment]
Good stuff. I'll make the change for the next release. Thank you

**Comment by JorgeMattos** [comment]
You are awesome!
Thank you very much.

**Comment by JuliusSweetland** [comment]
Added to 2.0.22 and released. Thank you @JorgeMattos

**Comment by JorgeMattos** [comment]
Auto start option was great!
Portuguese conversation layout was great!

Something wrong with version 2.22
I'll carry print screen

**Comment by JuliusSweetland** [comment]
@JorgeMattos uh oh? Yes, please upload a screenshot so I know whether to roll back. Thanks.

**Comment by JorgeMattos** [comment]
@JuliusSweetland  Also when clicking on Windows window the Optikey click stops working.

![capturar2](https://user-images.githubusercontent.com/39384525/51778101-3c236e80-20e7-11e9-90b9-ff2e90622fbf.JPG)

**Comment by JuliusSweetland** [comment]
@JorgeMattos Please can you download and reinstall version 2.22.0 again (I've updated the installer). It should fix the missing NEXT SUGGESTION button in the top right.  The taskbar being visible is odd. I cannot replicate this. If you click on the taskbar (or press the windows key) then the taskbar WILL be visible - you have to click on OptiKey again to cover it back up. That is standard Windows behaviour.

What do you mean when you say "clicking on Windows window the Optikey click stops working"?

Thanks for reporting the error!

**Comment by JorgeMattos** [comment]
Now it's good. :+1:  :-)

I'll make a video of the previous one to study.

**Comment by JuliusSweetland** [comment]
Phew! Thanks again

**Comment by JorgeMattos** [comment]
@JuliusSweetland   The last corrected version was great.

I made a video for study.
https://youtu.be/Ky17ejygBso

Thank you very much, my friend.

**Comment by JuliusSweetland** [comment]
Very helpful video. I must have built the first, buggy, version without
UIAccess which is why you can't click on the start menu, installer, etc.

I'm glad everything is working now.

Thanks again for your contribution to OptiKey - really helpful enhancement
that I wouldn't have thought to add.
