### ISSUE TITLE
Wrong value?

### ISSUE THREAD

**Issue by JorgeMattos** [OptiKey/OptiKey#531]
# How OptiKey was being used
      https://github.com/OptiKey/OptiKey/blob/41864c936ec113d2c7461b3a350ffb23ae86115f/src/JuliusSweetland.OptiKey/UI/Views/Keyboards/Portuguese/Alpha1.xaml#L290      WidthSpan="4" 

# Version
 - Operating system and version: [e.g. Windows 10]
 - OptiKey version [e.g. v2.21.0]

the correct value is? 
https://github.com/OptiKey/OptiKey/blob/41864c936ec113d2c7461b3a350ffb23ae86115f/src/JuliusSweetland.OptiKey/UI/Views/Keyboards/Portuguese/Alpha1.xaml#L290      WidthSpan="2"  
Not  WidthSpan="4"

![print](https://user-images.githubusercontent.com/39384525/50544261-dbcc0a80-0bd6-11e9-9e3f-a464c8079d2e.JPG)

**Comment by JuliusSweetland** [comment]
@JorgeMattos slightly confusingly there are 2 properties related to the key width: Grid.ColumnSpan (which is the actual width and is expressed as 2xthe number of actual keys. In this specific example it is 4, which is 2 keys wide) and ColumnSpan, which controls how the key's contents (label or symbol) is sized. This is 2 as the key spans 2 keyboard keys.

**Comment by JorgeMattos** [comment]
@JuliusSweetland Is this why the legend (SPACE) was smaller than the others? *_*

**Comment by JuliusSweetland** [comment]
Yes, you'll need to make room for it if you wish to make the space key
larger

**Comment by JuliusSweetland** [comment]
@JorgeMattos Replying to your question about creating a PR - yes please go ahead...
