### ISSUE TITLE
Localisation: Norwegian

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#542]
1.Keyboard layout

2.Word list/dictionary (about 100,000 entries)

3.Nuances, e.g. diacritical marks (e.g. accent), or behaviours of the characters or language.

4.Translate string on Transifex: https://www.transifex.com/optikey/optikey/language/no/

5.Programming changes to project

6.Test & release

**Comment by larsgrieg** [comment]
Can we please open this again? I would like to get this finished.

**Comment by JuliusSweetland** [comment]
@larsgrieg Reopened. I have created a new Norwegian branch for you to work on for the code changes: https://github.com/OptiKey/OptiKey/tree/Norwegian

**Comment by larsgrieg** [comment]
Thank you, will you create a new Transifex link?

**Comment by JuliusSweetland** [comment]
Is Norwegian on OptiKey's Transifex page already? If not I can add it

**Comment by larsgrieg** [comment]
Yes, there is a norwegian translation that I have started, I found it when I logged in. The link in the opening post was just not working.

**Comment by JuliusSweetland** [comment]
Can you send me the correct link and where it is wrong and I'll update it?

**Comment by larsgrieg** [comment]
Now the link seems to work, maybe I just had to log in. 
It gave a 404 error when I first tried to enter it.

**Comment by JuliusSweetland** [comment]
Yes maybe you needed to be logged in. Good news!
