### ISSUE TITLE
'Collapsed dock thickness' setting keeps resetting.

### ISSUE THREAD

**Issue by hmcomer** [OptiKey/OptiKey#545]
At seemingly random times, the 'Collapsed dock thickness' setting keeps resetting to 20%. Unfortunately I can't see what triggers this exactly. It happens sporadic when I reopen Optikey from the minimized status.

**Comment by JuliusSweetland** [comment]
@hmcomer When you sat "when I reopen Optikey from the minimized status" do you mean minimised completely out of view to the taskbar, so all you can see is the icon in the taskbar at the bottom? Or are you referring to the height of the collapsed dock? Thanks

**Comment by hmcomer** [comment]
Yes, I mean the height of the collapsed dock. See screenshots.
I'm certain that something triggers this, but I don't know what that is yet. 

I've had this issue for some time now but recently it happens more frequently, like multiple times per day.

Thank you...

<img width="1918" alt="opti1" src="https://user-images.githubusercontent.com/33103260/53956730-b7137800-40dc-11e9-9e32-c4d64128142a.PNG">
<img width="1920" alt="opti2" src="https://user-images.githubusercontent.com/33103260/53956731-b7ac0e80-40dc-11e9-8d4e-fd29b78505a9.PNG">

**Comment by JuliusSweetland** [comment]
@hmcomer Understood. Could you find a set of instructions that I can follow to replicate this? That might not be possible and I might have to play around, but for example:

1.Open OptiKey, open Management Console and set collapsed dock thickness to 10%.
2.Navigate to menu and collapse OptiKey
3.Expand OptiKey using collapsed key
4.Collapse Optikey again from menu
5.Observe that the size of the collapsed icon is back to 20%

Something like that. Thanks!

**Comment by hmcomer** [comment]
The steps that you've written are correct, I can't say more because I don't
know what triggers it.

So here is how I would written the steps:

1. Go to Management Console and set collapsed dock thickness to 10%
2. Collapse Optikey via menu
3. Expand Optikey
4. Collapse Optikey again and observe that collapsed icon is back to 20%

I just tried a bunch of things (like watching Youtube full screen, playing
a game on full screen) to see what triggers it, but no result.




Op do 7 mrt. 2019 om 14:22 schreef Julius <notifications@github.com>:

**Comment by JorgeMattos** [comment]
@hmcomer Do you use dynamic keyboard as well? Or just the Optikey keyboard?

Does this happen when the Optikey or the computer is turned off?

**Comment by hmcomer** [comment]
I don't use dynamic keyboards (because I don't know how design my own) but I've installed the 'big hacker keyboard' and I see now that that is what triggers this bug. Thank you @JorgeMattos!

It happens when I accidentally open the dynamic keyboard and restart Optikey afterwards, though this doesn't happen every time for some reason.
Here's how you can replicate the bug:

1. Make sure you have installed a dynamic keyboard and check if collapsed dock thickness is 10%
2. Navigate to that dynamic keyboard
3. Go back to menu
4. Close the whole application  and restart it
 5.Observe that the size of the collapsed icon is back to 20%

**Comment by JuliusSweetland** [comment]
Thanks. What happens if you do this:

Make sure you have installed a dynamic keyboard and check if collapsed dock
thickness is 10%
Navigate to that dynamic keyboard
Go back to menu
Minimize OptiKey

Is the restart of OptiKey significant?

**Comment by hmcomer** [comment]
Yes, restarting is significant it seems. I've now tried without restarting multiple times, but it didn't happen. When I restarted, then it did go back to 20%.

**Comment by JuliusSweetland** [comment]
Ok. I'll investigate as soon as I can.

**Comment by hmcomer** [comment]
Thank you very much!

Though in my case I can easily solve it by empting the folder containing the dynamic keyboards.

**Comment by JuliusSweetland** [comment]
True, but you shouldn't have to do I'll fix it!

**Comment by JorgeMattos** [comment]
That's right, for some reason the height of the dynamic changes the height of the Optikey keyboard.

**Comment by JuliusSweetland** [comment]
It must persist a height directly to the settings somewhere, or corrupt
them somehow.

**Comment by JorgeMattos** [comment]
I'll note if the change occurs in the User.config file in% appdata% Julius Sweetland

**Comment by JuliusSweetland** [comment]
Thanks

**Comment by JorgeMattos** [comment]
@hmcomer What version of Optikey are you using?
I can not replicate the bug.

**Comment by JuliusSweetland** [comment]
@hmcomer @JorgeMattos I've not had a chance to prove this, but from reading over the dynamickeyboard.cs code I believe it's caused by line 100, which (if an override height is specified on the dynamic keyboard) changes the setting value of the full docked height. If you subsequently caused OptiKey to persist this setting to disk (e.g. by changing the state to Collapsed), then this might override your default settings:

'''Settings.Default.MainWindowFullDockThicknessAsPercentageOfScreen = overrideHeight.GetValueOrDefault();

There is another way to resize the docked height so I'll do some experiments if I can tomorrow, but I believe the fix will be to not override the stored setting, but instead use this method on entry and exit to set and restore the correct heights:

windowManipulationService.ResizeDockToSpecificHeight(heightAsPercentScreen, persistNewSize:false);

**Comment by hmcomer** [comment]
@JorgeMattos I use version 2.23.

**Comment by hmcomer** [comment]
Hi @JuliusSweetland, 

The latest update (2.28.0) didn't solve this issue. 
I thought maybe the resolution (2160p) or the scaling of Windows (150%) is causing the issue, but on 1080p and no scaling the issue still occurred.

**Comment by JuliusSweetland** [comment]
@hmcomer please try with pre release 2.29.0 available here: https://github.com/OptiKey/OptiKey/releases/tag/v2.29.0

If the problem still persists please can you give me the exact steps to reproduce the problem as there have been numerous changes since this issue was originally created

**Comment by hmcomer** [comment]
Hi

I've tested the new release for a day and it seems the issue has been fixed. The 'collapsed dock thickness' setting didn't reset after installing the release.

Thank you very much.

**Comment by JuliusSweetland** [comment]
@hmcomer Excellent. I'll promote the official release version to 2.29.0
