### ISSUE TITLE
Rename manual mode -> mouse mode.

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#548]

**Comment by Ishaan28malik** [comment]
Can you please add a description to this issue so that I can work upon this?
@kmcnaught

**Comment by JuliusSweetland** [comment]
@Ishaan28malik This is a simple rename to change the "MANUAL MODE" to a "MOUSE CONTROL MODE" or similar.

**Comment by Ishaan28malik** [comment]
Oh I see , let me work on this issue then

**Comment by Ishaan28malik** [comment]
I am not able to find any keyname as MANUAL MODE ....

**Comment by JuliusSweetland** [comment]
If you do a text search you would find it in the English resource file.
