### ISSUE TITLE
Create language and version specific projects, applications, installers.

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#553]
There's a few interlinked things here:

- Make sure website has landing pages for specific apps (so someone wanting 'OptiKey Symbols' isn't need to be overwhelmed with information about 'OptiKey Pro')
- Make sure installation process is internationalised, and OptiKey's language is set during installation
- Streamline the selection of eye tracker via installer or simple first-time setup wizard. (probably installer, though a wizard for helping with eye tracker trouble would be good)

and finally (big one):
- Split OptiKey into standalone apps - names TBC, but including symbol communication, keyboard-only, simplified-keyboard, mouse-only and pro version. 
 
Each project needs own settings and management console. Possibly also different keyboards, allowing us to remove the MENU/BACK keys from some keyboards (e.g. Conversation Only, or Mouse Only). Alternatively we have a setting with the OptiKey version and customise each keyboard based on that setting.

**Comment by alexandre-mbm** [comment]
**Hint:** use `- [x] item` to show progress.

Link the related issues please.

Regarding _landing pages_ on website, see my #716 issue please.

### A technical question

Why some users are facing performance issues after upgrading for the **Pro** versions?

**Comment by kmcnaught** [comment]
Closing this and re-opening issue #720. The rest is complete.

**Comment by kmcnaught** [comment]
@alexandre-mbm I'm not aware of specific performance issues. Could you please open a separate issue with more details?

**Comment by alexandre-mbm** [comment]
> Could you please open a separate issue with more details?

@JorgeMattos
