### ISSUE TITLE
OptiKey startup wizard

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#559]
OptiKey startup wizard -present appropriate setting choices like look to zoom over click scrolling.

- also perhaps eye tracker choice (if not in installer), and eye tracker connection validation / diagnostics.

**Comment by kmcnaught** [comment]
- dwell or click would be important to include here, lots of EyeMine users assume that dwell is non-negotiable...

**Comment by Ishaan28malik** [comment]
So is this startup wizard being prepared or is it still pending? @kmcnaught  @JuliusSweetland

**Comment by JuliusSweetland** [comment]
Pending, but I would wait. OptiKey is currently being split into 4 versions

**Comment by Ishaan28malik** [comment]
Oh that's new
