### ISSUE TITLE
New installer ready for multiple apps

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#566]
For v3 (with split out apps) we'll want better onboarding via the installer (e.g. select language/eye tracker at installation time? or pick type of Chat keyboard) and we'll also want full internationalisation. 

To make this easier, we'll create an AdvancedInstaller project to do everything to the current app does, + internationalisation + modify initial user settings + scope for onboarding-type screens.

**Comment by JuliusSweetland** [comment]
https://social.msdn.microsoft.com/Forums/vstudio/en-US/7b365595-a425-4c06-830d-31cfa6c91b20/is-this-a-bug-or-by-design-settings-declared-internal-when-autogenerated?forum=csharpgeneral

The setting classes will get it's values from (in order):
- local user.config file
- roaming user.config file
- application.config file
- machine.config file
- DefaultSettingsValue attribute on the setting itself.

**Comment by JuliusSweetland** [comment]
@kmcnaught FYI I have checked in a small change on master to include the app.config file. This allows us to change the default setting values from the installer. I have tested changing values before packaging the files into an installer and it works as expected.
