### ISSUE TITLE
BACKLOG (future ideas, tasks, features)

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#57]
- Change behaviour of mouse pointer - looking above/below/left/right of cursor to move it, and within radius to progress selection
- Store usage statistics in a case sensitive way? Would need to keep track of originally cased entries (incl. suggestions). Does this have any benefit? Think about whole advantage of storing usage statistics. 
- Character codes – ALT on/lock, then numbers, then ALT off
- Auto correct words
- Predict next word
- Add high contrast theme
- No position input possible - automatically cycle through groups of keys, then keys in group: 
  Keyboards could define ordered set of KeyValues; the key "groups"
  New SelectionMode = KeyGroups - this then changes to PositionSource to a source which automatically loops through the current keyboard's groups.
  Position source can output more than one current point: CurrentKey would become a set (allowing the highlighting of a group of keys)
  Selection (of a set of KeyValues) when SelectionMode = KeyGroups does not produce a SelectionResult, but instead disables all keys not in the group (not explicitly, but instead based on a property, e.g. CurrentKeyGroup). SelectionMode then changes to Key.
  In Key mode the position source could iterate through all enabled keys in the key map (which should be the selected group of keys).
      Selection => normal key selection and reset mode back to KeyGroups.
      ? If no selection in X iterations through the keys then output a special selection, e.g. a null selection (the trigger can watch the position source, like the fixation triggers.
  Each key group should contain a 'back' key to return from group selection?
  Need a setting to determine whether a key group should be used directly (for T9 style matching), or only to reduce the key map (which will be iterated through to make the next selection).
  Key groups can have sub groups to allow the selection of a row, then a group of keys on that row, then a key (for example)
- Add support for T9 style selection; either individual keys, or multi key select?
- Prevent minimising, or at least ask before allowing it?
- Touch screen support - Ignore accidental presses | Select “on touch”, “on release” or by holding down your finger
- Add "activation" trigger to existing TriggerSources - e.g. button pressed down, or touch screen press to enable key/point fixation trigger (chaining triggers together)
  - When chaining triggers there are 2 options;
    1.First trigger acts as a gate and just needs to send a single high signal to enable the second trigger
    2.First trigger must remain high to enable the second trigger
- Add setting for trigger sources where you press down a key/touch the screen - press=high or low signal - this is possibly useful when chaining triggers so you can allow fixations only when the screen /a button is or is not being pressed
- Add calibration support for gazetracker

**Comment by smcguinness** [comment]
Remove dependency of stand alone eye tracker and utilize Assistive Context-Aware Toolkit https://github.com/01org/acat/releases

**Comment by JuliusSweetland** [comment]
* Improve fixation triggers by holding onto user focus more deliberately
P218/219 of Gaze interaction and applications of eye tracking.

Virtual expansion of the area being selected.
Grab and hold - keep adding to fixation until a saccade is detected that would move focus away from the selection zone.

**Comment by JuliusSweetland** [comment]
Gaze gestures - https://github.com/JuliusSweetland/OptiKey/issues/87

**Comment by JuliusSweetland** [comment]
tag elements near point-of-gaze w/ colors, IDs, and lines – project to large elements https://github.com/JuliusSweetland/OptiKey/issues/71

**Comment by JuliusSweetland** [comment]
Old and obsolete multi-key selection thought: batch submission of keyboard buttons – Variable dwell time necessary for activation https://github.com/JuliusSweetland/OptiKey/issues/72

**Comment by JuliusSweetland** [comment]
Cross platform support (Linux, OSX) #105

**Comment by JuliusSweetland** [comment]
Allow cursor position in scratchpad to be controlled https://github.com/JuliusSweetland/OptiKey/issues/110

**Comment by JuliusSweetland** [comment]
Add support for gamepads (so joystick/gamepad buttons can be used for selection) #70

**Comment by JuliusSweetland** [comment]
BCI - eg "Communication by BCI based on EEG": http://youtu.be/k98_1jSnEv4 https://github.com/JuliusSweetland/OptiKey/issues/27

    http://neurosky.com/ $80
    Lucas Steuber suggested that MND/ALS affects the electrical patterns that can be detected on the surface of the skin, so this may be a dead end.

**Comment by JuliusSweetland** [comment]
Add auditory trigger https://github.com/JuliusSweetland/OptiKey/issues/26

**Comment by JuliusSweetland** [comment]
Add blink trigger https://github.com/JuliusSweetland/OptiKey/issues/22

**Comment by JuliusSweetland** [comment]
Touch screen trigger and point source #23

**Comment by JuliusSweetland** [comment]
Clarify settings by adding previews, prompts, etc #54

**Comment by JuliusSweetland** [comment]
Old and obsolete multi-key selection thought: batch submission of keyboard buttons – Variable dwell time necessary for activation #72

**Comment by JuliusSweetland** [comment]
Simplify the potentially confusing mental model for docking/window position #134

**Comment by JuliusSweetland** [comment]
Auto show/hide when text entry control has focus/is detected

**Comment by JuliusSweetland** [comment]
Remember: Hide case specific settings for languages with no casing, e.g. Japanese/Chinese

**Comment by JuliusSweetland** [comment]
Customise cursor with current action and whether magnify is going to be used, e.g. Cursor + Left click icon + Magnify icon

**Comment by JuliusSweetland** [comment]
Move and resize OptiKey using a mouse at any time, allowing carers to manipulate OptiKey manually and help with setup

**Comment by JuliusSweetland** [comment]
Support PhraseExpress Text Expander:

(PhraseExpress listens for known combinations of keys and expands them into full text. When used in conjunction with OptiKey this can speed up text entry into other applications, but OptiKey will be unaware of the text expansions and the scratchpad will fall out of step. Below are details from the developer of PhraseExpress on how it works internally so that OptiKey might listen to the PhraseExpress events and detect the expanded text for inclusion in the scratchpad)

* If using the WH_KEYBOARD_LL you can detect injected key strokes by checking if the message flags member of KBDLLHOOKSTRUCT contains LLKHF_INJECTED.
* To detect PhraseExpress check if the dwExtraInfo member has a value of 747273397.
* PhraseExpress either simulates characters directly using SendInput or it simulates CTRL+V after filling clipboard with the phrase content.

**Comment by alexandre-mbm** [comment]
Profiling for switches (keystrokes)

**Comment by Razzeee** [comment]
Might want to remove this?

> Continuous integration - octokit uses QED: https://github.com/half-ogre/qed/

**Comment by JuliusSweetland** [comment]
@Razzeee done thanks

**Comment by rsrobinett** [comment]
Consider adding support for Intel RealSense gaze tracking.  This is a newer technology and is already available in several economical laptops.

Here is some information about the Intel SDK for RealSense
[RealseSense SDK Documentation](https://software.intel.com/en-us/intel-realsense-sdk/documentation)
[Realse Sense gaze tracking documentation](https://software.intel.com/sites/landingpage/realsense/camera-sdk/v2016r3/documentation/html/index.html?gazedata_pxcfacedata.html)

The references can be added to the project as a [nuget package](https://www.nuget.org/packages/libpxcclr.cs/).

**Comment by JuliusSweetland** [comment]
Archiving.
