### ISSUE TITLE
Incorrect expand/collapse dock icons on mouse keyboard when docked to bottom on screen

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#581]
This is a really minor issue, but hopefully will also be an easy fix.

Because of recent physical workspace set up changes, I've been experimenting with docking Optikey to the bottom of my screen (rather than the top, as has been my preference in the past).

With Optikey set up this way (docked to the bottom), the expand dock and collapse dock icons on the mouse keyboard appear to be drawn for a keyboard docked to the left side of the monitor. I know that when docked to the top, Optikey correctly displays icons reflecting the idea of expanding/collapsing from this location.

I will include some screenshots of the you can see the icons I'm referring to with the keyboard docked to the top and bottom of the screen.

![Docked to bottom](https://user-images.githubusercontent.com/33188271/63119924-3dc35f80-bf6f-11e9-87e2-954d42298a53.png)

![Docked to top](https://user-images.githubusercontent.com/33188271/63120007-5df31e80-bf6f-11e9-9a0d-86bc9aeca504.png)

If the correct icon already exists, this should be an easy fix, and I should be able to make the change myself. If not, then that's probably outside of my skill set.

**Comment by kmcnaught** [comment]
Hi Anna, 

It looks like the symbols are the same, but with an orientation applied in this code:  
[src/JuliusSweetland.OptiKey.Core/UI/ValueConverters/MinimiseAndDockPositionToSymbolOrientation.cs](https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey.Core/UI/ValueConverters/MinimiseAndDockPositionToSymbolOrientation.cs)

You can see where the converter is used in the xaml here, e.g. line 680 (and elsewhere):
[src/JuliusSweetland.OptiKey.Core/UI/Views/Keyboards/Common/Mouse.xaml](https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey.Core/UI/Views/Keyboards/Common/Mouse.xaml)

I assume there's a bug in the MinimiseAndDockPositionToSymbolOrientation logic - do you want to investigate yourself?

**Comment by JuliusSweetland** [comment]
@annakirkpatrick You could add logging to the converter to see which values are passed in:

https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey.Core/UI/ValueConverters/MinimiseAndDockPositionToSymbolOrientation.cs

The way it works is that the key is defined like this:

`<controls:Key Grid.Row="8" Grid.Column="6" Grid.RowSpan="2"
              SymbolGeometry="{StaticResource CollapseDockIcon}"
              Text="{x:Static resx:Resources.COLLAPSE_DOCK_SPLIT_WITH_NEWLINE}"
              SharedSizeGroup="KeyWithSymbolAndText"
              Value="{x:Static models:KeyValues.CollapseDockKey}">
    <controls:Key.SymbolOrientation>
        <MultiBinding Converter="{StaticResource DockPositionToSymbolOrientation}">
            <MultiBinding.Bindings>
                <Binding Path="MainWindowDockPosition" Source="{x:Static properties:Settings.Default}" />
                <Binding Path="MainWindowState" Source="{x:Static properties:Settings.Default}" />
            </MultiBinding.Bindings>
        </MultiBinding>
    </controls:Key.SymbolOrientation>
</controls:Key>`

This passes Settings.Default.MainWindowDockPosition and Settings.Default.MainWindowState to the converter, which then returns a SymbolOrientation enum value. This is set on the key's SymbolOrientation property. Finally the theme (from your screenshots this is the AndroidDark theme and so the logic starts here: https://github.com/OptiKey/OptiKey/blob/f67d0838e654e654f5941830f976c58ff7ee07fd/src/JuliusSweetland.OptiKey.Core/Resources/Themes/Android_Dark.xaml#L334). This interprets the SymbolOrientation value to apply a rotation transform to the key's symbol.

It looks like, somehow, this value is being set on the key: SymbolOrientations.Right.

I would start in the converter.
