### ISSUE TITLE
Update contribution guide

### ISSUE THREAD

**Issue by AblingerOscar** [OptiKey/OptiKey#583]
First up, I just found this project and think it's amazing.
When searching on how to contribute (mainly to add it to our [new awesome list](https://github.com/awesome-global-contributions/awesome-global-contributions)), I noticed that the contributing.md is lacking any tutorial on how to do this.

Might i suggest at least adding a link to https://github.com/OptiKey/OptiKey/wiki/Contribute? I could only find that page through googling ^^'
Additionally, a full contribution guide that explains the architecture of the project and what kind of contributions are wanted might also be useful. I don't how useful this would be for this specific project, but I also haven't found any discussion on this, so I thought, I'd bring it up.

**Comment by JuliusSweetland** [comment]
@AblingerOscar Hi. Thanks for your suggestions. There is currently a link from the wiki (right at the bottom) to the contributing page (see below), but I will definitely add it to the contributing.md file.

The solution project architecture is being changed quite dramatically at the moment, but when that is complete I will definitely look to enhance the contributing guide(s).

Will OptiKey be featured in the new awesome list?

Thanks again!

**Comment by JuliusSweetland** [comment]
This time with more screenshots:

![image](https://user-images.githubusercontent.com/4722561/63863366-052b7900-c9a6-11e9-80ce-6b7e59b3eb20.png)

**Comment by AblingerOscar** [comment]
Hey @JuliusSweetland, I'm aware of that link, but it's not somewhere, where I'd search for a contribution guide ^^
I searcher 1) README 2) CONTRIBUTING 3) Start of Wiki 4) Google
Maybe I'm the outlier, but it definitely doesn't hurt having a link in the Contribution file :)

And, yes, we'd like to feature this project to that list.

**Comment by JuliusSweetland** [comment]
@AblingerOscar Great, thanks very much!
