### ISSUE TITLE
Dynamic Keyboard Enhancement - Allow Key to Trigger Multiple Actions

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#589]
This enhancement is to make it possible for a key to trigger a sequence of actions.

Examples:
1. A key that minimizes the keyboard, turns the magnifier on, executes a left click, turns the magnifier back off, and then expands the keyboard.
2. A key that turns on control lock and then jumps to another keyboard.
3. A key that sends a a keystroke, turns off control lock, and then jumps to another keyboard.

**Comment by alexandre-mbm** [comment]
I would to want the Conversatiton keyboard jumping to the Writing keyboard
when copying the typed text. My father is needing the keyboard in full
screen.

Em sáb, 7 de set de 2019 1:34 PM, AdamRoden <notifications@github.com>
escreveu:

**Comment by AdamRoden** [comment]
@JuliusSweetland I've got a functioning version of this in place, but I'm not exactly happy about what I had to do to pull it off. I started out thinking I would make it all xml, but for simplicity I ended up using a string of name value pairs using "|" as delimiter and "=" as the link between name and value.
Here's an example of the xml:
\<MacroKey>\<Row>1\</Row>\<Col>5\</Col>\<Macro>Text=Hello World|Action=MoveAndResizeAdjustmentAmount|DestinationKeyboard=MyResize\</Macro>\<Symbol>UpArrowKeyIcon\</Symbol>\</MacroKey>

I know I still need to add a ReturnToKeyboard flag.
Do you have thoughts or concerns about doing it this way? 
Would you prefer some other design?

**Comment by JuliusSweetland** [comment]
@AdamRoden I don't have an issue with a pipe separated set of values, no. What are the available Actions and other values that can be used in the Macro tag?

**Comment by AdamRoden** [comment]
@JuliusSweetland If you don't see any red flags with this approach, then I might stick with it. Currently, you can have as many commands as you want in any order you want from 3 categories: Text key, Action key, Change Keyboard key. It is open to all the same actions as a standard Dynamic keyboard Action key. I didn't include plug-ins, but that might change if you think it would be valuable. Lastly, I don't know what interaction is functionable with the scratchpad and output panel, so if you know of scenarios to include, then let me know. I do suspect we will need to do some recoding around the scratchpad/output panel.

**Comment by JuliusSweetland** [comment]
Understood. Sounds good. We can grow the functionality as use cases become
apparent.
