### ISSUE TITLE
Dynamic Keyboard Enhancement - Keys to Display & Alter System Settings

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#591]
This enhancement is to add two new features.
1. The ability to retrieve a value, such as the "Adjust by pixel" amount and display it in a key's label.
2. The ability to submit a change to a system setting, such as the "Adjust by pixel" amount.

**Comment by JuliusSweetland** [comment]
@AdamRoden I think submitting a direct change to a setting could lead to users changing the OptiKey settings to unexpected values, potentially causing problems. I would prefer for changes to be handled by new function key values which toggle or cycle predictable values.

**Comment by AdamRoden** [comment]
@JuliusSweetland I can agree with you on that. Although, it inspires another idea that might be worth exploring. Here is potential new workflow:
1. User starts on the Size and Position keyboard
2. User activates the "Adjust by pixel" key
3. Instead of changing the value, this key triggers a jump to a new keyboard with a set of keys listing the valid options to set the "Adjust by pixel" value.
4. When the user activates one of the keys, the new value gets set and the UI returns to the previous keyboard.

**Comment by JuliusSweetland** [comment]
@AdamRoden That's a good idea. If it were also a dynamic keyboard it would allow it to be reused for any numeric setting.

I guess we'd need a new type of key (or two types of key):

1.Just a label to display what the setting is.
2.Display a setting value (with format) and also link to another keyboard.

Worth noting that the new keyboard would also need a context so it knows how to get back to the original keyboard once the value has been set.
