### ISSUE TITLE
Keyboard Enhancement - Alt, Ctrl, Shift, Win

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#595]
I have my keyboard running at a  pretty fast rate. Key fixation to lock on is 250 ms, and time to complete is 50 ms. With these settings I can get a nice typing rhythm.

One thing that I have been getting frustrated by is the behavior of the Ctrl, Alt, and Shift keys. I do like them to activate at the same speed as all my other keys, but it is sometimes challenging to get them into the state I want without accidentally double activating. I have a couple ideas to improve usability:

1. Timing: It would be nice if the initial time to activate was the same as text keys, but the time to switch on keylock was longer. Alternatively, add a setting so the key has an individual cool down period before it can be activated again.
2. Deactivation: It would be nice if the keys could be configured to remain in 'key down' state if a 'physical key' (home, end, arrows, etc...) is pressed and only automatically return to 'key up' state after pressing a 'text key' (letter or number).
3. Background color: It would be nice if the key background color would change when they are on because just changing the font color isn't always enough. When locked, a bigger bolder lock icon, or additional background color might also help.

**Comment by AdamRoden** [comment]
Attached is a note regarding 2 and sample code to change the new behavior.
[PreventModifierRelease.txt](https://github.com/OptiKey/OptiKey/files/3623514/PreventModifierRelease.txt)

**Comment by JuliusSweetland** [comment]
@AdamRoden Hi Adam. All good suggestions.

1.Adding support for different press down and lock down timing is possible. Might get confusing, but we can definitely look into this.

2.This is how a key which is locked down currently behaves. After pressing another (non-modifier) key the modifier keys (which are not locked down) are automatically released.

3.I like this. We can modify the themes to support this by default.

**Comment by AdamRoden** [comment]
@JuliusSweetland Hi Julius. Here are some further thoughts/explanation.

1. In regard to when to activate shift-down, vs shift-lock, vs shift-up. Assuming a dwell time of 500 ms, the logic could be:
if (dwell on key for 500)
{
  if (Up) {trigger Down}
  if (Down && time since activating Down < 500) {trigger LockedDown}
  if (Down && time since activating Down > 500) {trigger Up} 
  if (LockedDown) {trigger Up}
}

2. Would it make sense if I said "I want a change so the arrow keys do not trigger a shift up keystroke"?

**Comment by JuliusSweetland** [comment]
@AdamRoden 
1.The complexity is that the current framework expects an exact value on how long the users selects the key. We could change this so keys which can have 3 states can allow you to progress through 2 states in one selection, but really this could be achieved by making two concurrent selections on the same key. I get what you're aiming for, but I am struggling to think how to achieve this, and how to make selections obvious to users, as these keys would behave differently to all other keys. Let's come back to this idea later.

2.Yes that would be fine. We'd need to categorise those keys as not releasing modifier keys.
