### ISSUE TITLE
Holding down a key in a Dynamic Keyboard 

### ISSUE THREAD

**Issue by tqphan** [OptiKey/OptiKey#599]
I would like to create a dynamic keyboard where the user can hold down a key. Basically its behavior would be exactly how the modifier keys (shift, alt, ctrl) work. The reason for this is to play games. Many games require keys to be held down. Would this be possible without modifying the source code?

**Comment by AdamRoden** [comment]
@tqphan I don't know of any way to do what you are asking without modifying the code. However, the modifications could get tied in with any efforts toward #595. I'd like to have more control regarding key-down and key-up behavior, and your request makes it more likely something will be done.

**Comment by JuliusSweetland** [comment]
@tqphan @AdamRoden This might be possible by adding a new publicly settable properties for keys which can be pressed down and keys which can be locked down:
https://github.com/OptiKey/OptiKey/blob/master//src/JuliusSweetland.OptiKey.Core/Models/KeyValues.cs#L412:38

A dynamic keyboard could add keys to these properties when it is loaded, as long as exiting the keyboard handles the transition to another keyboard by checking the destination keyboard for keys which can be pressed and locked down and ensuring that the properties are updated and releasing keys which can no longer be held down.

**Comment by AdamRoden** [comment]
@tqphan @JuliusSweetland I'm thinking about how it would make sense to switch a key into locked down mode and have two ideas for you to consider.
a. If a key has locking enabled, then it can be locked down by staring at it for a specified amount of time.
b. We add a new key, that when pressed tells OptiKey to press down the next key, but do not release it. 

In either case the key would get released by changing keyboard or activating it again.

I think option 'a' is the fancy way and option 'b' is the easy to understand and implement way.

**Comment by tqphan** [comment]
@AdamRoden @JuliusSweetland  Games often requires holding down keys and maybe at the same time spamming keys. For example, holding down 'W' to move forward while spamming 'E' to swing an axe. The drawback for option B is that you'll have to constantly pressing the 'locking enabled' key to switch between the holding and spamming behavior.

**Comment by JuliusSweetland** [comment]
@AdamRoden @tqphan How about a LOCK key which itself can be locked down. The behaviour would be:
1.If LOCK is pressed down then the next key pressed is locked down and LOCK is then released.
2.If LOCK is locked down then multiple other keys can be locked down until LOCK is released manually.

A similar idea could be implemented for a RAPID or TURBO key which presses and releases a key, or set of keys every x milliseconds (based on a setting).

Thoughts?

**Comment by tqphan** [comment]
@JuliusSweetland @AdamRoden  In my opinion, all of timings and behavior properties should be per key basic that is specified in the custom keyboard XML. 

I would love to contribute programmatically. When I try to work with a new code base, my brain kinda explodes a little. It usually takes me quite a bit of time to familiarize myself. On that note, I tried opening OptiKey in VS 2019 but I get all kinds of warnings and a null reference error. What version of VS is recommended for OptiKey? I didn't want to open an issue, because it's probably just me being dumb.

**Comment by JuliusSweetland** [comment]
Hi Tom. I'm not sure. I use 2019. You'll have to post the errors for me to
be able to see what's going on.

**Comment by AdamRoden** [comment]
@tqphan If you know how to code, you should look into AutoHotKey to augment your abilities. It's quick and easy to do a lot of things once you get the hang of it. Also worth checking out for gaming would be Project Iris.

For your errors, that happens to me too when start new. I couldn't run my fork today until I cloned optikey/optikey to my machine, did a fresh build of that, and then after that worked, I was able to open my fork and run it.

**Comment by kmcnaught** [comment]
I know other people who have wanted a similar feature (also for games) - I always imagined dynamic keyboards would support this eventually. I think it's best to think of this separately to the usual typing / computer logic of holding down special (e.g. modifier) keys, or even treating 'lock' itself as a separate function to apply. For gaming, what you really want is to be able to define dynamic keys which individually do things like: 
(a) Press (and key held down) W to walk forward
(b) Press and release Space (with a defined delay between the actions) to jump. The latter is quite important for games which poll key presses rather than reacting directly to keyboard events. 

I was imagining something like::
(i) support for a KeyHold element that declares which key to be held down (or released, with Optikey showing state like it does currently for locked keys)
(ii) support for a PressAndRelease element that declares which key, and how long to hold it
(iii) perhaps a new function key for "release all held keys" ?

@tqphan does this fit better with what you were imagining?

**Comment by tqphan** [comment]
@kmcnaught That is exactly how I would imagine it. You described it more clearly than I did. Thank you.

@AdamRoden Cloning the Optikey repository works. I did not know there's a difference between git clone and downloading the zip. Thanks.

**Comment by AdamRoden** [comment]
@tqphan @kmcnaught Could you give examples games, their control mapping, and how you use keys and combinations of keys in those games.  That will help me understand and might inspire more ideas.

**Comment by tqphan** [comment]
@AdamRoden I will have a more detailed post of the games I play over the weekend. In the mean time here is the basic mapping for [World of Warcraft
](https://www.youtube.com/watch?v=0R5oqaygVIc). You don't have to watch all of it. The first 3 minutes should give you a general idea. It's true you can do most things with the help of Autohotkey, but I think the basic ability to hold down an arbitrary key should be native to OptiKey.

**Comment by lsaranto** [comment]
Alt Controller ([http://altcontroller.net/](http://altcontroller.net/)) has similar features. You can check it for inspiration.

**Comment by AdamRoden** [comment]
Alt Controller is very inspiring. The WoW video got me in the mindset for how a controller keyboard should work. If you are playing a game, the keyboard you use for game controls would be a different file than the one you use for typing text, and you might have a different keyboard file for each unique game. Then you would just jump between the keyboards depending on what you need to do.

So, at a design level:
1. Create key down, key up, and toggle key actions
2. Add an override dwell time element at the key level to enable fast activation
3. Add a cool down element to avoid multiple clicks when using a fast activation
4. Add color flags to customize the color of individual keys depending on their characteristics and state
5. Use the new DynamicKey type if we need to string together a sequence of actions (hold run, wait, press jump, wait, release run) 
6. Add a loop feature to DynamicKey if we want a turbo key.
7. Add a reset all key action.

**Comment by AdamRoden** [comment]
@JuliusSweetland I started implementing a key down action, but hit a snag, and after observing the behavior, I am not sure which direction to go.
Here's what happens: a key down event is sent, but there is no repeat. Observing in notepad, you will get a single letter no matter how long the key is down. 
If you compare that to holding a key down with the Windows on-screen keyboard, it send repeated key down events every 10 ms until you release the key.
I don't know how games will behave, but I'm thinking we should mimic the behavior of the Windows on-screen keyboard.
Thoughts?

**Comment by JuliusSweetland** [comment]
Hi Adam. Yes the single key press is the expected behaviour. We would need
to simulate repeated key strokes, but only for certain keys, e.g. holding
down modifier keys does not result in repeated key strokes as far as I
know. Maybe you could look for more info on how physical keyboards are
implemented as I remember reading something a long time ago that explained
the logic quite well.

FYI I am now in Tokyo so I'll have to look at your PR when I get back.

**Comment by tqphan** [comment]
@AdamRoden From my experience, the repeating behavior isn't needed for games. For example, Autohotkey default behavior for key down doesn't repeat and it works with all games I tried.

**Comment by AdamRoden** [comment]
@JuliusSweetland @tqphan I tested and confirmed what Tom had to say by playing an online driving game where I had OptiKey send a KeyDown event, sleep for 5 seconds, and then send a KeyUp event. The result was that my vehicle moved forward for 5 seconds and then stopped.

However, I can still think of compelling reasons to allow the user to define a key repeat rate, so we will need to build that into the final product as well.

**Comment by AdamRoden** [comment]
I'm far enough along now to share a concept OptiKey dynamic keyboard I built in my dev environment. It is a full screen transparent window, with large semi-transparent up/down/left/right keys. If you click in the areas that are 100% transparent, the click happens on the background window, not on the OptiKey keyboard. 

The keys will be programmable so when you activate one of them it can send:
1. A single standard press and release keystroke
2. A single toggle key state (if up then down / if down then up)
3. A continuous stream of press and release keystrokes until you deactivate it
4. A continuous stream of press and release keystrokes until you stop looking at it

![image](https://user-images.githubusercontent.com/45572061/67539475-e399f580-f6a7-11e9-8095-17f7ca262a52.png)

**Comment by JuliusSweetland** [comment]
Addressed in v2.32.0
