### ISSUE TITLE
Positioning bug with custom keyboards and docked mouse layout

### ISSUE THREAD

**Issue by SamuelSnowball** [OptiKey/OptiKey#605]
# How OptiKey was being used
Was using a custom keyboard and selected the mouse icon. When returning back to the keyboard via back button, the keyboard layout becomes distorted.

# What the user expected to happen
The keyboard layout should return to the size it was originally. 

# What the user actually experienced
The keyboard layout was distorted to the size of the docked mouse layout, very small and cannot see keys.

# Version
 - Windows 10
 - OptiKey v2.30.0

# Steps to reproduce the issue
1. Go to dynamic keyboards
2. Select any dynamic keyboard that contains a mouse icon
3. Press the mouse icon
4. Return to the keyboard via back button.

# Any other information that helps to describe and/or reproduce the problem
This does not appear to happen if you enlargen the mouse dock position before returning to the keyboard. As the dock size increases, when you go back to the keyboard, I imagine the keyboard size is set to the enlarged dock size, as opposed to the regular dock size, giving the appearence that all has worked.

# Screenshots
Loading into optikey:
![image](https://user-images.githubusercontent.com/23612173/66869282-f66d4580-ef96-11e9-9659-d470c2d31249.png)
Selecting a dynamic keyboard:
![image](https://user-images.githubusercontent.com/23612173/66869295-fe2cea00-ef96-11e9-9dae-440de0b12ca0.png)
![image](https://user-images.githubusercontent.com/23612173/66869307-05ec8e80-ef97-11e9-92a6-e4fff077080f.png)
Selecting mouse button:
![image](https://user-images.githubusercontent.com/23612173/66869317-0c7b0600-ef97-11e9-9ff9-cb0a4eb46e2d.png)
Returning from mouse layout:
![image](https://user-images.githubusercontent.com/23612173/66869327-13a21400-ef97-11e9-8a2f-902860a2ac7a.png)
Distorted keyboard:
![image](https://user-images.githubusercontent.com/23612173/66869342-1c92e580-ef97-11e9-8c37-bb6adc8250a8.png)

**Comment by AdamRoden** [comment]
Thank you @SamuelSnowball 
I am aware of this issue and plan to have it fixed with the next round of dynamic keyboard enhancements.

**Comment by JuliusSweetland** [comment]
@SamuelSnowball Thank you for raising the issue.
@AdamRoden Thank you for acknowledging.

**Comment by SamuelSnowball** [comment]
fixed in new version
