### ISSUE TITLE
Localisation: Hungarian

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#607]
1.Potential keyboard layout examples:
https://www.branah.com/hungarian

2.Online keyboards:
https://www.branah.com/hungarian
https://hungarian.typeit.org/
https://www.101languages.net/hungarian/keyboard/

3.Transifex: https://www.transifex.com/optikey/optikey/language/hu/

4.Breakdown of required characters: a-z plus á é öóő üúűű

5.Overview doc: https://r12a.github.io/app-charuse/?language=fa

6.Branch: Pending

**Comment by N1Official** [comment]
Hi!
I think we have finished the keyboard, can you check it please?

**Comment by N1Official** [comment]
Did I share it with you?
Sorry, I'm new with GitHub 
![image](https://user-images.githubusercontent.com/56759208/67902846-67e9ee00-fb6a-11e9-854a-64ea839a399b.png)

**Comment by JuliusSweetland** [comment]
@N1Official Hi Laszlo. Yes I received a pull request from you. I will look over it and try to test it tonight/tomorrow. I have another PR to review as well so please bear with me. Thanks!

**Comment by JuliusSweetland** [comment]
Included in PR #611. Closing issue. Thanks all!

**Comment by JuliusSweetland** [comment]
@N1Official Hi Laszlo. This looks good and is merged. I have conducted some testing and have created a pre-release of v2.31.0. Could you please test a little yourself to make sure everything is behaving as you would expect? Thanks!

Pre-release: https://github.com/OptiKey/OptiKey/releases/download/v2.31.0/OptiKeySetup-2.31.0.exe

**Comment by N1Official** [comment]
At the first start it shows me an error message and it's run in English.

After the first installation I deleted it and install it again and it worked well (The language was hungarian), but it runs twice.
![image](https://user-images.githubusercontent.com/56759208/68026758-e18bf400-fcb0-11e9-9b6f-c94e5ced0c52.png)

**Comment by JuliusSweetland** [comment]
When you complete the installer OptiKey will start automatically. Are you
perhaps starting it manually as well? Or starting OptiKey twice
accidentally?

There is a coming change which makes it impossible to accidentally start
OptiKey twice so don't worry about that

**Comment by N1Official** [comment]
Ooops 😅😅😅😅 It's definitely my fault, I'm sorry.

**Comment by JuliusSweetland** [comment]
@N1Official No problem at all

**Comment by JuliusSweetland** [comment]
@N1Official FYI this has now been released in the latest version of Optikey - v2.31.0. Thanks again for adding Hungarian!

**Comment by N1Official** [comment]
🤗🤗

Julius <notifications@github.com> (időpont: 2019. nov. 4., H, 22:38) ezt
írta:
