### ISSUE TITLE
Dental application

### ISSUE THREAD

**Issue by dentistfrankchen** [OptiKey/OptiKey#608]
Hi I'm a dental school student. I'm wondering about whether this software can be used for dental purpose.As I know, the dental procedure can sometimes be time-consuming and tedious, since the patients have to lie on the chair and cannot move for a long time which can last for hours sometimes. By using this software, patients can use their eyes to control the panel (which is above their heads) of the dental chair , so they can play games or select videos they want to watch during the whole procedure without the help from their dentists. 
I hope my issue can help you find more potential applications of this software.

**Comment by alexandre-mbm** [comment]
Hint: fund new keyboards for these applications and the author "could" reverse the proceeds to continue implementing the original use-case branch.

**Comment by dentistfrankchen** [comment]
Thanks for the hint from alenandre-mbm. I believe funding new keyboards can inspire more creative ideas.
However, when it comes to the dental application, a new keyboard might not be necessary. We can just use the original keyboard, since many patients are already familiar with the traditional version of keyboard.
I think a new keyboard may be more convenient for dental patients, but now I want to focus more  on how to integrate the current keyboard to the actual dental chairs.

**Comment by JuliusSweetland** [comment]
@dentistfrankchen It's certainly an interesting idea and should be possible. The main hurdle to overcome, I believe, would be positioning a tablet above the patient. This could be done with a hanging bracket, but there must be consideration to the problems that would be caused when you lean between the tablet and the patient's face, as they would not be able to control eye tracking or see the screen during those occlusions. I don't think this is a show stopping problem though as eye tracking would just pause.

**Comment by dentistfrankchen** [comment]
@JuliusSweetland Thanks for your reply and I'm really looking forward for new development with this software. If you make any progress with applying this software to dental care , I hope we can coordinate to introduce this technique to dental patients.

**Comment by JuliusSweetland** [comment]
I'll keep this in mind, thanks

**Comment by alexandre-mbm** [comment]
From @JuliusSweetland:
> The main hurdle to overcome, I believe, would be positioning a tablet above the patient.

http://ene.origem.net.br/blog/start/

**Comment by dentistfrankchen** [comment]
@alexandre-mbm What if we integrate the tensorflow technique to this project? It might render this software less costly and more reliable.

**Comment by alexandre-mbm** [comment]
@dentistfrankchen, have you some example by using stepper motors?
