### ISSUE TITLE
Errors in manual mode + mouse button clicks

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#618]
# How OptiKey was being used

Optikey was set up with EyeX + left mouse click for trigger. EyeX was not connected, so I went to manual mode to demo Optikey to someone.

# What the user expected to happen

Mouse position used as input while in manual mode, and left click trigger should work

# What the user actually experienced

I keep getting the error "Uh-oh! I cannot detect where you are directing your attention..." and clicking on buttons doesn't work.

# Version
Windows 10
Optikey 2.31.0

# Steps to reproduce the issue
1. Set up with eyetracker + mouse trigger
2. Turn on manual mode.

**Comment by kmcnaught** [comment]
(screen capture video available on demand)

**Comment by kmcnaught** [comment]
Looks like this is actually a dupe of https://github.com/OptiKey/OptiKey/issues/524

**Comment by JuliusSweetland** [comment]
Closing as #524 can be used to track this
