### ISSUE TITLE
Ideas for dynamic keyboard development

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#623]
Submitted via email by @AdamRoden 

1. Define 'SharedStyleGroups' for keys in the XML heading section with the override values I've added at the key level, and then each key can use the default style from settings, a 'SharedStyleGroup', or the individual overrides available today.
2. Define 'SharedTimeGroups' in the XML to enable overriding the default settings. This would be useful for the DynamicKeys. It would useful to have 'lock on time', 'activation time', and 'min time before key can be re-activated'.
3. A way to cancel a mouse action

**Comment by AdamRoden** [comment]
@JuliusSweetland 
I now have StyleGroups working, but as you know, I am in need of your assistance to get the TimeGroup dictionaries functioning.

**Comment by JuliusSweetland** [comment]
@AdamRoden Yes, I'll get back to your email later today

**Comment by AdamRoden** [comment]
@JuliusSweetland This can be closed.
