### ISSUE TITLE
Localisation: Bulgarian

### ISSUE THREAD

**Issue by sjuesju** [OptiKey/OptiKey#627]
1.Potential keyboard layout examples:
https://www.branah.com/bulgarian

Bulgarian keyboard layout:
![image](https://user-images.githubusercontent.com/4722561/69800706-b3290800-11cd-11ea-952b-0953fcb8f3a3.png)
![image](https://user-images.githubusercontent.com/4722561/69800730-bc19d980-11cd-11ea-9708-1b603e5cba6e.png)

Phonetic keyboard layout:
![image](https://user-images.githubusercontent.com/4722561/69800784-ce941300-11cd-11ea-8ee3-17c9bf70d797.png)
![image](https://user-images.githubusercontent.com/4722561/69800798-d5228a80-11cd-11ea-8525-90c8c0613273.png)

Other:
![image](https://user-images.githubusercontent.com/4722561/69800872-fe431b00-11cd-11ea-9a86-be4475343274.png)

2.Online keyboards:
https://www.branah.com/bulgarian
https://www.lexilogos.com/keyboard/bulgarian.htm
http://online-keyboard.org/Bulgarian-Phonetic-keyboard/BG-Bulgarian-Phonetic/Default/en
https://www.101languages.net/bulgarian/keyboard/
http://bg.translit.cc/

3.Transifex: https://www.transifex.com/optikey/optikey/language/bg/

4.Breakdown of (potentially) required characters:
Shift up: ючшертъуиопящьасдфгхйклѝзжцвбнм
Shift down: ЮЧШЕРТЪУИОПящьАСДФГХЙКЛѝЗЖЦВБНМ

Marks:  ̆  (combining Breve 0306)
Punctuation: §  ‐  –  —  ‘  ‚  “  „  …  ″
Symbols: №
Infrequents: ѐ  ё  ѝ  ы  ѣ  э  ѫ  Ѐ  Ё  Ѝ  Ы  Ѣ  Э  Ѫ  ̀  ̈

*We need to discuss the above to decide on the required set - there isn't space for everything and some of the above may be out of populate use*

5.Overview doc: https://r12a.github.io/app-charuse/?language=bg

6.Branch: Pending

**Comment by JuliusSweetland** [comment]
@sjuesju I have updated this issue with some basic info. The main things to decide upon now are the keyboard layout and which characters we should include. The translation on Transifex can also be started at the same time (you need to register for a free account and then request to join "Bulgarian", not "Bulgarian (Bulgaria)").

**Comment by sjuesju** [comment]
1. Phonetic keyboard layout would be great
2. https://www.branah.com/bulgarian would be ok
3. I made the needed request
4. I don't think those are needed at all:
Infrequents: ѐ ё ѝ ы ѣ э ѫ Ѐ Ё Ѝ Ы Ѣ Э Ѫ ̀ ̈

**Comment by JuliusSweetland** [comment]
I've approved your request on Transifex. Are you happy to start following
the localisation guide?

**Comment by sjuesju** [comment]
Yes, I am translating the string right now. When I finish them I will show them to my wife which is an English teacher to be sure that everything is translated correctly. Then we will continue with the procedure.
    В петък, 29 ноември 2019 г., 11:00:24 ч. Гринуич+2, Julius <notifications@github.com> написа:  
 
 I've approved your request on Transifex. Are you happy to start following
the localisation guide?

**Comment by JuliusSweetland** [comment]
Great.

**Comment by JuliusSweetland** [comment]
@sjuesju Hi - did you want to finish Bulgarian? I will close this issue unless I hear back.
