### ISSUE TITLE
Kommunicate board after modification does not displays all buttons.

### ISSUE THREAD

**Issue by Ar2rZ** [OptiKey/OptiKey#629]
# How OptiKey was being used

Added translated Kommunicate board, uploaded to the Kommunicate site and got .obz file

# What the user expected to happen

expected to be seen all buttons on communicate board

# What the user actually experienced
two buttons on the bottom row is not showing
# Version
 - Operating system and version: Windows 10
 - OptiKey version v3.0.2.0

# Steps to reproduce the issue

1. Translate Kommunicate ppt file
2. do some changes
3. create .obz file and ([https://designs.theopenvoicefactory.org/5bbd3db85db6884b4d11d77aa48bc3bf/data/pageset.obz]) download it
4. open Optikey
5. navigate to new Communicate .obz file
6. open Optikey
7. click on Communicate button
8. first page does not have two button the bottom row.

![image](https://user-images.githubusercontent.com/14283948/71845867-2a04cb00-30c1-11ea-8d3a-c33cec34793f.png)

**Comment by kmcnaught** [comment]
@joereddington, any idea?

**Comment by Ar2rZ** [comment]
i checked "broken" source files against working items, did not spotted obvious significant differences.. on Kommunicate site it displaying all buttons.... some tables still has all buttons as well...

**Comment by Ar2rZ** [comment]
@kmcnaught let me check something at home tonight. Will play around PowerPoint tables and will update this issue. might be i did something incorrect here.

**Comment by Ar2rZ** [comment]
sorted- to not get into this position need to keep buttons on the top left and top right corners, i moved them down.
PPT should looks like this:
![image](https://user-images.githubusercontent.com/14283948/71924151-56cee600-3186-11ea-849c-701dff8c0144.png)

**Comment by Ar2rZ** [comment]
and used like this:
![image](https://user-images.githubusercontent.com/14283948/71924195-6fd79700-3186-11ea-860e-e9002e042d53.png)

**Comment by Ar2rZ** [comment]
@kmcnaught i believe issue  can be closed.

**Comment by kmcnaught** [comment]
Thanks for the update :)
