### ISSUE TITLE
Kommunicate tables aren't appearing correctly on Optikey

### ISSUE THREAD

**Issue by Ar2rZ** [OptiKey/OptiKey#630]
# How OptiKey was being used

Modify Communicate tables, get new .obz file and import into Optikey trough menu

# What the user expected to happen

Kommunicate tables has to appear as designed:

.ppt main page:
![image](https://user-images.githubusercontent.com/14283948/72206493-86336a80-3486-11ea-85f6-4a5b96d8f9a0.png)
Optikey on one of PC:
![Kommunicate](https://user-images.githubusercontent.com/14283948/72206536-212c4480-3487-11ea-9e8e-ac18b1d00dd6.png)
# What the user actually experienced
no images on the buttons and instead of translated Yes to ДА, it still showing Yes. This same behaviour with all translated button, where is English images are in the place.
![ootikey](https://user-images.githubusercontent.com/14283948/72206557-4751e480-3487-11ea-852e-9552d1f75a10.png)

# Version
 - Operating system and version: Windows 10
 - OptiKey version v3.0.2

# Steps to reproduce the issue

1. Takes this ppt file
[TestingRu1.pptx](https://github.com/OptiKey/OptiKey/files/4049478/TestingRu1.pptx)

2. Uploade it to http://communikate.equalitytime.co.uk
3. Download .obz file  - https://designs.theopenvoicefactory.org/a0a0bf8720b438d78b9acb3518dd8c44/data/pageset.obz
4. Export into Optikey
5. open Kommunicate keyboard

# Any other information that helps to describe and/or reproduce the problem
Very strange is i have three pc's-  my dev pc and other two is used by my disabled child- home PC and MS Surface PRO for school. So, on my dev PC Kommunicate tables are showing images, but the button "Yes" still untranslated, but on child PC's no images for translated buttons and "Yes" is untranslated

**Comment by joereddington** [comment]
Hello all, I'm popping accross from The Open Voice Factory (which OP used to convert the PPTX file to OBZ).  

Some useful links: https://designs.theopenvoicefactory.org/a0a0bf8720b438d78b9acb3518dd8c44/ is our OBZ interpreter running on our site, and there's clearly a problem with the yes/no appearing in the wrong place. That's on us and I'll check that out properly.  I suspect that the images not appearing is a seperate issue though :(  

I like the work at lot by the way - I'm excited by a Russian Translation.

**Comment by Ar2rZ** [comment]
@joereddington if i am using old .obf from my initial test - https://drive.google.com/open?id=1cddZNdgYEFBQjtWLuxo0hjdg4oaaRj7w , i see images.. but after some changes in OpenFactory it does not show me the images any more..

**Comment by JuliusSweetland** [comment]
@Ar2rZ Can you upgrade to 3.0.3 and try again? There was an issue locating images with names containing non-latin characters that I believe is now fixed.

**Comment by Ar2rZ** [comment]
@JuliusSweetland Tested, images appearing correctly now.
![image](https://user-images.githubusercontent.com/14283948/73972045-fe6f3d80-4917-11ea-89a2-6368bea5a66f.png)
Still issue with Yes/No

**Comment by JuliusSweetland** [comment]
@Ar2rZ I believe the Yes/No buttons in the top left and top right are intentionally ignored. I suggest they will need to be included in the other 4 rows if you want them on the page.

**Comment by JuliusSweetland** [comment]
@Ar2rZ Hi Arthur. Any chance you could please email me the Russian pageset.obz file that you are using? I am compiling the existing translations to make it easier to users to find and use them. Thank you!

**Comment by JuliusSweetland** [comment]
@Ar2rZ Thanks for emailing them Arthur. Thanks.
