### ISSUE TITLE
Is it possible to import settings?

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#633]
I've been using OptiKey 2.3 and have customized the different dwell times etc- to my liking. I've done this a few times already from scratch because OptiKey has suddenly decided to forget everything. I've installed v3 but again the config was not transferred from the old version to the new one. I tried to copy the cfg file over, but v3 wouldn't start with the old cfg file.

I've stayed on v2.3, but would like to try the new dynamic keyboard enhancements.

**Comment by kmcnaught** [comment]
Hi @lsaranto, 

As far as I'm aware, a settings upgrade isn't officially supported. One thing to note is that the new dynamic keyboard enhancements are in v2.32.0, so you can try them out there. However, new features from now on will be in future 3.0 versions, so it would be worth you making the upgrade at some point.

For Optikey Pro, you could try the following steps to manually copy your settings over. This **will not work** for the other apps (Optikey Mouse, etc). And I can't guarantee it will work here, but it's worth a try - it seems to work ok on my machine. 

- Uninstall Optikey Pro (v3.x.x)
- Delete or rename the %APPDATA%\OptiKey folder (this won't affect v2 which uses %APPDATA%\JuliusSweetland)
- Reinstall Optikey Pro (v3.x.x) and launch it once
- Close Optikey Pro
- Copy user.config from v2 to v3 
- Open the (newly copied) v3 version with a text editor
- Change the two lines that contain "JuliusSweetland.OptiKey.Properties.Settings" to read "JuliusSweetland.OptiKey.Pro.Properties.Settings" instead. (make sure you keep the correct <> and </> brackets)
- Save and close the file
- Open Optikey Pro. 

It is expected that configs won't transfer from v2 to v3 without manual intervention (and this isn't officially supported currently), but settings shouldn't be lost with minor upgrades (e.g. v2.1 -> v2.2, or v3.0 -> v3.1). If / when this doesn't happen correctly for you, could you please log a bug with the version details so we can look into why that's happening?

**Comment by lsaranto** [comment]
Hi,
thanks! Looks like it worked fine. It even managed to find my dynamic keyboard in the old config file. And loaded it successfully (an earlier attempt failed and resulted in a squashed black bar).

**Comment by JuliusSweetland** [comment]
@kmcnaught Thank you Kirsty.

This is something I want to discuss with you for the future; the concept of bundling batch scripts with Optikey that can perform maintenance tasks such as:

Export setting file - for backup, sharing, etc
Import setting file
Factory reset setting file
Export latest log file (one) - for sharing (optionally as (encrypted?) zip file)
Export latest log file (all) - for sharing (optionally as (encrypted?) zip file)
etc...

I think these would be really useful for remote troubleshooting
