### ISSUE TITLE
Floating dynamic keyboards don't always remove appbar

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#635]
I've been seeing some strange behaviour, whereby if Optikey in general is docked, but a dynamic keyboard requests to be floating, it *sometimes* leaves the appbar space reserved while positioning itself in the correct floating position. I assumed this was me making a mistake in my own dynamic keyboard, but I've realised that both my new keyboard and the "Demo_Bottom" keyboard exhibit the same inconsistency - sometimes the appbar space gets cleaned up, sometimes it doesn't. It seems to be that the first time any keyboard goes floating, the appbar is cleaned up, but any subsequent times, it isn't. This gets reset by leaving the dynamic keyboards menu and going via the main menu. 

The easiest way to replicate it is:
- Launch Optikey in docked mode
- Go to dynamic keyboards
- Open "Demo_Bottom"
_the keyboard becomes floating, the appbar correctly gets cleaned up_
- Click back
- Open "Demo_Bottom" again
_Now the keyboard floats at the bottom, but the appbar space is still reserved_ 

You can also see the behaviour in this screen recording, before I found such an obvious way to replicate :)
[video](https://www.loom.com/share/a0b1a7f2e3b941e5b53fd786c1289265)

Actions shown in video and results:
- opened "Demo_bottom" : correct floating
- opened "Kingdom V1":  incorrect (docked appbar space still reserved)
- opened Alt Alpha horizontal EN"  : correct docked
- went back via main menu
- opened Kingdom V1 : correct floating
- opened Demo_Bottom" : incorrect floating

**Comment by JuliusSweetland** [comment]
@kmcnaught Thanks Kirsty. I notice something potentially related sometimes with Visual Studio incorrectly sizing to assume Optikey is still taking the appbar position at the top of the screen. Other apps are fine and resize to fullscreen, but VS is adamant that it must size to assume Optikey is still running and docked. Maybe something is wrong with the way the appbar is unregistered. A timing issue perhaps?

**Comment by kmcnaught** [comment]
@JuliusSweetland I've noticed that behaviour with VS as well (it's very annoying when you're working on a large docked keyboard!) but I don't think it's necessarily related to this behaviour. In the scenarios described above, it affects all apps, not just VS. 

Of course it could be a related bug, but my guess would be that the dynamic keyboards window-handling logic is getting in the wrong state? I have not yet looked at this bit of the code at all, but maybe @AdamRoden has some ideas?

**Comment by AdamRoden** [comment]
I don't know if my fix breaks something else, but my solution is to comment out one line of code in WindowManipulationService.

        private void UnRegisterAppBar()
        {
            Log.Info("UnRegisterAppBar called");

            //if (getWindowState() != WindowStates.Docked) return;

            var abd = new APPBARDATA();
            abd.cbSize = Marshal.SizeOf(abd);
            abd.hWnd = windowHandle;
            PInvoke.SHAppBarMessage(AppBarMessages.Remove, ref abd);
            appBarCallBackId = -1;
        }

**Comment by AdamRoden** [comment]
@JuliusSweetland 
I narrowed in on the issue, fixed it, and did a PR.
