### ISSUE TITLE
OptikeyPro Plugins not working

### ISSUE THREAD

**Issue by SamuelSnowball** [OptiKey/OptiKey#637]
# How OptiKey was being used
Trying to add existing (cmd) plugin to custom keyboard

# What the user expected to happen
Plugin executes successfully and notepad opens

# What the user actually experienced
An error occured during the handling of a key selection

# Version
OS Name:	Microsoft Windows 10 Pro
OptiKeyPro: 

# Steps to reproduce the issue

0. Enable plugins in optikey settings 
1. Click refresh plugins, the plugins will appear
2. Create custom keyboard, 
3. add the dynamic key code (as described in plugin tutorial, and as pasted below) run the code, see error.

`<DynamicKey>
     	    <Row>6</Row>
     	    <Col>4</Col>
	<Label>Notepad</Label>
	<Plugin>
		<Name>ExternalProgram</Name>
		<Method>RUN</Method>
		<Argument>
			<Name>command</Name>
			<Value>notepad.exe</Value>
		</Argument>
	</Plugin>
</DynamicKey>`

# Any other information that helps to describe and/or reproduce the problem
I also tried with full path to notepad.exe, still same error
DynamicKeys also dont appear to be working

# Screenshots
![image](https://user-images.githubusercontent.com/23612173/73254574-96ea1d00-41b6-11ea-984b-272900c6b62f.png)

**Comment by SamuelSnowball** [comment]
i have been using old dynamic keyboard and wasn;t placing keys under <content>

**Comment by JuliusSweetland** [comment]
@SamuelSnowball I'm glad this is resolved.
@AdamRoden Thank you for your help here.
