### ISSUE TITLE
OptikeyPro DynamicKeys not working 

### ISSUE THREAD

**Issue by SamuelSnowball** [OptiKey/OptiKey#638]
# How OptiKey was being used
Trying to add dynamic key to custom keyboard (as shown in tutorial)

`<DynamicKey>
	<Label>Space Loop</Label>
	<Symbol>SpaceIcon</Symbol>
	<Loop Count="0">
		<Text>&#32;</Text>
		<Wait>500</Wait>
	</Loop>
</DynamicKey>	`

# What the user expected to happen
Dynamic key executes succesfully

# What the user actually experienced
Error

# Version
Windows 10 pro
OptikeyPro

# Steps to reproduce the issue

Add code above into custom keyboard

# Any other information that helps to describe and/or reproduce the problem

# Screenshots

**Comment by AdamRoden** [comment]
@SamuelSnowball 
The code you provided works fine when copied into my keyboard. Can you provide the entire keyboard?

**Comment by SamuelSnowball** [comment]
Here is the XML: 

`
<Keyboard>
    <Name>CustomKeyboard</Name>
    <ShowOutputPanel>True</ShowOutputPanel>
    <SymbolMargin>15</SymbolMargin>
    <BorderThickness>1,1,1,1</BorderThickness>
    <Grid>
        <Rows>7</Rows>
        <Cols>11</Cols>
    </Grid>
    <Keys>
        <TextKey>
            <ShiftDownLabel>!</ShiftDownLabel>
            <ShiftUpLabel>1</ShiftUpLabel>
            <Text>1</Text>
            <Row>0</Row>
            <Col>0</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>@</ShiftDownLabel>
            <ShiftUpLabel>2</ShiftUpLabel>
            <Text>2</Text>
            <Row>0</Row>
            <Col>1</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>#</ShiftDownLabel>
            <ShiftUpLabel>3</ShiftUpLabel>
            <Text>3</Text>
            <Row>0</Row>
            <Col>2</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>$</ShiftDownLabel>
            <ShiftUpLabel>4</ShiftUpLabel>
            <Text>4</Text>
            <Row>0</Row>
            <Col>3</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>%</ShiftDownLabel>
            <ShiftUpLabel>5</ShiftUpLabel>
            <Text>5</Text>
            <Row>0</Row>
            <Col>4</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>^</ShiftDownLabel>
            <ShiftUpLabel>6</ShiftUpLabel>
            <Text>6</Text>
            <Row>0</Row>
            <Col>5</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>&#038;</ShiftDownLabel>
            <ShiftUpLabel>7</ShiftUpLabel>
            <Text>7</Text>
            <Row>0</Row>
            <Col>6</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>*</ShiftDownLabel>
            <ShiftUpLabel>8</ShiftUpLabel>
            <Text>8</Text>
            <Row>0</Row>
            <Col>7</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>(</ShiftDownLabel>
            <ShiftUpLabel>9</ShiftUpLabel>
            <Text>9</Text>
            <Row>0</Row>
            <Col>8</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>)</ShiftDownLabel>
            <ShiftUpLabel>0</ShiftUpLabel>
            <Text>0</Text>
            <Row>0</Row>
            <Col>9</Col>
        </TextKey>
         <TextKey>
            <ShiftDownLabel>+</ShiftDownLabel>
            <ShiftUpLabel>=</ShiftUpLabel>
            <Text>=</Text>
            <Row>0</Row>
            <Col>10</Col>
        </TextKey>
       <TextKey>
            <ShiftDownLabel>Q</ShiftDownLabel>
            <ShiftUpLabel>q</ShiftUpLabel>
            <Text>q</Text>
            <Row>1</Row>
            <Col>0</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>W</ShiftDownLabel>
            <ShiftUpLabel>w</ShiftUpLabel>
            <Text>w</Text>
            <Row>1</Row>
            <Col>1</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>E</ShiftDownLabel>
            <ShiftUpLabel>e</ShiftUpLabel>
            <Text>e</Text>
            <Row>1</Row>
            <Col>2</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>R</ShiftDownLabel>
            <ShiftUpLabel>r</ShiftUpLabel>
            <Text>r</Text>
            <Row>1</Row>
            <Col>3</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>T</ShiftDownLabel>
            <ShiftUpLabel>t</ShiftUpLabel>
            <Text>t</Text>
            <Row>1</Row>
            <Col>4</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>Y</ShiftDownLabel>
            <ShiftUpLabel>y</ShiftUpLabel>
            <Text>y</Text>
            <Row>1</Row>
            <Col>5</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>U</ShiftDownLabel>
            <ShiftUpLabel>u</ShiftUpLabel>
            <Text>u</Text>
            <Row>1</Row>
            <Col>6</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>I</ShiftDownLabel>
            <ShiftUpLabel>i</ShiftUpLabel>
            <Text>i</Text>
            <Row>1</Row>
            <Col>7</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>O</ShiftDownLabel>
            <ShiftUpLabel>o</ShiftUpLabel>
            <Text>o</Text>
            <Row>1</Row>
            <Col>8</Col>
        </TextKey> 
        <TextKey>
            <ShiftDownLabel>P</ShiftDownLabel>
            <ShiftUpLabel>p</ShiftUpLabel>
            <Text>p</Text>
            <Row>1</Row>
            <Col>9</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>{</ShiftDownLabel>
            <ShiftUpLabel>[</ShiftUpLabel>
            <Text>[</Text>
            <Row>1</Row>
            <Col>10</Col>
        </TextKey>
        <TextKey>
            <Symbol>TabIcon</Symbol>
            <Text>&#9;</Text>
            <Row>2</Row>
            <Col>0</Col>
	    </TextKey>
        <TextKey>
            <ShiftDownLabel>A</ShiftDownLabel>
            <ShiftUpLabel>a</ShiftUpLabel>
            <Text>a</Text>
            <Row>2</Row>
            <Col>1</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>S</ShiftDownLabel>
            <ShiftUpLabel>s</ShiftUpLabel>
            <Text>s</Text>
            <Row>2</Row>
            <Col>2</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>D</ShiftDownLabel>
            <ShiftUpLabel>d</ShiftUpLabel>
            <Text>d</Text>
            <Row>2</Row>
            <Col>3</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>F</ShiftDownLabel>
            <ShiftUpLabel>f</ShiftUpLabel>
            <Text>f</Text>
            <Row>2</Row>
            <Col>4</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>G</ShiftDownLabel>
            <ShiftUpLabel>g</ShiftUpLabel>
            <Text>g</Text>
            <Row>2</Row>
            <Col>5</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>H</ShiftDownLabel>
            <ShiftUpLabel>h</ShiftUpLabel>
            <Text>h</Text>
            <Row>2</Row>
            <Col>6</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>J</ShiftDownLabel>
            <ShiftUpLabel>j</ShiftUpLabel>
            <Text>j</Text>
            <Row>2</Row>
            <Col>7</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>K</ShiftDownLabel>
            <ShiftUpLabel>k</ShiftUpLabel>
            <Text>k</Text>
            <Row>2</Row>
            <Col>8</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>L</ShiftDownLabel>
            <ShiftUpLabel>l</ShiftUpLabel>
            <Text>l</Text>
            <Row>2</Row>
            <Col>9</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>}</ShiftDownLabel>
            <ShiftUpLabel>]</ShiftUpLabel>
            <Text>]</Text>
            <Row>2</Row>
            <Col>10</Col>
        </TextKey>
	    <ActionKey>
            <Row>3</Row>
            <Col>0</Col>
            <Symbol>ShiftIcon</Symbol>
            <Action>LeftShift</Action>
    	</ActionKey>
        <TextKey>
            <ShiftDownLabel>Z</ShiftDownLabel>
            <ShiftUpLabel>z</ShiftUpLabel>
            <Text>z</Text>
            <Row>3</Row>
            <Col>1</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>X</ShiftDownLabel>
            <ShiftUpLabel>x</ShiftUpLabel>
            <Text>x</Text>
            <Row>3</Row>
            <Col>2</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>C</ShiftDownLabel>
            <ShiftUpLabel>c</ShiftUpLabel>
            <Text>c</Text>
            <Row>3</Row>
            <Col>3</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>V</ShiftDownLabel>
            <ShiftUpLabel>v</ShiftUpLabel>
            <Text>v</Text>
            <Row>3</Row>
            <Col>4</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>B</ShiftDownLabel>
            <ShiftUpLabel>b</ShiftUpLabel>
            <Text>b</Text>
            <Row>3</Row>
            <Col>5</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>N</ShiftDownLabel>
            <ShiftUpLabel>n</ShiftUpLabel>
            <Text>n</Text>
            <Row>3</Row>
            <Col>6</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>M</ShiftDownLabel>
            <ShiftUpLabel>m</ShiftUpLabel>
            <Text>m</Text>
            <Row>3</Row>
            <Col>7</Col>
        </TextKey>
        <ActionKey>
            <Row>3</Row>
            <Col>8</Col>
	        <Action>BackOne</Action>
	        <Symbol>BackOneIcon</Symbol>
        </ActionKey>
        <ActionKey>
            <Row>3</Row>
            <Col>9</Col>
	        <Action>BackMany</Action>
	        <Symbol>BackManyIcon</Symbol>
        </ActionKey> 
        <TextKey>
            <ShiftDownLabel>~</ShiftDownLabel>
            <ShiftUpLabel>`</ShiftUpLabel>
            <Text>`</Text>
            <Row>3</Row>
            <Col>10</Col>
        </TextKey>
        <ActionKey>
            <Row>4</Row>
            <Col>0</Col>
	        <Action>LeftCtrl</Action>
	        <Label>Ct</Label>
        </ActionKey>
        <ActionKey>
            <Row>4</Row>
            <Col>1</Col>
	        <Action>Escape</Action>
	        <Label>Es</Label>
        </ActionKey>
        <TextKey>
             <ShiftDownLabel>"</ShiftDownLabel>
            <ShiftUpLabel>'</ShiftUpLabel>
            <Text>'</Text>
            <Row>4</Row>
            <Col>2</Col>
        </TextKey> 
        <TextKey>
	        <ShiftDownLabel>&lt;</ShiftDownLabel>
            <ShiftUpLabel>,</ShiftUpLabel>
            <Text>,</Text>
            <Row>4</Row>
            <Col>3</Col>
        </TextKey>
	    <TextKey>
            <Symbol>SpaceIcon</Symbol>
            <Text>&#32;</Text>
            <Row>4</Row>
            <Col>4</Col>
	        <Width>1</Width>
	    </TextKey>
        <TextKey>
            <ShiftDownLabel>&gt;</ShiftDownLabel>
            <ShiftUpLabel>.</ShiftUpLabel>
            <Text>.</Text>
            <Row>4</Row>
            <Col>5</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>:</ShiftDownLabel>
            <ShiftUpLabel>;</ShiftUpLabel>
            <Text>;</Text>
            <Row>4</Row>
            <Col>6</Col>
        </TextKey>
        <TextKey>
            <ShiftDownLabel>?</ShiftDownLabel>
	        <ShiftUpLabel>/</ShiftUpLabel>
	        <Text>/</Text>
            <Row>4</Row>
            <Col>7</Col>
        </TextKey> 
        <TextKey>
            <ShiftDownLabel>|</ShiftDownLabel>
	        <ShiftUpLabel>\</ShiftUpLabel>
	        <Text>\</Text>
            <Row>4</Row>
            <Col>8</Col>
        </TextKey> 
        <TextKey>
            <ShiftDownLabel>_</ShiftDownLabel>
	        <ShiftUpLabel>-</ShiftUpLabel>
	        <Text>-</Text>
            <Row>4</Row>
            <Col>9</Col>
        </TextKey>  
        <ActionKey>
            <Row>4</Row>
            <Col>10</Col>
            <Symbol>MenuIcon</Symbol>
            <Action>MenuKeyboard</Action>
        </ActionKey>
	    <ActionKey>
            <Action>ArrowUp</Action>
            <Symbol>UpArrowKeyIcon</Symbol>
     	    <Row>5</Row>
     	    <Col>0</Col>
	    </ActionKey>
        <ActionKey>
            <Action>ArrowDown</Action>
            <Symbol>DownArrowKeyIcon</Symbol>
            <Row>5</Row>
            <Col>1</Col>
        </ActionKey>
        <ActionKey>
            <Action>ArrowLeft</Action>
            <Symbol>LeftArrowKeyIcon</Symbol>
            <Row>5</Row>
            <Col>2</Col>
        </ActionKey>
        <ActionKey>
            <Action>ArrowRight</Action>
            <Symbol>RightArrowKeyIcon</Symbol>
            <Row>5</Row>
            <Col>3</Col>
        </ActionKey>
        <ActionKey>
            <Action>PgUp</Action>
            <Label>PU</Label>
            <Row>5</Row>
            <Col>4</Col>
        </ActionKey>
        <ActionKey>
            <Action>PgDn</Action>
            <Label>PD</Label>
            <Row>5</Row>
            <Col>5</Col>
        </ActionKey>
        <TextKey>
            <Symbol>EnterIcon</Symbol>
            <Text>&#13;</Text>
            <Row>5</Row>
            <Col>6</Col>
        </TextKey>
        <ActionKey>
            <Action>MouseMoveAndLeftClick</Action>
            <Symbol>MouseLeftClickIcon</Symbol>
            <Row>5</Row>
            <Col>7</Col>
        </ActionKey>
        <ActionKey>
            <Action>MouseMoveAndRightClick</Action>
            <Symbol>MouseRightClickIcon</Symbol>
            <Row>5</Row>
            <Col>8</Col>
        </ActionKey>
	   <ActionKey>
            <Row>5</Row>
            <Col>9</Col>
            <Symbol>MouseLeftDoubleClickIcon</Symbol>
            <Action>MouseMoveAndLeftDoubleClick</Action>
       </ActionKey>
       <ActionKey>
            <Row>5</Row>
            <Col>10</Col>
            <Symbol>MouseIcon</Symbol>
            <Action>MouseKeyboard</Action>
	    </ActionKey>
		
		
        <ActionKey>
            <Row>6</Row>
            <Col>0</Col>
	        <Action>LeftAlt</Action>
	        <Label>Al</Label>
        </ActionKey> 
		
	    <ActionKey>
            <Action>Insert</Action>
            <Label>Ins</Label>
     	    <Row>6</Row>
     	    <Col>1</Col>
	    </ActionKey>
		
	    <ActionKey>
            <Action>Delete</Action>
            <Label>Del</Label>
     	    <Row>6</Row>
     	    <Col>2</Col>
	    </ActionKey>

		<TextKey>         
            <Text>sam.snowball@hotmail.co.uk</Text>
     	    <Row>6</Row>
     	    <Col>3</Col>
			<Label>email</Label>
	    </TextKey>
		
<DynamicKey>
     	    <Row>6</Row>
     	    <Col>4</Col> <Label>Space Loop</Label> <Symbol>SpaceIcon</Symbol> <Loop Count="0"> <Text>&#32;</Text> <Wait>500</Wait> </Loop> </DynamicKey>
    </Keys>
</Keyboard>
`

**Comment by SamuelSnowball** [comment]
XML keyboard is here: https://pastebin.com/7WfGgCY8

**Comment by AdamRoden** [comment]
@SamuelSnowball 
The issue is that due to the drastic code changes involved in the new Dynamic Keys, they were purposefully made to only work with the new Dynamic Keyboard. Instead of enclosing the keys within the tag "Keys", it encloses them within the tag "Content". The first examples below will work, but the second will not. To use the new features you need to rewrite all the keys in your keyboard. Sorry. :-(

> 
    <Content>
	<DynamicKey> <Label>Space Loop</Label> <Symbol>SpaceIcon</Symbol> <Loop Count="0"> <Text>&#32;</Text> <Wait>500</Wait> </Loop> </DynamicKey>
    </Content>

> 
    <Keys>
	<DynamicKey> <Label>Space Loop</Label> <Symbol>SpaceIcon</Symbol> <Loop Count="0"> <Text>&#32;</Text> <Wait>500</Wait> </Loop> </DynamicKey>
    </Keys>

**Comment by SamuelSnowball** [comment]
ok, is the documentation updated to say this? if so this can be closed, and/or a new issue opened to update the docs

**Comment by SamuelSnowball** [comment]
the docs are up to date to reflect this - my bad
