### ISSUE TITLE
A key to dynamically add/remove words from a keyboard

### ISSUE THREAD

**Issue by SamuelSnowball** [OptiKey/OptiKey#642]
**Background**

When using optikey I often find myself repeatingly typing the same words (optikey, config, my name etc..) However these words are different depending on what I'm doing that day, so there's too much effort creating dynamic keyboards for each, as I don't know what words I'll be using tomorrow or in a week from now. For example today I have typed config using optikey at least 10 times but I'm too lazy to add it to a dynamic keyboard.

**Describe the solution you'd like**

It would be good to just type the word once at the start of a day, and have a key to dynamically add the last typed word to the keyboard as a new key (by getting the text from the scratchpad) - so i no longer have to type that word manually for the duration of the day. This feature would let you build up a selection of words that you are frequently using that day, without having to mess with dynamic keyboard files.

The feature would append the new key as XML to the currently used keyboard within the roaming directory. It would have to dynamically reload the keyboard for every new word added and removed (as currently you have to go back to the menu, and back into the dynamic keyboard for the change to appear). 

**Describe alternatives you've considered**

1. Typing out the same words again and again - this is very slow and annoying
2. Having multiple keyboards for different uses, however - you have to keep creating new keyboards which perhaps you will only use once.
3. Using the add to dictionary feature, however you still have to start typing out the word enough for the correct prediction to show. 

I have started to develop this plugin for use in dynamic keyboards and will post it as a plugin when its ready. However if others are interested it could be added as a toggleable feature, such as the copy all from scratchpad key in the main codebase.

**Comment by JuliusSweetland** [comment]
@SamuelSnowball Hi Sam. This sounds useful. I would suggest that the dynamic keyboard is created  with placeholder keys, which this new functionality (shown as a new key with a new function key value for adding word to dynamic keyboard frequent words keys) populates. I see it working as the user types a word, selects the add frequent word key, a confirmation is displayed using the last typed word, if the user selects then the next free frequent words key is populated. If all frequent words keys are populated then the first is populated in a circular fashion (so you'd need to keep track of the last frequent words key that had its value set so the next key populated is the next key along, etc).

**Comment by SamuelSnowball** [comment]
> @SamuelSnowball Hi Sam. This sounds useful. I would suggest that the dynamic keyboard is created with placeholder keys, which this new functionality (shown as a new key with a new function key value for adding word to dynamic keyboard frequent words keys) populates. I see it working as the user types a word, selects the add frequent word key, a confirmation is displayed using the last typed word, if the user selects then the next free frequent words key is populated. If all frequent words keys are populated then the first is populated in a circular fashion (so you'd need to keep track of the last frequent words key that had its value set so the next key populated is the next key along, etc).

That all sounds good, I was thinking of having a plugin option pointing to a dynamic keyboard that the user wants this functionality added to. This would let them use their existing keyboard layout with the plugin.

The main issue I'm having is refreshing the dynamic keyboard xml file once the new keys are added. I have found that when a dynamic keyboard is selected the ProcessChangeKeyboardKeyValue method is called, however this is a private method. It builds the dynamic keyboard object. It is called by a subscription setup in the constructor. Really, I just want the content reloaded as opposed to rebuilding the entire object.

On line 301 of MainViewModel.ServiceEventHandlers there is this code "Keyboard = newDynKeyboard;" which I believe calls set, which calls DynamicKeyboard OnEnter() which calls SetupKeyboardLayout then uses windowManipulationService. Which I think is how the view is updated, but I am a bit lost..

Any ideas how I can update the keyboard, from the plugin? Or would this require changes to the main code base? and is this out of scope?

**Comment by JuliusSweetland** [comment]
@SamuelSnowball Hi Sam. I am happy for the plugin to access the MainViewModel if that is required. Can you clarify how the plugin would work with an existing dynamic keyboard? Do you mean with the plugin enabled there would be:

1.Additional settings in the management console which allow you to determine where the new keys should be added, and how many there are (e.g. top/bottom row, 5 keys), and where the AddKey button should be injected?
2.A new AddKey key displayed somewhere in the dynamic keyboard
3.The AddKey would trigger the MainViewModel.Keyboard being modified to add or update the frequent words keys.

Am I understanding that correctly?

**Comment by SamuelSnowball** [comment]
> @SamuelSnowball Hi Sam. I am happy for the plugin to access the MainViewModel if that is required. Can you clarify how the plugin would work with an existing dynamic keyboard? Do you mean with the plugin enabled there would be:
> 
> 1.Additional settings in the management console which allow you to determine where the new keys should be added, and how many there are (e.g. top/bottom row, 5 keys), and where the AddKey button should be injected?
> 2.A new AddKey key displayed somewhere in the dynamic keyboard
> 3.The AddKey would trigger the MainViewModel.Keyboard being modified to add or update the frequent words keys.
> 
> Am I understanding that correctly?

Answering questions 1 and 2, I was originally thinking that with the plugin enabled, a new row of keys would be added to the bottom of the file which includes the addKey, just to keep things simple really - but perhaps a more customizable version would be better.
Answering question 3, if a "do you wish to addKey" dialog box is to be added, then the MainViewModel.Keyboard would have to be modified to do this (as would have to swap the keyboard to a YesNoQuestion object), but it has to be modified anyway to update the keyboard with the new key. So yes it would trigger MainViewModel.Keyboard to be modified, I can't see any other way.

**Comment by JuliusSweetland** [comment]
@SamuelSnowball Ok I actually prefer the simpler version of just adding a new row - at least to start with. We can add customisation options later as required.

I think whether the user is asked whether to add the text every time should be a setting as some users will want to just add the key regardless.

One more thought - take a look at the logic which scans the scratchpad text for new dictionary words when the user selects AddToDictionary as there is some logic in there to handle different casing of words. For example the user might start a new sentence with "Hello", but they actually only want "hello" added as a frequent key. If they then had a key with "hello" would this be cased correctly when used to start a new sentence? I think it would be, but could you please test to check?

**Comment by kmcnaught** [comment]
@SamuelSnowball, I was wondering if you'd tried hooking up Optikey to the Presage prediction engine? In my (limited) experience typing with Presage, I found it was much more sensitive to 'recentness' of words than the built in Optikey prediction. It's possible that it would naturally bubble up the words that you're using multiple times that day. I haven't used it for long enough to tell how biased it is to recent words even after you've used it for a long time, but it could be worth a try?

If this effect does reduce after lots of presage training, it's possible we could look at exposing the Presage Recency predictor as opposed to (or in addition to) the default Smoothed NGram predictor. Perhaps instead of having dynamic keys that are explicitly populated with 'recently saved' words, you could have an extra prediction row, which contains 'predictions based on recency'. This would expand the number of words you could have easy access to, and you wouldn't need to explicitly save any words, but you would need to type the first letter each time. 

@JuliusSweetland a related thought I've often had is that it would be really nice to be able to set the word prediction 'context', e.g. by loading a small dictionary of relevant words/sentences that take precedence over the main dictionary. This could work really well for people who are graduating from having pagesets with prepared responses in anticipation of a conversation, to being able to generate/tweak responses on the fly. You could imagine loading a corpus of sentences (responses to questions you think you'll be getting) but then while conversing you type out full unconstrained sentences, but with _very relevant_ predictions coming up. I mainly mention this as food for thought.

**Comment by JuliusSweetland** [comment]
@kmcnaught Great suggestion re:Presage

I also like the idea of priming the dictionary. I'll add this to the todo list along with the maintenance batch scripts.

**Comment by SamuelSnowball** [comment]
@kmcnaught Presage does what i want! didnt know it existed, thanks for the docs
@JuliusSweetland im happy to close this now ive found presage - unless you think this could still be useful?

**Comment by JuliusSweetland** [comment]
That's good news. I'm happy to generally go down the path of least
resistance so let's leave the new development for now.
