### ISSUE TITLE
v2 dynamic keyboards in v3

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#644]
This is something I noticed that you might want to look in to. Although this is relevant only during the migration from v2 to v3.

In the management console, I had the dynamic keyboards folder set to v2 folder. I had the startup keyboard set to v2 dynamic keyboard from that folder.

When Optikey v3 starts, it loads the dynamic keyboard just fine. But when you go to dynamic keyboards menu in Optikey and select the same keyboard, it fails to load that same file

**Comment by AdamRoden** [comment]
@lsaranto Please attach a sample keyboard that has the issue.

**Comment by lsaranto** [comment]
Here is the file. I had to change the extension to be able to attach it.
[FinnishKeyboard.xml.txt](https://github.com/OptiKey/OptiKey/files/4227436/FinnishKeyboard.xml.txt)

There is a strange leftover <Height> element. But the outcome is the same with or without it.

**Comment by AdamRoden** [comment]
In Optikey v3 we added many new options, one of which was the ability to set the height as an absolute pixel value or as a percentage of the screen. To make your keyboard compatible with v3 you need to change the height from '24' to '24%'.

**Comment by lsaranto** [comment]
The point I was trying to make, was that you most likely have one routine to read the dynamic keyboard file. Yet, there are two different outcomes:
1) When OptiKey (v3) starts, it is able to correctly read, process and display the "flawed" file.
2) When Optikey (v3) is already running, if the user loads the same file from the dynamic keyboards menu, the keyboard is displayed "incorrectly" (or at least differently).

I've already built a new keyboard file to take the benefit of the new features.added in v3.

All is good. Whether you want to look into this is your call. Like I said in the first post: This problem will go away on its own when nobody is using v2 anymore.

**Comment by AdamRoden** [comment]
@lsaranto I see what you mean now. If you have OptiKey configured to start at a Dynamic Keyboard it does not apply the size and position values from the file, and instead uses the values saved in the Management Console. That's a good catch and something we need to fix.
