### ISSUE TITLE
Add an off-screen key that triggers a popup menu

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#651]
I've played with this a bit and I know that I can position a dynamic keyboard to be partially outside of the screen and I am still able to activate the off-screen keys using OptiKey with a Tobii 4c. 

My idea is that OptiKey would run a second child window positioned off-screen, and when triggered it would change to a small menu keyboard on the center of the screen with a set of keys, (Sleep, Menu, Resize, etc..) that would impact the parent on-screen keyboard. After performing an action the second window would return to its off-screen position.

**Comment by JuliusSweetland** [comment]
@AdamRoden This sounds a bit like the Tobii context menu stuff. Is that what you are picturing here?

**Comment by AdamRoden** [comment]
@JuliusSweetland Yes, that is what I was thinking. I would make the built-in popup have a sleep key, and allow a dynamic keyboard to override that with additional keys.

**Comment by JuliusSweetland** [comment]
Would there be any code changes or do you think it can be achieved with the
dynamic keyboard functionality as it is?

**Comment by AdamRoden** [comment]
I suppose a rough version could be achieved with existing functionality, but doing it properly would require new code.

**Comment by JuliusSweetland** [comment]
Sounds interesting either way

**Comment by JuliusSweetland** [comment]
Closing until you are ready to start discussing the context menu you've mentioned to me recently (I'm having a bit of a clean up)

**Comment by bigmutty** [comment]
That sounds awesome! It would be cool if the popup would close after a set time.
