### ISSUE TITLE
Dynamic keyboard width, height and offsets not honored

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#653]
Looks like there are still some issues when parsing the keyboard file. When OptiKey starts and loads a dynamic keyboard, it does not respect the width, height and offsets tags. Only after you reload the same file from the Dynamic keyboard menu, they are honored.

[FinnishKeyboard.xml.txt](https://github.com/OptiKey/OptiKey/files/4302173/FinnishKeyboard.xml.txt)

**Comment by AdamRoden** [comment]
@lsaranto What version are you running? The keyboard you provided seems fine when I set it as the startup keyboard in v3.0.4.0

**Comment by lsaranto** [comment]
I was using 3.0.3. I now upgraded to 3.0.4.0 and the issue is indeed gone. Sorry.

There was a time when I updated everything just for the sake of updating. But I was young and energetic back then. :smiley:

**Comment by JuliusSweetland** [comment]
@AdamRoden @lsaranto Very cool to see things being raised and resolved in the background. Thanks to you both.
