### ISSUE TITLE
How can I set repeat rate and delay globally?

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#654]
Do I need to define a KeyGroup element in the header and then add it to every single key? There's no easier way? No default, hidden KeyGroup that is automatically included in keys unless overridden?

What might have been the repeat values before v3.0.4? Not sure I want it this fast in my default keyboard. I understand why it was added, and it's surely useful in certain situations.

**Comment by AdamRoden** [comment]
@lsaranto Yes, you need to define a KeyGroup element in the header and then add it to every single key.
The repeat value before 3.0.4 did not exist, so completion time was used every time.
Check out how I'm using them in my keyboard. Arrows and backspace repeat fast. Everything else is normal.
[AR16-Qwerty.xml.txt](https://github.com/OptiKey/OptiKey/files/4302604/AR16-Qwerty.xml.txt)

**Comment by lsaranto** [comment]
Well, since I need to add the KeyGroup element to all keys anyway, this isn't too bad.

What I didn't quite understand from the wiki, can a key have multiple KeyGroup elements?

**Comment by AdamRoden** [comment]
The answer is yes, and I'll try to make the wiki more clear based on your comments.

**Comment by JuliusSweetland** [comment]
@AdamRoden Thanks Adam. Closing this issue.
