### ISSUE TITLE
dynamic keyboard  -> menu window resize issue.

### ISSUE THREAD

**Issue by maartee** [OptiKey/OptiKey#658]
Hi!
Recently, I was trying new OptiKey Pro. I really enjoy  the improvements!
However, there's newly introduced mouse/dynamic keyboard/menu window resize issue.
I've tried on more versions of OptiKey Pro, on two computers. In OptiKey 2.x, it's working fine.

Current behavior:
selecting menu key on dynamic keyboard results in menu size shrinked to mouse keyboard (that makes OptiKey unusable with keys too small to use or see icons)

Expected behavior:
after we switch to menu from dynamic keyboard, the size of OptiKey stays the same.

Steps to reproduce: 
1. Switch to dynamic keyboard ( e.g. ALT ALPHA HORIZONTAL EN )
2. From dynamic keyboard, select mouse keyboard 
3. If mouse keyboard is in extended mode, switch to simple/normal mode (collapse dock) 
4. Select 'Back' to return to dynamic keyboard
5. Select 'menu' 
Your OptiKey window is now the size of collapsed mouse keyboard and stays small until you restart optikey.

**Comment by JuliusSweetland** [comment]
@maartee Hi Martin, which version of Optikey Pro are you experiencing this with? There have been a number of quick releases which may have already addressed this.

**Comment by maartee** [comment]
It's fresh install of 3.0.4 version from official link. I checked the changes in pre-3.0.5 and because I didn't find any size issue targeted, I created this.
Can perhaps someone else try to replicate the issue ?

**Comment by AdamRoden** [comment]
@maartee Thanks. I reproduced it and it will be easy to fix.

**Comment by JuliusSweetland** [comment]
@AdamRoden Thanks Adam
@maartee Martin - Adam has provided a fix for this issue. It will be included when v3.0.5 is released. I will close this issue for now, but please look out for the new release.
