### ISSUE TITLE
Dynamic key virtual keycodes incorrect for characters requiring modifiers

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#667]
I was trying to make a dynamic keyboard which would press "<" and ">" for a game. I found it gave me "," and "." instead. 

I've tracked it down to the method `KeyboardOutputService.ProcessSingleKeyPress` which calls `PInvoke.VkKeyScanEx` to get a virtual key code, but doesn't then do anything with the modifier information returned. 

I'll open a PR with a fix.

@AdamRoden @JuliusSweetland , I *think* the desired behaviour is for dynamic keyboards to respect the global Optikey modifier state, i.e. if I lock the Shift button down in Optikey, it *should* affect my dynamic keys, and turn a "," into a "<". Do you agree? For symbols this could be a bit unexpected, but it general it seems reasonable that modifier keys should work with dynamic keyboards.

**Comment by JuliusSweetland** [comment]
I agree that if the output character requires modifiers that they should be
pressed (or released) as necessary. To be clear I don't think modifiers
pressed outside of a keyboard should affect the current keyboard, unless
those keys exist on the current keyboard and are pressed. I don't think
that's what you are suggesting though.

Am I correct in thinking that your PR will just ensure that the required
modifier keys are down to be able to output the requested character and
then released afterwards (if not locked down already)?

**Comment by kmcnaught** [comment]
Sorry I actually realised I'd misunderstood something in the existing modifier logic. 

>  just ensure that the required
modifier keys are down to be able to output the requested character and
then released afterwards (if not locked down already)?

Yes, this is what it should be doing.

**Comment by JuliusSweetland** [comment]
Cool. I'm surprised it isn't doing that. From memory the modifiers should
be checked and executed as required. There's some logic in the Keyboard
output service

**Comment by kmcnaught** [comment]
Yeah, but at some point I think I half-copied your correct solution and missed some of the logic out...

**Comment by kmcnaught** [comment]
to be precise on how modifiers work now on a dynamic keyboard: 
1) if your character requires a modifier, and the modifier *isn't* held down within optikey, it holds it down temporarily while executing the requested key [press/release/prese-and-release] and then releases the modifier
2) if your character requires a modifier, and the modifier is already held down, it just does the keypress and leaves the modifier on (which gives the correct result). 
3) if your character does not require a modifier, but the modifier is held down, then the character will naturally be 'modified'. i.e. a dynamic key that outputs "." will output ">" if you also have a shift key locked down. This is the bit I'm not 100% sure of (but it seems reasonable)

What I don't know right now is whether modifier keys are ever left in a locked state after changing keyboards. I assume not? If they were, that would obviously work badly with (3)

**Comment by JuliusSweetland** [comment]
From memory modifiers should be released when switching from normal to a
dynamic keyboard, but I'd need to check that

**Comment by AdamRoden** [comment]
There are 3 key states: Up, Down, and LockedDown.
Standard keys go down and up when triggered.
Modifiers go down when triggered and stay down until a non-modifier is triggered. At that point all keys not LockedDown are released to 'Up'.
If a key is LockedDown it will stay down when other keys are pressed. 
If you trigger a LockedDown key, use a 'KeyUp' command, or change keyboards, then the LockedDown key is released.
All keys get released and changed to an 'up' state when you change keyboards. 

OptiKey only tracks its own key states. If you have another device or software sending keystrokes to your device, OptiKey will not be aware of those keystrokes.

**Comment by JuliusSweetland** [comment]
Exactly that. What Adam said.

**Comment by kmcnaught** [comment]
I think we're all in agreement then, and the PR gives the desired behaviour.

**Comment by JuliusSweetland** [comment]
Great thanks. I'll take a look as soon as possible

**Comment by JuliusSweetland** [comment]
@kmcnaught @AdamRoden FYI I am going to prepare a new pre-release as soon as this PR (https://github.com/OptiKey/OptiKey/pull/668) is ready to go.

Kirsty if you have a moment I've put a comment on that PR for you. Thanks.

**Comment by kmcnaught** [comment]
@JuliusSweetland I'm on it now...
