### ISSUE TITLE
Mouse magnification step appears on wrong monitor sometimes

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#670]
Yes, I know we don't _officially_ support multimonitor setups, but we're close enough that I think this bug is worth attempting to fix at some point (happy for it to go on my stack but I might not get round to it for a while). 

Setup is: 
- two monitors, the right hand monitor is primary, and both Tobii eye tracking and Optikey Pro (3.0.5) are running on the right hand primary monitor. 
- Mouse magnification is turned on, with magnification destination size 60% (this might be bigger than default?) 
- I use "left click at point" and the magnified area _sometimes_ appears on the left hand monitor, which I am unable to track gaze on. 

video demo here:
https://www.youtube.com/watch?v=ysc6Yw6IoSU&feature=youtu.be

**Comment by kmcnaught** [comment]
I had a brief look at this last week, so I'm commenting mainly as a message to my future self...

In `MagnifyPopup::SetSizeAndPosition`, there are a bunch of coordinate transforms making use of `Window::GetTransformFromDevice`. I haven't been able to pinpoint where any of these numbers are wrong, but I suspect they are (with my particular monitor setup at least!).

The behaviour I'm observing is that if my first click (to pick the magnified area) is at the left edge of the screen, but in the middle vertically, it gets positioned correctly. If I move up toward the top of the screen, everything is fine until it gets to the point where the magnifypopup ends up butting up against the top of the screen. If I go any higher, the popup gets requested "too high" and then gets auto-pushed onto the left monitor. This suggests that the inputs into this bit of logic are wrong:

```
    if (pointInWpfCoords.Y + (height / 2d) > screenHeight)
        distanceFromTopBoundary = screenHeight + (height / 2d);
    else
        distanceFromTopBoundary = pointInWpfCoords.Y - (height / 2d);
```

It's also worth noting that my monitors are setup so that the left (secondary) monitor is higher resolution than the right (primary) monitor, *and* it's a high-DPI Surface Pro. So either it's a simple issue of somewhere overestimating the screen height and allowing the popup to overflow, or it's a trickier issue with combined high-DPI / normal-DPI screens. 

Next steps:
- Interrogate the logic above again, see if I can find any numbers that are wrong!
- Look into f8505c2 in case there's an interaction there

**Comment by bigmutty** [comment]
I found a temporary workaround. If you enable "Show magnifier window at center of screen," the issue is nonexistent.

**Comment by JuliusSweetland** [comment]
@bigmutty Thanks Daryl. Good workaround, but I think the original bug remains and should be addressed at some point. I'll keep this issue open for now.
