### ISSUE TITLE
Dynamic Keyboards "BackReturnsHere" attribute is wrong

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#672]
Currently with a `ChangeKeyboard` action, the behaviour is incorrect:

`default`: returns to this keyboard (correct)
`BackReturnsHere="true"`: does _not_ return to this keyboard (wrong)
`BackReturnsHere="false"`: [Edit typo!] _does_ return to this keyboard (wrong)

I'll raise a PR. 

Here's an example set of keyboards to demo.
[test_keyboards.zip](https://github.com/OptiKey/OptiKey/files/4580753/test_keyboards.zip)

**Comment by JuliusSweetland** [comment]
@kmcnaught Fix merged and will be part of v3.0.5. Thanks.

**Comment by AdamRoden** [comment]
@JuliusSweetland @kmcnaught Closed?
