### ISSUE TITLE
Dynamic keyboard appbar persists after leaving keyboard

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#685]
If Optikey starts out in floating mode, and is put in docked mode by a dynamic keyboard, then the appbar space never gets freed up.

Present in 3.0.5.0 and latest code.

## To replicate
- Put Optikey Pro in a floating state.
- Restart Optikey Pro
- Open the attached keyboard which docks at the top of the screen
- Click "Back"
- Optikey reverts to a floating state, but the space reserved for the appbar remains. 

See https://www.loom.com/share/bd26703fb81448498916b61d98ae715c for demo

This doesn't seem to happen when Optikey starts out in a docked state, or when transitioning from a docked default state to a floating dynamic state, though I haven't thoroughly tested all possible transitions.

@AdamRoden 

[SampleDockedKeyboard.zip](https://github.com/OptiKey/OptiKey/files/4804221/SampleDockedKeyboard.zip)

**Comment by AdamRoden** [comment]
My fix for #691 will also fix this. They are linked.
