### ISSUE TITLE
some text too small

### ISSUE THREAD

**Issue by liuxilu** [OptiKey/OptiKey#686]
## How OptiKey was being used
Normally used.
## What the user expected to happen
Big texts.
## What the user actually experienced
Text small, some even hard to see.
## Version
 - Operating system and version: 1903
 - OptiKey version: v3.0.5.0
## Steps to reproduce the issue
Open OptiKey and gaze at a button.
## Any other information that helps to describe and/or reproduce the problem
None.
## Screenshots
<details>

![example](https://user-images.githubusercontent.com/53636947/86126708-60bc1b00-bb11-11ea-8304-4e0f85f7ec9c.png)
![example](https://user-images.githubusercontent.com/53636947/86126463-f4411c00-bb10-11ea-8661-e9b74e10b742.png)
</details>

**Comment by JuliusSweetland** [comment]
@liuxilu Thank you for the report. Optikey attempts to display all keys and text in a uniform way, which means sometimes longer text on some keys causes the shared font size to be reduced on other keys. This is a difficult thing to balance. The easiest thing I can suggest is that you enlarge Optikey so that the keys and their text are also larger.

**Comment by liuxilu** [comment]
Fine... Then can you add an option to adjust the shared size or just point me out the line of code where the text size is calced and set?

**Comment by JuliusSweetland** [comment]
@liuxilu Text sizing is automatic based on the text in all keys within the same "SharedSizeGroup". For example: https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey.Core/UI/Views/Keyboards/Common/Mouse.xaml#L73

Every key, on that keyboard, with the same SharedSizeGroup of "KeyWithSymbolAndText" will end up with the same font size. If any text in that group is long, e.g. you have these keys:

"KEY1"
"KEY2"
"KEY WITH WIDE TEXT"

Then scaling the 3rd key's text would result in the other keys being reduced to match.

The only easy ways around this would be:

1.Create a dynamic keyboard with your own sizing groups: https://github.com/Optikey/Optikey/wiki/Creating-and-Using-Dynamic-Keyboards

2.Change the text using on keys so there isn't any unnecessarily long text in a group. This would be considered a bug fix so I can help if you find an incorrectly long string in a group.

3.Change the hard coded key groups in the source code and then rebuild. If you go down this route then I would need to help you to compile your changed code, unless you are happy to lose Optikey's ability to float over everything, in which case you can build it yourself.

**Comment by liuxilu** [comment]
Thank you for your detailed info! And I'd like to say that "move by x pixels" and "scroll by x clicks" are actually too long.
I see a large padding in the key, can you tell me where could I change that?

**Comment by JuliusSweetland** [comment]
@liuxilu Hi, I have had a play and I can increase the text size on the expanded mouse keyboard, but the size & position keyboard is about as good as it can be. Although the text is not as large as it could be, I am happy that the symbols on their own (if the text is too small to read for some users) should be sufficient to convey the key's meaning). I will release the changes with the next release of Optikey.
