### ISSUE TITLE
Feature Request: Crash Dialogue Improvement

### ISSUE THREAD

**Issue by bigmutty** [OptiKey/OptiKey#689]
Instead of having the crash dialogue automatically close, have the option to close or reset the program. This would really help users using an eye tracker because currently if a crash occurs, they're stuck unless they have another way of access.

**Comment by kmcnaught** [comment]
Once a crash has happened, we don't really have any guarantees on what state Optikey is in, so it would be difficult to add a gaze-controlled user flow for closing or restarting. I think it would however be very easy to change the behaviour to just always restart the app when the crash window disappears. Would this be an okay solution? 

@JuliusSweetland for any objections or concerns.

**Comment by JuliusSweetland** [comment]
@kmcnaught I would err towards setting auto restart as an option (happy for it to be defaulted to true by default). The situation we want to avoid is a looping start->crash->restart->crash. To detect this we could do something like store a static application scope variable which records whether the startup has completed successfully. On a crash we could check this and prevent the auto-restart if optikey failed to bootstrap. The tricky bit would be deciding what event we consider the end of a successful boot. Maybe something linked to the first keyboard being rendered?

**Comment by bigmutty** [comment]
I agree with @JuliusSweetland. Maybe have the restart and close buttons be able to be activated by gaze or mouse click. That way if the program can no longer be accessed through gaze, it would still be able to be closed or restarted.

**Comment by JuliusSweetland** [comment]
That's not a bad idea. Agreed.

**Comment by kmcnaught** [comment]
Good point on the restart loop. I've proposed a fix very similar to @JuliusSweetland's suggestion, PR for review. Having optional restart / close buttons which are both eye gaze and mouse accessible is a much bigger task that I've ignored for now.
