### ISSUE TITLE
Support for Tobii 5

### ISSUE THREAD

**Issue by samgled** [OptiKey/OptiKey#690]
Tobii is coming out/ has come out with a new eye tracker.

Just wondering if this will likely get support? (Sorry, I do realize this is probably not the right place to ask...)

**Comment by 0kee** [comment]
I've tested it and it works fine on Tracker 4C settings. No Windows Eye
Control support yet but that's another story

**Comment by AdamRoden** [comment]
@0kee Please elaborate. TobiiDynavox released the I-13 and I-16 devices with their IS5 chip and more recently TobiiGming released the ET5 with the IS5 chip. I don't yet know the full compatibilities of either and am interested in learning more. I have the ET5 on order so I'll be trying it out myself soon.

**Comment by 0kee** [comment]
I tested the Tracker 5 on Optikey Pro a couple of days ago. I'm not an
Optikey power user but from my testing it worked very well when I had the
Tracker 4 C selected as my eye tracker. It is not however recognised by
Windows 10 as a supported eye tracker for Eye Control. It's a really nice
device and in my opinion worth the extra few euros ober the Tracker 4C.

**Comment by JuliusSweetland** [comment]
@0kee Thanks for testing and for providing feedback. A lot of people have been asking if Optikey supports the new generation of eye trackers. I have one on order, but have not yet been able to verify. It's good to hear that it does indeed work.

**Comment by nmalbran** [comment]
Hi! That's great to hear, I was looking for affordable eye trackers since I can't find the Tobii 4C, EyeX or EyeTribe trackers for sale anymore.
The next one is the [Tobii gaming ET5](https://gaming.tobii.com/product/eye-tracker-5/). I was thinking in getting one and trying it out.
If you have more information about it, please let me know!

**Comment by JuliusSweetland** [comment]
@nmalbran Hi Nicolas - I still have not received my tracker so I can't comment, but the feedback is that it works. Multiple users have fed that back.

**Comment by AdamRoden** [comment]
@samgled @nmalbran @JuliusSweetland 
This morning I removed my 4C and attached the Tobii Gaming ET5. The drivers installed automatically and after rebooting, it is working perfectly with Tobii's Windows Control and OptiKey Pro. However, it is not recognized by Microsoft's built-in Windows Eye.

**Comment by JuliusSweetland** [comment]
Excellent. I've added support to select it to OptiKey matter branch
already. It will go out with the next release. Thanks!

**Comment by kmcnaught** [comment]
FYI the rumours in the Tobii discord channels are that ET5 support for Windows Eye Control is expected at some point, pending some work on both sides. 🤞
