### ISSUE TITLE
Nested dynamic keyboards?

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#696]
@AdamRoden @JuliusSweetland 

I've noticed a few times that Optikey now comes with some built-in sample keyboards, some of which are in a subdirectory, and these are not by default available. Are these intended to be automatically available for users, or just for reference? 

In EyeMine I've now moved to a setup where subdirectories within the dynamic keyboards folder becomes a sub directory in the keyboard menu, i.e. for a folder called "Bonus keyboards" you'll have a key labelled "[Bonus keyboards]" in the dynamic keyboard menu that takes you to a version of the dynamic keyboard menu containing the inner files. This feels pretty intuitive as a user. 

Do you want the same behaviour in Optikey? If so, I'll bear that in mind and prepare a PR at some point...

**Comment by JuliusSweetland** [comment]
@kmcnaught I don't believe so, only because the sample keyboards are not really functional. They are more to be use as examples of how things are done and are referenced in the wiki page. Thank you though.
