### ISSUE TITLE
Command plugin with arguments

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#697]
This very helpful functionality, as documented in the wiki, allows you to launch a program / open a file.
```
<DynamicKey>
	<Label>Skype</Label>
	<Plugin>
		<Name>ExternalProgram</Name>
		<Method>RUN</Method>
		<Argument>
			<Name>command</Name>
			<Value>"C:\Program Files (x86)\Microsoft\Skype for Desktop\Skype.exe"</Value>
		</Argument>
	</Plugin>
</DynamicKey>
```

From the documentation, I was expecting this to work with commands with arguments also, for example:
```
<Value>"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" https://www.bbc.com/news</Value>
```

This does not work :( 

Looking at [the documentation for Process.Start](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netcore-3.1), passing a single string only _starts a process resource by specifying the name of a document or application file_ and doesn't allow parameter passing, so it's not the same as running an arbitrary command from the command prompt. You can pass commandline arguments by using the `Process.Start(string, string)` overload, so I imagine this could be added to the plugin fairly easily?

**Comment by kmcnaught** [comment]
Thanks for the PR @bigmutty

**Comment by bigmutty** [comment]
I'm glad I could help.
