### ISSUE TITLE
Localisation: Hindi

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#722]
1.Potential keyboard layout examples:
https://www.branah.com/hindi

Standard keyboard layouts:
Shift up:
![image](https://user-images.githubusercontent.com/4722561/92785157-17a10680-f39f-11ea-8fee-4c6ddcac5568.png)

Shift down:
![image](https://user-images.githubusercontent.com/4722561/92787451-06f19000-f3a1-11ea-8a29-1e1d751e1813.png)

Ctrl/Alt down:
![image](https://user-images.githubusercontent.com/4722561/92787520-17096f80-f3a1-11ea-9794-fc0fb0a52c2e.png)

2.Online keyboards:
https://www.branah.com/hindi
https://www.lexilogos.com/keyboard/devanagari.htm

3.Transifex: https://www.transifex.com/optikey/optikey/language/hi/

4.Breakdown of (potentially) required characters:

Shift up: 
ॊ ृ
ौ ै ा ी ू ब ह ग द ज ड ़ ॉ
ो े ् ि ु प र क त च ट
ॉ ॆ ं म न व ल स य

Shift down: 
ऒ ऍ ॅ ऄ ₹ ऽ ऀ ः ऋ
औ ऐ आ ई ऊ भ ङ घ ध झ ढ ञ ऑ
ओ ए अ इ उ फ ऱ ख थ छ ठ
ऑ ऎ ँ ण ऩ ऴ ळ श ष । य़

Ctrl/Alt down:
ॵ १ २ ३ ४ ५ ६ ७ ८ ९ ० ॄ ॠ
ॱ ॕ ॑ ॡ ॣ ॳ ॴ ग़ ॸ ज़ ड़ ढ़ ॲ
ॖ ॗ ॒ ऌ ॢ फ़ ॎ क़ ख़ ॹ ऺ
ऻ ॓ ॐ ॔ ॏ ॶ ॷ ॽ ॰ ॥ ॺ

Punctuation: - , . 

Infrequents: ?

DO THESE 3 SCREENS MAKE SENSE? If so I'm thinking we could have 2 keys to switch to the 2nd or 3rd layouts of character (and back)

5.Overview doc: https://r12a.github.io/app-charuse/?language=hi

From this doc:

Letters: अ आ इ ई उ ऊ ऋ ए ऐ ओ औ क ख ग घ ङ च छ ज झ ञ ट ठ ड ढ ण त थ द ध न प फ ब भ म य र ल व श ष स ह क़ ख़ ग़ ज़ ड़ ढ़ फ़
Punctuation:  ।  ॥  ॰  —  ‘  ’  “  ”
Numbers:  ०  १  २  ३  ४  ५  ६  ७  ८  ९
Others: U+200D U+200C
Infrequents:  ऍ  ऑ  ऽ  ॐ  ॅ  ॉ

6.Branch: https://github.com/OptiKey/OptiKey/tree/Hindi

**Comment by sanjayb75** [comment]
Could you please provide me access to translate to the Hindi language? 

Thanks, Sanjay

**Comment by JuliusSweetland** [comment]
You need to create an account on transfex.com and then request access to
translate Hindi on the optikey project there. I'll approve the request once
you have made it.

There's is a full guide to localisation that explains all the steps here:
https://github.com/OptiKey/OptiKey/blob/master/docs/Localize.md

**Comment by JuliusSweetland** [comment]
Google Indic keyboard layout (note the top row changes to display the last character with all diacritics applied):
![image](https://user-images.githubusercontent.com/4722561/92919593-ac037b80-f428-11ea-86e4-1ac2f134c9d8.png)

![image](https://user-images.githubusercontent.com/4722561/92919620-b58ce380-f428-11ea-8df2-e33e41c7553c.png)

**Comment by JuliusSweetland** [comment]
Proposed 2 screen layout from Sanjay:

![image](https://user-images.githubusercontent.com/4722561/92991728-be8bbc80-f4dd-11ea-9a7c-577df55a70a8.png)
![image](https://user-images.githubusercontent.com/4722561/92991731-c21f4380-f4dd-11ea-8e43-260a6fd369cd.png)

**Comment by sanjayb75** [comment]
Shift Up:
 ॅ  ॉ  ्
 ा  ि  ी  ु  ू   े  ै  ो  ौ  ं  ः ृ
क ख ग घ च छ ज झ ट ठ ड
ढ त थ द ध न प फ ब भ

Shift Down:
अ आ इ ई उ ऊ ए ऐ ओ औ अँ अः
म य र ल व स श ष ह ऋ
ङ ञ ण श्र क्ष त्र ज्ञ 

Also we may not need the third screen (Ctrl down). The half letters can be written by applying diacritic  ् to any letter. 
e.g. क +  ् = क्

**Comment by JuliusSweetland** [comment]
Thank you. In what order would you type the diacritic? Consonant and then
diacritic to add it, or the other way around?

**Comment by sanjayb75** [comment]
It would be Consonant first and then diacritic to add it.
    On Sunday, September 20, 2020, 02:52:20 AM EDT, Julius <notifications@github.com> wrote:  
 
 

Thank you. In what order would you type the diacritic? Consonant and then
diacritic to add it, or the other way around?

**Comment by JuliusSweetland** [comment]
@sanjayb75 So I've created the first draft of the keyboard layouts. I took prompts from this info: https://r12a.github.io/app-charuse/?language=hi so the character ordering or the vowels/diacritics is slightly different. What do you think?

Alpha 1:
![image](https://user-images.githubusercontent.com/4722561/93713866-a0196700-fb56-11ea-8566-7b98bb920032.png)

Alpha 2:
![image](https://user-images.githubusercontent.com/4722561/93713874-ab6c9280-fb56-11ea-98cc-2c823ed4f239.png)

Numbers & symbols:
![image](https://user-images.githubusercontent.com/4722561/93713965-53825b80-fb57-11ea-8d4c-5294a5a43132.png)

FYI when I prepare a version of you to test you'll need to change this setting to ENABLE typing diacritics AFTER characters. The default behaviour in Optikey is the otherway around: 
![image](https://user-images.githubusercontent.com/4722561/93713330-f1275c00-fb52-11ea-9e43-c067ea98d7f1.png)


**Outstanding items:**
If you like the layout I need to add the ConversationAlpha 1 & 2 keyboards
Hindi dictionary may be a little small - we need to test
Transifex UI translations
Native speaker to test

**Comment by sanjayb75** [comment]
Hello Julius,
The keyboard layouts look good. You can go ahead and add them. 
Please provide me access on Transifex for the Hindi language. I will work on the translation. Also, let me know what else I can help with.
Thanks,
Sanjay
    On Sunday, September 20, 2020, 10:38:56 AM EDT, Julius <notifications@github.com> wrote:  
 
 


@sanjayb75 So I've created the first draft of the keyboard layouts. I took prompts from this info: https://r12a.github.io/app-charuse/?language=hi so the character ordering or the vowels/diacritics is slightly different. What do you think?

Alpha 1:


Alpha 2:


Numbers & symbols:


FYI when I prepare a version of you to test you'll need to change this setting to ENABLE typing diacritics AFTER characters. The default behaviour in Optikey is the otherway around:


Outstanding items:
If you like the layout I need to add the ConversationAlpha 1 & 2 keyboards
Hindi dictionary may be a little small - we need to test
Transifex UI translations
Native speaker to test

**Comment by sanjayb75** [comment]
Here is the updated alpha 1 layout with diacritics in the correct order -
![Alpha 1 - Updated](https://user-images.githubusercontent.com/71115839/93733169-56ef0480-fba2-11ea-8206-8ad2df0d1d41.PNG)

**Comment by sanjayb75** [comment]
> @sanjayb75 So I've created the first draft of the keyboard layouts. I took prompts from this info: https://r12a.github.io/app-charuse/?language=hi so the character ordering or the vowels/diacritics is slightly different. What do you think?
> 
> Alpha 1:
> ![image](https://user-images.githubusercontent.com/4722561/93713866-a0196700-fb56-11ea-8566-7b98bb920032.png)
> 
> Alpha 2:
> ![image](https://user-images.githubusercontent.com/4722561/93713874-ab6c9280-fb56-11ea-98cc-2c823ed4f239.png)
> 
> Numbers & symbols:
> ![image](https://user-images.githubusercontent.com/4722561/93713965-53825b80-fb57-11ea-8d4c-5294a5a43132.png)
> 
> Conversation alpha 1:
> ![image](https://user-images.githubusercontent.com/4722561/93722426-885dd500-fb8e-11ea-8fab-5a1259120d82.png)
> 
> Conversation alpha 2:
> ![image](https://user-images.githubusercontent.com/4722561/93722450-c529cc00-fb8e-11ea-8925-785532bae9a9.png)
> 
> Conversation numbers & symbols:
> ![image](https://user-images.githubusercontent.com/4722561/93722461-e4c0f480-fb8e-11ea-8cc4-58c9e539759b.png)
> 
> **Outstanding items:**
> 
> * [ ]  Do you think the "swipe" style of input (called MultiKeySelection in Optikey) is useful in Hindi? If so can you give me a list of letters which could start a multikey selection - i.e. characters which can start a word. More info here: https://github.com/Optikey/Optikey/wiki/Multi-key-selection
> * [ ]  Hindi dictionary may be a little small - we need to test
> * [ ]  Transifex UI translations
> * [ ]  Native speaker to test

Multi-key selection may not be helpful in Hindi as we do not have all the letters in a single screen.

**Comment by JuliusSweetland** [comment]
Will do. You need to sign up to Transifex and request Hindi. I will then
approve your request.

**Comment by sanjayb75** [comment]
I have already signed up on Transifex and have requested the access for Hindi. 




On Monday, September 21, 2020, 12:01 PM, Julius <notifications@github.com> wrote:



Will do. You need to sign up to Transifex and request Hindi. I will then
approve your request.

**Comment by JuliusSweetland** [comment]
Oh I have been notified. I've approved now.

**Comment by sanjayb75** [comment]
Please take a look at the updated alpha 1 layout and see if it's possible to re-arrange the diacritics order.
![Alpha 1 - Updated](https://user-images.githubusercontent.com/71115839/93765047-40689d80-fbe2-11ea-87d6-95c8f2aca7d2.PNG)

**Comment by JuliusSweetland** [comment]
I will look at this tonight after work etc. I'll create a pre release for
you to test as well

**Comment by JuliusSweetland** [comment]
@sanjayb75 How does this look:

Alpha 1:
![image](https://user-images.githubusercontent.com/4722561/93811362-ef8b9000-fc47-11ea-9e1b-f87fb5768f79.png)

Conversation alpha 1:
![image](https://user-images.githubusercontent.com/4722561/93812401-742ade00-fc49-11ea-9322-6a1209859b09.png)

**Comment by JuliusSweetland** [comment]
@sanjayb75 Here's a pre-release of 3.0.10 with Hindi support: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_2/OptiKeyPro.exe

**Comment by sanjayb75** [comment]
This looks great. Thank you.
    On Monday, September 21, 2020, 03:31:59 PM EDT, Julius <notifications@github.com> wrote:  
 
 


@sanjayb75 How does this look:

Alpha 1:


Conversation alpha 1:

**Comment by sanjayb75** [comment]
Hello Julius,
I did some initial testing and it seems to be working perfectly fine. All the letters and diacritics are working fine. 
I just have one question. Is it possible to have the Next key (1 of 2) work like a shift key? In other words once a letter is selected on screen 2, can it automatically go back to screen 1 so that we can apply diacritic to the letter just selected. It would be nice to have diacritics available all the time after selecting a letter. Please let me know if it makes sense.
Thanks,
Sanjay
    On Monday, September 21, 2020, 04:05:33 PM EDT, Julius <notifications@github.com> wrote:  
 
 


@sanjayb75 Here's a pre-release of 3.0.10 with Hindi support: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_2/OptiKeyPro.exe

**Comment by JuliusSweetland** [comment]
@sanjayb75 I'll have a think about the best way to do this and see if I can come up with something.

**Comment by JuliusSweetland** [comment]
@sanjayb75 Right, I've implemented a way to do this: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_3/OptiKeyPro.exe

**Comment by sanjayb75** [comment]
@JuliusSweetland This is now working great. The display is going back to the first screen after selecting a letter on the second screen as expected. Thanks so much for implementing this. 

I did some more testing and noticed following two issues -
1. I missed a diacritic which is not commonly used but it would be a good idea to include that as well. The diacritic is ्र. Below is how it works -
ड +्र = ड्र
द + ्र = द्र
We can add this anywhere on the second screen. If required we can put it in place of  ॉ  or ऑ as both of these work similar.

2. The back word is not deleting the entire word. It's only deleting a part of the word.

Please let me know if you have any questions.
Thanks.

**Comment by JuliusSweetland** [comment]
@sanjayb75 
1.Is that this character: https://www.fileformat.info/info/unicode/char/094d/index.htm if so it exists on the 2nd row - next to the TAB key.

2.I've figured this one out. Optikey was not considering the vowel marks (in unicode these are categorised as "NonSpacing Marks") as not being letters. I've added support for these. Once I have an answer about 1 I'll prepare a new version for you to test.

**Comment by sanjayb75** [comment]
@JuliusSweetland 
1. It's actually a combination of 094D and 0930. However, I found a way to type it that so no need to do anything. We are good with the current layout.

2. Thank you for fixing that. I will wait for the revised version and do another round of testing.

**Comment by JuliusSweetland** [comment]
@sanjayb75 Good news on 1. New pre-release is here: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_4/OptiKeyPro.exe

Has your mother tested this? How did she get on?

**Comment by sanjayb75** [comment]
@JuliusSweetland Thank you. My mother has tried it a couple of times. She is having difficulty focusing on letters. She keeps moving her eyes on different letters before locking in. She can't open her right eye completely so may that's causing the issue. I think it will require more practice for her to get a good control over it.

Do you have any tips on how to improve the ? Are there any settings we can play with? We are using Tobii eye tracker 4C.

**Comment by JuliusSweetland** [comment]
Main tips:

Make sure her position in front of the screen is good. Use the Tobii
calibration to make sure that it can see her eyes well (right at the
beginning it shows you 2 white circles that are her eyes in a box - these
need to be as bright and central as possible). It may be that she/the
screen needs to be closer/further away/rotated.

Avoid strong sunlight - it interferes with the trackers

Spend some time getting a good calibration

Us the conversation keyboard where possible - the keys are larger and
easier to hit

You can try increasing/changing the processing amount in the Management
Console:
[image: image.png]
(there is a complete overhaul of the way jitter is smoothed out by Optikey
coming soon which should help as well).

**Comment by sanjayb75** [comment]
@JuliusSweetland Thanks so much, Julius. I will try these tips.

**Comment by JuliusSweetland** [comment]
Closing this issue and merging Hindi into master.

**Comment by JuliusSweetland** [comment]
@sanjayb75 I incorrectly closed this. Outstanding is still the Transifex translation and also what are your thoughts on the dictionary size? Is it useable?

**Comment by sanjayb75** [comment]
@JuliusSweetland I continue to work on Transifex translation. Have completed more than 400 translations so far. Will complete it soon. The dictionary size is decent. It has all the common Hindi words. I can add more words if required.

**Comment by JuliusSweetland** [comment]
If you're happy with the dictionary then we can keep it as it is. Users can
always add more words themselves.

Looking forward to your translations and then I will release Hindi for
everyone.

Thanks!

**Comment by sanjayb75** [comment]
@JuliusSweetland Yes, I am okay with the dictionary. We can keep it as is.

I have completed the transifex translations for all the strings. Please review and let me know if you need anything else.

Also, do you have a user manual for management console settings?

**Comment by sanjayb75** [comment]
Hello Julius,
I have been trying to get my mom to practice the Hindi keyboard for the last few days. She is getting better at it but I have noticed that she is struggling with the diacritics as they are only available on one screen and she has to go back and forth to apply them.
Can we try to fix that if it's not too much work fo you? I have tried to re-arrange screen layouts so that diacritics are available on both the screens all the time. Could you please take a look at the attached PPT with the proposed layouts and advice if it's easy to make this change? I feel that the proposed layouts look more practical in terms of user experience.
If we make this change, we can also remove the feature wherein the control comes back to the first screen after selecting a letter on the second screen.
Thanks so much for your help. Please let me know if you have any questions.
Thanks,
Sanjay
    On Monday, September 28, 2020, 06:38:32 AM EDT, Julius <notifications@github.com> wrote:  
 
 

If you're happy with the dictionary then we can keep it as it is. Users can
always add more words themselves.

Looking forward to your translations and then I will release Hindi for
everyone.

Thanks!

**Comment by JuliusSweetland** [comment]
@sanjayb75 I don't see any issues making this change, but can you post the images here again? The attachment did not work - I think you will need to paste the images in this thread manually.

**Comment by sanjayb75** [comment]
Thanks Julius. I am attaching the proposed layouts here.
![Hindi Alpha 1](https://user-images.githubusercontent.com/71115839/95020423-0dd69000-0639-11eb-84f4-a36875f71750.PNG)
![Hindi Alpha 2](https://user-images.githubusercontent.com/71115839/95020430-19c25200-0639-11eb-97cd-8206351ec167.PNG)

**Alpha 1 -**
ा ि ी ु ू े ै ो ौ ं ः ् 
क ख ग घ च छ ज झ ट ठ ड ढ 
त थ द ध न प फ ब भ म
 ँ  ़ ृ ङ ञ ण

**Alpha 2 -**
ा ि ी ु ू े ै ो ौ ं ः ् 
अ आ इ ई उ ऊ ए ऐ ओ औ अँ अः
य र ल व स श ष ह ऋ श्र
ॅ क्ष त्र ज्ञ

Please let me know if you have any questions. 
Thanks,
Sanjay

**Comment by JuliusSweetland** [comment]
@sanjayb75 Right, I've made the changes. Can you try this version and let me know: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_5/OptiKeyPro.exe

**Comment by sanjayb75** [comment]
Thanks Julius. I tested it and it works as expected. Thank you for making the change. I think we are all set for the release. 

There is one more minor item. The number/symbol screen is missing the hindi equivalant of a period. It is typed as । and the unicode is 0964. It's not a big deal but just thought of letting you know if you want to include it in the final release.

Thanks,
Sanjay

**Comment by JuliusSweetland** [comment]
Good news. Is that the same symbol that is included on the main Hindi
letters keyboard? Are there any symbols on the Hindi number keyboard which
are not needed?

**Comment by sanjayb75** [comment]
@JuliusSweetland This symbol is not included on the main Hindi letters keyboard either. We can add this to the number keyboard in place of the underscore (_). We do not use the underscore in Hindi.

**Comment by JuliusSweetland** [comment]
@sanjayb75 0964 is this next to comma on the main alpha keyboard: 
![image](https://user-images.githubusercontent.com/4722561/95054797-5306ca80-06ea-11eb-982f-ff6e7c885708.png)

I've added the symbol to the numeric keyboards now. New version here: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_6/OptiKeyPro.exe

**Comment by sanjayb75** [comment]
Yes that’s the same one. For some reason I can’t see it in conversation only mode. Thanks for adding it to number screen. 




On Monday, October 5, 2020, 1:53 PM, Julius <notifications@github.com> wrote:




@sanjayb75 0964 is this next to comma on the main alpha keyboard:


I've added the symbol to the numeric keyboards now. New version here: https://github.com/OptiKey/OptiKey/releases/download/v3.0.10_pre-release_6/OptiKeyPro.exe

**Comment by JuliusSweetland** [comment]
In conversation mode if you go to the numbers screen it's there:

![image](https://user-images.githubusercontent.com/4722561/95089443-0f2cb900-071c-11eb-814b-22c8acfd87e4.png)

**Comment by sanjayb75** [comment]
@JuliusSweetland Thanks Julius. This looks good. We are all set now.

**Comment by JuliusSweetland** [comment]
@sanjayb75 Great, glad we got everything finished! Thanks for your help. If you know of any organisations that could benefit, please let them know.

**Comment by sanjayb75** [comment]
@JuliusSweetland Thanks so much Julius for making this happen. Really appreciate it. This will surely help my mom a lot. Please let me know when you release it officially. Will let others know.

**Comment by JuliusSweetland** [comment]
No problem. I'm glad this will help your mum.

**Comment by prateekdubey23** [comment]
Made an account just to let you all know that this hindi keyboard has been life altering for my mom. She is learning to use an eye tracker and it creates real cognitive overload, especially for elder folks that have not used computers in the past. But this hindi keyboard allowed her to think and type in her first language and it has made a world of a difference. It's heartening to see her articulate her thoughts again, with all the comfort and flow that comes with one's first language. Thank you so much for putting in the effort. I've made a video demo to share with others and will link it out here once done.

**Comment by JuliusSweetland** [comment]
That's wonderful. Thank you for taking the time to update us. It really makes a difference to hear that Optikey is helping people. Please say hello to your mum for me.
