### ISSUE TITLE
Bug Report: Unable to Use Web Dropdown Menus Using Click Magnifier

### ISSUE THREAD

**Issue by bigmutty** [OptiKey/OptiKey#727]
When attempting to access dropdown menus on the web using Optikey using the magnifier, the menu closes when the magnifier control opens because the mouse cursor leaves the website and enters the magnifier control.  You can see it happen well on https://www.kinovarobotics.com/en.

I was thinking there was an [Extended Window Style](https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles) that would make the magnifier not receive any mouse events, but I didn't find it, We could possibly use a mouse hook and cancel those events.

**Comment by JuliusSweetland** [comment]
@bigmutty Hi Daryl - a workaround may be to use the extended mouse keyboard actions to move the mouse to a point, click to open the menu, then move the cursor down bit by bit and then execute a click at that point. This does not allow magnification, but does allow precise control

**Comment by AdamRoden** [comment]
@bigmutty I agree with Julius. This isn't necessarily a bug. Dropdowns can react differently to mouse position and clicking depending on the code behind them. A lot of them react to mouse position, but if you click they close and do something. So, the only solution is to move the mouse from point to point and then execute a click at current position. Give me an example website dropdown to troubleshoot to see if anything can be done to handle it better.

**Comment by AdamRoden** [comment]
@bigmutty I hate those kinds of dropdowns. I have a few ideas for work arounds, but they would take some work, and other than a new special key, the method suggested by Julius is best for now.

**Comment by JuliusSweetland** [comment]
Closing as there are solutions.
