### ISSUE TITLE
Context Menu Options: Unlock Keyboard Position and Mouse Control Activation Method

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#733]
he new feature to use the mouse to move and resize the keyboard has been causing me headaches. When I can, I use a mouse in combination with Optikey, but due to poor motor control I often inadvertently click and drag the keyboard out of position.

Perhaps we can change the default to disabled and have an option to the right-click context menu toggle enable/disable the feature.

While we're at it, can we also improve the context menu option for mouse control to allow the choice of mouse w/dwell or mouse w/click?

**Comment by JuliusSweetland** [comment]
I'm happy with both suggestions. Good ideas.

**Comment by kmcnaught** [comment]
That makes sense, having a context menu option seems like a good idea. My concern with defaulting to disabled is lack of discoverability, particularly for onboarding - when someone tries Optikey for the first time and it's not appropriately sized for them. I've come across people who have dismissed Optikey because they didn't take the time to set it up right. But obviously once it's set up for you, you don't want to ever trigger it accidentally.

**Comment by JuliusSweetland** [comment]
Context menu item to "disable manual size and position changes"

**Comment by AdamRoden** [comment]
Okay. Let's make the resize with mouse be an option that can be disabled in MC and have it be on by default.

**Comment by kmcnaught** [comment]
I'm completely happy with it being in the context menu but default on. That improves discoverability for the in-between user who's discovered the context menu but hasn't understood the plethora of options available in MC. It also means it's easy to switch back and forth - for instance an assistant can drag OK out the way temporarily.

**Comment by AdamRoden** [comment]
I didn't like the look and feel of EnableResizeWithMouse on the context menu, so I put it in MC. It works fine when disabling the option, but for a reason which I am unable to trace, when you enable the feature Optikeys stops detecting your gaze until you restart, so turning it back on requires a restart.

I had the Mouse Click as Selection Trigger toggle working to an extent, but it required some compromises and has some complex underlying issues that make it undesirable to complete.

**Comment by JuliusSweetland** [comment]
Closing as this will be in the 3.0.10
