### ISSUE TITLE
OptiKey doesn't update to the latest version

### ISSUE THREAD

**Issue by JDspeeder1** [OptiKey/OptiKey#735]
# How OptiKey was being used

Every time OptiKey starts

# What the user expected to happen

Update notice should stop

# What the user actually experienced

Update notice reappears every time OptiKey starts

# Version
 - Operating system and version:Windows 10 Pro version 2004
 - OptiKey version 3.0.8

# Steps to reproduce the issue

# Any other information that helps to describe and/or reproduce the problem
I get an alert that a new version of OptiKey, 3.0.9, is available to download from optikey.org.  When I go there and download what claims to be the latest version, I just get another copy of 3.0.8.

I should note that I'm a user, not a programmer.

# Screenshots

**Comment by JuliusSweetland** [comment]
@JDspeeder1 Absolutely correct. I had failed to update the download links from 3.0.8 to 3.0.9. I have corrected this so please try to download and install from the website again and the notice will go away. Sorry!
