### ISSUE TITLE
Update MC to offer the same logic as Completion Times in Dynamic keyboards

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#740]
Change the field for the time required to complete a key from a numeric value to a comma-delimited list.

**Comment by AdamRoden** [comment]
@JuliusSweetland I've got this one stashed and ready to go. I could offer it up now, or I can save it to be bundled with other new features later.

**Comment by JuliusSweetland** [comment]
Sounds interesting. How does it work?

**Comment by AdamRoden** [comment]
Works great! However, all pre-existing values saved using the timespan data type need to be swapped out for strings in order to allow comma-delimited-lists. (Unless you have a better idea)
KeyFixationSource uses the first number for the initial keystroke, and if you stay on the same key, the second number for the second keystroke, and so on, with the last number being the final repeat rate so that if you stay on long enough it will go really fast.

![image](https://user-images.githubusercontent.com/45572061/96390704-7cf4ce00-117b-11eb-8da7-8c59b207a5da.png)

**Comment by JuliusSweetland** [comment]
Looks really interesting, but what's the migration path for existing
settings. Perhaps a new setting would be better as it would introduce the
extra concept and be backward compatible?

**Comment by AdamRoden** [comment]
@JuliusSweetland I would agree, but the problem is that there are dozens of keys that can be individually set. They all get stored as strings in xml format, so I am performing a conversion when reading the xml and that works fine. The only field that's a problem is the default. Perhaps I leave the default as is and add an field below it called variable repetition times.

**Comment by JuliusSweetland** [comment]
I am leaning towards the new "repetition times" setting.

How does it work if the user makes an initial key selection, begins the
next one, but glances away (e.g. to check on the impact the first key press
had) and back to continue pressing - does the selection resume with the 2nd
selection completion time?

**Comment by AdamRoden** [comment]
In that situation, the fixation timer resets and a new lock on is required and the 1st selection completion time is used.

**Comment by JuliusSweetland** [comment]
Is it possible to retain the completion time on the partially completed
selection so the user has a chance to (intentionally or unintentionally)
lose focus on the key momentarily and continue where they left off?

**Comment by AdamRoden** [comment]
Perhaps. The question is what's it worth if it turns out to be a big challenge.

**Comment by JuliusSweetland** [comment]
I'm not sure. Let's say you are using the key repeat to type exactly 8
characters in a document for some reason - you probably wouldn't need to
glance to check your progress and can just count the selections. However,
what about the use cases where the key is providing input into a game -
wouldn't you want to be able to fire off a few key presses, glance to check
progress, and then continue?

I don't have the answer, but it feels like triggering a number of key
selections without being able to check another part of the screen is not
ideal.

What do you think?

**Comment by AdamRoden** [comment]
It sounds good, but there are a few options in MC that affect that behavior. Resume requires new lock on, and Incomplete time to live. Out of those two, the latter does not make sense to me I don't know what to infer based on its name.

Otherwise, I agree with your analysis but haven't been bothered by it because I always favored resuming to require a new lock on.

**Comment by JuliusSweetland** [comment]
"Resume requires new lock on" - this controls whether looking away and
resuming a selection would continue immediately, or whether the lock on
period is required before the selection continues. I don't think this
should impact whether the resumed selection takes the 1st selection time to
complete, or a later time to complete.

" Incomplete time to live" - this is how long an in progress selection will
survive when the user moves their attention somewhere else. If they return
to the selection within this time period then the selection can continue.
If they don't then the in progress selection is discarded.

I think both of the above play nicely with the idea of a user resuming
their 2nd/3rd/whatever selection. I am only thinking about how long that in
progress selection should take to complete - is the user back to the
beginning of the selection timings, or can they resume the (probably)
faster subsequent selection?

**Comment by AdamRoden** [comment]
HA! When you put it that way.
I thought it was Incomplete time to live (rhymes with dive), like when the key would activate if the initial selection was disrupted. Now you're telling me it is the time before incomplete fixations are discarded. That makes so much more sense.

I'm working the code out now. I just need to remove one clause and put something similar in a different spot.

**Comment by JuliusSweetland** [comment]
Sounds good...

Naming settings is hard - I've found people often interpret settings as
meaning something different from what I intended.

**Comment by hyperdeath666** [comment]
Could we consider adding a timer of key inactivity after which the completion time reverts to the first list entry (perhaps just using " Incomplete time to live")? Some of my keys (especially my one button keyboards) are getting stuck on the last time entry with no way to revert (wasn't a problem in 3.1)

**Comment by JuliusSweetland** [comment]
@AdamRoden is this something you expected, or can replicate?

**Comment by hyperdeath666** [comment]
From what I can tell, the time reverts to the first entry only when you lock on to a new key. But this yields somewhat counterintuitive behavior if you don't use the keyboard for a while and then interact with the same key you last used, and no (obvious) way to revert for one button keyboards.

Unrelated, but thank you both so much for all your work on optikey - it is literally life changing.

**Comment by AdamRoden** [comment]
@JuliusSweetland @hyperdeath666 
I'm experiencing the same thing and agree it is undesirable. I'll work on an improvement.

**Comment by JuliusSweetland** [comment]
@AdamRoden thanks Adam. It doesn't sound like it will be a show stopping bug for most people so don't stress too much.

**Comment by AdamRoden** [comment]
@JuliusSweetland @hyperdeath666 
The solution was simple. I had to move a line of code I wrote, and then moved, back to the spot I had originally put it. (I erred in moving it thinking it was only necessary under narrow criteria, when in fact the criteria is broad.)

**Comment by JuliusSweetland** [comment]
@AdamRoden Thanks Adam. I have merged in your change and will prepare a new release (3.2.1) over the weekend to give time for any other feedback to come in.

**Comment by hyperdeath666** [comment]
Thanks, both!
