### ISSUE TITLE
Mouse actions don't respect timing within dynamic key command lists

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#746]
This isn't entirely suprising in retrospect, but mouse actions are asynchronous, so happen out of sync when they're queued in a command list. 

For instance, consider you want to hold down shift for a left click event. This should work, but doesn't:
```
<KeyDown>Shift</KeyDown>
<Action>MouseMoveAndLeftClick</Action>
<KeyUp>Shift</KeyUp>
```

What you observe is Shift down then Shift up, then mouse click. The final `Shift up` doesn't get blocked waiting on the result of the dwell selection for MouseMoveAndLeftClick.

If you add a (sufficiently long) delay you do indeed get a Shift-click, but you can't know in advance exactly how long the selection will take, so this isn't a very robust workaround.

```
<KeyDown>Shift</KeyDown>
<Action>MouseMoveAndLeftClick</Action>
<Wait>3000</Wait>
<KeyUp>Shift</KeyUp>
```

I haven't really looked into the async handling that's in the command list processing, so I'm not sure how hard this would be to fix. @AdamRoden ?

**Comment by AdamRoden** [comment]
@kmcnaught It could be fixed by adding a virtual keystate for the mouse action and monitoring it when executing dynamic key. Otherwise, I haven't looked, but there might be a way to use an event listener.

**Comment by AdamRoden** [comment]
@kmcnaught I don't know how to fix this. I've experimented with an eventQueue mechanism to queue the mouse actions, but it had no affect. I'm currently perplexed by how the mouse action code is interpreted and handled.

**Comment by AdamRoden** [comment]
@kmcnaught I figured this out and fixed. I put a comment in #744 because I was working on a continuous click key for that related issue. It's in a PR at the moment.

**Comment by kmcnaught** [comment]
@AdamRoden great stuff! I can't see a PR yet - but when it's there I will review with your other one

**Comment by kmcnaught** [comment]
Oh I see, it's in the existing PR, no worries. It's on my todo.
