### ISSUE TITLE
New setting to make Magnetic Cursor on at startup

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#747]
@siamakmu Requested this.

**Comment by JorgeMattos** [comment]
Restarting with a locked MouseMagnifier is saved in user.config.
Could you do the same with a magnetic cursor?

**Comment by SCEhardt** [comment]
Should be resolved by pull request 779.  Leaving a comment since I don't see it linked yet.

https://github.com/OptiKey/OptiKey/pull/779

**Comment by kmcnaught** [comment]
Thanks @SCEhardt!
