### ISSUE TITLE
the size of the application is altered

### ISSUE THREAD

**Issue by freyesf** [OptiKey/OptiKey#751]
I was using the application and in a section change the size of the application was changed, I have edited the main menu, but I don't see that this is the problem. 

this error happens very rarely, so I can't see what the problem is. does anyone know what could be happening?
@AdamRoden  
@JuliusSweetland 

Version
 - Operating system: Windows 10
 - OptiKey version: 3.1.0

Steps to reproduce the issue
- I'm not sure how it happens, I was just switching from the main menu to the letters function. When correcting this problem by restoring its original size, perform the same steps as how the error occurred, but it didn't generate, it worked normally. 

Screenshots

![image](https://user-images.githubusercontent.com/71667237/103789400-b8869200-501e-11eb-955f-96fd8d6b027d.png)

screen alteration image.

**Comment by JorgeMattos** [comment]
Hi, Deselect this option.

![Capturar](https://user-images.githubusercontent.com/39384525/108612149-85c50d00-73c4-11eb-88b0-eccc17c942a0.PNG)

**Comment by freyesf** [comment]
thank you for replying, I will try the mentioned. @JorgeMattos
