### ISSUE TITLE
A Case for a Gaze Cursor Implementation

### ISSUE THREAD

**Issue by tqphan** [OptiKey/OptiKey#752]
In Windows Eye Control, there is a feature called “Gaze Cursor” that can help experienced users improve gaze accuracy. When enabled, a red dot is painted at the current gaze location. Some users may find a dot distracting and tend to follow the dot. However, I find that by knowing the position of the gaze point, I can make small eyes adjustments to compensate for small inaccuracies from the eye trackers. I think OptiKey should implement this feature.

**Comment by AdamRoden** [comment]
Hi @tqphan! Welcome to Optikey. Your issues are not going unheard. I like this idea. If you haven't found it yet, Optikey has a similar tool already built-in called magnetic cursor. However, I think at some point I would also like to have this gaze indicator option you speak of.
At the moment there are some significant changes pending, so your requests are on the back burner, but your feedback is appreciated, so stick with.

**Comment by AdamRoden** [comment]
@tqphan Are you still interested in this feature? I could add an option for a gaze position indicator if you are still interested.

**Comment by kmcnaught** [comment]
fwiw I just had a request from a user for this same thing. A visual indicator of gaze location that isn't actually moving the cursor.

**Comment by AdamRoden** [comment]
I did build the feature. I just never submit it for merge.

**Comment by tqphan** [comment]
@AdamRoden Hi, sorry I haven't been active in the last month.Yes, I still want this feature and thank you for implementing it.

**Comment by AdamRoden** [comment]
@tqphan I'll see about getting this merged soon. I appreciate your patience.

**Comment by AdamRoden** [comment]
@tqphan @kmcnaught The gaze indicator is available in the 3.2 pre-release. You can it in rows 6 and 7 of the visuals tabs of the management console.
