### ISSUE TITLE
Launching OptiKey minimised

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#756]
Is there a command line option to launch OptiKey minimised? I currently don't have OptiKey starting when Windows starts, because I don't want it covering almost a half of my desktop until I need to type. Most of the time I would need to minimise it straight away.

As a workaround, I've created a dynamic keyboard that I'll use as a start-up keyboard. It has just one key to open the real keyboard. I'm just not fully satisfied with the way it looks. What's the name of the circular icon that's shown when you minimise the keyboards with Minimise action? How do I reference it? Of course, it doesn't really matter what icon is used, but I'm so used to seeing that icon.

Also, I can't get the key to be as small as the built-in one. My dynamic keyboard's key is bigger and has huge borders even though I've set the width, height and symbolmargin values in the XML file.

This is the keyboard:
```
<Keyboard>
    <Name>Minimised</Name>
    <HideFromKeyboardMenu>True</HideFromKeyboardMenu>
    <PersistNewState>False</PersistNewState>
    <WindowState>Floating</WindowState>
    <DockSize>Full</DockSize>
    <Position>Bottom</Position> 
    <Width>96</Width>
    <Height>48</Height>  
    <HorizontalOffset>0</HorizontalOffset>
    <VerticalOffset>0</VerticalOffset>
    <SymbolMargin>0</SymbolMargin>
    <BorderThickness>0</BorderThickness>
    <BackgroundColor></BackgroundColor>
    <BorderColor></BorderColor>
    <Grid>
        <Rows>1</Rows>
        <Cols>1</Cols>
    </Grid>
    <KeyGroup Name="PrimaryKeys" CompletionTimes="666,1000,9999999" KeyDisabledOpacity=".2" />
    <Content>		
        <DynamicKey Width="1" ForegroundColor="gray">
	    <ChangeKeyboard BackReturnsHere="False">Finnish_Bottom</ChangeKeyboard>
            <Symbol>KeyboardIcon</Symbol>
            <KeyGroup>PrimaryKeys</KeyGroup>
	</DynamicKey>
    </Content>
</Keyboard>`
```

**Comment by tqphan** [comment]
Are you referring to this icon?
https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey.Core/Resources/Icons/SVG%20Source%20Files/ApplicationIcon.svg

All the icons can be found here
https://github.com/OptiKey/OptiKey/tree/master/src/JuliusSweetland.OptiKey.Core/Resources/Icons/SVG%20Source%20Files

Currently your keyboard is set as 96 width and 48 height and it seems to work for me. If you wanted a smaller still, I would adjust these values. Also you can try setting Opacity if you wanted a less visible key.

```
    <Width>96</Width>
    <Height>48</Height>  
```

As for starting OptiKey minimized, have you tried going into options under Visuals->Startup Keyboard and select "Minimised"?

**Comment by lsaranto** [comment]
Ah, yes. That's the icon. I went through the list, up and down, several times trying to come up with names for the icon. Application wasn't one of them.

This must again be a visuals related issue, that comes from the fact that I'm still using Windows 7. I wonder if it's some sort of library mismatch. I've gone as low as 20 with the numbers. The key doesn't get any smaller after a certain point. The limit is somewhere around 170 px for height. Using % doesn't change it.

Selecting Minimised as Start-up keyboard doesn't really work because when the view is restored, it then shows the Menu keyboard.

**Comment by AdamRoden** [comment]
@lsaranto The current  minimum limit for dynamic keyboards is 10% of screen size. However, there are some tricks.
Try this:
```
    <Keyboard>
    <Name>Minimised</Name>
    <HideFromKeyboardMenu>True</HideFromKeyboardMenu>
    <WindowState>Floating</WindowState>
    <Position>Bottom</Position> 
    <Width>96</Width>
    <Height>48</Height>  
    <BorderThickness>0</BorderThickness>
    <BackgroundColor>Transparent</BackgroundColor>
    <BorderColor>Transparent</BorderColor>
    <Grid>
        <Rows>2</Rows>
        <Cols>3</Cols>
    </Grid>
    <KeyGroup Name="PrimaryKeys" CompletionTimes="666,1000,9999999" KeyDisabledOpacity=".2" />
    <Content>		
        <DynamicKey Row="1" Col="1" ForegroundColor="gray">
	    <ChangeKeyboard BackReturnsHere="False">Finnish_Bottom</ChangeKeyboard>
            <Symbol>ApplicationIcon</Symbol>
            <KeyGroup>PrimaryKeys</KeyGroup>
    </DynamicKey>
    </Content>
</Keyboard>

**Comment by lsaranto** [comment]
@AdamRoden Thanks! That worked. I ended up using Row="0" and VerticalOffset so it hides the extra row off-screen.

**Comment by AdamRoden** [comment]
@lsaranto Glad to help. A word of caution, there is a Windows "security feature" where certain events will trigger any applications not contained in the screen bounds to be re-positioned.
