### ISSUE TITLE
Keyboard to work with Windows calculator.

### ISSUE THREAD

**Issue by JorgeMattos** [OptiKey/OptiKey#757]
...

**Comment by JuliusSweetland** [comment]
@JorgeMattos Thank you.
@AdamRoden If you have a second could you test the above dynamic keyboards and see if they are ready to be bundled with Optikey? Thanks.

**Comment by AdamRoden** [comment]
@JuliusSweetland I'm sorry. Something is missing. Which keyboards should I test?

**Comment by JuliusSweetland** [comment]
Hmm it's been closed. Maybe the attachment is missing. Don't worry. Thanks
