### ISSUE TITLE
Option to use old magnification method with mouse simulation tools

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#758]
**Is your feature request related to a problem? Please describe.**
I recently upgraded to the current version of OptiKey.  In the old version I had been using, the magnified screen portion (when using mouse simulation tools) always appeared in the center of the screen.  Now it appears near the first selection point.

I have difficulty targeting accurately near the edges of my screen.  I have had some difficulty selecting accurately on the magnified view when it is near the edge of the screen.  For example, I have especially struggled with scroll bars. 

**Describe the solution you'd like**
I would appreciate the option to use the old magnification method, with the magnified portion always appearing in the center of the screen.

I have looked for this option in the management console but have not been able to find anything that appears relevant. 

**Describe alternatives you've considered**
None 

**Additional context**
None

**Comment by AdamRoden** [comment]
@annakirkpatrick 
![image](https://user-images.githubusercontent.com/45572061/108772997-5842a580-7523-11eb-9c07-fd8039cba0e9.png)

**Comment by annakirkpatrick** [comment]
@AdamRoden Thanks! I just totally missed that setting.
