### ISSUE TITLE
Dynamic keyboard 'big hacker keyboard' has broken keys

### ISSUE THREAD

**Issue by annakirkpatrick** [OptiKey/OptiKey#759]
# How OptiKey was being used

I recently installed a new version and OptiKey, and it was cool to see that a few dynamic keyboards are now included and are copied by default into the appropriate directory.  It was even cooler to see that my Big Hacker Keyboard was included. 

While getting set up on a new computer with this new version of OptiKey, I tried to use the big hacker dynamic keyboard included with the install.

# What the user expected to happen

When I selected the dynamic keyboard, I expected a functional copy of my big hacker keyboard. 

# What the user actually experienced

Several keys on the keyboard are "broken" and generate an error message if pressed.  

Additionally, the arrow keys are misaligned because the space bar should be two keys wide. And the backspace key has been moved to a much less useful location.

# Version
 - Operating system and version: Windows 10
 - OptiKey version v3.1.0.0

# Steps to reproduce the issue

1. Install OptiKey 
2. Navigate to the dynamic keyboard menu 
3. Select big hacker keyboard

# Any other information that helps to describe and/or reproduce the problem

I had a copy of my original keyboard file, which still works fine.  So I am "up and running" with no problems.

I know that some changes were made to how dynamic keyboards are handled and that they are now much more powerful. I assume these changes are related to the changes to BigHackerKeyboard.xml. But I'm not sure exactly what was changed or why.

If my xml file needs to be "modernized" to comply with new formats, I can do that. I would just need some pointers on what needs to change. 

Regardless, we don't want Optikey to install with broken examples. :-)

# Screenshots

One of the error messages 

![error](https://user-images.githubusercontent.com/33188271/108763120-fbdd8700-751e-11eb-8407-b72d032565d2.png)

**Comment by AdamRoden** [comment]
@annakirkpatrick Thanks for the input. I can help you with any questions about the new dynamic keyboards. There are so many new features. It would be great if you update the Big Hacker Keyboard.

**Comment by tqphan** [comment]
Hi @annakirkpatrick 
I convert [your keyboard](https://github.com/tqphan/super-cool-keyboard/blob/main/src/BigHackerKeyboard.xml) to work with v3
I have not tested all the keys, so let me know if any keys that don't work

**Comment by kmcnaught** [comment]
I'm assuming this is resolved now, if there were any remaining issues please raise another issue.
