### ISSUE TITLE
Two ways to minimise produce different results

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#762]
I just stumbled upon the fact that Minimising using the FunctionKey does not behave the same way as when using the ChangeKeyboard key. This may also be related to an older issue with startup keyboards.

**Comment by AdamRoden** [comment]
@JuliusSweetland I took a look again and see that the root of it is that the FunctionKey enum 'Minimise' lacks the 'd' of the Keyboards enum 'Minimised' resulting in split whereby fixing an issue with one did not fix the other, and looking at one section of code and not the other it would be impossible to reproduce user reported issues. I feel like I just cracked an old cold case.

**Comment by JuliusSweetland** [comment]
@AdamRoden Great find! Is this potentially related to issues with Optikey sizing that we ran into occasionally with dynamic keyboards?

**Comment by AdamRoden** [comment]
> @AdamRoden Great find! Is this potentially related to issues with Optikey sizing that we ran into occasionally with dynamic keyboards?

@JuliusSweetland Without a doubt. I believe I fixed the old Minimise issue.

**Comment by JuliusSweetland** [comment]
Excellent. Raise a PR and I'll get it merged in.

**Comment by JuliusSweetland** [comment]
@AdamRoden Just to check is there a PR for this fix yet? I don't want to overlook it.

**Comment by AdamRoden** [comment]
@JuliusSweetland  No standalone PR. It is fixed in 749, so ideally no need for another PR.

**Comment by kmcnaught** [comment]
@AdamRoden sounds like this is fixed and can be closed?
