### ISSUE TITLE
AudioService Functioning Erratically

### ISSUE THREAD

**Issue by bigmutty** [OptiKey/OptiKey#763]
Sometimes Optikey will run fine and all the sounds will play, but other times Optikey runs, each time a sound tries to play this occurs:

2021-03-05 19:58:27,777 [ 1] ERROR JuliusSweetland.OptiKey.Services.AudioService: Exception encountered within the AudioService
System.ApplicationException: Bass was unable to create a stream from file 'Resources\Sounds\Click1.wav'
   at JuliusSweetland.OptiKey.Services.AudioService.PlaySound(String file, Int32 volume) in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\Services\AudioService.cs:line 161
[OptiKeyPro 1.log](https://github.com/OptiKey/OptiKey/files/6111042/OptiKeyPro.1.log)

**Comment by JuliusSweetland** [comment]
@bigmutty Anything in the windows event log?

**Comment by bigmutty** [comment]
What exactly would I look for? I didn't see anything in the locations in the event viewer that I thought to look.

**Comment by JuliusSweetland** [comment]
I would replicate the error in optikey and then look in the error or
application log for an entry at the right time linked to BASS. I'm
wondering if the library I use is logging a more useful error somewhere
else.

**Comment by bigmutty** [comment]
I use OptiKey on 2 computers on the same network, and it seems like either one or the other computer will have working sound in OptiKey. I tried exitting OptiKey on the one with sound and restarting Optikey on the one without sound, but that had no effect. I noticed when I restart my laptop when I'm away from my home network, Optikey will have sound.

**Comment by JuliusSweetland** [comment]
Hi Daryl. I can't think why this would affect optikey. Optikey does use a
licensed library to output some sounds (not voices), but I would not expect
multiple open copies of optikey to cause any issues. I don't think this is
related to optikey itself.

**Comment by bigmutty** [comment]
I just accidentally found something interesting. If I run OptiKey as an admin, the sound always works, but the OptiKey graphics don't draw on top of the start menu or Windows notifications.

**Comment by JuliusSweetland** [comment]
The admin mode difference to how Optikey is drawn makes some sense. Optikey is built with something called UIAccess enabled, but not for elevated accounts (running as admin). It may be that it doesn't work when run as admin. I have no idea why the sound is erratic though. That still doesn't make sense to me.

**Comment by kmcnaught** [comment]
I've added a log which will give us an extra error code when this happens, which should hopefully shine some light on this one when we roll the next release

**Comment by alexandre-mbm** [comment]
You can to try it opening from a shortcut at Start Menu folder.
