### ISSUE TITLE
Optikey is hanging on master branch

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#787]
Using recent (undeployed) code on master, Optikey is very very laggy, quickly becoming completely unresponsive. I can't even right click on it to quit cleanly. 

I did a git bisect and the issue is introduced in c10fe5a9e8d. Looking at Task Manager, it's clear that Optikey is firing on all cylinders. I profiled the code before and after and have included some screenshots. 

### Profile without issue 
0898bd5e
![profile_before](https://user-images.githubusercontent.com/12151404/148300469-57d62358-6a60-494c-a919-ccd3a7d5b799.PNG)

### Profile with issue 
c10fe5a9e  - truncated because I am unable to quit cleanly so the profiler doesn't capture the whole session
![profile_after](https://user-images.githubusercontent.com/12151404/148300574-3c587724-cafa-4395-8191-490b476d8afe.PNG)

This looks suspicious:
![profile_deserialize](https://user-images.githubusercontent.com/12151404/148300592-239cb593-bf32-44dd-90e6-f1d45b5eb3d0.PNG)

Maybe points at it being to do with my settings file?? I blew away all my config files for this testing, but it's possible I had "accidentally good" config previously, if that makes sense?

I also see these logs in the Visual Studio output (running c10fe5a9e8d). 

> Exception thrown: 'System.Xml.XmlException' in System.Xml.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in System.Xml.dll
Exception thrown: 'System.ArgumentNullException' in System.Core.dll

Weirdly I've been running this code for weeks now and the problem has only just arisen - I haven't been able to track down what has changed in my setup today. Some code I deployed yesterday is still working fine - but if I run the same code from Visual Studio I get the bad behaviour. 

I'm hoping this is to do with a bad state wrt settings rather than a fundamental performance limitation in the new code. I'd appreciate some other eyes on it.

**Comment by kmcnaught** [comment]
Here's an excellently recorded phone video of Task Manager for a more visceral demonstration of the performance issue...

https://user-images.githubusercontent.com/12151404/148301654-c5ba5343-cf00-4734-8bd4-516035652312.mp4

**Comment by kmcnaught** [comment]
Okay it looks like what's happening is that the `EyeGestureSource` is trying to deserialise a new `XmlEyeGestures` every time it receives a new point, but since my settings have an empty string for `Settings.Default.EyeGestureString`, this fails, requiring it tries again next time.

**Comment by kmcnaught** [comment]
Aha! In an earlier `user.config` I have found the value
```
<setting name="EyeGestureString" serializeAs="String">
    <value>&lt;EyeGestures /&gt;</value>
</setting>
```
If I manually put this in my current config (which has no such entry), the problem goes away. I don't know when this was populated - perhaps an earlier commit had it as a default? And yesterday I was testing some other things that involved resetting config.

From what I've read of the code, it seems like the `EyeGestureSource` is running always, even if it's not been enabled. If this is necessary, it's important that it bails out ASAP in the event that it's not enabled or correctly configured. 

We can get most of the way to a 'fix' by adding the guards at the top of the the `eyeGestureSubscription`:
```
var eyeGestureSubscription = pointSource.Sequence
.Where(_ => disposed == false)
.Where(_ => State == RunningStates.Running)
.Where(tp => tp.Value != null) //Filter out stale indicators - the fixation progress is not reset by the points sequence being stale
.Select(tp => new Timestamped<PointAndKeyValue>(tp.Value, tp.Timestamp))
.Buffer(2, 1) //Sliding buffer of 2 (last & current) that moves by 1 value at a time
.Subscribe(tps =>
{
    if (!Settings.Default.EyeGesturesEnabled) { return; }

    if (gestureList == null && String.IsNullOrEmpty(Settings.Default.EyeGestureString))
    {
        return;
    }

   ... all the existing code here ... 
}
```

However, this still leaves open the failure mode I've been seeing which would still occur if:
- gestures are enabled; and
- the `EyeGestureString` is not non-empty but incorrectly configured

Without figuring out all the rest of the implementation I'm not sure the best way to avoid this - it feels like it's not a good idea to have any (de)serialisation inside the point subscription, even if it's intended to only happen once sporadically. Ideally any changes to the gestures config (such as enabling for the first time or changing the XML spec) should be processed outside the point source subscription and then generate a new subscription if/when everything is correct. Equally if the gestures are turned off, it would be best if the sequence isn't instantiated until such time as it is turned on.

**Comment by AdamRoden** [comment]
@kmcnaught This piece of code and default file were meant to preempt the issue you are experiencing. Are you missing something related to this?
![image](https://user-images.githubusercontent.com/45572061/148397334-29de0c81-29b5-40a5-bcae-95d2ab9fc1ce.png)

**Comment by AdamRoden** [comment]
@kmcnaught The trouble is my goal was to make a Management Console view where Eye Gestures could be modified and tested on the fly without needing to restart Optikey. In order to meet that objective a service of some sort needs to be running watching for change. The Eye Gesture file is not meant to be manually edited. It is meant to be modified, imported, exported, and always validated by the management view.

Please look at the management view and let me know your thoughts. If you understand what I was trying to do, then maybe you'll see a simple solution.

**Comment by kmcnaught** [comment]
Thanks, that's helpful context, I hadn't seen the `ValidateEyeGesturesFile` logic. I do not currently have the EyeGestures folder or file. When I run on c81b2a25 (current master) and step through with a debugger I get the following behaviour:
- `Settings.Default.EyeGestureFile` is an empty string
- inside `XmlEyeGestures:ReadFromFile`, an exception is thrown when it tries to read from a non-existent file
- this exception is swallowed by `catch { }`
- so the installed file doesn't get copied and is still missing

**Comment by JuliusSweetland** [comment]
@kmcnaught Is this an issue that new or existing users would experience if they upgraded to the version on master? I ask as I've just renewed my open source code signing certificate with a view to creating a new release. Obviously I will hold off if there is still an issue. Thanks.

**Comment by kmcnaught** [comment]
I'm not sure yet whether they would get into the state that triggers this. The observations in my comment above suggest that they could be in this situation (since the `ValidateEyeGesturesFile` method doesn't seem to work) but I did deploy a fork recently to one user who didn't hit the problem, so the jury is out. 

If you are happy to wait a couple of weeks I am most of the way to adding joystick support as a trigger mechanism which would be great to get deployed.

**Comment by JuliusSweetland** [comment]
Sure I can wait. Joystick input (and all the switches that this might
enable) would be with the wait. That's been on my list since 2015

**Comment by JuliusSweetland** [comment]
Hi Kirsty

Just to let you know that I have a renewed certificate so I'm in a position
to create a new release when you are. Absolutely no rush, just letting you
know.

**Comment by kmcnaught** [comment]
This particular issue definitely needs some more testing before full deployment to be confident it won't affect any typical user setups/workflows

**Comment by JuliusSweetland** [comment]
@kmcnaught Agree. Is this something you are happy to look at?

**Comment by kmcnaught** [comment]
@JuliusSweetland I will put some guards in to make this safer

**Comment by JuliusSweetland** [comment]
I appreciate your help. Thanks

**Comment by JuliusSweetland** [comment]
@kmcnaught Are you happy that this can be closed now?

**Comment by kmcnaught** [comment]
Yes
