### ISSUE TITLE
Remove maximum size rules for dynamic keyboards

### ISSUE THREAD

**Issue by hyperdeath666** [OptiKey/OptiKey#788]
This is closely related to issue #785

I have recently been experimenting with positioning keyboards in physical space (i.e. not on the monitor itself), which is possible by using large vertical and horizontal offset values. For example, as I have configured things now, if I look at the left speaker on my desk, this performs a left click, whereas if I look at the right speaker on my desk, this performs a right click. I find this to be a very useful way to interact with my eye tracker, as I find I am more accurately able to trigger large buttons in physical space than small ones on my monitor (and as an added bonus, buttons in physical space do not take up screen real estate).

To accomplish this, I am currently running multiple instances of optikey, with each button corresponding to its own instance, and running as its own keyboard. But this is inconvenient for a number of reasons, and I believe I could accomplish the same functionality with a single keyboard if I could make the keyboard larger than the display size of my monitor (for my purposes, 300% would suffice, but larger values provide more flexibility). As matters stand, it appears dynamic keyboards cannot be larger than the current monitor size - is it possible to remove this limitation, perhaps (as somebody suggested regarding issue 785) by setting some explicit flag in the dynamic keyboard xml file?

Apologies if this is already possible somehow - I've been looking for a way to do this, but have been unable to find one.

**Comment by AdamRoden** [comment]
@hyperdeath666 
There is a hard limitation in that you cannot make any Windows application larger than your desktop screen and all visual elements must be contained in a window. To work around that limitation, the next release of Optikey will incorporate a new feature called Gestures that will allow you to create off-screen regions that will behave like dynamic keys.

**Comment by hyperdeath666** [comment]
Ah, got it. That sounds like a great workaround. Thanks!
