### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by Loksta13** [OptiKey/OptiKey#792]
# How OptiKey was being used

[Please complete this section]

# What the user expected to happen

[Please complete this section]

# What the user actually experienced

# Version
 - Operating system and version: [e.g. Windows 10]
 - OptiKey version [e.g. v2.17.0]

# Steps to reproduce the issue

# Any other information that helps to describe and/or reproduce the problem

# Screenshots

**Comment by kmcnaught** [comment]
Hi @Loksta13 did you have issues running Optikey on Windows 11?
