### ISSUE TITLE
Look to scroll Windowed mode isn't working

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#796]
With the latest code, trying to scroll with the "Window" option for Scrolling point and boundary results in the scroll centre in the top-left of the screen, and the scroll effect applies to all windows (ie the bound also doesn't work). See video:
https://www.loom.com/share/c3653d096f904610ba30a2efc35e244d

My settings are default except changing to "Window"
![image](https://user-images.githubusercontent.com/12151404/156168786-27155e77-bbf4-4548-ac78-ed57c68ac78b.png)

The behaviour is the same with both the expanded and minimised mouse keyboards. If docked at the top it still uses the screen top left (i.e. where the keyboard is) which makes me think there's a null calculation happening somewhere. I am using a single monitor so there isn't an extended desktop interfering.

**Comment by kmcnaught** [comment]
@JuliusSweetland @AdamRoden I have verified the issue starts with https://github.com/OptiKey/OptiKey/commit/d4773de955d713f46ceb99c093ad85354d735327 - "Make Look to scroll default"

**Comment by AdamRoden** [comment]
@JuliusSweetland @kmcnaught 
I fixed the issue, but question whether there is benefit to having the option for look to scroll bounds or if we would be better off to eliminating the bounds option and simply always use the versatile screen at point bound setting.

**Comment by JuliusSweetland** [comment]
@AdamRoden @kmcnaught Thanks Adam. A new pre-release of 3.2.0 is now available for testing. FYI if you already installed the last 3.2.0 pre-release you'll have to manually uninstall it first.

**Comment by kmcnaught** [comment]
Thanks for the quick fix @AdamRoden. I seem to remember finding the "Window" bounds really useful for situations like typing into this tiny comment box without scrolling the whole issue thread. But I haven't used LTS for a long time so more than happy to have a separate discussion. I think @annakirkpatrick was planning to try out the LTS options soon which will be another user perspective.

**Comment by annakirkpatrick** [comment]
@kmcnaught @AdamRoden Thanks for taking care of this bug!  I'll be trying out look-to-scroll in my daily work as soon as there's an official release with this fix and the new joystick input method.  I'll let you know how it goes!

**Comment by annakirkpatrick** [comment]
I just tested [3.2.0_pre-release-2](https://github.com/OptiKey/OptiKey/releases/tag/v3.2.0_pre-release-2) on my personal computer.  Both Window-mode look-to-scroll and joystick input (DirectInput) seem to be working!

**Comment by JuliusSweetland** [comment]
Great news, thanks Anna
