### ISSUE TITLE
Scroll up disabled?

### ISSUE THREAD

**Issue by JuliusSweetland** [OptiKey/OptiKey#809]
# How OptiKey was being used
Just started up

# What the user expected to happen
Scroll UP key to be enabled

# What the user actually experienced
Scroll UP key was disabled

# Version
v3.2.0

# Steps to reproduce the issue
Open mouse keyboard and expand it.

# Any other information that helps to describe and/or reproduce the problem

# Screenshots
![image](https://user-images.githubusercontent.com/4722561/158008700-85adf436-f311-4b57-8d72-cc56b999633f.png)

**Comment by JuliusSweetland** [comment]
@AdamRoden Is this intentional?

**Comment by JuliusSweetland** [comment]
@AdamRoden I've found and fixed the ScrollToTop key issue. I guess there was a merge problem. I will include the fix in the next release (3.2.1), but I'm still not sure how to disable look to scroll if a user wanted to continue using scroll up/down keys.

**Comment by JuliusSweetland** [comment]
@AdamRoden I've had a go at this, reinstating a setting called "Look To Scroll is the default scrolling method". It's in the pre-release of v3.2.1 here: https://github.com/OptiKey/OptiKey/releases/tag/v3.2.1_pre-release-1

The setting looks like this:
![image](https://user-images.githubusercontent.com/4722561/158034499-a5daa2c6-0ad8-4a58-97c4-993b61363cbb.png)

**Comment by JuliusSweetland** [comment]
Released

**Comment by falkokatze** [comment]
Hello. Thanks for such useful software. I installed 3.2.1.0 and I still have a Disabled scroll up key. If there's somethiing I can do to correct it please let me know. Cheers.

**Comment by JuliusSweetland** [comment]
@falkokatze I'm afraid I cannot replicate your problem - everything is fine when I test. Could you please try upgrading to the latest pre-release and try again: https://github.com/OptiKey/OptiKey/releases/tag/v3.2.2_pre-release-1

**Comment by falkokatze** [comment]
Thanks for your reply. I attached a photoo. I don't know if it is a bug or if it is ssomething in my system. But I understand even companiies with 50 employees have bugs. I've been using 3.1 which is very cool. Thanks. Have a nice dayy
![BUG](https://user-images.githubusercontent.com/85040002/159105097-56cb5a17-815e-4b14-8935-59d79a2c1246.gif)
.

**Comment by JuliusSweetland** [comment]
@falkokatze Actually there was another bug. Please try the new pre-release here: https://github.com/OptiKey/OptiKey/releases/tag/v3.2.2_pre-release-3

**Comment by falkokatze** [comment]
cool. bug is gone. thanks.

**Comment by JuliusSweetland** [comment]
@falkokatze Good news. Yes - I'm glad you are enjoying it.
