### ISSUE TITLE
Silent crashes on 3.2.0

### ISSUE THREAD

**Issue by hyperdeath666** [OptiKey/OptiKey#810]
Since installing 3.2.0, Optikey has been crashing regularly (the crashes are silent, i.e. no notification or error message is displayed). I've been trying to find steps that reliably reproduce the crash but I'm not having any luck; at the moment, it feels random, and typically occurs within 30-60 minutes of use. The log consistently shows the following immediately before the crash (some full logs are attached; more can be collected):

`2022-03-11 18:58:58,931 [11] DEBUG JuliusSweetland.OptiKey.OptiKeyApp: NBUG:NBugError - An exception occurred during bug report generation process. See the inner exception for details.
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at JuliusSweetland.OptiKey.UI.Windows.CrashWindow..ctor() in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\UI\Windows\CrashWindow.xaml.cs:line 14
   at JuliusSweetland.OptiKey.OptiKeyApp.<>c.<AttachUnhandledExceptionHandlers>b__20_1(Object sender, CustomUIEventArgs args) in C:\dev\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\OptiKeyApp.cs:line 590
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at NBug.Core.UI.Custom.CustomUI.ShowDialog(UIMode uiMode, SerializableException exception, Report report)
   at NBug.Core.UI.UISelector.DisplayBugReportUI(ExceptionThread exceptionThread, SerializableException serializableException, Report report)
   at NBug.Core.Reporting.BugReport.Report(Exception exception, ExceptionThread exceptionThread)`

# Version
 - Windows 10
 - Tobii 5

# Other Info:
I exclusively use dynamic keyboards. Almost all of my keys do something and also change the keyboard. I typically run multiple instances of Optikey, but I have confirmed the crash occurs even if I only run one instance.

[OptiKeyPro - Copy (7).log](https://github.com/OptiKey/OptiKey/files/8237921/OptiKeyPro.-.Copy.7.log)
[OptiKeyPro - Copy (8).log](https://github.com/OptiKey/OptiKey/files/8237922/OptiKeyPro.-.Copy.8.log)
[OptiKeyPro - Copy (6).log](https://github.com/OptiKey/OptiKey/files/8237920/OptiKeyPro.-.Copy.6.log)

**Comment by AdamRoden** [comment]
@hyperdeath666 I don't know your cause, but we have one known issue related to auto-capitalization. If you turn it off does it solve your problem?
![image](https://user-images.githubusercontent.com/45572061/158028250-3ee5bcc2-f00e-4951-be1e-7c3c6d9ef2dd.png)

**Comment by hyperdeath666** [comment]
Unfortunately, no - just tried it and it still crashed. It took longer this time, so the log file is too large to post, but it looks similar to the other ones.

**Comment by JuliusSweetland** [comment]
@hyperdeath666 Please try the pre-release of v3.2.2 which addresses the exception in your logs: https://github.com/OptiKey/OptiKey/releases/tag/v3.2.2_pre-release-1

I'm not sure what caused the original exception. Your logs are a problem submitting the error report back to me, so I've made a change to prevent crash loops because of that.

@AdamRoden What is the known issue with auto-capitalisation?

**Comment by AdamRoden** [comment]
@JuliusSweetland #789 is the known issue.

**Comment by hyperdeath666** [comment]
Thanks so much @JuliusSweetland. I've been running 3.2.2 all day with no crashes or other obvious problems, so unless you'd prefer otherwise, I'm tempted to close this.

**Comment by JuliusSweetland** [comment]
Excellent news. I'll close.

**Comment by hyperdeath666** [comment]
I spoke too soon - a few crashes today. The common thread across the logs appears to be this:

`2022-03-15 16:15:17,848 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: CommandList: Change keyboard
2022-03-15 16:15:17,848 [ 1] INFO  JuliusSweetland.OptiKey.UI.ViewModels.MainViewModel: Look to scroll is no longer active.
2022-03-15 16:15:17,848 [ 1] DEBUG JuliusSweetland.OptiKey.UI.Controls.KeyboardHost: GenerateContent called. Keyboard language is 'EnglishUS' and Keyboard type is 'JuliusSweetland.OptiKey.UI.ViewModels.Keyboards.DynamicKeyboard'
2022-03-15 16:15:17,848 [ 1] DEBUG JuliusSweetland.OptiKey.Services.InputService: PointToKeyValueMap property changed (setter called with null map).
2022-03-15 16:15:17,848 [ 1] DEBUG JuliusSweetland.Opti
[OptiKeyPro15.log](https://github.com/OptiKey/OptiKey/files/8257070/OptiKeyPro15.log)
Key.Services.InputService: DisposeMultiKeySelection called.
2022-03-15 16:15:17,849 [12] DEBUG JuliusSweetland.OptiKey.OptiKeyApp: NBUG:NBugTrace - Starting to handle a System.AppDomain.UnhandledException.
2022-03-15 16:15:17,849 [12] DEBUG JuliusSweetland.OptiKey.OptiKeyApp: NBUG:NBugTrace - Starting to generate a bug report for the exception.
`

The crashes are sufficiently infrequent that they don't bug me much, so don't rush to fix this on my account. Full log attached if it helps.

**Comment by JuliusSweetland** [comment]
@kmcnaught What do you make of the log file? Lots of exceptions when trying to play audio files, but I think these are ignorable. Then nothing obvious until NBUG logs this:

2022-03-15 16:26:51,361 [ 5] DEBUG JuliusSweetland.OptiKey.OptiKeyApp: NBUG:NBugTrace - Current report count is at its limit as per 'Settings.MaxQueuedReports (3)' setting: Skipping bug report generation.

**Comment by kmcnaught** [comment]
@JuliusSweetland have you been getting crash dumps via email from log4net? That would be helpful, please forward it if you have one.

I've often found when a crash happens, the local log file ends prematurely without information about the actual source of the error. On my own forks I added extra flushing but it didn't fully resolve the issue so I never submitted the change, assuming that the information you get by email was better!

My guess with the `MaxQueuedReports` error is that something is going wrong with the report upload. I believe the upload happens the next time Optikey is launched? So in this case it is saying that there are 3 pending bug reports not yet sent, so it's not going to create any more. 

We could consider changing the log4net config to also dump the file locally for pre-releases, so that we have a backup option for requesting a manual upload from a user. Alternatively, if there are still queued reports then @hyperdeath666 may be able to find one to send us, depending whether you already have any to inspect.

**Comment by JuliusSweetland** [comment]
@kmcnaught I don't I'm afraid. I had an attempt to fix the crash reporting a while ago, but they've not worked for a while. Maybe we need to get a ticket in to disable the reporting as users seem to generally be pretty good at emailing over logs?

**Comment by kmcnaught** [comment]
It's also possible to get Windows to create CrashDumps by setting a registry key, but only if log4net is completely disabled (because otherwise it catches the exceptions). CrashDumps are more useful than logs in my experience

**Comment by kmcnaught** [comment]
This particular message in the first logs shared is a bit fishy: 

`System.InvalidOperationException: The calling thread must be STA, because many UI components require this. `. 

It sounds like this exception is happening when the crash-handling is invoked, in which case it is unrelated to the original source of the crash. It might be worth triggering #789 deliberately using the installed release (there are easy reproduction steps) and seeing if it gives this particular exception - it feels plausible since #789 is to do with an exception being thrown from somewhere within the XAML UI logic. It could be that somehow the nbug exception handling can be routed onto an unexpected thread, which is something we'd want to fix separately. Either way the `calling thread must be STA` exception is probably not directly linked to the root cause here.

**Comment by kmcnaught** [comment]
Ah okay great, I missed some of the earlier back and forth. I expect your commit has solved that log, which _may_ have been related to the #789 issue, and there is still the other (unknown) crash which we don't seem to have many leads on. I'd have thought the best course of action would be to find a way to get a better crash dump and then ask @hyperdeath666 to reproduce

**Comment by AdamRoden** [comment]
I hit one while testing. Placing stack here for follow-up.

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at JuliusSweetland.OptiKey.Observables.TriggerSources.KeyFixationSource.<>c__DisplayClass26_1.<get_Sequence>b__10(Int64 _) in C:\Users\adamr\OneDrive\Documents\GitHub\OptiKey\src\JuliusSweetland.OptiKey.Core\Observables\TriggerSources\KeyFixationSource.cs:line 205
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Timer._.Invoke()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass1`1.<Schedule>b__0(Object _)
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c__DisplayClass1.<QueueUserWorkItem>b__0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    System.Collections.Generic.Dictionary<TKey, TValue>.this[TKey].get(TKey)
    JuliusSweetland.OptiKey.Observables.TriggerSources.KeyFixationSource.get_Sequence.AnonymousMethod__10(long) in KeyFixationSource.cs
    System.Reactive.AnonymousSafeObserver<T>.OnNext(T)
    System.Reactive.Linq.ObservableImpl.Timer._.Invoke()
    System.Reactive.Concurrency.Scheduler.Invoke(System.Reactive.Concurrency.IScheduler, System.Action)
    System.Reactive.Concurrency.DefaultScheduler.Schedule.AnonymousMethod__0(object)
    System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.QueueUserWorkItem.AnonymousMethod__0(object)
    System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object)
    System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, object, bool)
    System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, object, bool)
    ...
    [Call Stack Truncated]

**Comment by kmcnaught** [comment]
@AdamRoden great, thanks! I presume your key fixation source was dwells, right?

**Comment by JuliusSweetland** [comment]
I haven't had a chance to debug this yet. Is there a theory on what is
happening here?

**Comment by kmcnaught** [comment]
Here's my initial train of thought... 

@AdamRoden's crash seems to suggest a Dictionary `KeyNotFound` exception inside the `KeyFixationSource`'s Sequence. The changes to `KeyFixationSource` are related to the `timeToCompleteTriggerByKey` changes - looks like it used to be a string and is now a TimeSpan. So my initial guess would be that the `timeToCompleteTriggerByKey` dictionary is at fault somehow related to these changes. 

You can see the file diff here:
https://gist.github.com/kirstym-student/ac5dfde4239a902303ebe9698a182b0d/revisions

PS - does anyone know how to get a direct single-file diff within github?? I tried https://stackoverflow.com/questions/14500240/how-can-i-generate-a-diff-for-a-single-file-between-two-branches-in-github but it doesn't seem to work any more..

**Comment by kmcnaught** [comment]
Huh, I notice that the other Dictionaries in the `KeyFixationSource` are `ConcurrentDictionary`s but those relating to overrides are just `Dictionary`s. Are these liable to be modified from multiple threads? That could explain a sporadic exception.

**Comment by JuliusSweetland** [comment]
@kmcnaught Yes that looks like it: L205 is where the exception is coming from:
![image](https://user-images.githubusercontent.com/4722561/159566778-cbff4721-9b23-405f-b4cc-28f73dc4a1bb.png)

**Comment by kmcnaught** [comment]
@AdamRoden it looks slightly fishy to me that this comparison (now line 204)
` if (lockDownAttemptTimeout > TimeSpan.Zero)`
has changed to 
`if (fixationTimeout != incompleteFixationTtl)`

In particular going from `>` to `!=` for a `TimeSpan`

Could this be the issue? I have not sat down and followed all the logic yet but it seems suspicious

**Comment by AdamRoden** [comment]
Let me review it before I answer because right now I don't know and need to refresh my memory.

**Comment by AdamRoden** [comment]
> @AdamRoden it looks slightly fishy to me that this comparison (now line 204) ` if (lockDownAttemptTimeout > TimeSpan.Zero)` has changed to `if (fixationTimeout != incompleteFixationTtl)`
> 
> In particular going from `>` to `!=` for a `TimeSpan`
> 
> Could this be the issue? I have not sat down and followed all the logic yet but it seems suspicious

@kmcnaught I think the issue is that `fixationTimeout` was populated by `overrideTimesByKe`y, but then `overrideTimesByKey` was cleared by a `KeyboardHost` during a change of keyboard. The `if ("~")` evaluation needs to re-check to ensure the key is still in the dictionary. I believe this is a different cause than the other silent crashes.

`if (overrideTimesByKey != null && overrideTimesByKey.ContainsKey(fixationCentrePointAndKeyValueCopy.KeyValue))`

**Comment by JuliusSweetland** [comment]
It looks like we just need to follow the same pattern used elsewhere and revert to using TryGet instead of the indexer lookup?

**Comment by kmcnaught** [comment]
@AdamRoden I have time I can look into a fix tomorrow if you haven't already made progress?

**Comment by AdamRoden** [comment]
@kmcnaught All I know is the one line should definitely be:

 `if (overrideTimesByKey != null && overrideTimesByKey.ContainsKey(fixationCentrePointAndKeyValueCopy.KeyValue))`

Beyond that, I don't really know about the other silent crashes. I'm using an AutoHotKey script that runs on a timer in the background and launches Optikey whenever it is not running.

**Comment by AdamRoden** [comment]
@kmcnaught Good find. I don't know if there is a reason for it, but the minimum value for the `defaultLockOnTime` is actually not zero, but one, so it may be better ignore a zero value.
```
            if (overrideTimesByKey.TryGetValue(keyValue, out var timeSpanOverrides) 
                && timeSpanOverrides.LockOnTime > TimeSpan.Zero)
            {
                return timeSpanOverrides.LockOnTime;
            }
            
            return defaultLockOnTime;
```

**Comment by kmcnaught** [comment]
If we ignore for a moment your observation about the minimum value being 1, then I believe this PR #823 is a simple fix for the issue. 

@JuliusSweetland was there any technical reason why the LockonTime in the Settings has a minimum value of 1 or was it just an arbitrary bound when setting up the UI? It's working fine with zero lockon when this is specified via XML keyboards. Any objection to us continuing to allow it?

**Comment by JuliusSweetland** [comment]
What is the measurement, ms? If so there's no practical difference between
0 and 1 so I don't mind which we set as the min value on this setting.

**Comment by kmcnaught** [comment]
Yes, milliseconds to lock onto a key. 👍

**Comment by JuliusSweetland** [comment]
Then either will work, but if you make 0 a valid value then how can you
tell if the value is unset (do you need to?) as default is 0?

**Comment by kmcnaught** [comment]
I've made it an optional so you know if it's been set or not. I'm not keen on the idea of having zero be used as an implicit "not set" signifier, as that would be very confusing when a user tries to set a key to zero lock-on and ends up with non-zero lockon.

**Comment by JuliusSweetland** [comment]
Sounds sensible, thanks

**Comment by AdamRoden** [comment]
Well, I believe one more fix is necessary in `DynamicKeyboard.xaml.cs` because in the current state it uses a `LockOnTime > 0` condition and now we want to allow `LockOnTime >= 0`.

**Comment by kmcnaught** [comment]
Ah okay I didn't realise it was restricted there also, I will make that change.

**Comment by kmcnaught** [comment]
@AdamRoden is this change here okay? https://github.com/OptiKey/OptiKey/pull/823/commits/f621a197c46af64a82b595237cc38f9ad8f02f60 
Thanks for the heads up

**Comment by hyperdeath666** [comment]
@kmcnaught Thank you! I've been on 3.2.3.0 for 2 days now and have had 0 crashes. This could still be random noise, and I'll post an update if it crashes, but it's certainly looking like the problem is fixed.

**Comment by JuliusSweetland** [comment]
Yes that sounds like a likely suspect. In which case we could change to a
concurrent dictionary.
