### ISSUE TITLE
Look to scroll sometimes not working

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#818]
I'm running v3.2.2 from Visual Studio. 

A few times this evening I've tried to use LTS and not seen any scrolling or deadzone. It usually stays in this state for a while, i.e. I turn LTS off and on again and it still doesn't work. At some point it starts working again, possibly only after alt-tabbing to a different app - but this doesn't always fix it, I haven't managed to get a consistent set of steps to reproduce, but it is always accompanied by these logs in the console:

```
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-5' BindingExpression:Path=ActiveLookToScrollMargins.Top; DataItem='MainViewModel' (HashCode=19595720); target element is 'RowDefinition' (HashCode=8774784); target property is 'Height' (type 'GridLength')
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-5' BindingExpression:Path=ActiveLookToScrollMargins.Bottom; DataItem='MainViewModel' (HashCode=19595720); target element is 'RowDefinition' (HashCode=59065489); target property is 'Height' (type 'GridLength')
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-5' BindingExpression:Path=ActiveLookToScrollMargins.Left; DataItem='MainViewModel' (HashCode=19595720); target element is 'ColumnDefinition' (HashCode=54290376); target property is 'Width' (type 'GridLength')
System.Windows.Data Error: 5 : Value produced by BindingExpression is not valid for target property.; Value='-5' BindingExpression:Path=ActiveLookToScrollMargins.Right; DataItem='MainViewModel' (HashCode=19595720); target element is 'ColumnDefinition' (HashCode=18029231); target property is 'Width' (type 'GridLength')
```

I have had the gaze indicator on most of the time I've been testing so it is probably the case that it is only happening with the gaze indicator present, but it's sporadic enough I can't be sure.

I am using two monitors, the primary is on the right (with Optikey) and when it works it's consistently scrolling on the correct screen so I think that is unrelated.

There is another log in the console which I now believe is benign: 
```
Exception thrown: 'System.ArgumentException' in PresentationFramework.dll
System.Windows.Data Error: 6 : 'TargetDefaultValueConverter' converter failed to convert value '-∞' (type 'Double'); fallback value will be used, if available. BindingExpression:Path=ActiveLookToScrollDeadzone.Height; DataItem='MainViewModel' (HashCode=54373085); target element is 'RowDefinition' (HashCode=11864197); target property is 'Height' (type 'GridLength') ArgumentException:'System.ArgumentException: 'value' parameter cannot be Infinity.
   at System.Windows.GridLength..ctor(Double value, GridUnitType type)
   at System.Windows.GridLengthConverter.ConvertFrom(ITypeDescriptorContext typeDescriptorContext, CultureInfo cultureInfo, Object source)
   at MS.Internal.Data.DefaultValueConverter.ConvertHelper(Object o, Type destinationType, DependencyObject targetElement, CultureInfo culture, Boolean isForward)
   at MS.Internal.Data.TargetDefaultValueConverter.Convert(Object o, Type type, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.ConvertHelper(IValueConverter converter, Object value, Type targetType, Object parameter, CultureInfo culture)'
```

This is due to this initialisation: `private Rect activeLookToScrollDeadzone = Rect.Empty` and goes away once the deadzone has been initialised, so it probably isn't causing any issues.

My LTS settings are:
![image](https://user-images.githubusercontent.com/12151404/159793540-329c4dea-6e2a-4585-9a77-fe151c91c5b0.png)

and I've mainly been using `Gaze Indicator = Monical`

**Comment by kmcnaught** [comment]
Okay I got a breakpoint in for this scenario and it looks like the gaze indicator "window" is indeed being selected as the bounds for scrolling, which is smaller than my deadzone and therefore gives negative margins. @AdamRoden this is something you found and fixed previously, right? Have we lost the fix or is it just not working all the time? There were a couple of changes back and forth that I didn't fully follow.

![image](https://user-images.githubusercontent.com/12151404/159796667-879b9c95-a3d4-44e5-a461-6192eace63e3.png)

In addition to fixing this bug, it might be worth adding a check for negative margins, and turning scroll off in this scenario? Since you don't see the boundary in this case, you don't have any visual feedback of the fact it has failed.

**Comment by AdamRoden** [comment]
@kmcnaught Everything is fine for me in the 3.2.2 release under the conditions you describe. I only have one monitor. You do understand that the LTS has a transparency effect now, so it is invisible when you are in the deadzone and becomes more opaque as you move away from the deadzone. Other than that, I have noted differrin behaviors for Optikey when running from Visual Studio vs a signed release, but this was not something I had issues with.

I will say that the code to isolate the correct window under the cursor has been picky, so perhaps it can be further improved.

**Comment by AdamRoden** [comment]
@kmcnaught I suppose we could add something more here like hiding the gaze indicator window when doing the search for front most. Like I said, I'm not able to reproduce, so I wouldn't know for sure if my change would fix it.

**Comment by AdamRoden** [comment]
@kmcnaught Would this fix it?
![image](https://user-images.githubusercontent.com/45572061/159930722-af982a50-375b-4aff-b60a-c7e7a85f0256.png)
```
        private IntPtr HideCursorAndGetHwndForFrontmostWindowAtPoint(Point point)
        {
            // Make sure the cursor is hidden or else it may be picked as the front-most "window"!
            ShowCursor = false;

            //Temporarily hide any gaze indicators
            var showCrosshair = ShowCrosshair;
            var showMonical = ShowMonical;
            ShowCrosshair = false;
            ShowMonical = false;

            var result = GetHwndForFrontmostWindowAtPoint(point);

            ShowCrosshair = showCrosshair;
            ShowMonical = showMonical;

            return result;
        }
```

**Comment by kmcnaught** [comment]
I think your comment re: Visual Studio is the answer. I get it 90%+ of the time when running in Debug mode, even with the suggested change to `HideCursorAndGetHwndForFrontmostWindowAtPoint`. I have not managed to replicate it either in Release mode or with the installed version. I shall close this as a weird VS quirk.
