### ISSUE TITLE
How to test my changes with no AdvancedInstaller's license?

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#856]
I see the [`Build and deploy with AdvancedInstaller.md`](https://github.com/OptiKey/OptiKey/blob/master/Build%20and%20deploy%20with%20AdvancedInstaller.md) "tutorial", and I want to know if I can to adapt the step-to-step by making a workaround to generate useful set of binary files **whitout** the AdvancedInstaller.

Why? Because the 30 days Trial will are not sufficient for me. And I think that I don't need installers...

PS.: Maybe I'm asking a silly question because I haven't even started installing the tools yet, but I am curious regards the [`Deployment.md`](https://github.com/OptiKey/OptiKey/blob/master/docs/Deployment.md) approach.

**Comment by kmcnaught** [comment]
If you build the project in Release mode, you should be able to run the app from the `bin` directory without installing - you can move this to another computer, so long as you include the whole `bin` directory - i.e. everything in `[base path]\OptiKey\src\JuliusSweetland.OptiKey.Pro\bin\Release`

The one thing that **won't** work is the elevated UIAccess, which requires you to (a) sign the app with a code signing certificate and (b) install the app properly. This will mean that Optikey won't be able to sit on top of some full screen applications, including (I believe) the Windows log in and some other system dialogs? But for many people this won't be a problem.

**Comment by alexandre-mbm** [comment]
Let me see if I am understanding it. We here need only:

1. Do `git clone` and open the project at **Visual Studio Community**
1. Run the **"Build"** task (for the `OptikeyDeployment.sln` entire) **as Release**
1. Move the result to that `bin/Release` directory
1. Restart the Optikey instance 

@kmcnaught, odes it mean this "private" building+deploy will can to be achieved with **VSCode** (or `dotnet.exe` only) later?

**Comment by kmcnaught** [comment]
If you are just running it on your own computer for testing, you just need to:

1. Do git clone and open the project at Visual Studio Community **2017**
2. Run the "Build" task (for the OptikeyDeployment.sln entire) as Release

Then either:
3. Right click on JuliusSweetland.Optikey.Pro project and select "Set as startup project" 
![image](https://user-images.githubusercontent.com/12151404/186885804-8f302dc1-1509-48ae-a0cb-87dfbf4348dd.png)
4. Hit "Start" to run the application

Or:
3. Navigate to `[base path]\OptiKey\src\JuliusSweetland.OptiKey.Pro\bin\Release` and run OptikeyPro.exe directly

Note that the app will have a different settings file compared to the installed one, so you will need to set all your preferences again. There will also be a different settings file for a Debug build vs a Release build which can be confusing if you are debugging things.

If you want to use your custom app on another PC (for instance for your father to use) then you will need to copy the whole `bin/` directory, and run the executable from inside the directory. There will be some limitations which may or may not affect your use case.

**Comment by kmcnaught** [comment]
> @kmcnaught, does it mean this _"private" building+deploy_ will can to be achieved with **VSCode** (or `dotnet.exe` only) later?

Possibly, if you can get VS Code supports the .NET Framework 4.6, but I don't know for sure and cannot advise on how to set it up. It would be simplest to use Visual Studio Community 2017 (or 2019 I think - but not 2022) so I can answer any questions you have :-)

**Comment by alexandre-mbm** [comment]
> 2\. Run the "Build" task (for the **OptikeyDeployment.sln** entire) as Release

I have used ``Optikey.sln`` with success...
