### ISSUE TITLE
Discussion: Please offer thoughts on EyeGestures & offscreen keys

### ISSUE THREAD

**Issue by AdamRoden** [OptiKey/OptiKey#861]
1. Does anyone use eye gestures? If yes, please explain. 
Unless someone has come up with a creative use I intend to scrap them and implement offscreen keys as a replacement.

2. Does anyone want offscreen keys? If yes, please explain the action and desired position.
They will probably only be available when using dynamic keyboards, but let's hear any requests.

3. I've completed initial development of offscreen keys for dynamic keyboards. 
Here's how they work:
    - They are defined in the `Content` section of a keyboard. 
    - They inherit all the properties of a dynamic key, but instead of specifying their position in the grid you define a rectangular gaze region to indicate where to look to progress the key. 
    For example, ~~`<PopupKey Left="-.2" Top="1" Width=".2" Height=".2" ... />`~~ `<Popup GazeRegion="-.2,1,.2,.2"><Action>Sleep</Action><Symbol>SleepIcon</Symbol></Popup>` would create a Sleep key with width and height equal to 20% of the screen size, and positioned to the left and below the screen. 
    - When you look at the gaze region a popup of the same size and having all the visual properties of the key opens and appears on the screen providing visual feedback of what you are selecting and your selection progress.

I'm open to questions, comments, and suggestions.

**Comment by alexandre-mbm** [comment]
> I've completed initial development of offscreen keys for dynamic keyboards.

Where is it? I want to test them. I think it changing configs. For example, `LockOnTime`  and `CompletionTimes` for some key.

**Comment by AdamRoden** [comment]
> > I've completed initial development of offscreen keys for dynamic keyboards.
> 
> Where is it? I want to test them. I think it changing configs. For example, `LockOnTime` and `CompletionTimes` for some key.

The code, (along with a work in progress keyboard layout editor for management console) can be found here: https://github.com/AdamRoden/OptiKey

**Comment by alexandre-mbm** [comment]
I want time to try run your code **after.**  Currently I need validate configurations in the  simplified dynamic keyboard with two steps for typing. It can have bug on _lock-on_ for the second step. Also I need extra automation to make the adjusts. Thanks.

Do you intent **to rebase** your master branch with more descritive message commits?

**Comment by tqphan** [comment]
@AdamRoden Will the offscreen keys exist independently from a keyboard layout? Currently, I'm using gaze gestures but not at full capacity. I'm only using it as offscreen keys. I use it mostly for games. For example, I look top-left of the screen to activate a key. So as long as it's independent from the current keyboard layout, it will work for me.

**Comment by AdamRoden** [comment]
@tqphan No, not independent. Offscreen keys would be keyboard specific, so you'd have to include the special key on each of your dynamic keyboards.  If that doesn't work for you, can you elaborate on why not?

**Comment by AdamRoden** [comment]
There is a built-in keyboard designer with style and customization enhancements as well as support for offscreen keys, but the features are only in my fork with no plan to merge them into Optikey root.
