### ISSUE TITLE
Alexa integration question

### ISSUE THREAD

**Issue by marcstein** [OptiKey/OptiKey#863]
I'm trying to integrate with Alexa and need to be able to introduce a delay in an entered phrase, e.g.,
Alexa...what is the time?
Multiple commas work to some extent. But is there something that generates a consistent pause?

In a related issue, is there a notion of macro expansion in Optikey, e.g., I create a dictionary entry "story" which expands to "Alexa [pause] tell me a story"

Thanks in advance!

**Comment by alexandre-mbm** [comment]
In the case of you using (creating) a dynamic keyboard, you can to define a "speak" key customized. It would adds "alexa.. ", would make the pause by `<wait>`, and then it would speak your setence finally.

**Comment by marcstein** [comment]
Thanks, Alexandre!
