### ISSUE TITLE
[study] Comments request about KeyEnabledStates

### ISSUE THREAD

**Issue by alexandre-mbm** [OptiKey/OptiKey#864]
I am studying to solve  kmcnaught/optikey-keyboard-scripts#7.

![KeyFixationSource](https://user-images.githubusercontent.com/957501/190621790-3ff4d515-7c35-49e3-817e-6b6c1d94bed4.png)

I will make a _sequence diagram_ for the **Sequence**'s logic.

**Comment by AdamRoden** [comment]
@alexandre-mbm I replied here https://github.com/kmcnaught/optikey-keyboard-scripts/issues/7#issuecomment-1249292463

**Comment by alexandre-mbm** [comment]
> What is this?

"KeyEnabledStates is the toggle controlled by things like the sleep key or ongoing mouse actions and so forth."

**Thank you!**
