### ISSUE TITLE
Irisbond Hiru support

### ISSUE THREAD

**Issue by richardchui** [OptiKey/OptiKey#873]
I selected Irisbond Hiru in the Source dropdown and have a Hiru attached to my laptop.  When I started Optikey, I did not see any error message (so I assumed that the tracker was successfully detected).  However, the software is not responding to the gaze at all.

P.S. I have tried starting HID with Hiru Systray before running Optikey, but in this case Optikey will actually display an error saying it has problem detecting the tracker.

Thanks for the help!

**Comment by rbsantos1** [comment]
May I ask where you purchased hiru and how much did it cost?

Thanks

Ronaldo

Sent from my iPhone

On 13 Nov 2022, at 05:06, Zengusan ***@***.***> wrote:

﻿

I selected Irisbond Hiru in the Source dropdown and have a Hiru attached to my laptop. When I started Optikey, I did not see any error message (so I assumed that the tracker was successfully detected). However, the software is not responding to the gaze at all.

P.S. I have tried starting HID with Hiru Systray before running Optikey, but in this case Optikey will actually display an error saying it has problem detecting the tracker.

Thanks for the help!

**Comment by richardchui** [comment]
I bought the Hiru directly from Irisbond.  As for pricing, you may have to contact them directly.

**Comment by kmcnaught** [comment]
Hi @richardchui could you please share the log files from %APPDATA%/Optikey/Optikey/Logs 

I remember having some issues myself with the Hiru drivers but it involved an obvious crash so might not be the same thing. Could you please try installing IrisbondSetup from here and then try again:
https://irisbond-published.s3-eu-west-1.amazonaws.com/hiru/IrisbondSetup_en.exe

**Comment by richardchui** [comment]
Hi @kmcnaught , here is the log file.  Seems the tracker was detected successfully, but I don't see any response to my gaze.

[OptiKeyPro.log](https://github.com/OptiKey/OptiKey/files/10042730/OptiKeyPro.log)

**Comment by kmcnaught** [comment]
@richardchui Do you know if the EasyClick software uses the HID mode as input? Does it have an option for calibration? I can't remember the process, I'll have to check if I have one available for testing or if I returned it to Julius!

**Comment by richardchui** [comment]
@kmcnaught Nope. They are mutually exclusive, you either use one or the other.  Hiru has a systray app where you can start the HID mode.  When in HID mode, the tracker can be used with Windows built-in Eye Control.  There is also a calibration option in the systray app when HID mode is started.  When HID mode is on, you won't be able to run EasyClick, and Optikey will give a error saying no tracker is detected.

You can also use EasyClick (for mouse control), and inside EasyClick there is a calibration option.

So I am not sure how we can calibrate the Hiru if we use Optikey instead of EasyClick.

P.S. Wondering if you guys have tried the Skyle trackers.  We are thinking of getting one to try out their SDK.

**Comment by kmcnaught** [comment]
@richardchui According to the source code it should offer calibration via the main optikey menu - this key:

![calibrate](https://user-images.githubusercontent.com/12151404/203381913-c2a7848d-97cb-4a3d-958c-7c6b9d7c5ac3.PNG)


Does it work?

**Comment by richardchui** [comment]
@kmcnaught I may have found out the reason why, it maybe due to the display resolution.  My 15" laptop has a 4k screen.  When I changed the resolution from 4k to 1080p and then recalibrate using the calibration function on the main optikey menu, it starts working.  Perhaps the tracking is working all along, just that it is way off because of the 4k resolution.  Dunno, just guessing.  FWIW, the EasyClick software does not have such issue.

Thanks for the great help and tips, really appreciate that.
