### ISSUE TITLE
Cursor flipping makes it hard to fixate near edge of screen

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#877]
This was briefly discussed offline but I'm raising it here so we can hear other opinions if anyone else wants to chime in. 

When you are performing a mouse action (e.g. left click at next dwell point), it shows a magnified virtual cursor at your gaze position. Currently, when you reach the right hand side of the screen the cursor flips left-to-right and when you reach the bottom it flips top-to-bottom. This is necessary as the cursor overlay is a `Popup` and cannot be moved offscreen, so in order for the 'point' of the cursor to be in the right place we need to flip the overlay accordingly. 

My gripe with this is that if you want to select a point _near_ the "flipping" boundary, the cursor jumps around and is very distracting, making it harder to get a good dwell fixation. 

Given the technical constraints, and looking for a simple solution that doesn't require changing the core implementation of the cursor as a popup we have two obvious options. 

(1) make the cursor shrink to a point near the problematic edges
![shrink](https://user-images.githubusercontent.com/12151404/207024869-786a2c64-2e7a-4ca7-9c29-fe4d36727ee5.gif)

I thought this would be fine, but imo once you're using a noisy eye tracker the fluctuations are still a bit distracting. 

(2) allow the cursor to flip, but with some hysteresis - don't flip it back near the same threshold, to avoid jumping back and forth at the same attempted dwell position. The dumbest version of this is to take the existing behaviour but not flip back until required for the opposite side.
![hysteresis](https://user-images.githubusercontent.com/12151404/207024896-5f9be192-981b-4280-bc7c-b45be74c4759.gif)

In my opinion this massively improves the transient behaviour and predictability. However, I wonder if the reversed cursor that you might get 'stuck' with is harder to work with just because it's less familiar? If this was the case then we could be more generous on flipping back to the standard orientation, so long as the boundary to flip back is far enough away that it doesn't get triggered by general eye tracker noise

@JuliusSweetland TL;DR I have implemented the hysteresis shown in the second GIF as part of the pending PR, if anyone objects in any way there are things that can be tweaked.

**Comment by JuliusSweetland** [comment]
Cool. I really like option 2. Nice solution!
