### ISSUE TITLE
Installer shouldn't ask for eyetracker/language choice on upgrades

### ISSUE THREAD

**Issue by kmcnaught** [OptiKey/OptiKey#881]
Currently the installer gives you the choice of eyetracker and language on every install, not just the first. After the first install the choice won't affect anything, since you will already have user settings which take precedence (assuming you ran the older app at least once).

Pretty sure this has always been the case, though not intentionally. And I'm pretty sure I've fixed it elsewhere (on another fork, presumably).

**Comment by kmcnaught** [comment]
When I tried the 4.0.0 pre release I didn't get asked, which might mean I've fixed the issue in that branch

**Comment by SCEhardt** [comment]
@kmcnaught I just upgraded today and wasn't prompted for eyetracker or language.  I think this is fixed and can be closed.

**Comment by kmcnaught** [comment]
thanks for letting me know :-)
