### ISSUE TITLE
Docs for command line options?

### ISSUE THREAD

**Issue by lsaranto** [OptiKey/OptiKey#898]
My understanding is that command line options were implemented and merged into the main branch. But I can't find any info about it in the wiki.

**Comment by kmcnaught** [comment]
@lsaranto thanks for the flag, here you go: https://github.com/OptiKey/OptiKey/wiki/Command-line-options

**Comment by lsaranto** [comment]
@kmcnaught Thanks!

So, just add the file or folder name after the executable. I probably should have been able to figure it out. 🤓 😃
